### ISSUE TITLE
Node scripts with calls to shell commands should fail fast

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#100]
Currently we use shell.exec from shelljs: https://github.com/shelljs/shelljs

However, shell.exec doesn't throw an exception on a non-zero exit code, and so things can fail in weird ways. We should replace these execs with stricter ones and (importantly) make sure there's no code that implicitly relies on the existing behavior to work.

Is there a better node shell library, maybe one that uses Promises so we can use async/await too?

**Comment by danielgavrilov** [comment]
If we're just using the `exec()` function from shelljs, could we get away with using the native `child_process.exec()`? Are there any drawbacks?

From the [node documentation](https://nodejs.org/docs/latest-v10.x/api/child_process.html#child_process_child_process_exec_command_options_callback), something like this could work:

```js
const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function lsExample() {
  try {
    await exec('ls');
  } catch (error) {
    // can access error.stdout & error.stderr here
  }
}
lsExample();
```

**Comment by mispy** [comment]
Sounds reasonable! If you make a wrapper I'd probably put it in `src/admin/serverUtil` or similar and then import it from there.
