### ISSUE TITLE
Embedded explorers do not respect entity type

### ISSUE THREAD

**Issue by kwijibo** [owid/owid-grapher#1008]
Hi, I'm not totally sure if this is the right repo to raise this bug, but noticed this on https://ourworldindata.org/environmental-impacts-of-food
<img width="343" alt="image" src="https://user-images.githubusercontent.com/78849/132303070-f312312b-988d-4769-b392-669d0783aa89.png">

**Comment by danielgavrilov** [comment]
Notion issue: https://www.notion.so/owid/Explorer-entity-picker-of-an-embedded-explorer-doesn-t-respect-entity-type-a27562653486452cb5b8718e3f4fcba7

**Comment by larsyencken** [comment]
From @MarcelGerber : 

> apparently this happens because we don't pass the the entityType into the SelectionArray here: https://github.com/owid/owid-grapher/blob/48e20ee24270821bd148343cf0854880a1fcd72d/site/multiembedder/MultiEmbedder.tsx#L153-L155

**Comment by larsyencken** [comment]
From our discussion, seems like `entityType` doesn't need to be in the selection array at all, it could be somewhere else.

**Comment by marcelgerber** [comment]
We [got user feedback](https://owid.slack.com/archives/C3RAU3BJ9/p1670476352748279) today from a user that is confused about this.
