### ISSUE TITLE
Remove legacy metadata columns from variables table

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#102]
We chatted with @mispy about this—some columns in the `variables` table were originally used to store metadata, but due to many different metadata formats, `originalMetadata` is now used to store all metadata as JSON. 

Some of these columns are: `unit`, `shortUnit`, `code`, `coverage`, `timespan`. Ideally, if they are useful and cannot be derived from anything else, they should be moved to `originalMetadata` as JSON fields.

**Comment by danielgavrilov** [comment]
After a few imports I think `code` should stay as a column—it's useful for updating existing variables, as they can change name but more rarely change code. It helps to have the `(code, datasetId)` constraint especially.

The others (`unit`, `shortUnit`, `coverage`, `timespan` & `columnOrder`) should be moved to being keys in `originalMetadata`. 

I'm not exactly sure how this will affect the grapher, but it seems that #126 should be fixed before we run this migration?

(Also while making this migration, it would be helpful to have a `DEFAULT {}` (empty object) for the `display` field...)

**Comment by mispy** [comment]
Agreed, code is a useful column! And should have a unique constraint.

The functionality in #126 doesn't exist with these old columns at the moment either, so feel free to do it in either order. Default makes sense too.

**Comment by breck7** [comment]
Closing as we're going to move off mysql.
