### ISSUE TITLE
Basic version history for chart configuration

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#108]
Talking to Esteban, there a couple of cases where published charts have been broken in some way by a mistake in editing and it was tricky to find out what the original settings were. It'd be great to have some way of seeing previous published versions of a chart configuration and rolling back. 

This doesn't have to be fancy, just fulfil the function of being able to undo. Storing old jsons in a table somewhere with a date on them and a little interface in the admin editor to select them is all that is needed.

**Comment by sherinkurian** [comment]
Hi guys, I should have asked a day sooner but hope no one is working on this. Can I claim this :)

**Comment by mispy** [comment]
Thanks Sherin! This is live now. The tweaks I made were mainly to make it like Wordpress revision history (since our authors are likely familiar with how that works) https://github.com/owid/owid-grapher/commit/012cfb435e94c1e61bcd1e4c0bb025e73d2574a3

**Comment by HannahRitchie** [comment]
Thank you very much Sherin for your work on this! It is incredibly useful for us! You're a star :-)

**Comment by sherinkurian** [comment]
@HannahRitchie! So kind of you. Jaiden tells me the team is going to be in California next year. I would love to meet up with you if it works out :)

P.S: @mispy I wouldn't call your changes "tweaks". LOL - Just teasing.. happy to learn.
