### ISSUE TITLE
Project: improve author experience of prominent links

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1083]
## Scope

- [x] Fix existing issues with prominent links
  - [x] #1147 
  - [x] #1126
- [ ] ~~Identifying the most important problems to solve (input for Matt)~~

Out of current scope:
- ~~Iterate on the visual design of prominent links~~
- ~~Implement several of the new link variants~~

**Comment by mlbrgl** [comment]
planning to assess whether prominent links variations are still relevant based on the review of the poverty entry on Feb 23, 2021 with @JoeHasell and @mathisonian

**Comment by larsyencken** [comment]
Split out the all the new prominent link work to a new card: https://github.com/owid/owid-grapher/issues/1213

This one is otherwise done!
