### ISSUE TITLE
Project: refactor tolerance to make it more maintainable

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1085]
_Fix current and future tolerance issues by streamlining how tolerance works._

## What

- [x] #1385
- [ ] Refactor the tolerance layer that’s used for visualisation
- [ ] Fix outstanding tolerance issues
    - [x] https://github.com/owid/owid-grapher/issues/1091
    - [ ] https://github.com/owid/owid-grapher/issues/1182

## Why / why now

Some of our glaring correctness issues come from tolerance bugs, but the way tolerance has been implemented to date makes it very difficult for us to fix these issues. So several tolerance issues have been open for a very long time; we'd like to close these correctness issues off.

## Risks

- It’s not yet certain that we’ll find a clean architectural way to express tolerance
- Fixing tolerance could make performance worse

## See also

- [Notion: Tolerance improvements/fixes](https://www.notion.so/owid/Tolerance-improvements-fixes-d526637f8f52431f89af03a087df678e) (private)

**Comment by larsyencken** [comment]
Marked it as not this cycle.

**Comment by danyx23** [comment]
@larsyencken I would close this issue unless you object and only leave the sub-issue about asymmetrical tolerance open - I think the other remaining issues with tolerance were fixed as part of my perf improvements in summer.

**Comment by danyx23** [comment]
I'll just close it but feel free to reopen if I am missing something
