### ISSUE TITLE
Scatterplot: tolerance broken with mixed time units

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1091]
Notion parent: https://www.notion.so/owid/ScatterPlot-tolerance-broken-with-mixed-time-units-ed771026c1184fa9866f1f83cc9b30e1

**Describe the bug**

Our data series support two types of time unit: years and days. It's possible to join them together based on year, and using tolerance, but this functionality is not working properly.

The implementation is complicated and we hope re-architect all tolerance implementation in #1085.

Brief context of how it currently (doesn't) works: We currently require authors to specify an X axis time override when joining mixed time units in a ScatterPlot (and a ScatterPlot is the only chart that supports mixed-time units). This means the variable tables are joined on [entity] instead of [entity, time], which avoids dealing with joining on mixed-time units. But this is buggy – depending on the order of the variable table joins, you get different results. The `CoreTable.complete([entity, time])` is the main source of bugs (@danielgavrilov thinks) because we omit `originalTime` columns from it, and a bunch of other columns.

**Comment by larsyencken** [comment]
See: https://github.com/owid/owid-grapher/pull/894

**Comment by larsyencken** [comment]
@danielgavrilov Just putting you on this again since you had a draft PR against it. I had trouble articulating the issue well, can you have a go explaining it at the top?

**Comment by danyx23** [comment]
Related to #1085

**Comment by danyx23** [comment]
This was fixed as part of #1565
