### ISSUE TITLE
Split "Hide automatic time/entity" toggle into multiple controls

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1094]
Parent Notion issue: https://www.notion.so/owid/Split-Hide-automatic-time-entity-toggle-into-multiple-ones-a3056259ca2248ad865a01a55af12807

## Core problem

We have a single admin control for a chart which controls how the chart title gets modified in multiple ways. This is not clear enough for authors, and not enough control for situations where you want some changes but not others.

![automatic-time](https://user-images.githubusercontent.com/36012/150866212-3dd63451-64cd-4d01-844c-d8dac7804a91.png)

This tiny toggle here - "Hide automatic time/entity" - [really controls three different aspects](https://github.com/owid/owid-grapher/blob/5a4400afae21f9342a8a14f93fc52cde9ab668f9/grapher/core/Grapher.tsx#L1120-L1148) of the chart title:

- Automatically append the shown entity name - e.g. "Greenhouse gas emissions, France"
- Automatically append the shown time (range) - e.g. "Greenhouse gas emissions, 1990 to 2021"
- Automatically prepend "Change in" for line charts in relative mode - e.g. "Change in greenhouse gas emissions"

## Proposed solution

Having the ability to disable the automatic annotations can be helpful when our heuristics fail or when *someone* is abusing the grapher's capabilities.

However, that's all-or-nothing at the moment.

Instead, we should split it up into *at least*:

- Hide automatic time
    - see also ~related issue: [Title of svg/png export doesn't include date annotation, but interactive chart does](https://www.notion.so/Title-of-svg-png-export-doesn-t-include-date-annotation-but-interactive-chart-does-89bce5655f3a4ae5a66083e9aae88a6f)
    - A chart where we would definitely want the time annotation disabled: [https://ourworldindata.org/grapher/coal-phase-out-timeline](https://ourworldindata.org/grapher/coal-phase-out-timeline)
- Hide automatic entity
    - There are definitely some cases where our current code would show a nonsensical entity annotation, e.g. here: [https://ourworldindata.org/grapher/exports-from-western-europe-to-other-regions](https://ourworldindata.org/grapher/exports-from-western-europe-to-other-regions) (would be: "Western European exports by region of destination, Western Europe")

## Alternatives

If we want to take this further, we could also consider making these three-way options. Basically:

- Show automatic time: Always / Automatic / Never
- Show automatic entity: Always / Automatic / Never

**Comment by sophiamersmann** [comment]
Has a consensus been reached on how to best solve this issue? Do you prefer a simple toggle or three options, @danyx23 @larsyencken?

**Comment by marcelgerber** [comment]
This certainly sounds like the most complete solution, yes.


> Always: Show entity or time when appropriate (current default behaviour)

Not sure if this is what I would expect for "Always". I realize that we can't really _always_ display the entity name (for example, in maps it's not possible). However, maybe we want "Always" to be showing entity/time in _more_ cases than is currently possible.

Also, it's worth keeping in mind that this will entail a database migration, migrating all occurrences of `hideTitleAnnotation: true` with something like `titleAnnotations: { entity: "auto", year: "auto" }` (this is a serialisation I just came up with, not necessarily close to reality 😁 ). If you have questions about how to write that migration, reach out!

Another tiny thing is that for "Change in", we probably only have the choice between "Automatic" and "Never". But if it is easier to do the three-way toggle for this one, too, then go for it.

**Comment by sophiamersmann** [comment]
Thanks for the input, Marcel!

> Not sure if this is what I would expect for "Always". I realize that we can't really _always_ display the entity name (for example, in maps it's not possible). However, maybe we want "Always" to be showing entity/time in _more_ cases than is currently possible.

Agreed! The wording isn't great here. Maybe we should opt for something that is a bit more specific like: "Always" -> "Show when appropriate" and "Automatic" -> "Hide unless necessary" (or something similar).

Apart from the wording, do you have specific cases/charts in mind where it would make sense to show the entity/time but it is not displayed at the moment?

> Another tiny thing is that for "Change in", we probably only have the choice between "Automatic" and "Never". But if it is easier to do the three-way toggle for this one, too, then go for it.

Good point!

**Comment by marcelgerber** [comment]
@sophiamersmann tangentially related (because it also handles title generation) is https://github.com/owid/owid-grapher/issues/1542
