### ISSUE TITLE
Upgrade to node 16 (gallium)

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1096]
## What

We are currently on Node 12.22.3 (erbium) which reaches end-of-life in April this year. We would like to update to 16.13.2 (gallium), both for speed and continued support, but also because it's blocking an upgrade to Webpack 5.

## Steps

- [x] Remove the fibers package
- [x] Update `.nvmrc` to gallium
- [x] Test that everything works locally
- [x] Test that everything works on a staging server
- [x] Solve outstanding problems
  - [x] Admin server restart when special charts are updated
  - [x] Wordpress's `yarn runPostUpdateHook` runs using the wrong Node version
- [x] Probe the whole upgrade process
- [x] Deploy to live
- [x] Make sure the pm2 path given in `/etc/systemd/system/pm2-owid.service` is correct (see: [Server setup: set up PM2 startup](https://www.notion.so/owid/Server-setup-on-Ubuntu-20-current-fda904f53dfc4635b95289558923c05a#2a14dc0050064fa6b1a6033a2de61944))

**Comment by MarcelGerber** [comment]
Okay we're in a good state here now; all staging servers are now running on Node 16 and mostly fine.[^1][^2]

This here is the procedure we will have to run on `live`:
```sh
nvm install 16.13.2
nvm alias default 16
npm install -g yarn pm2
sudo vim /etc/systemd/system/pm2-owid.service # change 'v12.22.3' to 'v16.13.2'

# Re-create pm2 entries so they use the correct PATH and run using Node 16
cd live
pm2 stop live live-deploy-queue
pm2 delete live live-deploy-queue
pm2 start --time --name live "yarn startAdminServer"
pm2 start --time --name live-deploy-queue "yarn startDeployQueueServer"
pm2 save

# Deploy with Node 16 changes merged

sudo reboot # see that everything still works
pm2 log live # check for errors
pm2 log live-deploy-queue # check for errors
```

[^1]: One exception is that, for all servers that don't have 140a68eceb55f7a3235e27d35559a887c23fd5e2 applied (currently all but `tufte`), the admin server will restart after a chart update for a chart that doesn't have country data.
[^2]: We can actually keep some (especially older) staging servers running on Node 12 and only update newer ones to Node 16, no problem.

**Comment by MarcelGerber** [comment]
All done, live and staging servers are all updated to Node 16.
