### ISSUE TITLE
Tagging of individual charts

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#110]
A high-priority feature is creating a public index of all of our charts. For this, we need to know the categories that individual charts fall under.

I was originally thinking we would categorize charts based on either the page they are embedded in or the dataset they originate from. But after talking with people it becomes clear that we do want charts to have their own categories, and maybe just use one of those reference points to assign an initial set to all the existing charts.

The database structure for this is straightforward (same as for datasets). Then it is just a matter of doing the UI for it.

**Comment by danielgavrilov** [comment]
What exactly is "index" in this context—is it for visitors to browse all our charts, or is it for machines?

(Is there maybe a basecamp discussion about it?)
