### ISSUE TITLE
Pinning rows in the Bulk FASTT editor

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1109]
When I imagine how I would like to work on curating a lot of related variables then I can see a situation where you'd like to have a few variables that are related on screen at the same time even if there isn't an easy unifying search for this. E.g. it could be the case that you want to have the old "poverty as share of population" variables from dataset A visible next to similar ones with a different name from dataset B.

For such cases I want to implement row pinning. This would add an icon at the beginning of each grid row that allows you to pin this row to the top. Pinned rows would then not be cleared when paging through a search or even when searching for something new. This way they would be like a "bag of work items" that are currently relevant for you that you can pick up and then work on at the same time (e.g. dragging changes across all of them)

A few requirements for pinning:

- [ ] Pinned datasets should be refreshed on every search request - i.e. we want to always construct a search query that uses whatever search filters are active right now and then a logical OR that fetches pinned rows by id. This is to make sure that they don't get very stale if an editing session lasts for hours
- [ ] When fetching with pinned rows the paging limit should be increased so that pinned rows don't exhaust the paging of the "normal search"
- [ ] It should probably be possible to DnD change the order of pinned rows

**Comment by larsyencken** [comment]
Closing as not planned for now
