### ISSUE TITLE
Convert existing "default" prominent links into "thin" ones

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1110]
## Core problem

From slack: _Max has a strong impression that the default style prominent links (the big ones, like this) are never helpful. And that we should convert all these to thin-style links._
<img width="705" alt="Screenshot 2022-01-26 at 19 40 23" src="https://user-images.githubusercontent.com/13406362/151371741-8590ee60-ff05-4529-91a3-3c91ea6b0dc8.png">

## Proposed solution

Convert existing "default" prominent links into "thin" ones

## Context

This supersedes https://www.notion.so/owid/Remove-large-prominent-links-variation-20f7fb84fb1a4bd18f1b926f99054da6.
This might be a good opportunity to make "thin" style the default.

**Comment by larsyencken** [comment]
@JoeHasell Is is this something that you will do manually? If so, should I move this to the `owid-issues` issues list?

**Comment by JoeHasell** [comment]
Thanks @mlbrgl – let me know if it will require a manual push at any point. (I'm subscribed to notifications).
