### ISSUE TITLE
Chart selection persists and is not editable in the admin

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1111]
Parent notion issue: https://www.notion.so/owid/Selection-leaks-out-to-URL-f483bf775fe44f86a00cd6383a169082

## Description

In some charts, there is a selected entity that persists and cannot be edited out in the admin.

## Expected behaviour

All selection should be managed through the admin only.

## Examples

The chart `indoor-pollution-death-rates-clean-fuels` is constantly redirected from https://ourworldindata.org/grapher/indoor-pollution-death-rates-clean-fuels to https://ourworldindata.org/grapher/indoor-pollution-death-rates-clean-fuels?country=~SLB (Solmon Islands selected).

The selection persists after being removed in the admin.

In the chart config, Solomon Islands was in the `selectedEntityNames` field.

## Analysis

There are three ways of specifying selection in the Grapher config:

- `selectedData`
- `selectedEntityIds`
- `selectedEntityNames`

Ideally we would migrate to only using one. The least likely to go wrong is `selectedEntityIds`.

**Comment by larsyencken** [comment]
@spoonerf Got a case with this chart: https://ourworldindata.org/grapher/share-with-mental-health-males-vs-females where Libya is always selected. It again was listed in `selectedEntityNames` and needed manual removing.

**Comment by danielgavrilov** [comment]
Charlie had the issue https://owid.slack.com/archives/C46U9LXRR/p1645021297421849?thread_ts=1644959726.567109&cid=C46U9LXRR

Likewise `selectedEntityNames` was populated and I cleared it in devtools.

**Comment by larsyencken** [comment]
Set priority to `medium` since this keeps coming up. Estimated `3d` since I think we would need to do a data migration of selections to fix it once and for all.

**Comment by MarcelGerber** [comment]
As mentioned in #1241 this is also affecting color selection: If a color is specified in the legacy `selectedData`, then we cannot reset to the color scheme default (we can override it, however).

**Comment by larsyencken** [comment]
Closing this and tracking it in #1245 instead.
