### ISSUE TITLE
i18n Based Translations

### ISSUE THREAD

**Issue by TurtIeSocks** [owid/owid-grapher#1116]
## Core problem

Is there interest in integrating an i18n based solution for managing translations instead of purely relying on Google Translate?

Having setup a local copy of the repo and my own database, it's apparent that this wouldn't be a simple task but I'm curious what kind of translation solutions the team has considered.

## Proposed solution

I've used[ React i18next](https://react.i18next.com/) in a couple of projects now and have really enjoyed it. 

If there is interest, I wouldn't mind slowly chipping away at the PR myself. I only read/write in English though so I can't offer much help in terms of the actual translations 😄

**Comment by larsyencken** [comment]
I think it would be a big project for us to do i18n properly, and would require us to keep an ongoing pool of translators, manage their work etc. We probably don't have capacity to take it on this year. Once we get to a stage when it's in the plan, then I think we'd welcome this kind of contribution. Until then we might keep it on ice 🧊 

Thanks for the suggestion, and the offer to contribute!
