### ISSUE TITLE
Tracking issue: improve colour palettes in grapher

### ISSUE THREAD

**Issue by HannahRitchie** [owid/owid-grapher#1118]
## Problem

We believe that for a lot of charts, our colour palettes could be a lot better.

## Technical issues

We have split out editorial issues (https://github.com/owid/owid-issues/issues/262) from technical issues. Only the technical issues are kept here:

- [x] #1514
- [ ] #1177
    - E.g. [This chart](https://ourworldindata.org/grapher/co2-emissions-and-gdp?time=earliest..2019&country=~ATA) say it shows change of GDP and emissions in Antarctica. But it does not show GDP change.
- [x] #1296
    - [Some](https://ourworldindata.org/corruption#which-countries-are-perceived-by-business-executives-as-more-likely-to-export-corruption) charts (here is [another](https://ourworldindata.org/grapher/pneumococcal-vaccination-averted-deaths)) have no color palettes associated to them, but it’d be nicer if they did.

**Comment by danielgavrilov** [comment]
This needs to be split up and understood a bit better how to tackle each of the points – I will try to do that.

**Comment by danielgavrilov** [comment]
@HannahRitchie (cc @maxroser) I edited the original issue:

- Under **Technical issues** are the things we can improve on the Grapher side
- Under **Authoring issues** are things that I think need to be fixed by chart authors. Potentially a developer can help find instances that need fixing.

Do you agree with the above? If so, each point in Authoring issues either belongs in owid-issues or should be a guideline for authoring charts.

**Comment by HannahRitchie** [comment]
@danielgavrilov great, that definitely makes sense.

I think @maxroser should be the one to select the new palettes we want to add, definitely. You can loop me in as co-pilot for selecting of "bad" palettes to get rid of. And for me to be the facilitator of back-and-forwards (especially if you need someone to nudge to hurry things up). 

Does that make sense?

**Comment by larsyencken** [comment]
@HannahRitchie Gavrilov and I did a refactor of this card, moved the authoring issues back into `owid-issues` and called it a "project" for someone. Hopefully that makes it clearer how to move it all forward.

**Comment by larsyencken** [comment]
A guide for creating org color palettes by Lisa Charlotte Muth: https://blog.datawrapper.de/colors-for-data-vis-style-guides/

**Comment by danyx23** [comment]
@HannahRitchie I think we can close this issue? It looks like #1177 is still open but I think we don't need this tracking issue anymore.
