### ISSUE TITLE
'Relative change' does not work on faceted charts

### ISSUE THREAD

**Issue by HannahRitchie** [owid/owid-grapher#1121]
## Description

The 'relative change' toggle does not work when charts are in facet mode.

## Expected behaviour

This chart (edit [here](https://owid.cloud/admin/charts/5545/edit)) is only really appropriate in 'relative mode'. It should not used in non-relative mode. This works fine for a single country. But when turning facets on, for different countries it reverts back to non-relative mode.

## Screenshots

Screenshots with 'Relative' ticked and unticked. Charts do not change.

<img width="757" alt="Screenshot 2022-02-01 at 09 35 18" src="https://user-images.githubusercontent.com/35040753/151944521-beff6a22-cd7d-4d3c-bfb2-6c7d216f5c4f.png">

<img width="753" alt="Screenshot 2022-02-01 at 09 35 29" src="https://user-images.githubusercontent.com/35040753/151944528-ae67d7c9-a894-49e9-b1dc-0a993303abb9.png">

**Comment by danielgavrilov** [comment]
Thanks! I will move some information from here into #1098, which documents the same issue.
