### ISSUE TITLE
Report more types of failure to Bugsnag

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1127]
## Description

Currently, we have some code paths that lead to an error message on the user side (via `grapher.setError()`), but that won't ever be reported back to us via Bugsnag.

These code paths include
* [fetching/loading an explorer table](https://github.com/owid/owid-grapher/blob/36fb4246211d2a66c18bb9da52cfcbfcbc354778/explorer/Explorer.tsx#L297)

Slack discussion here: https://owid.slack.com/archives/CQQUA2C2U/p1643712834733399

**Comment by larsyencken** [comment]
Hey @MarcelGerber, if you think you can make some best-effort progress in 2-3h, then perhaps pick this up next. Otherwise, we can leave it until the end of the cycle.

**Comment by marcelgerber** [comment]
We had a [live failure just now](https://owid.slack.com/archives/CQQUA2C2U/p1660837740392959) that didn't end get reported by Bugsnag, which might have been because of this issue.
Here's the stack trace:
![image](https://user-images.githubusercontent.com/2641501/185445729-9bb0932c-f862-4d58-bccb-66617d286612.png)

**Comment by danyx23** [comment]
This issue is over two years old now and we haven't gotten around to it - closing it
