### ISSUE TITLE
Get rid of versioned svg exports (to speed up Netlify deploys)

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1129]
## Description

Currently, we create a static svg export of every version of every chart and put them into `exports/` in the baked site. The old versions are left in place [^1].

This was initially meant as a way to never serve outdated versions of a static chart.
But instead they just clutter up our repo and site, especially since Covid charts are updated multiple times a day. Also, these exports will arguably become less important after #1123 is merged (they are still used as a fallback for non-JS or super-old browsers).

## Proposed solution

Stop including the version in the filename of exports. To ensure freshness of these assets, we can still include a `?v=...` query param in `<img>` tags linking to these exports.

## Additional context

Slack discussion (one of many): https://owid.slack.com/archives/CQQUA2C2U/p1643711806952369

[^1]: Unless they are manually deleted using `~/delete-old-exports.sh`.

**Comment by danielgavrilov** [comment]
> they are still used as a fallback for non-JS or super-old browsers

And for every chart embed on mobile! Which is the most significant aspect, so I don't think that

> these exports will arguably become less important
