### ISSUE TITLE
Use text fragments to enable deep linking to paragraph from search

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1156]
## Core problem

Search results show excerpts from relevant paragraphs, but the search result link points to the top of the page. This requires an extra scroll (or in-page search) to get the relevant piece of information.

## Proposed solution

Use text fragments (https://web.dev/text-fragments/) to enable deep linking to the relevant paragraph, e.g.: 

https://ourworldindata.org/oral-rehydration-therapy#:~:text=It%20is%20also%20important%20to%20note%20that%20diarrhea%20as%20the%20cause%20of%20death%20is%20often%20determined%20by%20a%20verbal%20examination%20rather%20than%20an%20actual

<img width="1438" alt="Screenshot 2022-02-14 at 10 55 58" src="https://user-images.githubusercontent.com/13406362/153842063-65b69372-c59d-4e72-a4a8-7521ce79a39d.png">

## Alternatives

Attributing immutable IDs to paragraphs in Wordpress.

## Context

This could also be applied to backlinks to related articles in all our related research and data block:
<img width="1438" alt="Screenshot 2022-02-14 at 11 17 21" src="https://user-images.githubusercontent.com/13406362/153846101-5f4cca90-e8d3-4e90-9c81-903b1f2c3078.png">

## Limitations

Browser support https://caniuse.com/url-scroll-to-text-fragment

**Comment by danielgavrilov** [comment]
I just tried searching for for `"poverty"` and Algolia would link me to https://ourworldindata.org/extreme-poverty#how-do-researchers-reconstruct-historical-poverty-estimates, 2 thirds down the article, even though the word `poverty` appears in the very first sentence of the entry.

Tried `"fertility"` and it links me to the bottom of the entry, in the sources: https://ourworldindata.org/fertility-rate#the-demographic-and-health-surveys-dhs

Those are the only 2 I tried. I guess we would need to do some tweaking to help Algolia do a better job.
