### ISSUE TITLE
Support negative values for stacked bar charts

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1166]
## Core problem

We are trying to use stacked charts with data that contains negative values, which they simply weren't designed to handle. Right now negative values don't display correctly, which can be misleading.

## Proposed solution

Redesign a variant of ~~stacked area and~~ stacked bar charts that can handle negative values and implement it.

- [ ] Sketch out a design and validate it
- [ ] (probably) move the axes to accomodate negative values
- [ ] (probably) make a new visual mark for the totals of each stack
- [ ] (probably) might be some entity label layout changes needed

## Special concerns

With negative values, the total is no longer the top of the bars/area, instead it needs a separate and visually distinguishing mark. The tooltop might need updating, and axis will need shifting.

**Comment by larsyencken** [comment]
> An example by Hannah is this popular chart (https://ourworldindata.org/grapher/annual-co-emissions-by-region) where she had to remove a small category called ‘statistical differences’ because in some years it was positive, in some it was negative. But the grapher could not handle negative values and instead made them positive anyway.

**Comment by danielgavrilov** [comment]
Some Slack context discussing the difficulty of implementing a StackedArea with negative values: https://owid.slack.com/archives/C5BDCB2R3/p1592400048124500

**Comment by larsyencken** [comment]
Cutting stacked area from scope, since it's so difficult. We can make a new issue for that if we want to take that discussion.

**Comment by sophiamersmann** [comment]
Came up again in the context of climate charts. Screenshots posted in [Slack](https://owid.slack.com/archives/C46U9LXRR/p1703760502160699):


![Screenshot 2023-12-28 at 10 39 45](https://github.com/owid/owid-grapher/assets/12461810/1e2d154d-fd4c-4331-bc4f-12c50656b835)
![Screenshot 2023-12-28 at 10 40 01](https://github.com/owid/owid-grapher/assets/12461810/c479981e-6bc0-4d44-88e9-e1f08c794209)

**Comment by sophiamersmann** [comment]
Here is another chart where negative values lead to incorrect bar placements: https://ourworldindata.org/grapher/food-emissions-supply-chain?country=Apples~Bananas

<img width="1199" alt="Screenshot 2024-04-09 at 09 54 36" src="https://github.com/owid/owid-grapher/assets/12461810/0250bc21-5747-498b-9c66-e605498f4279">

(Note that Land use change is a negative value)
