### ISSUE TITLE
Scatterplots mark non-countries as "No data" in the legend

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1167]
## Description

If a scatterplot contains regions, they are listed in the legend as "No data".

<img width="1095" alt="Screen Shot 2022-02-16 at 11 42 16" src="https://user-images.githubusercontent.com/36012/154248239-df7eb667-bc01-431f-a835-ac3f5bef7348.png">

## Proposed fix (Mar 2023)

Hide the "no data" label in the color legend.

Later, we can consider revisiting how we handle aggregates as described in #1686

**Comment by danielgavrilov** [comment]
The ideal fix here is to [**define color scales on the variable level**](https://www.notion.so/owid/Store-color-scale-config-on-variable-level-ce3c98d8c3a846b0b0f9976e57ffb316). Then, for the Continents variable, we can set the "No data" label to something better.

**Comment by marcelgerber** [comment]
Ah wait, I just saw that daniel was unassigned from this issue. Why is that? Is the fix in #1306 not worth pursuing?

**Comment by maxroser** [comment]
This issue would be good to fix, when we have the time.

Relatedly it'd be good to not assign the population size to the size of the bubble for world regions – and especially for the entity 'World'. Because [that means](https://ourworldindata.org/grapher/access-to-electricity-vs-gdp-per-capita) that the 'World'-bubble is massive and all others small.

**Comment by sophiamersmann** [comment]
This came up again, brought to our attention by Natasha [on Slack](https://owid.slack.com/archives/C03NV9Z3YSV/p1678887904983129)

Link: https://ourworldindata.org/grapher/mean-height-males-vs-females?country=East+Asia+and+Pacific~Europe+and+Central+Asia~Latin+America+and+Caribbean~Middle+East+and+North+Africa~North+America~South+Asia~Sub-Saharan+Africa~OWID_WRL

![mean-height-males-vs-females](https://user-images.githubusercontent.com/12461810/225329794-909dae89-945d-4424-b14b-a331ad572453.png)

**Comment by larsyencken** [comment]
@samizdatco I suggest shipping the simplest possible fix first, that of hiding "No data" in the legend, and deferring any more sophisticated aggregate handling until we have a more compelling need.
