### ISSUE TITLE
Data downloads should exclude data that can't be used by the chart

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#117]
From Max:

> If you download the data behind this chart https://ourworldindata.org/grapher/gini-index-around-2015-1990-2015-countries-vs-gini-index-around-1990-1990-2015-countries

> it gives you the population figures for all countries in all years for the last two centuries.

> Let’s make a note to change this!

Ideally, the extra data shouldn't even be served in the JSON chart data since it can't be used in any way?

**Comment by mispy** [comment]
Yes, only downloading the needed data would be great! Especially for scatterplots, which are a little too resource intensive at the moment. Probably this would be done by baking the data for the chart at the time it is saved, into a JSON form.

**Comment by breck7** [comment]
This (and other variations of this) are now possible in Next. We can allow for downloading all data at the first step, the last transformed step, or any step in between.
