### ISSUE TITLE
Create a page that lists all our Data Explorers

### ISSUE THREAD

**Issue by maxroser** [owid/owid-grapher#1170]
To help users find our Explorers and for us to keep an overview of all the Explorers that are online it would be good to create a page that lists links to all existing Explorers (like [that page](https://ourworldindata.org/charts) that lists all charts).

Users are apparently trying to find it already:
https://owid.slack.com/archives/CLDM2AWCD/p1644399871345639?thread_ts=1644348562.046449&cid=CLDM2AWCD

We briefly discussed it in Slack here https://owid.slack.com/archives/C0149NKLZAM/p1644595871527849

–

One possibility would be that this list is simply at the very top of the all charts page (https://ourworldindata.org/charts).

**Comment by larsyencken** [comment]
@mlbrgl Can you take a look at this, just to estimate?

**Comment by mlbrgl** [comment]
> One possibility would be that this list is simply at the very top of the all charts page (https://ourworldindata.org/charts).

~ 1h for a bare-bones version

**Comment by mlbrgl** [comment]
@larsyencken  given this had been marked `important` for the past 2 months and I was in between things, I spent ~1h+ on a bare-bones implementation.

@HannahRitchie there are duplicates in the published explorers (probably internal tests). Could you please unpublish those we don't want to list here?
<img width="1129" alt="Screenshot 2022-04-20 at 12 31 40" src="https://user-images.githubusercontent.com/13406362/164212931-d56ac2b6-b9e0-4ab7-9ec1-bf03b9b0b5da.png">

**Comment by HannahRitchie** [comment]
Thanks @mlbrgl. I unpublished all of the test explorers now.

In future for this sort of thing it would be good to be able to have an additional option which is 'Published but not indexed'. Sometimes we need to share explorers with external users for review, without them being 'findable' on the site.

**Comment by mlbrgl** [comment]
thanks @HannahRitchie!

Yes that makes sense, I've submitted your request in #1405
