### ISSUE TITLE
Use scientific notation in log axes with a wide span of magnitudes

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1171]
## Core problem

Data with values ≥10¹⁸ starts to have number suffixes duplicated, so you get axis labels like `1 billion trillion`:

![compute-used-in-the-largest-ai-training-runs_overall](https://user-images.githubusercontent.com/1308115/154270499-5c52db0c-13c6-447f-a844-2f16d9364d3f.png)

## Proposed solution

Ideally, we would start using scientific notation at that point, as they do in the original paper that dataset was extracted from:

![image](https://user-images.githubusercontent.com/1308115/154270856-c2120c2d-4e0d-4768-b636-6cc11eb08e0e.png)

This could be either automatic, or there could be an additional axis setting in the Admin.

## Context

[Raised by Charlie on Slack](https://owid.slack.com/archives/C0146HTMV2R/p1644935513096149?thread_ts=1644931416.138679&cid=C0146HTMV2R). See the currently [published Grapher chart](https://owid.cloud/admin/charts/5566/edit).

**Comment by larsyencken** [comment]
The impact of this is pretty low right now, so we won't tackle it. If we get more cases we can revisit.
