### ISSUE TITLE
ScatterPlot with a time X dimension should not include a Year column in CSV download

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1173]
## Description

A ScatterPlot with a time X dimension includes a non-sensical `Year` column in the CSV download (e.g. [this chart](https://ourworldindata.org/grapher/ai-training-computation) –[ai-training-computation.csv](https://github.com/owid/owid-grapher/files/8080276/ai-training-computation.csv))

<img width="550" alt="Screenshot 2022-02-16 at 13 39 27" src="https://user-images.githubusercontent.com/1308115/154276355-ed3f8434-576d-489d-a3a7-a7501d2bec58.png">

## Expected behaviour

The CSV should not include a `Year` column.

## Additional context

[Reported by Charlie](https://owid.slack.com/archives/C46U9LXRR/p1644955837722169).

**Comment by larsyencken** [comment]
Marked as won't fix. Only happening with two datasets, and the correct data is also there in the CSV. If we see it happen more, we can reevaluate.
