### ISSUE TITLE
Add "semi-private" Axis config options to Grapher schema?

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1174]
Currently, **some `Axis` config options are not in the Grapher schema**:

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L19

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L24-L28

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L35-L39

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L41-L46

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L48-L52

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L54-L58

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L60-L63

**With #1159, a few more are being added**:

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L21-L22

https://github.com/owid/owid-grapher/blob/4444296e5dff3d6b6ef3e9eac228d191fd2115f5/grapher/axis/AxisConfigInterface.ts#L65-L70

---

These config options can _technically_ be provided from the top-level Grapher config, but currently cannot be defined through the Admin. They are only used in facets and some chart-type-specific configuration.

Do they belong in the schema? What does it mean to be in the schema?

I think I'd prefer not to encourage them being defined at the top-level, which kind of makes them some kind of private properties, despite being defined at the same level.

Need to discuss with @danyx23.

**Comment by danyx23** [comment]
Hm, interesting questions. I think if something comes up in existing configs it has to be in the schema (which is what we have now). But going forward the schema should also serve as a documentation of the config API surface. As such I think we should aim for a reasonable in-between in what we include in the schema: Not every field has to go in there, but things that might be reasonable to use in some contexts should probably be added. From skimming the above list my guess would be that maybe we should add 

* hideGridlines
* nice
* compactLabels
* hideAxis

but I haven't thought about this a lot. What is your hunch?

**Comment by danielgavrilov** [comment]
My hunch is to **not add any of them until we have a valid use case** – same as adding configuration options in the Admin. If they are defined in some config, it's totally ok to raise an error.

My biggest concern is **users not realising the effects of them under all contexts**. The way most of them are implemented now is: **if they are defined from the top-level config, they are not overridden** by logic down the line. This can cause issues, contrived example: the faceting logic knows that it should hide the axis, but maybe `hideAxis: false` is defined at the top-level, so it doesn't.

Potentially we might want to change that, but it needs some thought/discussion if these config options could be defined by users.

Looking at the list though, `nice` and `hideGridlines` feel relatively safe. With the rest I'm less comfortable. 

Potentially, we might also want to make it more explicit, have some separation, between public & private config options. It's only because of convenience that I've implemented things on `AxisConfigInterface` recently.

**Comment by larsyencken** [comment]
I agree with Gavrilov here, I would avoid adding anything that we do not expect to occur in any actual JSON grapher config. We should also ensure that we enforce that by checking everything against the schema.

It's ok to have a few more things than the schema in our private object model, as long as they are all automatically set and never set by config.

**Comment by danyx23** [comment]
We haven't seen a good use case to pull this up into the config proper from the internal state implementation so we think it's fine to close this issue.
