### ISSUE TITLE
Option to only show countries with data for all variables in selection dialog (hide countries with partial data)

### ISSUE THREAD

**Issue by HannahRitchie** [owid/owid-grapher#1177]
## Core problem

In some charts where we plot multiple variables we would like to hide countries which are missing data for some variables, because it leads to weird views that have no resemblance to the title, or are in some cases wrong. 

For example in [this chart of GDP and CO2 emissions](https://ourworldindata.org/grapher/co2-emissions-and-gdp-per-capita?time=1750..2019&country=~GBR) there are three variables which should be shown. But for some countries or regions, only GDP is available (see for example [Africa Eastern and Southern](https://ourworldindata.org/grapher/co2-emissions-and-gdp-per-capita?time=1750..2019&country=~Africa+Eastern+and+Southern)). Therefore when you select that country, you only get one variable plotted which is out-of-sync with the title and the point of the chart. 

![co2-emissions-and-gdp-per-capita](https://user-images.githubusercontent.com/35040753/154437103-fbc09262-0bff-49fe-9753-6533a7f58812.png)

**Other examples**:

- https://ourworldindata.org/grapher/production-vs-consumption-co2-emissions?country=~MKD
- https://ourworldindata.org/grapher/daily-new-estimated-covid-19-infections-icl-model?country=~Asia

## Proposed solution

An option in the Admin to hide countries from the "change country" dialog if they don't have data for all variables.

**Comment by danielgavrilov** [comment]
@HannahRitchie This doesn't apply to all charts right, because [Norway doesn't have "Nuclear" in this chart](https://ourworldindata.org/grapher/electricity-prod-source-stacked?country=~NOR), but we still would like to show it. So what we need is for **authors to have control when we want the suggested or existing behaviour** (but both need to coexist). Right?

**Comment by HannahRitchie** [comment]
Yes, good point. Having this be an automatic functionality would create a lot of problems, so it would have to be an author decision on a chart-by-chart basis.

**Comment by larsyencken** [comment]
We think you need a new config option, which can be `KEEP_IF_ANY_NON_NULL` or `KEEP_IF_ALL_NON_NULL`, or something equivalent. Right now we only offer the first option.

Scope:

- [ ] Config option
- [ ] Filtering code in entity selector 
- [ ] Admin checkbox

Note that we also can use variables for the x axis, and for color, and size. It's probably good enough to just do it for the y axis for now though.

**Comment by HannahRitchie** [comment]
@larsyencken, yes a `KEEP_IF_ANY_NON_NULL` customisation for authors is what we need 🙂
