### ISSUE TITLE
Map timeline tooltip shows wrong time

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1179]
## Description

The map handle is set to `"latest"` meaning `+Infinity` meaning the latest year in the dataset.

But the tooltip is showing the earliest year on hover:

<img width="1328" alt="Screenshot_2022-02-17_at_10_23_02" src="https://user-images.githubusercontent.com/1308115/154456340-9e775bc4-f1a6-4399-b9fe-d4f767d22592.png">

([link to chart](https://ourworldindata.org/grapher/population-since-1800?tab=map))

The same can happen when dragging the handle to `"earliest"`.

## Expected behaviour

The tooltip should show the correct year.

## Steps to reproduce

1. Go to any [map chart](https://ourworldindata.org/grapher/population-since-1800?tab=map)
2. Drag timeline to latest year
3. Click in the middle of timeline (without dragging)
4. Drag timeline to latest year again
5. Hover over the timeline to see the tooltip

The same can happen for the earliest year.

**Comment by danielgavrilov** [comment]
The issue seems to be that the map chart is actually shows **two handles** both the minimum and maximum handles.  

The easiest fix might be to hide the tooltip of the minimum handle for single-handle timeline charts (like map and bar chart).

**Comment by danielgavrilov** [comment]
Has been reported again on Slack: https://owid.slack.com/archives/C46U9LXRR/p1656922784624119

Not sure if it makes sense to elevate priority. Only if it takes a short time to fix? (I don't know)

**Comment by marcelgerber** [comment]
Has been reported again on Slack: https://owid.slack.com/archives/C46U9LXRR/p1674661716780109
