### ISSUE TITLE
Project: visualize uncertainty

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1180]
Author: @CGiattino 
Author-rated priority: High
Completed?: No
Created on: December 6, 2021 10:47 PM
Description: Make it easier and prettier to visualize uncertainty intervals.
Last modified: February 17, 2022 11:23 AM
tags: Author request

## Motivation

We want to effectively present data that has uncertainty estimates, for example the Economist's estimates of excess mortality.

Right now we track them as multiple variables.

## Considerations

One issue that I (Max) think we need to consider in the design is that most common designs of uncertainty visualization draws a lot of attention to very far away, unlikely values –– the 95% uncertainty interval. Spiegelhalter has good thoughts on how to avoid this by better design.

Most likely needs to be part of the data (i.e. proper confidence intervals as metadata) to be able to visualize accurately.

Some cases like the IHME that do provide the error bars have error bars that are very far from taking account for uncertainty in a trustworthy and prudent way. In those cases it's better to not show the wrong uncertainty interval – and instead surface our text that describes the issues with the data (e.g. in the Knowledge Window).

The huge majority of our data doesn't come with data on uncertainty; instead uncertainty's presented verbally by the writing that gives context to data. The knowledge window is also in the theme of tackling uncertainty.

## Examples

- Environmental impacts of foodstuffs (have to use the median today)
- Excess mortality according to the Economist's model
- Land use, water use, etc.

**Usefulf resources:**

- [Visualizing uncertainty](https://www.stat.berkeley.edu/~aldous/157/Papers/spiegelhalter_visualizing.pdf) – by Spiegelhalter

**Comment by larsyencken** [comment]
From triage: this is actually a big thing, which touches on our data model as well as the visual layout of the chart. We will talk about it as part of variable relationships and source switching.

We are already able to do this right now, in a just-good-enough way, e.g. https://ourworldindata.org/grapher/sea-surface-temperature-anomaly?country=~Global

We shouldn't do more work here until we have a clear picture of what would be much better and what it would take to do it.

**Comment by larsyencken** [comment]
Removing this, we can use a tracking issue if more specific things come up
