### ISSUE TITLE
Better handling of axis values when selected data changes

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1183]
Author: @HannahRitchie 
Author-rated priority: Low
Completed?: No
Created on: December 7, 2021 1:02 PM
Description: Charts are not very smart at picking y-axis minimum and maximum values when the data shown changes. This can trip some users up.
Last modified: December 7, 2021 1:06 PM
tags: Author request

### What's the problem or goal?

When we change the data shown on the chart (e.g. by changing country) the axis ranges do not automatically change very well. One simple example is when you look at China on [this chart](https://ourworldindata.org/grapher/traded-energy-share-domestic?tab=chart&country=~CHN).

The x-axis (y=0) should be shown, and the chart shouldn't fall out the bottom.

The goal would be to have smarter adaptability of y-axis minimum and maximums based on the data shown.

![traded-energy-share-domestic_(4)](https://user-images.githubusercontent.com/13406362/154457973-63c9f72a-c546-48e9-acf3-67e08168d867.png)

### If this idea works well, how will the user's life be different?

The y-axis changes smartly in line with the data shown, so users are not fooled or confused by weird axis cut-offs

**Comment by danielgavrilov** [comment]
Not a technical issue but a config issue, tracked in https://github.com/owid/owid-issues/issues/140
