### ISSUE TITLE
Enable 1x2 faceting

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1184]
Author: @CGiattino 
Author-rated priority: Low
Completed?: No
Created on: December 6, 2021 10:40 PM
Description: Right now if there are two entities selected, the faceted view shows that in 2 (rows) x 1 (column). It would be nice to have an option to show it in 1 row x 2 columns.
Last modified: December 14, 2021 4:08 PM
tags: Author request

**Comment by danielgavrilov** [comment]
@CGiattino Could you share an example (or a few) where you'd like this? Just to help figure out the details of the issue.

Currently, the grid is decided based on the **aspect ratio of the viewport** (e.g. on mobile it's quite tall and narrow), and the **ideal aspect ratio of a plot**, which is currently a constant defined in the code. Potentially, the ideal aspect ratio is dependent on the chart type and maybe the type of variable being plotted.

**Comment by CGiattino** [comment]
Looking at this now I think it's probably not a big deal / is low priority. I think when I wrote this I was looking at charts like this of [excess deaths vs covid deaths](https://ourworldindata.org/explorers/coronavirus-data-explorer?Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=USA~GBR~JPN&Metric=Deaths+and+excess+mortality) and thinking it would be nice to set a different faceting ratio.

**Comment by danielgavrilov** [comment]
Thanks! I will close this but feel free to re-open if it becomes a bigger deal.
