### ISSUE TITLE
Smaller fonts for article titles and excerpts

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1187]
Requested by: @maxroser 
Completed?: No
Created by: Matthieu Bergel
Created for: Anonymous
Created on: December 8, 2021 12:47 PM
Last modified: December 8, 2021 2:35 PM
Slack: https://owid.slack.com/archives/CLDM2AWCD/p1638570888025400?thread_ts=1638559949.023000&cid=CLDM2AWCD
tags: Author request

Thanks for adding this @Matthieu Bergel!

I like many things about the look of the site (colors, fonts, etc) but In general I would like it if things aren't so very large on OWID. It feels like living in Mario Land.

Headlines like this look way out of proportion to me:

<img width="1573" alt="Screenshot_2021-12-08_at_13 26 02" src="https://user-images.githubusercontent.com/13406362/154466709-b61f213e-2d5e-4e85-bbb7-e40449ebd509.png">

If I'd design it I would make the font a third as large or so.

And would less space between headings and the preceding and following text.

Also the 'Additional Info' boxes I would suggest should be less than half as high.

<img width="754" alt="Screenshot_2021-12-08_at_13 28 23" src="https://user-images.githubusercontent.com/13406362/154466919-1c5bb494-b598-4abf-bf1a-2b40c4de48d1.png">

The text 'Summary' here too:

- I'd just make it a bold word that precedes the text. Like so:
  
        **Summary:** Two centuries ago the majority…
    
- Or perhaps it shouldn't be placed there automatically. All the Summary box does in this option would be to make the background yellow and put a box around it. Whether the author wants to start the summary with the word 'Summary' is then up to the author –– that gives them the freedom to choose a different word (e.g. 'Key takeaway', 'Abstract', etc.).

<img width="812" alt="Screenshot_2021-12-08_at_13 30 48" src="https://user-images.githubusercontent.com/13406362/154467067-0fbefde6-f6a4-4779-9212-684484288483.png">

There are other things that I feel are too gigantic. But these are some examples to get thinking about whether you agree with me or not.

**Comment by larsyencken** [comment]
Marking this one as "needs design", since it risks snowballing as adjusting one thing leads to leading to adjust another, and so forth.

**Comment by ShwetKhatri2001** [comment]
@mlbrgl I'd like to make the changes if required now.

**Comment by mlbrgl** [comment]
@ShwetKhatri2001 thank you for offering! We still have some design work ahead of us for this to be actionable at the implementation level though, so nothing to do really for now here. We're working on making this delineation gradually cleaner so you'll be able to jump on issues more easily. Thanks again for your support!
