### ISSUE TITLE
Allow multiple Related URLs for a particular chart → Quasi-knowledge window

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1188]
Author: @JoeHasell 
Completed?: No
Created for: Anonymous, Anonymous
Created on: January 21, 2022 9:26 AM
Last modified: February 1, 2022 2:34 PM
tags: Author request

See [comments](https://www.notion.so/Allow-multiple-Related-URLs-for-a-particular-chart-Quasi-knowledge-window-7fb735443c6f4c468d4938e7c9529daf?d=3367a0997ac9447a9966af98fc9744af)

**Background:**

A key task for us is connecting the technical text that explains a metric to charts that show that metric.

The knowledge window is still far away. But maybe there are simpler incremental ways this could be done so that we can a) begin writing this type of content b) begin experimenting with how it should be displayed.

### **V0 is already implemented:**

The Related URL is already a step on this path.

([link to this Explorer](https://ourworldindata.org/explorers/coronavirus-data-explorer?facet=none&Metric=Stringency+index&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=USA~ITA~CAN~DEU~GBR~FRA~JPN))

<img width="1113" alt="Screenshot_2022-01-21_at_08 34 18" src="https://user-images.githubusercontent.com/13406362/154468680-4be90328-1af6-433c-8767-301797d486bf.png">

### **V1: A**llow multiple related URLs

From an author’s perspective that would already give us a lot of options.

**Example 1**

A nice example for where TWO related URLs would already be helpful is this chart by Bastian:

<img width="814" alt="Screenshot_2022-02-01_at_12 14 17" src="https://user-images.githubusercontent.com/13406362/154468755-b91d10a1-899a-49f2-af82-1c74a6b353a5.png">

Currently it links to this post: [https://ourworldindata.org/democratic-rights](https://ourworldindata.org/democratic-rights)

But it should have a second Related URL for→ ‘[The ‘Regimes of the World’ data: how do researchers identify which countries are democracies?](https://ourworldindata.org/regimes-of-the-world-data)’

**Example 2**

E.g. for a chart on poverty it could be:
– “Metric Explained”: [What is the poverty headcount ratio?](https://ourworldindata.org/extreme-poverty#what-are-the-main-indicators-used-to-measure-poverty)
– “Unit of measurement Explained”: [What is the International dollar?](https://ourworldindata.org/what-are-ppps)
– “Methodology Explained”: [How are surveys used to measure poverty?](https://ourworldindata.org/extreme-poverty#how-does-the-world-bank-estimate-extreme-poverty)

Or alternatively we are shifting away from the idea of these being ‘related links’ and towards the idea that these points tell you about the data itself: that it’s an extended footnote.

**Example 3**

- Data is measured in **international-$**, which means that differences in purchasing power and inflation are taken into account ➥ [Read more](https://ourworldindata.org/what-are-ppps)
- Global data relies on a mix of income and expenditure household surveys ➥ [Read more](https://ourworldindata.org/extreme-poverty#how-does-the-world-bank-estimate-extreme-poverty)
- Non-monetary sources of income, like food grown by subsistence farmers for their own consumption, are taken into account ➥ [Read more](https://ourworldindata.org/poverty-home-production-and-consumption)

### **V2: I**mprove design/layout of this feature → Quasi-knowledge window

I see that this is essentially the same project as:

Obviously space will be a constraint if we’re adding more related URL links - especially if we’re trying to write whole sentences, as in the second example above.

I’m very unclear what a good solution would be, but in recent sketches I’ve been imagining something like this ‘About this data’ box:

<img width="1180" alt="Screenshot_2022-01-21_at_08 46 13" src="https://user-images.githubusercontent.com/13406362/154468850-bc016a08-b2b2-49dd-9a9e-81efc2b687a8.png">

But maybe it should go below, or to the side of the chart. Maybe we should more directly embrace the idea that these are footnotes and think of a solution more along the traditional approach to footnotes (example below), just with better design.

<img width="408" alt="Screenshot_2022-01-21_at_08 56 32" src="https://user-images.githubusercontent.com/13406362/154468879-e072f79e-6a4a-4743-99d0-8f7cd24009e4.png">

One question would be what this quasi-knowledge window should look like when people externally embed our charts. Should it be there or not? (e.g. or could there be a parameter of the chart URL that specifies if this quasi-knowledge window shown or hidden?)

**Comment by mlbrgl** [comment]
@larsyencken refreshing my memory on the [vertical space optimization question](https://www.notion.so/owid/Improving-content-discoverability-through-embedded-graphs-4c5ce2d541f34cb5824fc9db01032dd9#3850db98d5f54debad0400af6f934f5e) (prompted by considering adding more than one related question), I realized the initial constraint I had in mind was how to add multiple related questions **without eating away at the chart space**, not so much whether the chart could shrink.
<figure>
<img width="1439" alt="20200625-related_question" src="https://user-images.githubusercontent.com/13406362/155183999-91eb9ffb-d207-4de8-9933-ac627f13f738.png">
<figcaption>Fig.1 - Compressing non-chart elements to make space for a related question (initial thinking, current design)</figcaption>
</figure>

**Comment by danyx23** [comment]
We could also have a **more** button next to the one related link if there are several which then opens a drop-down style menu above? Not the most elegant but it's tricky to fit more items there

**Comment by larsyencken** [comment]
@JoeHasell There's a general sense that we can't take this step too far and add multiple links here, since we have to accommodate tiny screen sizes (mobile browsers) where even one more link becomes compromising for the chart. It might be better for us to live with this constraint until we can identify a better general solution for technical text.

**Comment by JoeHasell** [comment]
That makes sense @Lars. This issue is at heart a broader question of how and where to fit the technical text in. That's something Matt, Matthieu and I are discussing, and is probably the better process for this question.

I think we can close this issue. But cc'ing @maxroser – as I think this request was something that he had suggested in a call.
