### ISSUE TITLE
Ops: set up docs domain and build process for covid docs

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1190]
## Problem

We want to serve docs for each project from a common domain, e.g. `https://docs.owid.io/<project>`

## Proposed solution

- [ ] Set up an `owid-docs` bucket, and a cloudflare worker to rewrite `docs.owid.io` to `owid-docs.nyc3.digitaloceanspaces.com`
- [ ] Set up `covid-19-data` to build to the `owid-docs` bucket on push

**Comment by larsyencken** [comment]
The first example docs that we'd do are: https://covid-docs.ourworldindata.org/en/latest/

**Comment by lucasrodes** [comment]
This was implemented:

- We have a repository for central https://docs.owid.io website: https://www.github.com/owid/owid-docs
- There, we list the different projects. 
- For instance, ETL docs live at https://docs.owid.io/projects/etl

The docs are hosted on RtD, and we use `sphinx` or `mkdocs` to create these.
