### ISSUE TITLE
Possible design improvements for Entries

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1192]
Author: @JoeHasell 
Completed?: No
Created on: February 16, 2022 8:31 AM
Last modified: February 16, 2022 8:34 AM
tags: Author request

### Most urgent: Improved design and range of prominent/automatic links authors can use

Related to: #1213 
Related to: #1147 (EDIT)

### Experiment: in-situ chart/slide switching

Our existing ‘All our charts on ...’ block is very good for letting people *quickly* navigate many charts.

The many links to charts in the current Energy topic page is in a way inferior user experience: you have to navigate away to see the chart.

Could we bring in something like the ‘All our charts on...’ block to the topic page?

Like this (which also shows other options for seeing the explorer and perhaps a mini slide-show). 

https://user-images.githubusercontent.com/13406362/154480004-632c8a69-3698-4174-b184-a8bf7addc303.mp4

I think something along these lines could help resolve many of the points people were bringing up in their [feedback on the energy topic page](https://www.notion.so/Thinking-about-the-Shorts-and-Entry-design-aaa45654a082481eb714b574724dd93d).

**Comment by larsyencken** [comment]
Marking this as "wont fix" for now, since we have a new All Our Charts block design that we're going to look at in the second half of this cycle (#1380). Feel free to revisit the idea on the other side of that, if you think it would still help then.
