### ISSUE TITLE
Project: allow switching of sources for different metrics

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1200]
## Core problem

For some metrics, there are tons of different sources. Or there may be two reference sources, e.g. WHO and IHME. 

## Proposed solution

We would like to easily co-plot or switch between metrics that are "the same". This requires some design thinking on how to reveal these relationships in Grapher when they exist, and a workflow for marking metrics as "the same".

## Technical notes

- What exactly we mean by two metrics being "the same" is hugely complicated and potentially error prone
  - We should probably err on being conservative here
- We should assume that every relationship needs to be manually added (by an author? by a data manager? in an admin interace?)

## Alternatives

We can get by by manually creating explorers that handle this for specific situations, without building anything new.

**Comment by danielgavrilov** [comment]
Relevant to this, with Jason >2 years ago we were discussing switching to **standardized measures** and **metrics** across the whole database. It was more conceptual, without concrete implementations.

Roughly:
- a **measure** would express the more general concept that is measured, e.g. food production, deaths
- a **metric** would concretely express the **unit of the measure**, e.g. food production (kg per day), deaths (total count)
- **every variable would have a measure and metric** assigned to it, and any two variables with the same measure & metric are the same and can be switched between

Also, along we would support multiple arbitrary dimensions in datasets – e.g. for deaths, you can have countries, causes, age groups.

This is also how the [IHME Global Burden of Disease](http://ghdx.healthdata.org/gbd-results-tool) structures their data – with measures and metrics:
<img width="395" alt="Screenshot 2022-02-18 at 14 30 09" src="https://user-images.githubusercontent.com/1308115/154701727-c83f487b-22da-4d8e-9743-c5d39be370c7.png">
<img width="372" alt="Screenshot 2022-02-18 at 14 30 16" src="https://user-images.githubusercontent.com/1308115/154701740-7ade06d1-3884-4b6e-ab3d-35c12b9709e4.png">

---

But once you have lots of multi-dimensional datasets, it becomes more complicated to express what is the _same_.

One idea was to use [**measure aliases**](https://www.figma.com/file/AQAy57MhNZNMCyBEeV4us6/Measures-%26-Variables?node-id=2%3A3):

<img width="907" alt="Intro to measure aliases" src="https://user-images.githubusercontent.com/1308115/154702435-9ba6be34-0aa8-4c0a-94a8-20cf540772a4.png">

**Comment by larsyencken** [comment]
Source switching relates to our direction of making an "Indicator-based OWID" with dimensions, closing this specific ask for now.
