### ISSUE TITLE
refactor: do not throw in getPostBySlug

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1204]
## Core problem

Throwing in [`getPostBySlug()`](https://github.com/owid/owid-grapher/blob/e925bd457c20da71aaf0d8ac5a279a63a430edee/db/wpdb.ts#L557) is not always helpful and often gets in the way. In this part of the codebase, we don't usually throw when a resource cannot be found. As a result, this creates an unusual need for special handling around this function: 
- in [`getPostBySlugLogToSlackNoThrow()`](https://github.com/owid/owid-grapher/blob/e925bd457c20da71aaf0d8ac5a279a63a430edee/baker/pageOverrides.tsx#L12)
- in [`renderPostThumbnailBySlug()`](https://github.com/owid/owid-grapher/blob/e925bd457c20da71aaf0d8ac5a279a63a430edee/baker/siteRenderers.tsx#L439)
- in [`renderProminentLinks()`](https://github.com/owid/owid-grapher/blob/e925bd457c20da71aaf0d8ac5a279a63a430edee/baker/siteRenderers.tsx#L476) 

## Proposed solution

Return undefined and throw in caller if necessary.

**Comment by larsyencken** [comment]
Marking it as nice to have, but we can bump it if it keeps coming up more. Also good to pick up in cooldown.
