### ISSUE TITLE
Wordpress: Make the 'thin' prominent link style the default (rather than 'default' as the default style)

### ISSUE THREAD

**Issue by JoeHasell** [owid/owid-grapher#1208]
cc @mlbrgl 

When pasting a link into Wordpress you have to manually change the style from 'default' to 'thin'. This is laborious, since we rarely – if ever – use the 'default' style. 

The 'thin' style should be applied by default upon copy and paste.

**Comment by mlbrgl** [comment]
@JoeHasell as a quick solution, you can define the default style as a one-off setting on any prominent link. This setting is per browser, and persists across pages and log-ins as far as I remember, so you only ever have to set it once.

<img width="269" alt="Screenshot 2022-02-21 at 17 47 10" src="https://user-images.githubusercontent.com/13406362/154998889-58feaa85-a5a2-41f4-bfa1-519752f616c0.png">
.

**Comment by JoeHasell** [comment]
@mlbrgl Ah sorry – I hadn't noticed that somehow! I'll close this, that's a fine solution thanks!
