### ISSUE TITLE
Feature: more varied prominent link support

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1213]
## Feature request (by @JoeHasell)

One issue identified with the new Energy topic page is that because, all links look the same, it makes it hard for the reader to distinguish between e.g. key flagship articles, shorts, charts, explorers, data etc.

This sort of differentiation was a quite important of our sketches of topic pages, and I think forms a central part of this whole experiment:

<img width="557" alt="Screenshot_2022-01-20_at_16 50 48" src="https://user-images.githubusercontent.com/13406362/154479723-8e00a1c3-5644-4cbd-ba86-b25b7c2e8ace.png">

There’s both a design and a tech element to this task: how do we want different links to show, and how do we implement that.

## Why / why now?

Topic pages are blocked needing design iteration. The lack of visual distinction between prominent links was a major critique.

## Who

Matthieu, Joe

## Success means

- Prominent links can visually distinguish between articles and charts
- Prominent links are no longer the blocker for future topic page rollouts

## Risks

- Better prominent links might not be enough to unblock topic page development, which might still need an overall design iteration
- Having more prominent link types could increase complexity in the CMS, so the implementation could drag out

## Context
- [notion request](https://www.notion.so/owid/Thinking-about-the-Shorts-and-Entry-design-aaa45654a082481eb714b574724dd93d#299e3cb0c6704449aa389a271dcd6d9f)
- Mar 4, 22: [slack](https://owid.slack.com/archives/CLDM2AWCD/p1646402177728299)

**Comment by mlbrgl** [comment]
planning to assess whether prominent links variations are still relevant based on the review of the poverty entry on Feb 23, 2021 with @JoeHasell and @mathisonian

**Comment by mlbrgl** [comment]
prominent links haven't been used as an element of the sketches of the poverty entry, presented on Mar 2:
- https://www.figma.com/file/t6uTma3ym4CNAhykNDdH8U/POVERTY-TOPIC-SKETCHES?node-id=0%3A1
- https://www.figma.com/file/KTAkwHJ7r21LTWzuegjEsK/Explorer-%3D-metric-search?node-id=107%3A3920
