### ISSUE TITLE
Concept: API for data access

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1215]
## Concept

Design a stable and performant API for accessing data from our data catalog.

## Working documents

- [Problem brief: API for data access](https://www.notion.so/owid/API-for-data-access-91f58e739435448db1c8444e50281a1a)
- [Condensed problem assessment: API for data access](https://www.notion.so/owid/Condensed-problem-assessment-API-for-data-access-401068cf7bb747bda2e9d3a0d32e948f)

## Key questions

- Will it be dynamic, or pre-baked?
- Will it be based off our data catalog, or off MySQL? (preference: data catalog)

**Comment by Marigold** [comment]
Might be a good idea to do after this https://github.com/owid/etl/issues/106 as multiple channels could significantly reduce size of the catalog (metadata) being pulled.

**Comment by larsyencken** [comment]
Notes from discussion on the solution space: https://www.notion.so/owid/Solution-space-API-for-data-access-e9141e8e421842478f85b0e8f2feec6f

**Comment by larsyencken** [comment]
Closing this for now, since we have an internal API implemented. We can open a new issue for future work on variants or improvements to that API.
