### ISSUE TITLE
Focus state on line chart legend gets stuck

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1218]
Migrated from Notion: https://www.notion.so/owid/Focus-state-on-line-chart-legend-gets-stuck-c3db0fe48c8f4f989f996998a9d7e618

## Description

When you move your mouse over the legend of a line chart and then off the chart, one line can get stuck in focused mode.

## Expected behaviour

When your mouse is not on the legend, no specific line should be in focus.

## Steps to reproduce

1. Go to a line chart with multiple entities.
2. Sweep your mouse across the legend and out of the chart
3. Repeat until one gets stuck

https://user-images.githubusercontent.com/36012/155513101-3eb9386f-34be-412c-96e4-16d873cd82b5.mov

## Proposed solution

@danielgavrilov suggested adding a `mouseLeave` handler on the container of the legend, which might have been there in the past but removed now.

**Comment by i-anuragmishra** [comment]
Hey @larsyencken if it's open I would Like to work on it. Thanks

**Comment by larsyencken** [comment]
Hi @i-anuragmishra , you're most welcome to give it a go!

**Comment by mpark63** [comment]
Hi @larsyencken, I believe there is a `mouseLeave` handle in `grapher/lineLegend/LineLegend.tsx` around line 227. Or is this not what you meant in the proposed solution? 
I also wanted to share with anyone interested that it might be arising from a known JS issue where if the cursor moves too fast, [a few intermediate DOM elements might be skipped](https://www.w3docs.com/learn-javascript/moving-the-mouse-mouseover-out-mouseenter-leave.html). I've tried replacing `mouseover` with `mouseenter` etc... but to no avail. 
I will keep working on it, thank you.
