### ISSUE TITLE
CSV file format guide redirects to About page

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1222]
## Description

The link to the 'csv file format guide' (https://ourworldindata.org/how-to-our-world-in-data-guide/#1-2-single-variable-datasets) on the 'Import dataset' page of Grapher, redirects to the About page.

(Initially reported by @spoonerf)

**Comment by danielgavrilov** [comment]
### Todo

- [ ] Remove dead link to About page
- [ ] Write up a guide on the blank `/admin/import` page. Should mention what the column names should be (investigate source code to figure out the requirements)

**Comment by marcelgerber** [comment]
There's no more "Import csv" page, so this is no longer relevant.
