### ISSUE TITLE
Project: Persist content graph in MySQL

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1223]
## Problem

- During baking, we currently construct a just-in-time content graph, which is expensive due to parsing
- During grapher chart edits, we also have to search for chart references in posts, which is expensive

## Proposed solution

Materialise the relationships between charts and articles or other pieces of content in MySQL for fast querying. We should also be able to add SDG references and explorer references here.

## Alternative solutions

Not so clear. Persisting to redis has been suggested, baking to static files has been suggested.

## Scope 

- [ ] #1194 
- [ ] #1353 
- [ ] #1466

## Context

- #1448 (similar concerns of surfacing back-references)

**Comment by danyx23** [comment]
Chatted with @marcelgerber about this. Some random notes:
* This will have to include redirects to be useful. See the [_redirects](https://github.com/owid/owid-static/blob/master/_redirects) file for a full view of what is redirected.
* We could either create specific tables for different types of entities or have a table with json content that can change by type
* It might be useful to have the information for links between WP pages and WP blocks
* Details on Demand are a kind of link that should be included
* The granularity of what a link is is interesting - for Graphers it makes a difference if you register the main url or the full or including the query parameters. Depending on what you want to know it could be very interesting to be able to differentiate this.
* It would be good to try and create a table or view that has all the relative urls that we know about and point to where this links to and what kind of entity that is
* Clearly define the update cycles for different pieces (SVG tracker can be manual, links in posts should probably be instantaneous as a view, explorers maybe on write in the gitcms?)

Use cases:
* conflicting redirects
* backlinks
* broken link detection

**Comment by danyx23** [comment]
Closing this in favour of #1353
