### ISSUE TITLE
Consider use of markdown/links in subtitles and footers

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1225]
## Core problem

Until we have a working knowledge window our authors often have to deal with the tension between trying to cram as much information and caveats into subtitles and footnotes. Hannah tries to alleviate this by pasting FAQs under explorers but it would be great if this could be more context sensitive. Once we have a working knowledge window then this will be used for such explainers, but since that is probably some way in the future the question here is if we can provide a short term solution without too much problems.

## Proposed solution

Allow use of markdown (or some other, maybe more limited markup language) to turn words or phrases in the subtitle and footer into hyperlinks that link to shorts that further explain those details.

## Alternatives

Stay with the current solution that can only use a single "related" link in the lower right corner.

## Evaluation

Our appetite for this is probably limited and we only want to do it if this is not too much work. To discuss:

- [ ] Where would we have to interpret this markup? Only in grapher?
- [ ] Is markdown a decent choice for now or is it too powerful? Should we just come up with our own markup for creating links?
- [ ] Other objections?
- [ ] What is the estimated size of implementing this?

**Comment by danielgavrilov** [comment]
We will leave this for the next cycle plan – we might like to do it if there is a scope we can finish in 1-3 weeks.

**Comment by larsyencken** [comment]
Giving it prio 2 "important" since it helps authors avoid the issue of having to overly repeat text in the subtitle.

**Comment by danielgavrilov** [comment]
Grapher subtitles and notes now support markdown links (implemented in #1552).
