### ISSUE TITLE
Timor should be renamed to East Timor

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1227]
## Description

We use the display name "Timor" to refer to the country known as "East Timor" or "Timor-Leste". Timor is inappropriate since it refers to the overall island, whereas the country East Timor is just the east part of that island.

## How to change a country name

- Change the code in `owid-grapher`
- Add a `owid-grapher` data migration and run it
- Update the code in `covid-19-data`, which we run hourly
- Update the code `importers`, each section of which gets run a few times a year

**Comment by danielgavrilov** [comment]
A past PR that renamed countries: https://github.com/owid/owid-grapher/pull/734

**Comment by eri-tsuzuki** [comment]
Nice to meet you. My name is Eri Tsuzuki. I am from Japan and am a third-year university student at the department of Economics, especially Demography.

I worked on this issue.
https://github.com/owid/owid-grapher/pull/1248

Please check my code. Thank you.

**Comment by larsyencken** [comment]
Even though we want this to be better, we need to get more examples of bad countries before we can motivate this change.
