### ISSUE TITLE
Decoupled web projects under ourworldindata.org

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#123]
Nothing to look at right now, just organizing some thoughts I have floating around.

OWID tech at the moment is very centralized and about scaling a standard pattern of articles and visualizations. This is effective, but especially as we attract more fun developers and designers, it would be cool to also be able to do some really good once-off creative web projects like Nadieh Bremer or Nicky Case do. I'm particularly thinking of Parable of the Polygons: https://ncase.me/polygons/

How would we actually build those and attach them to the domain? Some considerations:

Netlify has a mechanism for proxying one netlify project on a path to another: https://stackoverflow.com/a/48604942/1983739 This is how the grapher works right now. We could also use it for independent subprojects.

The very old header navigation on the site wouldn't work for such subprojects, since you need to rebake it for every new entry and that couples everything together. If we wanted to have a similar kind of navigation that is compatible we could do it with some JS that grabs an independent list of the entries.

There's no way to really build upon the grapher tech for custom projects right now. That would be one motivation for separating out the frontend as its own library.

In most cases I imagine it would be reasonable for the data and content of any custom projects to go directly in the github repository and be updated manually, so we wouldn't need to worry too much about coupling with the database.

**Comment by breck7** [comment]
> There's no way to really build upon the grapher tech for custom projects right now. That would be one motivation for separating out the frontend as its own library.

In Next, we now have about a dozen subprojects, and all components of Grapher are now decoupled and unit tested. So we could use bits and pieces in interesting ways for bespoke visualiations.
