### ISSUE TITLE
Update covid vaccinations table automatically

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1231]
## Core problem
Lucas manually updates [a COVID vaccination table](https://ourworldindata.org/covid-vaccinations#source-information-country-by-country) every day by copying [generated HTML](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/source_table.html) from a script, and pasting into the Wordpress editor ([slack](https://owid.slack.com/archives/CLDM2AWCD/p1646220129149699)).

## Proposed solution

Keep the table updated using a new `<DataToken>`: `{{RawHTML url="xxx"}}`.
This would require the table HTML to be available on a public URL, e.g. https://covid.ourworldindata.org/xxx.

For reference, another `<DataToken>` currently in use is: `{{LastUpdated timestampUrl="xxx"}}`

SEO considerations: Google renders the `{{LastUpdated}}` correctly (recheck on https://search.google.com/test/mobile-friendly to confirm understanding of crawled vs rendered).

Performance: extra request + JS rendering

The main advantage of this solution is that it uses the existing DataToken framework, so effort would be minimal. Also, the site doesn't need to be rebaked for the change to take effect, so feedback loop is tighter.

## Alternatives
- server-side <DataToken> (currently, the <DataToken> configuration is generated on the server but rendered on the frontend). This is probably the next best alternative, but requires more dev. 
- move table HTML into reusable block and update using Wordpress API
- inject SQL

**Comment by mlbrgl** [comment]
@lucasrodes nice! #1392 requires a slightly modified version of the vaccinations-source-table.html file to work:

https://user-images.githubusercontent.com/13406362/163555799-ed8ce111-ea52-46ef-9e28-7f3d7941ce0c.mov

**Comment by lucasrodes** [comment]
Thanks @mlbrgl!

I updated the table accordingly, should be live at https://covid.ourworldindata.org/data/internal/vaccinations-source-table.html!
