### ISSUE TITLE
Triage issue-spotting session issues for site

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1237]
see 
- https://owid.slack.com/archives/CLDM2AWCD/p1646746400762349
- https://docs.google.com/spreadsheets/d/1pzDLxB7TalliYVrO3JctbuKjkgK1tm9J5kwxrWdtBsU/edit#gid=660478851

**Comment by danyx23** [comment]
@mlbrgl some time has passed now and it looks like most are triaged - can we close this now?

**Comment by mlbrgl** [comment]
@danyx23 there are still more than 50% that haven't been looked at, but so far I believe none of these issues have made it to the top of the pile. What I can do is take a cursory glance at the remaining ones, and only surface those that I believe are critical and unknown. The rest will fall through the cracks. 

Probably better that way than spending time creating issues only to close them a few weeks later, what do you think @larsyencken?

**Comment by mlbrgl** [comment]
Two issues were brought up repeatedly:
-   missing publication date. This is now clearly identified as part of #1487 and needs to be solved with that larger scope in mind
-   text / chart alignment issues on medium-size screens (#1377, #1397). This will be addressed by Marwa's redesign of the articles and topic pages ([figma wip](https://www.figma.com/file/9bQW46okOjxeJtismQQdPu/%5BDesktop%5D-Screens-1.0?node-id=148%3A4496))
