### ISSUE TITLE
Add a language button that links to google translated pages

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1246]
## Core problem

We only publish in English but a large part of humanity doesn't speak it that well. Google translate does a pretty good job translating our site (even charts!) but many non-english speakers are probably not aware of this.

## Proposed solution

We could add an English flag icon + EN label in the top right of our page that opens a drop down with other languages that google translate supports. Clicking a different language would redirect to the google translated page (e.g. [like this](https://ourworldindata-org.translate.goog/military-spending?_x_tr_sl=en&_x_tr_tl=de&_x_tr_hl=en-US&_x_tr_pto=wapp)). We should make it clear that these are automatic translations.

We discussed this a bit [here ](https://owid.slack.com/archives/C0149NKLZAM/p1646680573220029) in slack.

## Alternatives

We could either leave it as is and only have the English page or we could double down on this and have human translations (maybe volunteer translated?) but that would be a big project to keep the whole content up to date etc.

**Comment by danielgavrilov** [comment]
I have a few worries that this seemingly small task turns into a big task.

- **Design**: We need to restructure the header and change the breakpoints to accommodate a dropdown. Making it clear it's automatic means either that information is in the header (probably not) or we have a non-standard dropdown that contains a notice (probably)
- **Design**: We need to design the option for mobile too?
- Google Translate doesn't interact well with React, Marcel has been fixing Google Translate related issues ([latest](https://github.com/owid/owid-grapher/commit/fed56e7bdc147ce548790a627f97857b06a09858)). We will need to review in more depth before deploying.
- Line breaks in charts change, and in turn width/height calculations change, leading to things overflowing. We might want to change how that works.
- How will it interact if someone translates the site using the browser prompt? (don't want double-translation happening)

Also, I'm not sure whether the potential value is truly high:
- Most browsers (Chrome, Edge & Safari by default) already offer to translate websites, in a more noticeable way, and smoother in-place translation.
- Non-english speakers I know already use translation often (a lot of the web is in english)

**Comment by larsyencken** [comment]
Marking as "wontfix" since this is quite expensive for a nice-to-have and risks blowing out.
