### ISSUE TITLE
Reach feature parity between Docker Compose and Lando dev setups

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1249]
A few follow-up tasks after the migration to Docker compose to reach feature parity with the previous Lando setup (#1230):
- [x] #1381
  - [x] #1593 
  - [ ] ~~#1638~~
- [ ] reinstall wp-cli? (used by [db_search_replace.php](https://github.com/owid/owid-grapher/blob/master/wordpress/web/app/plugins/owid/src/db_search_replace.php))
- [x] XDEBUG setup (see https://github.com/owid/owid-grapher/commit/63a1f95b13c66b5476f227e34d237d05a10f663c)
- [x] update README with use cases in mind

**Comment by danyx23** [comment]
@mlbrgl can we close this issue?

**Comment by mlbrgl** [comment]
@danyx23 almost! See my comment in https://github.com/owid/owid-grapher/pull/1638#issuecomment-1263719846

Issue description updated accordingly.
