### ISSUE TITLE
Small horizontal scrolling on pages

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1251]
_reported by @maxroser_
## Description

Small horizontal scrolling on pages (not posts)

## Expected behaviour

No horizontal scrolling on pages

## Screenshots

https://user-images.githubusercontent.com/36012/170021901-765cb919-0b02-46f0-8ae2-b439dd33463d.mov

## Environment

TBD

**Comment by danyx23** [comment]
Can reopen after the site grid work is done which will probably fix this issue
