### ISSUE TITLE
Self-redirects (same source and targets) lead to infinite recursion

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1257]
## Description
Infinite recursion in URL resolver possible when source and target are identical:
https://github.com/owid/owid-grapher/blob/8e650f6443c8e76269fd36200afff8c297451b46/baker/redirects.ts#L119-L134

## Expected behaviour

Break the recursion if:
- source and target identical
- more than x recursion levels

## Steps to reproduce

- Create a redirect with source and target identical
- Add a prominent link using that URL

## Additional context
[slack conversation](https://owid.slack.com/archives/CQQUA2C2U/p1647252505522149)

## Checklist
- [x] how were those redirects created in WP admin?
--> Manually, see [slack](https://owid.slack.com/archives/CK0RKGGSC/p1647255388603159)

**Comment by marcelgerber** [comment]
Tasks:
- [ ] Break the recursion (as outlined above)
- [ ] Add a test case
- [ ] In the event of a recursion break, log an error to Slack

**Comment by mlbrgl** [comment]
Downgrading to "important" now that the source of those redirects have been identified, and won't be added in the immediate future.
