### ISSUE TITLE
Tracking issue: better tables

### ISSUE THREAD

**Issue by maxroser** [owid/owid-grapher#1263]
## Issues with tables today

- [x] #1272
- [x] #1273
- [x] #1274
- [x] #1275
- [x] #1276
- [x] #1876
- [x] #2787
- [x] #2831

## Full description

This became very clear in our issue spotting session. Several of the issues that were catalogued are about this.

Two problems:
- Tables don’t show the actual title and subtitle and therefore don’t make it understandable to the reader what data they are displaying.
- The titles and units of measurement that are shown in tables are often very unclear and look weird.
  - The table version of a chart in "Relative" mode should automatically add the % sign to all values

I think even a one-week-project that focuses on the most problematic aspects of tables could be very useful. 

One possible project that this could be a part of is the ‘all chart types on different tabs’-project that @danyx23 will be working on. In a way, tables are a different chart-type. For example it would already be helpful if the title and subtitle (as shown on the line-chart) would also be shown above the tables.

**Comment by larsyencken** [comment]
We're using this issue now as a holder to track all the issues for tables. If you spot more, feel free to add them.

**Comment by danyx23** [comment]
This project should also consider other improvements to tables (e.g. allowing to sort and maybe filter)

**Comment by larsyencken** [comment]
> This project should also consider other improvements to tables (e.g. allowing to sort and maybe filter)

Feel free to add more here and reformat the main card for the issue.

I'd prefer that we don't think of tracking issues as projects, but instead treat them as things that are bigger than projects and outlive any one push. They make a good place to accumulate issues and ideas for improvements in a problem area. 

We've seen in the past that accumulating issues in a project gets weird when we reach our appetite and close the project, but there are tons of issues left undone. I think all the undone things should get pushed back to the tracking issue.

**Comment by maxroser** [comment]
One thing that would be helpful for tables is to **filter**, as Daniel also says above. 

The most basic one that would already be very helpful is to see only countries — and filter out aggregate world regions. 
(For tables that's so helpful because in most sorted tables right now it's the world regions that dominate the top.)

[Later we could add additional filters: see all European countries, see all countries with a GDP per capita over $10,000, etc.]

**Comment by sophiamersmann** [comment]
One issue with Grapher's data tables that came up in the Grapher redesign bug bash is that the "Relative change" column sometimes doesn't make sense ([example chart](https://ourworldindata.org/grapher/lgbt-rights-index?tab=table&time=earliest..2019)).

We discussed this in yesterday's tech tea, and considered our options:
- Keep the table as is, but allow authors to hide the change columns
- Show raw data for all entities and all years (needs design work to make the table easy to digest, and an engineering effort to make this performant)
- We could also go maximalist and integrate a spreadsheet, or maybe provide a link to a Google sheet with the chart's data

**Comment by larsyencken** [comment]
The idea of generating public Google Sheets for our indicators is super interesting. That deserves its own partitioned-off cooldown exploration at some stage.

**Comment by natasha-ahuja** [comment]
This comment reminded me of how the team behind Information is Beautiful shares its data ([Link](https://informationisbeautiful.net/data/)). 

A related idea --  both Data is Plural & Information is Beautiful (among others) make it possible for users to sign up for email updates when new data is uploaded to their databases. That's also something that I can imagine some users might really like for their topics of interest.

**Comment by sophiamersmann** [comment]
Superseded by https://github.com/owid/owid-grapher/issues/3175

The problems mentioned in this issue have been resolved in the Grapher redesign (& other efforts). To keep things tidy, I have created a [new tracking issue](https://github.com/owid/owid-grapher/issues/3175) that tracks problems of Grapher's data table as it is today.
