### ISSUE TITLE
Tracking issue: categorical variable improvements

### ISSUE THREAD

**Issue by maxroser** [owid/owid-grapher#1264]
## Known issues

- [x] #1273
- [x] #1323
- [x] #1324
- [ ] #1325

The way we work around it is is to have half a legend below the chart and the other half in the subtitle like this:
<img width="709" alt="Screenshot 2022-03-14 at 16 31 53" src="https://user-images.githubusercontent.com/14162061/158217820-9e33d0e1-7023-4b01-935a-5065add4d362.png">
[link to the map](https://ourworldindata.org/grapher/forest-transition-phase?country=~BOL)

**Comment by danyx23** [comment]
Changed the link for "tables do not work for categorical variables" to point to a similar issue that is already triaged

**Comment by sophiamersmann** [comment]
Let's keep this one open

**Comment by danyx23** [comment]
Most of these have been fixed so we are closing the tracking issue and only keep the remaining sub-issue open
