### ISSUE TITLE
Cleanup: Remove superfluous whitespace in chart FASTT

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1265]
## Problem

There is excess whitespace all through our FASTT.

## Proposed solution

This time around, let's attempt to do it on the _input_ side. If we do that and it comes up again and again, we should admit defeat and do it on the _output_ side instead.

- [x] Trim whitespace on save in the chart admin
- [x] Trim whitespace on save in the variable admin
- [ ] Trim whitespace on save in the bulk FASTT admin
- [ ] Do a once-off migration to fix any cases of excess whitespace in the data

---

(Initial report by @marcelgerber)

We have lots of charts where the title, subtitle etc. contains one of the following:
1. Extra whitespace _before_ the actual text, e.g. `•Net portfolio investment`
2. Double spaces _inside_ the text, e.g. `Taxes on goods••and services`
3. Extra whitespace _after_ the text, e.g. `Union density•`

This isn't too bad (since the browser won't render them), but we should clean them up nonetheless.

We can query for just these charts using something like the following query (for case 2 here):
```sql
SELECT config->>"$.title", id
FROM charts
WHERE config->>"$.title" LIKE "%  %"
```

We can and should normalize these using MySQL functions such as [TRIM and REGEXP_REPLACE](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html). We should also ensure that they are normalized in the Grapher Admin _before_ they are saved to the database.

---

(More details from @danielgavrilov)

#### This issue

A bulk update should be fine. One thing we might want to do is **bump the version number in the chart config**, so they get republished (if whitespace gets rendered anywhere).

```sql
UPDATE charts
SET config = JSON_SET(
  config,
  "$.version", config->"$.version" + 1,
  "$.title", '...',
  "$.subtitle", '...')
WHERE
  ...;

```

#### Related issue

There is a very related issue with trailing newlines, documented here: https://github.com/owid/owid-grapher/issues/1092 Potentially we could add to that to trim the extra whitespace on render?

#### How to prevent this issue

How/should we prevent extra whitespace from being saved in the config? 

1. One way is not to, and only make sure it's handled on render, as above. This means the database could still contain useless whitespace. One way it might be bad is if this stuff ever is used outside Grapher (for example in a page like [all charts](https://ourworldindata.org/charts) or in search).
2. Or, we could make sure the Admin trims whitespace before saving.

Since this is an easy fix, it doesn't seem that we'd accumulate maintenance costs if we don't address it now.

**Comment by larsyencken** [comment]
See also:

- #1092

**Comment by larsyencken** [comment]
Closing this for now, although Bulk FASTT might still need work in future.
