### ISSUE TITLE
Axis tick labels do not include sufficient decimal places for small values

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1267]
## Description

Axis tick labels sometimes do not include sufficient decimal places.

## Expected behaviour

Axis ticks should display enough decimal places to be meaningful.

## Example

https://ourworldindata.org/grapher/share-of-cumulative-co2?tab=chart&time=latest&country=~MKD

## Screenshots

![image](https://user-images.githubusercontent.com/7103774/158381537-5c221bcd-7153-410b-b174-9b96548391cb.png)

**Comment by larsyencken** [comment]
From discussion with Gavrilov: there's already logic to do this for some charts, but for some reason it's not being invoked in this case. The main work would be debugging this specific chart and trying to see why that logic doesn't get run.

**Comment by marcelgerber** [comment]
I'm reopening this now because of the different fix proposed in #1422.
