### ISSUE TITLE
Tables do not show title and subtitle

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1272]
## Problem

When we visualise data in a chart, we try to describe the data in the title and subtitle to make it easier to understand.

When you click on the table view for the chart, the title and subtitle disappear. Since many people share links to the table view directly, we often get asked questions about the table that are answered in the title or subtitle.

## Example

https://ourworldindata.org/grapher/gdp-per-capita-maddison-2020

The chart view

<img width="1100" alt="Screen Shot 2022-03-18 at 14 32 25" src="https://user-images.githubusercontent.com/36012/159012085-9b4fe96a-e04f-4f70-8e72-601623542a52.png">

The table view

<img width="1095" alt="Screen Shot 2022-03-18 at 14 32 29" src="https://user-images.githubusercontent.com/36012/159012042-e7ef88ec-2794-49e7-8208-a038dec393ab.png">

^ this table also has a spurious "annotations" section, that's a different issue

## Proposed solution

We think this could be improved by maintaining the title and subtitle for the chart, even when displaying the table view.

**Comment by jesi-rgb** [comment]
Hi! I would know a bit more about this. What tables are we talking about? I see that in [here](https://ourworldindata.org/owid-grapher), the tables have titles, but that may not be what you mean.

**Comment by larsyencken** [comment]
Hey @jesi-rgb , I tried to explain it better now. Does that make sense?

**Comment by jesi-rgb** [comment]
Yeah, crystal clear!

Should we preserve the exact title and subtitle, as in the main chart? Or may we font-match it to the table?

The charts have serif fonts but the tables do not. Minor, but I think rather important detail.

**Comment by larsyencken** [comment]
@jesi-rgb We talked about it now and figure that actually we don't want to do this until we've got a design for it that we're happy with. Thanks for investigating anyway!

**Comment by jesi-rgb** [comment]
@larsyencken no problem!
