### ISSUE TITLE
Support static images with transparent background more easily in articles

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1280]
## Core problem

@maxroser would often like to include images in the text, usually charts, that have a transparent background and blend more seamlessly into the text. Right now that's painful to do.

<img width="846" alt="screenshot_2022-03-17_at_11 27 11" src="https://user-images.githubusercontent.com/36012/158802926-1c25d8e2-c326-4434-ad21-5e02a49f2f86.png">

## Proposed solution

Provide a new way to include such images in the CMS that removes the box-shadow and displays them inline with the text.

**Comment by mlbrgl** [comment]
There is additionally the question of whether these images should be lightbox-enabled. In the early (manual) implementation, we decided against it but worth revisiting if this should be more of an on/off option. 

See also the [list of inline / no frame / no ligthbox image blocks manually created](https://www.notion.so/owid/CMS-for-no-frame-no-lightbox-inline-images-ef9a3980443c4548b28e5abf9cb553d3#fb532d4df77143e195a9f09d0ee880f8) so far.

**Comment by danyx23** [comment]
@mlbrgl if you can fix it within an hour or two feel free to fix it, otherwise we would close it as wont-fix for now

**Comment by mlbrgl** [comment]
@danyx23 isn't `nice to have` better in this case? Closing it means it will stand very little chance to get picked up during cooldown.

**Comment by larsyencken** [comment]
Seems unlikely it'll be picked up before August. I'll close it for now, but we can always reopen it if it's asked for again.
