### ISSUE TITLE
Add Instagram to social links

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1283]
_Suggested by @CGiattino ([slack](https://owid.slack.com/archives/C023SHCDB1Q/p1647514428556719))_

- [ ] Homepage
- [ ] Footer
- [ ] ?

**Comment by ianxul** [comment]
Hello. I am looking to participate in the Google Summer of Code in this project and think this would be a good first issue to start getting used to the code base (I guess that's also what the "good first issue" tag means). I can see where the social links are in the homepage and in the footer, but I was wondering what the interrogation sign in the checklist means...

**Comment by marcelgerber** [comment]
I checked where we link to Twitter on our site, and it is indeed only on the homepage and in the footer. So I think we're good after @ianxul's PR :)

**Comment by mlbrgl** [comment]
thanks @ianxul, thanks @marcelgerber!
