### ISSUE TITLE
Design: Every chart can display nearly all chart types

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1295]
This is the placeholder issue for the design work for #1162. Design considerations will be logged here in the Mar/Apr iteration, implementation work will probably happen in the May/June iteration.

**Comment by danielgavrilov** [comment]
Copying from issue-spotting session: 

> In line-chart/bar-chart hybrids such as this one, I intuitively do not know how I have to drag the slider to either give me a bar chart per year or a line chart across time.

The explicit tabs should hopefully make this easier.
