### ISSUE TITLE
Change the default color scheme for DiscreteBar to 'OWID Distinct'

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1296]
A request from Max ([Slack discussion](https://owid.slack.com/archives/CLDM2AWCD/p1646406804766299)).

We would like `OWID Distinct` to become the default color scheme for DiscreteBar. Currently all bars are blue by default ([chart](https://ourworldindata.org/grapher/global-warming-potential-of-greenhouse-gases-over-100-year-timescale-gwp?country=~OWID_WRL)): 

<img src="https://user-images.githubusercontent.com/1308115/159249327-4220341e-c69c-4811-ab76-9e12c34f950d.png" width=600 />

With `OWID Distinct`:

<img src="https://user-images.githubusercontent.com/1308115/159249527-2e3871dd-3e6e-43c4-b751-ff8240dd9439.png" width=600 />

**Comment by danielgavrilov** [comment]
Currently we have some logic to check if a DiscreteBar is a LineChart-turned-DiscreteBar using the timeline, perhaps that logic becomes part of DiscreteBar now?

**Comment by danielgavrilov** [comment]
There are some implementation details in a (now closed) PR: https://github.com/owid/owid-grapher/issues/1296

**Comment by danyx23** [comment]
Closing this; as part of issue #1118 it was decided that distinct bar charts should be single color by default instead and it was implemented like this
