### ISSUE TITLE
TextWrap: do not render unescaped HTML when linkifyText is `true`

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1299]
## Description

In the subtitle of Grapher charts we currently use `linkifyText: true` which will wrap any strings beginning with `https://` with `<a>` tags. But it also means we are injecting unsanitized HTML, so if an author writes `<0.1mm` in the subtitle, that gets treated as an HTML tag and is omitted by the browser.

## Expected behaviour

When we wrap with `{ linkifyText: true, rawHtml: false }` we should escape HTML.

## Example

For the following chart, we had to replace `<` with `&#60;` to get the subtitle rendering properly, otherwise it breaks:

https://ourworldindata.org/grapher/prevalence-of-vitamin-a-deficiency-in-pregnant-women

## Technical scope

- [ ] Do a data migration of all HTML entities in published charts
- [ ] Fix the escaping in subtitle rendering

**Comment by danyx23** [comment]
I think this should be fixed now that we parse content and render it differently since we have DoDs
