### ISSUE TITLE
Project: implement the key insights block for topic pages

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1301]
## Overview

We want to surface most important insights and data in a digestible and easy to find way. The "Quick Insights" block is part of this. We should 

## Scope (Cycle 2)

- [x] Convert low-fidelity mockups into realistic, high-fidelity design mocks
- [x] Implement the high-fidelity version of the block in HTML+CSS
- [x] Wire this up to the baker

## Scope (Cycle 3)

- [ ] Merge CMS support for key insights
- [ ] Publish key insights block live on the poverty page (Joe)

## Success means

We would like to get the final design approved and get this block onto at least one topic page. We can start by deploying it to the Poverty entry with @JoeHasell handling the content, and can add it to other, smaller topic pages after that. The success criteria here will be defined as feedback and approval from the research team.

**Comment by larsyencken** [comment]
@mlbrgl @mathisonian

**Comment by larsyencken** [comment]
Linking in the high-fidelity figma prototype:

<img width="1124" alt="Screen Shot 2022-04-11 at 14 43 16" src="https://user-images.githubusercontent.com/36012/162741729-2a3f1151-6ac2-43ad-a95c-aafb2e2b9fcc.png">

https://www.figma.com/file/g0DBDgC0PLhXTLEHwy99dw/HIGH-FIDELITY-POVERTY-PAGE-3%2F22?node-id=0%3A1

**Comment by mlbrgl** [comment]
Gathering here the discussions related to the data model and implementation of key insights, for reference:
- March 30: [decision to go with `one key insight = one short` approach](https://www.notion.so/owid/c895fc5b178f49ab821ebd9bf0931d05#76c365bd152a4d67af4ae2802a7570f9)
- April 14: [reservations about `one key insight = one short` approach](https://owid.slack.com/archives/CLDM2AWCD/p1649923125439659)
- April 20: [comparison with `key insights are part of the topic content` approach](https://www.notion.so/owid/071e174050894b73a1dae801507933b9#b7dfb45455aa43fc8b3125845b7a3d5d)
- April 21: [decision to go with `key insights are part of the topic content` approach, with description of trade-offs](https://owid.slack.com/archives/CLDM2AWCD/p1650570785844799)

**Comment by mlbrgl** [comment]
Progress:
- Demo
<img width="1438" alt="Screenshot 2022-04-27 at 18 54 18" src="https://user-images.githubusercontent.com/13406362/165579469-73852e62-2e55-4548-8e3d-a717f06dec7e.png">

**Comment by mlbrgl** [comment]
Progress:
- CMS intention approved by authors (Apr 28th, [slack](https://owid.slack.com/archives/CLDM2AWCD/p1651128368191779?thread_ts=1651079238.129079&cid=CLDM2AWCD))
- [x] CMS implementation

Next steps:
- finish tests
- submit PR

**Comment by larsyencken** [comment]
Updated scope for this cycle, and removed reference to getting it into the CMS, since I understand that's part of the exist work to merge.
