### ISSUE TITLE
Allow blog content endnotes to be anchor linked

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1308]
## Core problem

Not to be confused with #1225 

Today I was having a discussion about [an article](https://ourworldindata.org/malaria-introduction) that required me to reference something that was only mentioned in the article endnotes. As is, I had to write which endnote I was referring to, which was fine, but for "wikipedia-feel" parity I would like to be able to link to the endnotes directly.

[The endnotes are actually already correctly ID'd to be anchor linked](https://ourworldindata.org/malaria-introduction#how-can-the-world-make-progress-against-malaria#note-5), but the citation tooltip click handler seems to be overriding behaviour that appends the anchor link to the browser's URL, so there's no way to share a link with a endnote anchor link without already knowing about this browser behaviour (and the ID naming format we use: `#note-1`)

## Proposed solution
Give the "Endnotes" heading its own "chain link" icon like other article headings that allows users to easily link to it if needed.

## Alternatives
1. Close this ticket immediately, because the endnote tooltip is working as intended
2. Tweak the endnote click handler to append the anchor link ID to the URL, so that when you click on a citation reference, your URL is also updated but page location isn't moved. (_This was my initial thought, but I think it's messier than the thing I've proposed_)

## Context

![anchor-link-mockup](https://user-images.githubusercontent.com/11844404/159528171-bc6874de-edc9-4133-8603-9ee4451acd5a.png)

**Comment by marcelgerber** [comment]
There is some discussion of exactly this in the very old #436, where I initially implemented the interactive-tooltip footnotes (before that, they were only jump-to-anchor).
In fact, in my initial go at it I included a "Jump to footnote" link in the footnote itself that links to the anchor - just like Wikipedia does with its "Jump to reference". Screenshots in there.

**Comment by danyx23** [comment]
Sounds nice but we won't schedule this as it seems not very high priority - feel free to fix it in cooldown though!
