### ISSUE TITLE
Automatically linkify DOIs and PMCIDs in Sources when present

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1326]
## Description

> On the sources tab for the Covid sequences by variant I noticed that the DOI URL is hyperlinked strangely - the full doi hasn't become a URL but a small part of it is a broken url to that little bit of the url.

https://ourworldindata.org/grapher/covid-variants-bar

<img width="790" alt="Screenshot_2022-03-29_at_14_16_26" src="https://user-images.githubusercontent.com/1308115/160619907-68205136-cb11-4c14-a793-88eaa676675c.png">

## Expected behaviour

The DOI URL shouldn't be turned into a link

**Comment by danielgavrilov** [comment]
Not clear how easy this is to fix. Maybe there is a library out there that has less false positives.

**Comment by larsyencken** [comment]
As a proposed solution, why not make things nicer? 

In this case, we could linkify both DOIs and PMCIDs in a sensible way, and that would be a nice enhancement. Nothing like fixing a regex with another regex!
