### ISSUE TITLE
Relative-only LineCharts with mixed units shouldn't collapse to DiscreteBars

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1327]
## Description

A "relative LineChart" plots the difference of the value from the starting point of the timeline to the endpoint of the timeline ([example](https://ourworldindata.org/grapher/kaya-identity-co2?time=1988..2001&country=~DZA)):

<img src="https://user-images.githubusercontent.com/1308115/160620726-7dc0dfb7-a83a-4dd0-9076-cc5c53dcbc33.png" width="600" />

When a LineChart timeline is collapsed into a single point, it becomes a DiscreteBar:

<img src="https://user-images.githubusercontent.com/1308115/160621123-b29c2777-99c4-4ef5-a2f5-cef0247faee7.png" width="600" />

The issue in this example is that the metrics have different units, so tonnes is simply incorrect here. It's for this reason that the relative toggle was disabled for this chart.

## Expected behaviour

If a relative-mode chart has mixed units, you should not be able to switch it to unrelative-mode. Collapsing a single year to a bar chart is a form of switching to unrelative-mode, so it should also be disallowed.

## Technical notes

To be robust, it should not be possible to collapse neither by interacting with the timeline, nor by setting the URL parameter manually.

## Proposed solution

- Do not do any fancy detection of common or mixed units
- Instead, just check if relative mode is optional or not for this chart. If going "unrelative" is not possible, then the timeline should not be collapsable
- A possibility is to simply show no data for a collapsed timeline

**Comment by larsyencken** [comment]
Estimate as 1h if we just say "no data" when you collapse, though it would be nicer to tackle #1378 at the same time which is estimated at 1d.

**Comment by larsyencken** [comment]
This one has been nice to have for ages, marking as "wontfix" for now unless it comes up again.

Mostly, it's been ok since we have so very very few mixed unit charts.
