### ISSUE TITLE
Explorers can have a picker metric selected that isn't available in the dropdown

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1328]
## Description

> in the [data explorer embedded on the coronavirus page](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=desc&pickerMetric=new_cases_per_million&Interval=7-day+rolling+average&Relative+to+Population=true&Color+by+test+positivity=false&country=IND~USA~GBR~CAN~DEU~JPN&Metric=Confirmed+cases), it is not clear what the data values shown in the country picker refer to.

<img width="347" alt="Screenshot_2022-03-29_at_14_36_53" src="https://user-images.githubusercontent.com/1308115/160624304-4ecc29f4-8ef7-4135-8a8f-ca12adee0c73.png">

Technically, what is happening is that:
- The URL parameter `pickerMetric=new_cases_per_million` is a valid column that is being used
- There is filter for dropdown options we show in the Explorer config (`pickerColumnSlugs`) and it doesn't include the column `new_cases_per_million`

## Expected behaviour

Do not allow sorting by columns that are excluded from the dropdown options.

**Comment by larsyencken** [comment]
Generally, we'd like to disable or prevent this kind of bad state for an explorer, but it's pretty low priority for us. Marking this as "won't fix", and making a new bug for the specific explorer embed which we can just manually fix.
