### ISSUE TITLE
It's often not possible to hover and see the tooltip for the last value in LineChart/StackedArea

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1331]
## Description

> in the [coronavirus-data-explorer](https://ourworldindata.org/explorers/coronavirus-data-explorer) (and more generally in line charts with many dates on the x-axis), I often find it super difficult to hover over the latest date of data availability.
> e.g. for daily new confirmed covid deaths per million, today the latest data point is March 3rd. If I hover just slightly too far to the right on the line chart, then the whole hover box disappears. And if I am slightly too far to the left then I see data for March 2nd, not March 3rd.

https://user-images.githubusercontent.com/1308115/160626763-b33ca05e-1115-426e-8d8a-7f541f5a8758.mov

## Expected behaviour

It should be possible to hover over the last data point (maybe by extending the hoverable area slightly beyond the plot?)

**Comment by larsyencken** [comment]
Estimated as 3h. The idea is to extend the bounding box for tooltip hover by a few pixels for the last data point.
