### ISSUE TITLE
ScatterPlot: Use X/Y min/max from config when only a single bubble is plotted

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1332]
## Description

> The x axis in this chart sometimes includes negative values when scrolling through early years e.g. 1793-4, the values in the data are limited to 0-1.

https://ourworldindata.org/grapher/life-expectancy-vs-liberal-democracy?time=1790

![life-expectancy-vs-liberal-democracy](https://user-images.githubusercontent.com/1308115/160630799-1adbccd1-0e0f-4ae8-b785-46b05739758b.png)

The chart has X min/max defined by authors:

<img width="490" alt="Screenshot 2022-03-29 at 15 10 20" src="https://user-images.githubusercontent.com/1308115/160630875-335ea8f3-cd49-4573-8254-a21a13c50ecb.png">

The issue is probably in this bit of code

https://github.com/owid/owid-grapher/blob/4417e7515fea7473a819aae7112445908070ebef/grapher/scatterCharts/ScatterPlotChart.tsx#L821-L840

## Expected behaviour

X/Y min/max should be respected when set.

**Comment by Pawank06** [comment]
Hey, @danielgavrilov  I am a beginner to open source, how can I solve this issue can you please help me or provide me with some resources?
