### ISSUE TITLE
Site CSS "leaking" into Grapher embeds

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1339]
## Description

Since we're using iframeless embeds on the site, any CSS properties applied to site content are also applied to Grapher embeds.

Issues:
- Images appearing in Source tab are larger. For example [this grapher with a GSAID image in sources](https://ourworldindata.org/covid-cases?country=GNB~VAT~HKG~CHL~PAN#coronavirus-sequences-by-variant) (with included `width=` attribute) gets rescaled:
   <img width="843" alt="Screenshot 2022-03-30 at 12 04 31" src="https://user-images.githubusercontent.com/1308115/160819093-3057bf06-cb76-4c56-b466-02abd6c77683.png">

## Expected behaviour

Site CSS shouldn't leak into Grapher embeds.

Is there potentially some way to reset CSS, so that no styles are applied inside Grapher embeds?

**Comment by danyx23** [comment]
@danielgavrilov I just stumbled across this which may help solve exactly this case? https://cloudfour.com/thinks/resetting-inherited-css-with-revert/

**Comment by danyx23** [comment]
Availability is not stellar but all modern browsers have it: https://caniuse.com/mdn-css_properties_all_revert

**Comment by larsyencken** [comment]
Estimated as 3h, in which someone could check if the general approach breaks anything. If it does, you could always just back off and fix the specific issue.

**Comment by sophiamersmann** [comment]
I have looked into this:
- Reverting CSS properties doesn't really work as a general solution
- I opened a PR for the facet control label: #2338
- The sizing issue of images in the source seems to be fixed (though the images are placed weirdly, but I think we can ignore this for now, given that we plan to do a sources tab overhaul next cycle)
