### ISSUE TITLE
Floating country selector allows selecting multiple entities on single-entity charts

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1340]
## Description

> It’s possible to add multiple countries to charts that should only support a single country selection, through the floating country selector. In Cape Verde CO₂ profile, I added another country, and the result is the chart methane emissions by sector, but the sectors are not shown: https://ourworldindata.org/grapher/methane-emissions-by-sector?time=latest&country=CPV~DMA

https://user-images.githubusercontent.com/1308115/160821479-9baac2ec-695d-4165-82df-e77e85690632.mp4

## Expected behaviour

It should not be possible to select multiple countries for single-entity charts.

## Possible solutions

- **Pick the first country only, when the chart only supports one country** (preferred)
- Show a "cannot display" message, when the chart only supports one country
- (Bonus) Switch to faceting whenever possible

## Related

- https://github.com/owid/owid-grapher/issues/1124

**Comment by larsyencken** [comment]
Gavrilov: What's tricky here is that the chart is watching an external selection object, but has no layer to make its own decisions about how to process that selection. Fixing it needs refactoring.

```
// move from this
chart = new Chart(..., externalSelection)

// to this
chart = new Chart(...)
chart.subscribeToSelection(externalSelection)
```

It could also be done in the constructor, but what's important is the internal logic that we are subscribing to something, and processing it, but that we maintain our own internal selection.
