### ISSUE TITLE
Maps: Renamed categorical labels should not show original name in tooltip 

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1342]
## Description

It's possible to change the labels for categorical values:

<img width="491" alt="Screenshot 2022-03-30 at 12 22 09" src="https://user-images.githubusercontent.com/1308115/160823425-74517357-252a-4d78-9916-6308442268e3.png">

But the names are not used in the tooltip ([example chart](https://ourworldindata.org/grapher/lead-petrol-ban)):

<img width="772" alt="Screenshot_2022-03-30_at_12_18_48" src="https://user-images.githubusercontent.com/1308115/160822998-7f145427-84d9-4975-8f65-27015ccb6371.png">

## Expected behaviour

The custom categorical labels should be used (this already works for custom numerical labels when "Show custom label in the tooltip, instead of the numeric value" is ticked).

**Comment by MahmoudHamdy02** [comment]
I am going through the code and here is what I found so far, please let me know if I've misunderstood this:

1. In `MapTooltip.tsx`, the `datum` is obtained from the original table.
![image](https://user-images.githubusercontent.com/90795679/165647052-7567133a-8458-4085-abd4-a55e2d4248e2.png)
 
2. In `HorizontalColorLegends.tsx`, the legend obtains the value from these `bin`s, 
![image](https://user-images.githubusercontent.com/90795679/165647609-0c121d44-0d06-4f3f-bb03-a9edc20bf94e.png)
which are updated in `EditorColorScaleSection.tsx` whenever the value changes.


Would the same approach be used in `MapTooltip.tsx`? 
Please let me know if I am on the right track, thanks!

**Comment by danielgavrilov** [comment]
@MahmoudHamdy02 I think you are right that we need to look at the `ColorScale` bins!

This transformation of values into custom labels is already being done for numeric values: https://github.com/owid/owid-grapher/blob/e7ab17e7dfb4c2b4dad4e7ba71c9245cf5915e87/grapher/mapCharts/MapChart.tsx#L325-L338

I think that's potentially the right place to implement the logic for textual/categorical values too.
