### ISSUE TITLE
Variable time span is wrong?

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1343]
## Description

> the Life Satisfaction variable (x-axis) is always for 2015 — even though based on the SOURCES tab it seems like there should be new data because the variable timespan says “– 2020”. In general it seems odd in a scatterplot to have the y-axis variable (life expectancy) change over time while the x-axis variable of life satisfaction is static (only 2015)

https://ourworldindata.org/grapher/life-satisfaction-vs-life-expectancy

## Expected behaviour

The variable time span should be correct?

**Comment by larsyencken** [comment]
In this case, an author hard-coded the year to 2015 for life satisfaction data, when 2020 data was also available.

<img width="605" alt="Screen Shot 2022-04-19 at 13 01 16" src="https://user-images.githubusercontent.com/36012/163989728-ebe0f9ec-0390-4708-b499-d6b660412ad4.png">

This is probably an editorial issue then for this chart, marking as "wontfix" here in our tech issues.

@HannahRitchie Do you want us to move this issue back to owid-issues?
