### ISSUE TITLE
Allow a custom order of bars in StackedDiscreteBar (use selection order?)

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1344]
## Problem

Sometimes we need to apply a custom sort to bars. For example:

- In [this chart](https://ourworldindata.org/grapher/death-rates-smoking-age), we should sort by age range.
   
   ![death-rates-smoking-age](https://user-images.githubusercontent.com/1308115/160825926-b1d9d97e-a99b-42a2-9290-399dc21e92fe.png)

- In [this chart](https://ourworldindata.org/grapher/global-crop-production-by-farm-size), we should sort by farm size. 

   ![global-crop-production-by-farm-size](https://user-images.githubusercontent.com/1308115/160825939-e05d9f50-e9a5-474d-b37d-df76c01f0f02.png)

## Proposed solution

Use the entity selection order, which would at least allow authors to easily sort the entities.

(At some point, if we rely on this feature more, it should be possible for readers to reorder selected entities too?)

**Comment by marcelgerber** [comment]
I updated the following charts after deploying this:
* https://ourworldindata.org/grapher/estimated-lifetime-hours-of-work-and-leisure-alt
* https://ourworldindata.org/grapher/share-who-drank-on-5-or-more-days-by-income
* https://ourworldindata.org/grapher/condom-use-during-last-high-risk-sex
* https://ourworldindata.org/grapher/countries-with-minimum-urban-threshold
* https://ourworldindata.org/grapher/death-rates-smoking-age
* https://ourworldindata.org/grapher/crop-allocation-farm-size
* https://ourworldindata.org/grapher/global-crop-production-by-farm-size
