### ISSUE TITLE
Do not duplicate source text in Grapher Sources tab when multiple variables have the same source

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1345]
## Description

In charts with multiple variables, some variables can be from the same source. Currently we list the source individually for each variable, even if the sources are identical.

Examples:

- https://ourworldindata.org/grapher/covid-variants-area?country=~GBR
- https://ourworldindata.org/homelessness#estimated-number-of-homeless-people-in-the-us-by-shelter-status
- https://ourworldindata.org/income-inequality#income-shares

## Proposed solution

Try to deduplicate sources, ⚠️ **only if it's an easy task**. It might be more complicated because the sources can be distinct in the database for each variable, even though all information is identical.

Suggest to merge or show in sequence headers for all variables that share a source, then show the shared source.

**Comment by larsyencken** [comment]
Estimating at 3h. Priority "important" if we can fix it the easy way, "wontfix" if it looks like it's blowing out.

**Comment by larsyencken** [comment]
Marking as `wontfix` for now, given that it's not hurting anyone badly.
