### ISSUE TITLE
Use StackedArea-style tooltip in StackedBar

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1348]
## Problem

In [stacked bars over time](https://ourworldindata.org/grapher/deaths-in-conflicts-and-one-sided-violence), we have a tooltip per each section of the bar:

https://user-images.githubusercontent.com/1308115/160829446-4c635ab8-2db1-4525-bb3f-98ab3d12c86f.mp4

They are often hard to hover over because they are so small, and the design of the tooltip isn't great (a lot of whitespace).

## Proposed solution

We should use the StackedDiscreteBar-style or StackedArea-style tooltip:

<img width="666" alt="Screenshot 2022-03-30 at 13 00 54" src="https://user-images.githubusercontent.com/1308115/160829904-fbbba4e3-886a-4b54-a763-7e3c59ee893a.png">

**Comment by larsyencken** [comment]
You can easily copy the tooltip from `StackedDiscreteBar`, but you need to make the hover logic work on time instead of on bars. Estimate is 1d.
