### ISSUE TITLE
Slope charts should handle label overlaps better

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1349]
## Problem

Slope charts hide labels that overlap, without attempting to do any repositioning: 

https://user-images.githubusercontent.com/1308115/160831054-c70cc7c4-0277-4412-8c58-25d153cb041d.mp4

https://ourworldindata.org/grapher/relative-change-in-maternal-mortality?time=earliest..2015

## Proposed solution

We could instead use LineLegend-style repositioning, with faint guides:

<img width="224" alt="Screenshot 2022-03-30 at 13 09 17" src="https://user-images.githubusercontent.com/1308115/160831245-b7c003c8-0153-473a-82e2-59d6b3e9386b.png">

They'd need to be implemented to work in either orientation – left or right.

**Comment by danyx23** [comment]
We discussed a few options but don't think there is a straigtforward improvement to be had here vs the status quo nowadays
