### ISSUE TITLE
Remove "Hide countries with <1m people" checkbox

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1351]
## Problem

> When there are no countries with a population less than 1 million, then there shouldn't be the option to 'hide countries < 1million people' shown. https://ourworldindata.org/grapher/q2-gdp-growth-vs-confirmed-deaths-due-to-covid-19-per-million-people

https://user-images.githubusercontent.com/1308115/160832713-7d65990c-8765-4328-9b5c-4c3319b1c96c.mp4

## Decision

We will completely remove the "hide countries < 1million people" checkbox, since it's quite a fragile implementation and currently requires us to maintain a population dataset in the Grapher codebase.

**Comment by larsyencken** [comment]
@maxroser Any objections to us removing this checkbox entirely?

**Comment by maxroser** [comment]
No objections. That makes sense.

**Comment by larsyencken** [comment]
Raised its priority from "nice to have" to "important", since it's really short but lets us cut out the hard-coded population dataset, and associated logic, from grapher. \o/
