### ISSUE TITLE
Improve ScatterPlot bubble hover logic

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1352]
## Problem

> it's quite difficult to read or interact with [this chart](https://ourworldindata.org/grapher/share-of-protein-supply-from-animal-based-foods-vs-gdp-per-capita) (as is): e.g. if I want to hover over China, it's pretty much impossible

https://user-images.githubusercontent.com/1308115/160837576-ea955c09-c110-40b1-958e-5ebea6bdeb5c.mp4

**Comment by larsyencken** [comment]
We don't have a concrete proposal to make it better, and any change would be tradeoff, making some things worse. Marking as "wontfix" for the time being.
