### ISSUE TITLE
Random sample entity selection runs even in single-entity selection mode

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1354]
## Description

See video:

https://user-images.githubusercontent.com/2641501/161047941-14cbfc7b-bf42-4891-9a4c-14f9ddb426d0.mp4

## Steps to reproduce

1. Go to https://owid.cloud/admin/charts/2504/edit
2. Remove the x dimensions step by step
3. Observe how the chart jumps to displaying countries rather than sex/age groups

## Additional context

I think the sampling code that causes this lives here:
https://github.com/owid/owid-grapher/blob/1af4c20651bc82b29fe42d3f39b28b488dc34788/adminSiteClient/EditorBasicTab.tsx#L116-L122

**Comment by larsyencken** [comment]
Decision is that we should remove that chunk of code, meaning that an author will always have to make a manual selection to see the chart "in action". Worth an hour to chop the code out.

**Comment by marcelgerber** [comment]
The issue here is fixed now, but the auto-selection code is still there (just less buggy).

It's still not super awesome, but I feel like there's also at least some value in being able to quickly see some data when prototyping a chart. So I'll leave the decision to remove and/or rework the auto-selection code for the future.
