### ISSUE TITLE
Handle more pages in pagination UI more gracefully

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1362]
## Core problem

 _I'm looking at [blog page 8](https://ourworldindata.org/blog/page/8), and on the bottom there are links to each page of blog posts. There are 15 pages in total, but if there were more pages added, would the buttons just keep growing wider until they went off the page?_ - @saloni-nd

## Proposed solution

_I think something like having a button to the first and last pages would be better maybe._ - @saloni-nd 

## Context

![image](https://user-images.githubusercontent.com/13406362/161706195-8359094a-792f-417d-9fe6-cff355f5139f.png)

**Comment by mlbrgl** [comment]
Marking as `nice to have`: the current system is not conventional, but scalable to at least double the amount of articles we currently have (e.g. on mobile, the pagination numbers would wrap onto ~ 4 lines). It is also straightforward and understandable.

**Comment by larsyencken** [comment]
Closing as "wontfix", seems like not a big problem right now.
