### ISSUE TITLE
No data loading on the life-expectancy graph page 

### ISSUE THREAD

**Issue by radhikarungta** [owid/owid-grapher#1365]
I followed all the steps given in the wiki  to create a local dev setup however when I navigate to the life-expectancy chart page 
[](http://localhost:3030/grapher/life-expectancy?tab=chart), I don't get to see any data.
At the same time I am also not able to login into owid-admin page [](http://localhost:3030/admin). 
It says no user exists with the given name  .
I checked in the mysql db as well and couldn't find any credentials to login.

![image](https://user-images.githubusercontent.com/63709232/162022298-60f6ae9d-02fa-47db-b9b7-988f95a62575.png)

![image](https://user-images.githubusercontent.com/63709232/162022516-0f86eadc-4478-49c4-971f-09f08c6ce51b.png)

Please guide me through the process if I missed upon something . I'd be really grateful !

**Comment by danyx23** [comment]
Hi @radhikarungta!

Which version of [running our codebase](https://github.com/owid/owid-grapher/blob/master/docs/setup-options-overview.md) are you using? Once I know that I should be able to tell you some further steps for things to try to debug this.

**Comment by danyx23** [comment]
@radhikarungta I removed the -e option so it should also work with older tmux versions. Can you try to pull the latest version and run make up again?

**Comment by larsyencken** [comment]
Hope you got it working! Since we didn't hear back, closing this issue now.
