### ISSUE TITLE
StackedBar mouse-hover highlights more than one dimension

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1366]
## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/deaths-from-natural-disasters-by-type
2. Hover over 'Drought' in the legend on the top-right
3. => Both drought and extreme temperature are highlighted, both in the legend as well as in the chart

## Screenshots

![image](https://user-images.githubusercontent.com/2641501/162073490-c0f65a7f-e0e0-4c56-a4f3-2ef428403d2f.png)

## Additional context

It seems that the dimension colors play a role here? It happens both for `Drought / Extreme temperature` and `Wildfire / Extreme weather`.

**Comment by larsyencken** [comment]
From discussion with Gavrilov:

> The highlight logic operates on colour, which is why reused colours get co-highlighted. If the legend logic is specific to this chart, it could take less time to refactor it. But if it's shared across all charts, we'll need to redo it over all charts.

**Comment by larsyencken** [comment]
Marking as "nice to have" since we have a functioning workaround: assign unique colour per label.

**Comment by sophiamersmann** [comment]
Came up again for stacked area charts: https://admin.owid.io/admin/charts/4676/edit

**Comment by sophiamersmann** [comment]
For categorical legends, using labels as identifiers is more appropriate than relying on colors, but for numeric legends, colors are convenient. I am closing this issue since it doesn't seem worth the effort since duplicate colors in a legend are a rare case (and can be easily fixed by assigning unique colors).
