### ISSUE TITLE
More consistent WORDPRESS_DB_PASS(WORD) env var

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1383]
## Core problem

Inconsistency on Wordpress DB var name:
[.env.example.full](https://github.com/owid/owid-grapher/blob/5b9bfe760e4c2f99e68db7a4207db36ff95c4144/.env.example-full#L14): `WORDPRESS_DB_PASS`
[.env.example](https://github.com/owid/owid-grapher/blob/5b9bfe760e4c2f99e68db7a4207db36ff95c4144/wordpress/.env.example#L3): `WORDPRESS_DB_PASSWORD`

## Proposed solution

`WORDPRESS_DB_PASSWORD` -> `WORDPRESS_DB_PASS`

## Context
Follow-up to #1369

**Comment by larsyencken** [comment]
Good call, normalise it with the top-level grapher `.env.example-full` and `.env.example-grapher` 👍
