### ISSUE TITLE
Add anchors to topics in homepage (was: Improve sharing of topics on homepage)

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1396]
_raised by @Marigold_

## Core problem

At the moment, sharing a topic on the homepage is not discoverable and requires giving directions such as "scroll to the red header that says "Health" ".

## Proposed solution

_it would be cool to have URI fragments on https://ourworldindata.org/ to make sharing easier. E.g. I could send someone link https://ourworldindata.org/#health instead of having them scroll through the entire page (or maybe that’s what we want?)_ @Marigold 

## Alternatives
Adding a table of contents component was suggested in the past

**Comment by mlbrgl** [comment]
As a matter of fact, ids already exist on each topic header on the homepage. So https://ourworldindata.org/#health already scrolls to the right place on the homepage. Short of inspecting the source code, this is feature is not discoverable though.

**Comment by danyx23** [comment]
It seems like this is very optional - maybe pick it up for cooldown if you like but not important to keep around?
