### ISSUE TITLE
Can't click on grapher svg links in Safari

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#140]

**Comment by danielgavrilov** [comment]
We may be able to fix this one [by using `<a xlink:href="...">`](https://stackoverflow.com/a/43464942)

**Comment by mispy** [comment]
There's a couple of different related issues with SVG and text, so I'm just going to replace it with HTML for the interactive versions (the only reason the text is in svg at all is cos it needs to be for the image exports)
