### ISSUE TITLE
Scrolling to 'earliest' in timeline shows wrong value

### ISSUE THREAD

**Issue by MahmoudHamdy02** [owid/owid-grapher#1403]
In graphs with a timeline at the bottom, [like this one](https://ourworldindata.org/explorers/energy?time=1985&facet=none&country=USA~GBR~CHN~OWID_WRL~IND~BRA~ZAF&Total+or+Breakdown=Select+a+source&Select+a+source=Fossil+fuels&Energy+or+Electricity=Electricity+only&Metric=Annual+generation), when dragging to the far left of the timeline, the number shown is 'latest' not 'earliest'

Example:

Cursor at 1985:
![image](https://user-images.githubusercontent.com/90795679/164111556-5b1c0b14-f079-4052-82df-1b95ee489af5.png)
![image](https://user-images.githubusercontent.com/90795679/164111920-21217e4f-3ccf-4d6e-afd8-93d5915d23f3.png)

Cursor all the way to the left:
![image](https://user-images.githubusercontent.com/90795679/164112001-3f21e21f-ec8d-4aa3-bf3e-652a55bd1ae0.png)
![image](https://user-images.githubusercontent.com/90795679/164112097-3e5db195-9378-4fed-92c6-d9b6f0b8ee36.png)

(Windows remove the cursor from screenshots so I put a red dot where the mouse would be when dragging)

**Comment by danielgavrilov** [comment]
Thanks @MahmoudHamdy02! We are tracking this one in #1179, I've edited it to include this case.

**Comment by MahmoudHamdy02** [comment]
Thanks for the heads up! I searched through the issues for a duplicate but looks like I still missed it :)
