### ISSUE TITLE
Allow explorers to be published unlisted

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1405]
## Core problem

Spin off from #1170 
_In future for this sort of thing it would be good to be able to have an additional option which is 'Published but not indexed'. Sometimes we need to share explorers with external users for review, without them being 'findable' on the site._

At the moment, either an explorer is published and listed on /charts or it is not published and not listed on /charts. We'd like to allow for more combinations, such as "published and not listed on /charts".

## Proposed solution

Reuse "publication context" terminology from Wordpress posts to allow for explorers to be visible in selected contexts only. To start with, there would only be one context ("Charts index") but this could be expanded further in the future by adding more.

<img width="288" alt="Screenshot 2022-04-20 at 15 00 54" src="https://user-images.githubusercontent.com/13406362/164237463-958da9dc-913b-47c8-9193-68bc06143fbf.png">

`publicationContext` would be an additional property on the explorer spreadsheet

<img width="255" alt="Screenshot 2022-04-20 at 15 10 33" src="https://user-images.githubusercontent.com/13406362/164237852-e42317ba-937c-47e2-980e-a8d6cd5f2010.png">

**Comment by larsyencken** [comment]
Closing this until it becomes an thing again.
