### ISSUE TITLE
Static SVGs shouldn't contain <foreignObject>s 

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1412]
## Description

Static SVGs seem to contain `<foreignObject>`, even though nothing is rendered inside of one (I think?)

## Expected behaviour

Any `<foreignObject>` should be excluded from static SVGs.

## Examples

- https://ourworldindata.org/grapher/exports/share-of-land-covered-by-lakes-and-rivers.svg

**Comment by danielgavrilov** [comment]
Prioritising as important since these are the potential cause for some broken SVGs in the SVG tester.

The `<foreignObject>` contents appear truncated for some reason ([see here](https://github.com/owid/owid-grapher-svgs/commit/8e1617db618265241b788ae82e58c2533e49ef5c#diff-6dfcda27fd479b9a5802ac04ddc7649cf2940b6f45549c896c38b8722993c719)):
<img width="1152" alt="Screenshot 2022-04-25 at 13 17 21" src="https://user-images.githubusercontent.com/1308115/165078908-c97b8232-0051-4a19-90af-301201e1c818.png">

**Comment by marcelgerber** [comment]
Ah, once that is fixed we can probably also remove some special code handling `react-select` ids from the svgTester:
https://github.com/owid/owid-grapher/blob/073a087f936f0fc14f80540d2b663d517f030906/devTools/svgTester/utils.ts#L275

**Comment by larsyencken** [comment]
Downgrading to `nice to have`, happy for someone to pick it up during cooldown.

**Comment by danyx23** [comment]
This problem is basically done now - the NoDataModal is the only thing that still comes up when you search our current svg tester repo for foreginObject. We could fix that too at some point but that is more for convenience
