### ISSUE TITLE
Start/end axis ticks should be lower priority than the 0 tick on bar charts

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1413]
## Problem

I think what is happening is the generated start/end ticks can be higher priority (or same priority) than the `0` tick, and therefore the `0` tick gets hidden ([chart](https://ourworldindata.org/grapher/total-wealth-by-asset-group-in-millions-2014-us-dollars?country=~OWID_WRL)):

![total-wealth-by-asset-group-in-millions-2014-us-dollars](https://user-images.githubusercontent.com/1308115/165139420-aeb16e96-e9d2-4458-81ea-667fc7498027.png)

## Proposal

The `0` tick is more important and should have higher priority (for discrete bars, not sure if this applies beyond that).

**Comment by danielgavrilov** [comment]
Actually, maybe these start/end ticks shouldn't even get injected for bar charts? They make sense in some charts, but definitely not bar charts. If I remember correctly, there is logic specific to horizontal axes that injects these start/end ticks.

**Comment by sophiamersmann** [comment]
Closing as not planned because we removed the axis for discrete bar charts
