### ISSUE TITLE
Map chart: Cyprus not visible in Europe map projection with narrow viewport

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1428]
## Description

When viewing a map projection set to Europe, and using a narrow viewport, Cyprus is not visible in the map chart.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/life-expectancy?region=Europe
2. Shrink the browser window to a narrow viewport

## Screenshots

Wide viewport:
![image](https://user-images.githubusercontent.com/2641501/167219507-4b0edf6e-bbdd-4144-aab4-318edfe7ba38.png)

Narrow viewport:
![image](https://user-images.githubusercontent.com/2641501/167219526-cd929fc1-f014-4ce8-96b8-32d49d0fb7db.png)

**Comment by larsyencken** [comment]
Under the assumption that this is just about finding and changing a few coordinates for the narrow version of the map, then this seems worth doing and should only take a few hours.

If it takes longer than a day, we should abort and call it "won't fix".

**Comment by larsyencken** [comment]
The solution is probably around these settings here: https://github.com/owid/owid-grapher/blob/master/grapher/mapCharts/MapProjections.ts#L71
