### ISSUE TITLE
Cleanup: Remove ScatterPlot `hideLinesOutsideTolerance` option

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1444]
## Description

There is a special option for ScatterPlots called `hideLinesOutsideTolerance`.
@danielgavrilov and I were unsure what it even does when we stumbled across it last week, which is a bad sign 🚫 
Then we found out that [only 8 charts currently use that feature](https://owid.cloud/admin/test/embeds?ids=705,1237,1293,1321,2846,3114,3174,5474).

In the admin, the setting can be accessed under `Scatter > Hide entities without data for full time span (within tolerance)`.

## What does it do?

That option was [introduced in September 2017](https://github.com/owid/owid-grapher/commit/5da37f905989055502c938b9d25542afee80b391).
If enabled, then we do roughly the following:
```py
for country in countries:
	if (
	 	no data point for year minTime ± tolerance exists for country
	   or
	 	no data point for year maxTime ± tolerance exists for country
	   ):
			excludeFromView(country)
```

## Can we remove it?

Given how few charts have this flag enabled, and how specific it is, I think we can remove it. But we should ask authors for their stance on it.
The setting seems most important when `Average annual change` is enabled, because in that case it ensures that the average change is only calculated for countries which have lots of data, and where the calculated average is actually meaningful. We might want to enable a similar feature for the `Average annual change` mode, but without any config behind it.

The crassest example of that is [this chart](https://tufte.owid.cloud/admin/charts/1237/edit), where toggling the checkbox in the admin makes the chart shift around by a lot (that chart is never used).

In the screenshot, the setting is disabled (default) on the left and enabled (as in the config) on the right.
![image](https://user-images.githubusercontent.com/2641501/168909463-af2aab27-f9c3-4e76-b974-e83f927b7816.png)

## Suggested steps
- [x] Ask authors whether they need this feature
- [ ] Decide what to do about `Average annual change` mode
- [ ] Remove option
- [ ] Write DB migration to remove that property from all existing configs

**Comment by danyx23** [comment]
@marcelgerber can you ask the authors about this? 😃

**Comment by marcelgerber** [comment]
Just asked Hannah and Max about it (in a private chat).
They will most likely be the only two people that know about the existence of this setting, so doesn't make sense to ask a larger group about it.

**Comment by marcelgerber** [comment]
Both Max and Hannah are okay with it being removed in the future. Hannah didn't even know the toggle existed 😁 

<details>
<summary>Their responses</summary>

> No, I didn't really know it existed, or at least I've never had it on my radar or used it. I don't think anyone in the team does (as per the fact that only 8 charts use it).
> 
> I'd say it's definitely okay to remove the setting. No one will even notice that it's gone.

-- Hannah

> Yes, I agree with it. If it causes trouble or is hard to maintain then yes, let’s discontinue it.

-- Max

</details>
