### ISSUE TITLE
Inconsistent citation instructions on vaccinations page

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1446]
## Core problem

From Research team, tracked by @CGiattino
_Inconsistent citation instructions: “Cite this research” button at top (leading to footer) says cite general coronavirus page; download box says to cite Nature article_
https://ourworldindata.org/covid-vaccinations

## Proposed solution

My preference and recommendation goes to “Hardcoded overrides” first, and “Remove all citation elements” next (see below).

## Alternatives

I can see a few ways of dealing with this.

### Hide the (visible) undesired citation elements

Hide link in the header

<img width="263" alt="Screenshot 2022-05-18 at 09 59 56" src="https://user-images.githubusercontent.com/13406362/169031922-bd327d0c-6bd5-4e33-8c49-f6ade49f94ca.png">

Hide citation block in the footer

<img width="577" alt="Screenshot 2022-05-18 at 10 00 07" src="https://user-images.githubusercontent.com/13406362/169031966-cca8a7b7-4ac8-4ecb-8859-2a4ff8da3ca1.png">

This is relatively low effort but leaves meta tags consumed by Google Scholar untouched, so they’ll still be inconsistencies at that level:
<img width="613" alt="Screenshot 2022-05-18 at 10 00 30" src="https://user-images.githubusercontent.com/13406362/169032051-2ad37d05-3cff-41c8-b86e-c6c71ff38bb4.png">

### Remove all citations elements

Here, the citation elements are not visually hidden like in the previous option but entirely removed, which is cleaner. Google scholar meta tags will be removed too.

The main drawback of this option is that licence and citation go hand in hand, so removing citation elements will remove licence ones too.

Both links will go

<img width="346" alt="Screenshot 2022-05-18 at 10 19 42" src="https://user-images.githubusercontent.com/13406362/169032312-701bdbce-8bf7-40f0-8c80-d6a31a15164d.png">

Both licence and citation blocks will go

<img width="782" alt="Screenshot 2022-05-18 at 10 19 57" src="https://user-images.githubusercontent.com/13406362/169032332-9b430293-975f-404f-8d02-ba7c5ca2399b.png">

This can be mitigated by adding a manual “Reuse our work freely” block at the bottom of the content. It won’t be kept in sync with the rest of the site though.

Effort is similar to the previous option, and should be favoured if removing google scholar meta tags is either preferable or not a concern for this one case.

### Hardcoded overrides

At the code level, we can plug into the page overrides system and hardcode all citation metadata (title, url, publication date, journal title, authors) so they’ll be reflected in the google scholar meta and in the citation blocks in the footer (standard and BibTeX).

Effort is slightly higher, given that “journal title” is currently hardcoded to “Our World in Data” and will need to be parametrized.

This is also not scalable, and shouldn’t be used on more pages.

### Deep integration

Allow per-page citation overrides from the CMS, either through the `<!--formatting-options -->` block or as metadata in the Wordpress side bar.

Effort is high, and probably not worth it if the need is a one-off.

## Context

Initially reported in [notion issue](https://www.notion.so/owid/Inconsistent-citation-instructions-Cite-this-research-button-at-top-leading-to-footer-says-cite-21f1d2c436b14da693b76dbde724033c)

**Comment by mlbrgl** [comment]
Confirmed by @CGiattino over Slack, going with "Hardcoded overrides" option given this only applies to one page.

**Comment by larsyencken** [comment]
@CGiattino Just to confirm, is this something that's still important? I marked it as "nice to have", but when I look at the two citations, they appear to be for different things (the page including written content vs the data), so I would normally not consider this a bug.

**Comment by CGiattino** [comment]
@HannahRitchie what do you say?

**Comment by HannahRitchie** [comment]
@CGiattino I think we want them to cite our Nature Human Behaviour article if they're using COVID vaccination charts or data that we publish. i.e. we want to drive them to the peer-reviewed article as much as we can. I think many will still cite the covid-vaccinations page in their own way, but we should encourage the paper as much as we can.
