### ISSUE TITLE
Concept: Data API for visualisation

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1453]
## Problem statement

We would like to design an API for internal and external use. The API should be sufficient to power grapher charts and explorers, meaning it must meet both their _data_ and their _metadata_ needs.

## This cycle

- [x] Establish and document grapher's metadata requirements
- [x] Write an API proposal that meets these requirements
- [x] Take feedback on the proposal until it is approved

## Relevant problems

- Metadata alignment between grapher and ETL
- Addressing a specific variable without integer IDs
- API versioning
- Supporting selections or ranges (optional)

## Out of scope

- For this proposal, discoverability of data is not important
- For this proposal, the exact mechanism powering the API is not important
- For this proposal, the baking or otherwise serving of grapher configs is not important

## Technical notes

It might be helpful to make a few small proposals rather than one big one. (Like small PRs are easier to review than large ones.)

**Comment by Marigold** [comment]
@larsyencken shouldn't this be called `Concept: Data API for visualisation`?

**Comment by Marigold** [comment]
The first batch of notes https://www.notion.so/owid/API-for-Data-Metadata-for-Grapher-78045acf2f9c4bc9bdfc7edb8bf7911f, more coming tomorrow.

**Comment by larsyencken** [comment]
Linking this question as to whether dataset or variable names need prettifying or not as part of backport: https://github.com/owid/etl/issues/167
