### ISSUE TITLE
Search: Send click-through analytics data to Algolia

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1457]
Algolia lets us track click-through rate and the average click position of search results.
These metrics can help us to further improve the Algolia search, but we currently don't send these details back to Algolia.

[More details here](https://www.algolia.com/doc/guides/getting-analytics/search-analytics/advanced-analytics/).

**Comment by larsyencken** [comment]
@marcelgerber I reckon this is actually important for us to do at some stage. Does 3h look like a good estimate?

**Comment by marcelgerber** [comment]
I think 3 hours is reasonable, yes!

**Comment by larsyencken** [comment]
Downgrading to "nice to have"

**Comment by marcelgerber** [comment]
Duplicate of #1877, which is now fixed!
