### ISSUE TITLE
Download from Living Planet Explorer to be limited/redirected.

### ISSUE THREAD

**Issue by spoonerf** [owid/owid-grapher#1475]
## Core problem

We are hoping to build an explorer with the [Living Planet database](https://livingplanetindex.org/data_portal). They are generally happy for us to do this but are wary of us being an alternative location where their full dataset could be downloaded as they have previously had bad experiences with this. They are fairly flexible with proposed solutions and suggested a few to us. 

They are releasing a new version of the dataset in September and it would be great to have something workable for this by then, if possible.

## Proposed solution

Possible solutions:

* The download button redirects to the location of their data where a user must acknowledge their data license agreement
* The user can only download the current view of the explorer, therefore adding a barrier to downloading the full dataset. 
* Their data license agreement is shown on our site when a user tries to download this. I'm not sure if this is a workable solution as they have a public dataset and a larger research dataset. We would want to use the latter but I think they might be even less keen to allow our users to download this. I will clarify this with them.

## Alternatives

* We disable all downloads from this explorer, not ideal but maybe the most feasible.

**Comment by danielgavrilov** [comment]
> Maybe a silly question, but if it's not a link to a csv but another webpage the download button will just redirect there?

That's a great question! I checked and it won't redirect, but will download the HTML of the page. So that's not option 1 😅 

It think we would just need to change explorer so it's possible to add a link that users follow instead of download. This seems like the most reasonable solution?


> * The user can only download the current view of the explorer, therefore adding a barrier to downloading the full dataset.

We can easily implement this, but it would apply to all explorers. It's also not exactly straightforward to isolate precisely which columns are used in the current view, partly because we transform the data on the Grapher side, so it's not the _true_ data table at the end.


> * Their data license agreement is shown on our site when a user tries to download this.

Potentially we could include a text field in Explorer config that gets included in/under the download button.

**Comment by spoonerf** [comment]
> It think we would just need to change explorer so it's possible to add a link that users follow instead of download. This seems like the most reasonable solution?

This definitely seems like the one to go for. Do you see this being an option on the Download tab?

**Comment by danielgavrilov** [comment]
Yes, we would need to turn it into a link instead of a button, as it is now.

And we would need to add another field to the Explorer config potentially, to differentiate between "trigger download" and "follow link". 

Should take ~1-2h of dev work, so shouldn't be a burden.

**Comment by larsyencken** [comment]
Hey @spoonerf, did you hear back from them on this?

**Comment by spoonerf** [comment]
Hello! They are discussing internally this week - if we don't hear anything by early next week I'll chase them up. Would that be okay?

**Comment by larsyencken** [comment]
@spoonerf Did this end up being something that the living planet team wanted in the end?

**Comment by spoonerf** [comment]
Ah we are chatting to them about this tomorrow afternoon so will get back to you then! Sorry for the delay!

**Comment by spoonerf** [comment]
Hi @larsyencken - they are happy with this solution. Would be great it if you could add it when you get a chance, but very much no rush. I don't think the explorer this will be used for will be in place before Q4.

**Comment by larsyencken** [comment]
Ok, no sweat. It'll sit in our backlog for a bit then, but yell if it becomes more urgent.
