### ISSUE TITLE
Add `short_name` column to `datasets` table to better align with ETL data model

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1483]
## Core problem

In [etl](https://github.com/owid/etl) our datasets have both `short_name` and `title` fields. The `short_name` is underscored name that could be used as a column name in DB (e.g. `ggdc_maddison__2020_10_01`) and `title` is a human readable version (e.g. `Maddison Project Database (GGDC, 2020)`).

Currently we map `short_name` to column `datasets.name`, but because it's not human readable, it's hard to read it and search for it in the admin.

## Proposed solution

1. Add column `datasets.short_name` in addition to `datasets.name` in admin
2. Map `short_name -> datasets.short_name` and `title -> datasets.name`

## Alternatives

1. Don't do this (we don't display `datasets.name` anywhere anyway)
2. Map `title -> datasets.name` and ignore `short_name` from ETL (could there be problems with referencing datasets in API then?)

## Context

An [example](https://staging.owid.cloud/admin/datasets/5576) in staging and [slack discussion](https://owid.slack.com/archives/C0193RW5E2J/p1654251450021749).

Screenshot from admin

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1550888/172121175-c13ea5f2-80b2-4ce9-bf79-3772e9867082.png">

**Comment by danyx23** [comment]
I think this is quite high priority since we want to move more work over to ETL soon but inside the admin we still match on dataset name in search in some cases and then the current short names are less then ideal

**Comment by larsyencken** [comment]
Relates to:

- https://github.com/owid/etl/issues/167

**Comment by larsyencken** [comment]
@Marigold To address your concern, let's make the field read-only in the admin once it's been created.
