### ISSUE TITLE
Hide archived datasets

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1486]
## Core problem

`datasets` table now have `isArchived` column after [this migration](https://github.com/owid/owid-grapher/pull/1463). These datasets shouldn't be displayed to users anywhere.

## Proposed solution

Hide archived datasets in `admin/datasets` view and in a list for creating charts. We won't let users [unarchive datasets](https://github.com/owid/owid-grapher/pull/1463#issuecomment-1145715396) in the UI, so there's nothing to do on this front.

## Context

**Comment by marcelgerber** [comment]
@Marigold I think this one is done, right?
