### ISSUE TITLE
Concept: citation is coherent with byline and dateline

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1487]
## Core problem
Discrepancy between citation information and relevant page metadata: authors (byline) and publication date (dateline).

## Things to consider

The proposed solution has to take into consideration:
- how the relationships between subtopic / articles and their parent topics (see #1070) drives inheritance of metadata and citation information
- whether metadata has to be semantic (as opposed to freeform text)
- whether citation information is always derived from page metadata
- what can be overridden at the page level
- the different types of date: publication, content vs data updated, reviewed?
- semantic vs non-semantic updates (e.g. data update vs typo fix)

## Context

- [x] https://github.com/owid/owid-issues/issues/266
- [x] https://github.com/owid/owid-issues/issues/280
- [ ] [Last reviewed date](https://www.notion.so/owid/Last-reviewed-date-2d98870dee8249e5a320e6474951319f#54e73381e7824c648aa8b26913cd11c8)
- [ ] [Sync last updated date with citation](https://www.notion.so/owid/Sync-last-updated-date-with-citation-c6ce6a725c4445aeb2430a6a643a2c0f)
- [ ] [Citation and by-lines for landing pages and posts](https://www.notion.so/owid/Citation-and-by-lines-for-landing-pages-and-posts-f46300a9e5494dbebc540f1cd5141579)
- [ ] https://github.com/owid/owid-grapher/issues/1484
- [ ] #1446 (including a proposal for manual overrides)
- [x] Automate citation and licence information on subpages

**Comment by larsyencken** [comment]
Marking this as `needs design`, since it's both a visual design and information architecture issue.

**Comment by larsyencken** [comment]
This is quite a big space. I'm going to close it here, and perhaps we can decide whether we want a tracking issue for citations, or whether we just maintain an awareness on the product side and revisit when we're ready.

/cc @JoeHasell
