### ISSUE TITLE
Ability to fully specify display order of options in explorers

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1496]
## Core problem

Currently in explorers, one can only specify a _global_ display order of options.
For example, with the following config:
```
Roman Dropdown	Greek Dropdown
A		α
A		β
A		γ
B		β
B		α
```

then for `Roman Dropdown = B` it has `α, β` for `Greek Dropdown`, since `α` comes _globally_ before `β`.

In particular, it is not possible to have `Greek` sorted _differently_ for `A` and `B`.

For the political regimes explorer, @bastianherre would like to be able to do exactly that.

## Context

[Bastian writes this here](https://github.com/owid/owid-issues/issues/176#issuecomment-1140126897):

> Sometimes the explorer lists the sub-metrics in the order in which I listed it in the spreadsheet, sometimes it does not. Is there any way to make it such that it always uses my specified order?

## Additional considerations

* Make sure to check that existing explorers don't change too much in their options order.

**Comment by marcelgerber** [comment]
I would estimate this to take 4 hours to one day to do.

**Comment by marcelgerber** [comment]
This also come up as an issue in the demography explorer.

**Comment by marcelgerber** [comment]
Rated this as priority 2, keeping in mind that we want to build a global health explorer later this year where we will probably also run into this issue.

**Comment by larsyencken** [comment]
@marcelgerber I recalled you had a specific idea on how to solve this. My sense is that we only want it if it doesn't add a new horrible layer of maintenance, i.e. if we have a very clear config and abstraction for doing it. Otherwise we might accept it as a limitation of explorers.

**Comment by larsyencken** [comment]
Reducing the prio for now, but we can bump it again if hit it in a bad way for a new explorer.

**Comment by spoonerf** [comment]
Hello from the health explorer - running into this issue again :) It would be useful to be able to control the ordering of different drop down metrics -https://docs.google.com/document/d/19hTiUnrHnKp_DMRtvn4d0bRabxSM6mlzBmTuLk7MspI/edit?disco=AAAAhz6qF9s
