### ISSUE TITLE
Dot sizes disappear on scatter plots when 'Hide connected scatter lines' is selected

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1513]
From @saloni-nd:

I was trying out to see how this scatter plot looked without the scatter lines.  (https://owid.cloud/admin/charts/5656/edit)

Over the timeline, the scatter lines are shown.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/31684905/163557408-72cdc544-4106-4267-89e2-1dcd48731e10.png">

In a single year, they aren't shown, and the dots are shown with the size of the country's population.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/31684905/163557102-381f1751-b1ea-490b-ab07-2ba50e204021.png">

But if I check the box for "Hide connected scatter lines", then the dot sizes disappear, and the points are just labelled with the country's name.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/31684905/163557367-e51d62e0-f7e7-4795-ae67-60aea1362339.png">

Is there another way to hide connected scatter lines but keep showing the dot sizes by population when I've selected a specific year? I think this is a bug.

**Comment by danielgavrilov** [comment]
"Hide connected scatter lines" is a bit of an obscure setting that was implemented for CORE-Econ. Only 4 published charts exist with the setting enabled: https://owid.cloud/admin/test/embeds?ids=3103,4269,4334,4339

When selected, the ScatterPlot needs to plot only a single country (Data → User can change entity) and you get this kind of plot, with points for each year for a single country:

![inflation-and-presidential-election-victory-in-the-us](https://user-images.githubusercontent.com/1308115/175930599-7a4a3127-bee4-48ff-b160-723d71d9b749.png)

Just sharing this to check if this is what @saloni-nd intended to create. The link to the Admin no longer works (the chart doesn't exist).

**Comment by saloni-nd** [comment]
Thank you @danielgavrilov! That makes sense.

I no longer need it now, it was meant to be part of this post: https://ourworldindata.org/polio-testing but it was quite hard to interpret two scales at once anyway, so we changed it to the final map in the post which shows the data in categories instead.

I was trying to show the different countries on two scales (screening & testing) for each year on the timeline. But when the scatter lines were shown the chart also became very crowded with lines for each country over time.

**Comment by larsyencken** [comment]
Thank you both for the context. Based on that, I think I'll mark this as "wontfix" for now.
