### ISSUE TITLE
Add test pages for colour schemes

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1514]
## What

Add two new test pages for colour schemes, as per @danyx23's idea:

- [x] All the charts with non-default color schemes in either the main color scheme or the map color scheme
- [x] All charts for a given color scheme

## Why

Authors want to be able to review colour schemes in bulk, so that they can replace or remove bad ones as part of our cleanup project.

**Comment by marcelgerber** [comment]
This is something we can easily integrate into the "Bulk downloads" feature in the admin.

**Comment by danyx23** [comment]
Talked about this with Marcel - we talked about this in the wider context of https://github.com/owid/owid-issues/issues/262 . We think that two new pages should be added to the tests. The two test pages should do the following:
* One shows all the charts with non-default color schemes in either the main color scheme or the map color scheme
* The other shows all charts for a given color scheme

This should allow Marwa and the Authors to get a good feeling for currently used color schemes and think about which to remove or add/replaced

The bulk csv export should also be extended with the baseColorScheme from the chart and the map for easy searching by the data team.

**Comment by larsyencken** [comment]
Updated the title and scope now to reflect your suggestion

**Comment by larsyencken** [comment]
Marking it as "nice to have" until we get a clearer signal from Marwa that we still want this.

**Comment by danyx23** [comment]
Implemented this as as series of observable notebooks as part of the #1611 project (see [this notion page](https://www.notion.so/owid/2022-09-Colors-in-Grapher-1ae8d68d35fa4a7483713482426cfcdb) for the links to the notebooks)
