### ISSUE TITLE
Bibtex citations have problematic author name ordering

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1515]
## Description

"I just copy-pasted the suggested Bibtex citation for Our World In Data from https://ourworldindata.org/policy-responses-covid#citation and noted it creates an error in LaTeX due to the ordering of authors' given and family names. This rearranged code works:

```
@Article{owidcoronavirus,
author = {Ritchie, Hannah and Mathieu, Edouard and Rodés-Guirao, Lucas and Appel, Cameron and Giattino, Charlie and Ortiz-Ospina, Esteban and Hasell, Joe and Macdonald, Bobbie and Beltekian, Diana and Roser, Max},
title = {Coronavirus Pandemic (COVID-19)},
journal = {Our World in Data},
year = {2020},
note = {[https://ourworldindata.org/coronavirus}](https://ourworldindata.org/coronavirus%7D)
}
```

## Expected behaviour

You should be able to copy our generated BibTex and not have to edit it manually.

**Comment by danyx23** [comment]
Super easy to fix, let's just do it
