### ISSUE TITLE
Do not include unit in map tooltip sparkline axis ticks

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1516]
Space is precious in the tiny map tooltip sparklines. We could drop the `shortUnit` being included in the axis ticks, because it's already shown in the value next to the chart.

For example, `kWh` is redundant in the axis [on this chart](https://ourworldindata.org/grapher/per-capita-energy-use), because `kilowatt-hours` is mentioned in the text alongside:

<img width="382" alt="Screenshot 2022-06-28 at 09 23 35" src="https://user-images.githubusercontent.com/1308115/176131451-4d55c609-4734-42b9-a954-6bfeb5a26355.png">

Likewise we can drop `years` from the axis on [this chart](https://ourworldindata.org/grapher/life-expectancy):

<img width="285" alt="Screenshot 2022-06-28 at 09 26 22" src="https://user-images.githubusercontent.com/1308115/176131814-fbac3b8e-d22d-48b4-8d83-090df19628e1.png">

**Comment by marcelgerber** [comment]
Sorry for chiming in here, but I think we'll want to display "short" units still, like percent and dollars.
E.g. here: https://ourworldindata.org/grapher/share-firms-top-female-manager

![image](https://user-images.githubusercontent.com/2641501/177284165-5bcc91f0-9bb3-4f61-82f6-0f18b96431c9.png)

**Comment by danielgavrilov** [comment]
Good idea! Created a separate issue: #1530
