### ISSUE TITLE
Fix styles in Download tab of charts in "All our interactive charts on" block

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1518]
_[Issue](https://owid.slack.com/archives/CK0RKGGSC/p1656419985063979) reported by @CGiattino_

## Description

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13406362/176195121-cd6c8f10-9ea4-41a8-8198-dfb2979c4e37.png">

## Expected behaviour
<img width="805" alt="image (1)" src="https://user-images.githubusercontent.com/13406362/176195157-6f85270a-505f-455e-a0d5-b5e379da430b.png">

Check hover behaviour too.

## Steps to reproduce

1. Go to https://ourworldindata.org/world-population-growth
2. Open the "All our interactive charts on..." block at the top of the page

## Context

Might be superseded by #1447 if we decide to retire the current block (#1380)

**Comment by danyx23** [comment]
Looks like this was fixed at some point
