### ISSUE TITLE
Cleanup: Get rid of VariableCountryPage

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1525]
I just now realized for the first time that we have a page that shows a variable for a single country.
It is only available on localhost, though, e.g. here: http://localhost:3030/admin/variables/147845

![image](https://user-images.githubusercontent.com/2641501/176653394-e2f5c9e4-964a-45cd-874a-ebc11cc423ab.png)

Seeing how broken the page currently is, I _think_ we can just get rid of it and the related code.

### Code

https://github.com/owid/owid-grapher/blob/c8f117b034ab130eb075051c79d53fab671cd063/adminSiteServer/mockSiteRouter.tsx#L198-L201

https://github.com/owid/owid-grapher/blob/c8f117b034ab130eb075051c79d53fab671cd063/baker/siteRenderers.tsx#L321-L357

https://github.com/owid/owid-grapher/blob/c8f117b034ab130eb075051c79d53fab671cd063/site/VariableCountryPage.tsx

https://github.com/owid/owid-grapher/blob/c8f117b034ab130eb075051c79d53fab671cd063/site/VariableCountryPageProps.ts

https://github.com/owid/owid-grapher/blob/c8f117b034ab130eb075051c79d53fab671cd063/site/runVariableCountryPage.tsx

**Comment by danyx23** [comment]
Also very small, let's just do it when it makes sense. @danielgavrilov can you think of any purpose of this weird page? Otherwise Marcel would just get rid of it when working on something related.

**Comment by danielgavrilov** [comment]
Can remove, it was a beginning of a prototype for a"page for every variable" project that we didn't work on.
