### ISSUE TITLE
Updated topic page front matter

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1532]
## Front matter component
<img width="618" alt="image" src="https://user-images.githubusercontent.com/11844404/177334997-11f666c4-0fee-4cd9-970d-2cd216bb2214.png">

Because of likelihood of changes, best to compose it from separate modules
Update header typography

Sticky nav:
- [x] [Merged](https://github.com/owid/owid-grapher/pull/1570)

Expandable paragraph:
- [x] Create the Gutenberg block ([example](https://github.com/owid/owid-grapher/commit/d7515b7b5fd1f1299c752baa52117612556fce80))
- [x] Implement hydration logic (`owid.entry.ts`, `runBlocks()`)
- [x] Add actual react component (e.g. `AdditionalInformation.tsx` - this may also have reusable code with `AnimateHeight`)
- [x] [Merged](https://github.com/owid/owid-grapher/pull/1579)

Download button:
- [x] Implement via a custom HTML component, or create a Download button component (or just default link if the behaviour is that simple)
- [x] [Merged](https://github.com/owid/owid-grapher/pull/1596)

**Comment by mlbrgl** [comment]
@ikesau thanks for taking notes, sounds good! 👍

**Comment by larsyencken** [comment]
Thanks Ike! Looks like we can close this now!
