### ISSUE TITLE
Research and writing block

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1533]
<img width="758" alt="Screenshot 2022-07-05 at 16 26 25" src="https://user-images.githubusercontent.com/13406362/177351423-c7a4362c-000c-4ec5-a96c-3268e76b4514.png">

**Comment by mlbrgl** [comment]
Assuming that in the first pass, those lists are all manually curated and ordered (as opposed to automatically generated from some form of categorisation which doesn't fully exists yet).

## Some implementation ingredients

### Grid cards
At the level of the individual grid cards, all the metadata (title, excerpt, authors) is already available in the article and should be dynamically pulled from the Wordpress DB.

The Card component offers article selection from autocomplete and a UI for manual override of title, excerpt and image. The whole package might be overkill here but [URLInput](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/url-input) is probably part of the equation on the CMS end (see [Card.js](https://github.com/owid/owid-grapher/blob/master/wordpress/web/app/plugins/owid/src/Card/Card.js) for example usage)

On the baker end, this URL should be passed through the [internal resolver](https://github.com/owid/owid-grapher/blob/0ad5705909abebbb927f38a1ea4f2a7080c36e83/baker/redirects.ts#L169) before pulling the metadata. An example of that is done in the [prominent link rendering function](https://github.com/owid/owid-grapher/blob/0ad5705909abebbb927f38a1ea4f2a7080c36e83/baker/siteRenderers.tsx#L477).

### Grid
The [Grid](https://github.com/owid/owid-grapher/blob/master/wordpress/web/app/plugins/owid/src/Grid/Grid.js) component provides a responsive 4-column grid (e.g. https://ourworldindata.org/coronavirus) which should be close to handle the last two rows as-is.

### Sub-categorization
Articles are not attached to Wordpress categories / subcategories. They can be attached to entries through the [subnavigation JS object](https://github.com/owid/owid-grapher/blob/0ad5705909abebbb927f38a1ea4f2a7080c36e83/site/SiteSubnavigation.tsx#L14) for a handful of deeper / more recent topics. It might be preferable to push that categorization to the content graph rather than extending alongside this model. This categorization is outside of the scope of this project and should be added manually in the page content for the time being.

**Comment by danyx23** [comment]
@mlbrgl I think we can close this one?
