### ISSUE TITLE
Ability to show relative toggle in spreadsheet explorer charts

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1543]
## Core problem

Stacked area charts, in particular, could greatly benefit from the ability to show a relative toggle in spreadsheet explorers.
E.g. this view here: https://ourworldindata.org/explorers/population-and-demography?Metric=Population+by+broad+age+group&Sex=Female&Age+group=At+age+0&Projection+Scenario=None&country=~AFG

## Proposed solution

We already have `stackMode` as a property on spreadsheet explorers. We should add `hideRelativeToggle`, too - potentially under a different name.

**Comment by sophiamersmann** [comment]
I think this is a duplicate of #2028 (or the other way around)

**Comment by marcelgerber** [comment]
Yep, closing this as a duplicate of #2028, which is more sketched out.
