### ISSUE TITLE
Ability to disable entity names on scatter plots

### ISSUE THREAD

**Issue by CGiattino** [owid/owid-grapher#1550]
## Core problem

For the AI Project I'm making a bunch of time scatter charts, and sometimes the fact that the entity names show by default makes the chart very busy and hard to read.

Two example charts: [GPU price-performance](https://owid.cloud/admin/charts/5885/edit), where it's just way too busy and you can barely see the points, and [ImageNet performance](https://owid.cloud/admin/charts/5887/edit), where one of the names slightly occludes the line for "Human baseline."

It's very important to have all the entity names in these charts. I foresee more examples of this coming up as I make more charts.

## Selected solution (updated 2022-08-02)

Add an option to turn off entity names being shown by default, so that they're only shown on hover.

- [ ] Add a new option to the grapher schema
- [ ] Use the new option to disable entity names on scatterplots
- [ ] Ensure it works for explorers too

## Alternatives

Add a variable control control what that lets you choose what share of names are shown -- from 100% (show all entity names) to 0% (show none, only show them on hover).

**Comment by larsyencken** [comment]
@danielgavrilov Do you know if the top of your head whether our current algorithm would be easy to tweak in this way?

**Comment by danielgavrilov** [comment]
If I remember correctly, the labelling algorithm only cares about whether there are overlaps between text labels.

A thing to tweak might be the _minimum distance to the next label_ such that a higher value leads to less labels close together.
