### ISSUE TITLE
Facebook (and Twitter?) are not showing our thumbnails in cards

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1561]
## Description

For some reason Facebook has stopped showing our thumbnails when sharing a link. A [user reported this](https://owid.slack.com/archives/C3RAU3BJ9/p1658348834662369) last week, and I waited a week to see if it fixes itself (it hasn't).

Nothing has changed on our side as far as I could see.

Twitter card validator does not show our thumbnail, but it is shown when writing a tweet 🤷 

## Steps to reproduce

Use Facebook sharing debugger to see the card Facebook generates when sharing a link: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fourworldindata.org%2Fmuch-better-awful-can-be-better

Or, for Twitter:
1. Go to https://cards-dev.twitter.com/validator
2. Enter `https://ourworldindata.org/much-better-awful-can-be-better`

## Screenshots

<img width="1016" alt="Screenshot 2022-07-25 at 14 27 26" src="https://user-images.githubusercontent.com/1308115/180788564-f4a75344-651a-42e3-aca1-44d68be09cab.png">

<img width="1023" alt="Screenshot 2022-07-25 at 14 27 13" src="https://user-images.githubusercontent.com/1308115/180788579-5c6a8ae7-0b18-4e52-bf6a-fb8304252219.png">

**Comment by larsyencken** [comment]
Seems like a good next step would be to check if settings `og:type` to `article` fixes the issue for either Twitter or Facebook, perhaps making the change on a staging server.

**Comment by larsyencken** [comment]
Suggested to time box initial investigation to 1d, then come back to the team if it's not promising.

**Comment by marcelgerber** [comment]
A fix for Facebook is here: #1574. tl;dr the thumbnail URL we were providing was a 301 redirect, and FB apparently doesn't like that.

I'm also confused by Twitter. The card validator is never working for me currently, and I also had a few times where the thumbnail wouldn't show up for the tweet. But other times it was working just fine.

**Comment by marcelgerber** [comment]
Twitter has - very much undiscoverable - [announced that its Card Validator has been removed](https://twittercommunity.com/t/card-validator-preview-removal/175006), and is only to be used for legacy purposes.
However, the Card validator is still up under the same URL, has no mention of its discontinuation, and is only giving back `Unable to render preview` as its error message. That's not helpful at all, Twitter 🤦🏻 

Facebook previews work again, after rewriting thumbnail URLs to avoid redirects.
![image](https://user-images.githubusercontent.com/2641501/183410229-2eb5f93f-bfb9-41f3-9720-3912be70a891.png)

**Comment by larsyencken** [comment]
Thanks Marcel!
