### ISSUE TITLE
Proposal: migrate baking to Next.js

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1583]
## Problems

- We can't make dynamic pages or dynamic content on our site today -- it's all static
  - This prevents us from templating out some combinatorial options
  - This prevents us from generating accurate grapher thumbnails
- We have a lot of custom baking code, that can't benefit from paralellisation or other strategies that modern static site frameworks allow

## Proposal

- Look into the feasibility and benefits of moving to Next.js for our site baking

/cc @mathisonian

**Comment by Marigold** [comment]
I touched baking this week and decided to see whether it'd be feasible to migrate it to Next.js. I was hoping to use it for **efficient** (= parallel, caching, standardisation) generation of static HTMLs for all grapher charts.

I've tried to implement grapher pages with their [Dynamic routing](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths), however I hit the following blockers:

1. There's **no easy caching** from build to build (e.g. only rebuilding grapher charts when input data has changed). There's an [incremental strategy](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), but it only applies after we've built the site

2. No straightforward way how to bake grapher png and svg images just like we'd bake grapher html. One could run them as a side-effect of [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props), but it felt hacky

It's fair to say that I've only used Next.js once before for a simple project, so it's possible there's a way.

**Comment by larsyencken** [comment]
Thanks for looking into this Mojmir! Super interesting... I watched their demo video on the incremental strategy now. I couldn't understand whether you'd need to run a continuous build server and shoot an API request on any data change to have it rebuild that route.

It's also unclear to me whether Next.js would assume run-time access to MySQL, or whether bake-time access is enough to begin with.

**Comment by larsyencken** [comment]
If we wanted to deploy on CloudFlare Pages, we'd need to use the [Edge runtime](https://blog.cloudflare.com/next-on-pages/) for any dynamic functions, and we'd need to use a [DB connector](https://blog.cloudflare.com/relational-database-connectors/) to be able to query MySQL.

I reckon that, rather than try to port our existing work across, it would be pretty interesting to do a small example Next.js app on Cloudflare Pages with a MySQL connection, just to see what that end-to-end setup looks like and how hard it is to work with.

**Comment by larsyencken** [comment]
Closing this for now, we can keep the idea alive in discussions instead.
