### ISSUE TITLE
Concept: modularise and open source site components

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1584]
## High level vision

We want to be able to remix site elements easily to quickly make new pages and new visualisations.

To enable this, we'd like to identify and make modular and consumable elements that are high value for reuse.

## Proposed changes

- Grapher is split out and consumable as an independent open source project, with releases to NPM
- OWID site is its own private repo
- (Are there other reusable components that we would want here?)

## Sub-issues

- #1082

**Comment by larsyencken** [comment]
@mathisonian Did you have a specific sense of which components would be most useful to be thinking about here?

**Comment by mathisonian** [comment]
I think the following would be helpful to start thinking about as independent pieces:

- grapher 
- front-end component library (buttons, dropdown, images, etc)
- shared database types / utils
- baker
- admin + wordpress (the code for these might be better off separate or together, depending on how coupled they are)

We'd want them each to be independently packaged, versioned, and released. I don't have a strong stance on if its better to break these modules into their own repos or keep them in a monorepo using something like [lerna](https://lerna.js.org/). The monorepo structure is likely nicer to work with.

**Comment by larsyencken** [comment]
Ah, Ierna looks cool! It sounds to me like a monorepo would be best for internal development, provided it's still easy to work on just one project at a time, and the build system is sane. Looks like Ierna and Nx solve the build problem.
