### ISSUE TITLE
Can't properly load localhost:3030 web app

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#1589]
## Description

I am trying to run the docker following the instructions from [here](https://github.com/owid/owid-grapher/blob/master/docs/docker-compose-mysql.md), and after running it - apparently - successfully, I can't access the web app in port 3030.

## Steps to reproduce

I first run `make up`, which outputs all the expected messages.

Then, I go to localhost:3030, and the site seems not to load properly.

![image](https://user-images.githubusercontent.com/18101289/183917347-5a9f9548-8c10-4e1f-a43a-5bc313ff814c.png)

Then, if I try to access localhost:3030/admin, I am prompted with username and password (which might indicate that something is working). After introducing the values for development, the page loads and seems to stop responding (blank page).

Note: I am actually running this from a remote machine (Linux), where I create an ssh tunnel (`ssh despatx -L 3030:localhost:3030 -N`).

**Comment by danielgavrilov** [comment]
Ah hold on, only port `:3030` is forwarded? You also need `:8090` for webpack.

**Comment by lucasrodes** [comment]
Thanks!

```
ssh remote -L 8090:localhost:8090 -L 3030:localhost:3030 -N
```

solved it

**Comment by lucasrodes** [comment]
The same issue happened again today. The problem now was that I my web browser (Brave) was blocking some content via its "Brave Shields" plugin.
