### ISSUE TITLE
Error importing new data

### ISSUE THREAD

**Issue by nwaughachukwuma** [owid/owid-grapher#16]
The images below is a screenshot of the errors I got when I tried to import new data into the application. Could you help explain what the problem might be. Thanks

![image](https://cloud.githubusercontent.com/assets/20521315/22336210/49d6a9d8-e396-11e6-8d54-5650dca2469b.png)

![image](https://cloud.githubusercontent.com/assets/20521315/22336241/6064842c-e396-11e6-8a70-88007774ee4f.png)

**Comment by asangansi** [comment]
May be the explanation here helps - https://github.com/OurWorldInData/owid-grapher/issues/15

**Comment by nwaughachukwuma** [comment]
Thanks @asangansi

**Comment by nwaughachukwuma** [comment]
Hi guys, i get the error in the image below, when I try to save/store a new dataset. Any idea what can be done?

![image](https://cloud.githubusercontent.com/assets/20521315/22731416/6fca00e6-ed9f-11e6-8dde-fc5d59010f2b.png)

**Comment by nwaughachukwuma** [comment]
Hi @mispy I noticed that the App\Http\Controllers\ImportController::store() is missing. Is it intentional?
