### ISSUE TITLE
Implement new grapher colour palettes

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1611]
Marwa has enumerated and fixed a lot of issues in our existing color palettes (see https://www.figma.com/file/EpWbE8AkTYWxK8FECGhoHj/Color-Explorations). This project is about adapting Grapher as much as possible to using these new palettes.

[This Notion page](https://github.com/owid/owid-grapher/issues/1611) contains more details and background

The subtasks of this project will be:

## This cycle

- [x] Update core OWID Distinct palette with improved colors
- [x] Make simple alignments with Marwa's set (add new color palettes that are straight forward)
- [x] Bar charts should have a single color for all bars that is chosen from one of 5 sets
- [x] Add hatching for no-data value in Maps
- [x] Make two different color dropdown color scale choices - one for line-ish charts and one for solid-ish charts
- [x] Remove old style dampening of line colors after optimized line chart palettes are in place

## Not this cycle

For the work that was not done in this cycle there is the follow up tracking issue: #1673

### Improvements

- [ ] Remove obsolete/bad palettes like Inferno (Question: what to replace them with?)
- [ ] See if it is easy to add flexible single hue palettes from color.js
- [ ] Add descriptions to color palettes and surface them in the color dropdown
- [ ] Remove ability from admin to use free colors - only colors from the current palette should be available
- [ ] Fix Marimekko continents color mapping

### Cleanup tasks (propably outside the eng task):

- [ ] A lot of bar charts use multiple colors - do we want to fix this?
- [ ] Remove color palettes from actual use that are only used very rarely
- [ ] Make a tool that matches individually chosen colors to the closest color palette and see if we want to switch all/some

**Comment by danyx23** [comment]
This work was implemented in the the PRs:
* #1653 
* #1658 
* #1662 
* #1663 
* #1664 
* #1670
