### ISSUE TITLE
Admin for managing Google Docs articles

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1613]
_(original description by @mlbrgl)_

As part of the migration from Wordpress to google docs (#1597), we're replacing the Wordpress block editor with Google docs.

Beyond editing documents, Wordpress provides some non-editor features, such as publication workflows, media management, document management or category management.

```
Wordpress block editor  ≡  Google docs
Wordpress admin  ≡  ?
```

**This issue aims at filling some of this gap, starting with document management.**
_Other candidate CMS features of the current set-up can be found in the [CMS glossary](https://www.notion.so/owid/067696ab94f54167a20f64d702a9e93d?v=09c7595411944e5ab0300c58adc2dd27), which will serve as a basis for migration decisions around CMS features._

A possible approach has been developed in the https://github.com/owid/owid-show experiment and might be ported over to 
https://github.com/owid/owid-grapher. Some other approaches will be considered as well, in anticipation of the port of all remaining CMS features into this new foundation.

## Cycle 2022.5 (Aug 29 -> Sep 16)

Wireframes, background work

## Cycle 2022.6 (Sep 26 -> Oct 14)

**Completed on branch, awaiting [PR](https://github.com/owid/owid-grapher/pull/1703) review**
- [x] gdocs refresh flow
- [x] API routes
- [x] content checks
- [x] UI, dialogs
- [x] wiring with Matt's work
- [x] feedback rounds
- [x] integration of additional metadata (e.g. authors, date)
- [x] UX polishing, probably around document status and available actions
- [x] preview in new tab?

**Merged and shipped**
⏳

**Additional scope**
- [ ] integration with feed (and newsletter)
- [ ] integration with Algolia

**Comment by mlbrgl** [comment]
### Gsheet-based publication workflow
This is an exploration of using Gsheet as the replacement fro Wordpress admin features, starting with the publication workflow.

```mermaid
sequenceDiagram
Author ->> Gdocs: write draft
Author ->> Gsheet: register article
Author ->> Gsheet: publish article
Gsheet ->> Gsheet: run appscript
Gsheet ->> Baker: send baking request w/ document ID
Baker ->> Gdocs: get document content
Gdocs -->> Baker: receive document content
Baker ->> Baker: process ArchieML
Baker ->> Grapher DB: save JSON
Baker ->> Baker: bake site
```

_Authors write ArchieML documents in Gdocs, then list them with their [metadata](https://www.notion.so/owid/067696ab94f54167a20f64d702a9e93d?v=2649dcb45a2c4f648ea4dd691ec7117d) in the companion spreadsheet._

**Comment by mlbrgl** [comment]
### Conclusion 
Gsheet as an admin for managing articles is not convincing. **Favour tighter integration in bespoke admin.**

### Rationale
With most of the article metadata pushed to the document frontmatter, there is little to no content left in this sheet. This makes the value of spreadsheet functions and scripting features equally limited.
Versioning and commenting are probably among the most salient features spreadsheet offer (incidentally not specific to the format), but fail to outweigh the benefit of tighter relationships between charts and articles (including referential integrity), a [visible and well-known limitation of the current system](https://www.notion.so/owid/Knowledge-graph-entries-as-topics-unify-grapher-and-Wordpress-taxonomies-4992c4f2671248c8872e19073debb172).


### Pros and cons of Gsheet as an admin interface for articles
_Roughly by order of importance_

**Pros**
- versioning / rollback
- contextual (per cell) commenting + notifications
- little code / maintenance effort to benefit from spreadsheet features
- sheets can be enhanced through scripting (e.g. bulk operations)

**Cons**
- lack of native referential integrity for manual, non [content graph](https://github.com/owid/owid-grapher/pull/1070), article <-> chart relationships (e.g. [originURL](https://github.com/owid/owid-grapher/pull/1455), categories (if kept))
- wiring required between independent systems (gsheet and baker)
- filtering / searching article content and frontmatter not in the sheet requires API calls (to Algolia or Grapher)
- appscript DX?
- preferable to export to grapher DB in case of API unavailability

**Comment by mlbrgl** [comment]
Admin screen for managing google docs based articles (lo-fi wireframe) 

👉 [Interactive prototype](https://www.figma.com/proto/KjlMj8wxYXoOZWfkOokNYK/Untitled?node-id=5%3A497&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=5%3A497)
--

<img width="1246" alt="Screenshot 2022-09-02 at 15 51 33" src="https://user-images.githubusercontent.com/13406362/188163686-77663a3b-db69-46c3-8ce9-e238866f4b2e.png">

<img width="1246" alt="Screenshot 2022-09-02 at 15 51 50" src="https://user-images.githubusercontent.com/13406362/188163721-25954678-d809-4c5c-8bab-996c4e577e7d.png">

_Done with [Lo-Fi Wireframe Kit](https://www.figma.com/community/file/887892609124245416)_

**Comment by mlbrgl** [comment]
Wireframe update:
- replace "Published" toggle by button: not appropriate for tasks with delays or dialogs
- add latest publication date
- create a "danger zone" by colocating "unpublish" and "delete"
- swap "publish" for "update" when document already published
- remove inactive / mutually exclusive buttons, see decision diagram below:

```mermaid
graph LR
    A{Is published} -->|Yes| D
    A -->|No| B[fa:fa-cloud-upload-alt Publish]
    D{Has updates} -->|Yes| C[fa:fa-redo-alt Update]
    D{Has updates} --> F[Unpublish]
```

<img width="1246" alt="Screenshot 2022-09-07 at 15 39 51" src="https://user-images.githubusercontent.com/13406362/188898664-80c6e5c4-15a7-4eec-a7ff-c0698fe7155f.png">

**Comment by mlbrgl** [comment]
Wireframe update:
- move "danger zone" actions (unpublish, delete) behind a dropdown. Frequency of use doesn't require them to be always visible, making space for other more recurring actions.

<img width="1241" alt="Screenshot 2022-09-09 at 13 37 49" src="https://user-images.githubusercontent.com/13406362/189341760-8f698c38-6513-4d7c-a8fc-d37c64d3a3c6.png">

- add publication settings screen. Will be triggered before initial publish, and when pressing "Settings". Not shown on updates (assuming unchanged settings always validate)

<img width="1241" alt="Screenshot 2022-09-09 at 13 37 58" src="https://user-images.githubusercontent.com/13406362/189342059-6834b6d9-6e70-49fb-86c5-88c92f3a753d.png">

**Comment by mlbrgl** [comment]
### An argument for metadata source of truth to be the admin DB

In order to simplify the publishing workflow for authors, we want the slug to be automatically derived from the title upon publishing
	- When the title changes later on, the slug should remain unchanged to avoid creating broken links
	- The slug can be manually changed if necessary
	- When a slug is manually changed, we should create a redirect between the old and the new slug

**Source of truth**

With the slug edited in the admin, we can...
- check for uniqueness
- implement character validation 
- regenerate it from the current title

... in a more straightforward way than if the slug was typed in as text in the document frontmatter. It also promotes a tighter feedback loop for errors or suggestions.

With the slug edited in the admin, authors can carry out all publication workflow related tasks in the same place, instead of going back and forth between the document (for editing metadata) and the admin (for validation).

**Comment by mlbrgl** [comment]
_Status update (Tues 13th)_

With the biggest part of the UI / UX work done on [Admin for managing Google Docs articles](https://github.com/owid/owid-grapher/issues/1613), I'm moving more confidently on the implementation of the basic publication flow this week, including:
- gdocs refresh flow
- API routes
- content checks
- UI, dialogs
- wiring with Matt's work

I'm aiming to get the happy path handled by the end of the week, to run through a first feedback cycle during cooldown. The rest will most likely span over 2/3 of the next cycle, giving one (maybe two) additional opportunities for feedback. Some of the "source of truth" discussions haven't fully landed yet. This brings a layer of uncertainty which we should account for.

**Comment by mlbrgl** [comment]
_Status update (Sep 14)_

A demo a of the (now abandoned) early implementation of the wireframes above ([commit](https://github.com/owid/owid-grapher/commit/8bbe4c950cf61d98f9ad7cf3b2c7f885c3e5e336) from Sep 14)


https://user-images.githubusercontent.com/13406362/191674624-f9c8c201-a728-4690-baf5-ef98a13428f6.mp4

**Comment by mlbrgl** [comment]
Feedback from individual sessions with @larsyencken (Sept 20) and @eoo-owid (Sept 22)
- in draft mode, the "Publish" button might be too prominent for the frequency at which it will be used. In that sense, it is not a primary action, but "Save draft" is. That prominence might also attract accidental clicks. This suggests that it should be managed, either by making the button look more "dangerous" or by adding a confirmation dialog.
- comments and suggestions are not visible in preview: that might be an important information to surface when deciding to go ahead with publishing. A more restrictive version of the workflow could prevent publishing when the source document has unresolved comments or suggestions
- if A edits and previews at the top of a document and doesn't notice B is also editing the document, A might go ahead and publish B draft changes without knowing
- surfacing the changes that are about to be published would help with the problem above, but is also probably a valuable sanity check. Content diffs are already available in google docs, but there is no indication of which version is published. Named versions could help but are manual
- additive suggestions are being considered part of the text and transparently integrated: this is probably not desired. Subtractive ones are being ignored, which is less of an issue, but should still be surfaced (see above)
- title of the google docs file vs title of the article: should these be synced? In case the title of the document changes later on, the difference might create confusion. To note, the google docs title might currently be used for metadata, e.g. with prefixes ("-final", "-v3").
- we are creating two independant organization systems: google drive (team and/or private), and the CMS. How will that scale? What is the reference?

**Comment by mlbrgl** [comment]
See [status update](https://owid.slack.com/archives/C03G5HF66DD/p1664386573440939) following demo.

Slides: [Google Docs admin demo - 28 Sep 22.pdf](https://github.com/owid/owid-grapher/files/9667614/Google.Docs.admin.demo.-.28.Sep.22.pdf)

**Comment by mlbrgl** [comment]
_Status update Thu 29_

<img width="1440" alt="Screenshot 2022-09-29 at 18 36 18" src="https://user-images.githubusercontent.com/13406362/193093159-5714737d-595c-4687-83f0-e058dfd95106.png">

### Content metadata vs publication metadata

After experimenting with editing the title in the admin, I'm bringing it back to the google doc. The split is roughly:
- content metadata (e.g. title, subtitle) --> google doc
- publication metadata (e.g. slug, publication context) --> admin

By keeping the content metadata in the google doc, authors get to save more complete drafts of published articles, including the content metadata. Otherwise, when the content metadata is saved in the admin, authors have to publish straightaway or discard their changes - as changes to published articles cannot be saved.
Keeping content metadata in the google doc might also make it easier to leave comments related to these fields, although this has been deemed a minor concern thanks to the :skip section.

The [slug will remain in the admin](https://github.com/owid/owid-grapher/issues/1613#issuecomment-1243779268).

Another dimension for these source of truth considerations is the complexity of the data being entered. Titles are simple strings but authors or categories might benefit from a tighter integration in the admin, to provide a better editing UX as well as enforcing referential integrity between e.g. articles and their categories. As an example, this would prevent deleting a category used by an article and also allow for renaming categories across all articles.

**Comment by mlbrgl** [comment]
_Status update on current cycle scope - Oct 7_
For @larsyencken, @mathisonian 

- [x]  gdocs refresh flow
- [x]  API routes
- [x]  content checks
- [x]  UI, dialogs
`nice to have` Notify when leaving the page with unsaved edits in non-gdocs metadata. Gdocs metadata is saved either way in gdocs, so nothing is lost if the preview is closed with unpublished changes - which is not the case for non-gdocs metadata.
- [ ]  wiring with Matt's work
Baker and Wordpress integration operational, but no publish on change yet
- [x]  feedback rounds
2 formal meeting to date with Joe and Mallika (and Hannah for one of them), in addition to informal feedback from other team members (see above). Recurring meetings set up on Tuesday PM.
- [ ]  integration of additional metadata (e.g. authors, date)
Dateline, publication date, byline, excerpt added. Missing publication context.
- [x]  UX polishing, probably around document status and available actions
- [x]  preview in new tab?

**Comment by larsyencken** [comment]
Thanks for the update Matthieu, looks like it's coming together.

Can you please update the issue summary at the top, and perhaps reorganise the checklist into things that are completed on-branch vs things that have passed review and shipped?

For this project, it would probably look like this:

- [ ] Prepared PR for review
  - [ ] Feature 1
  - [ ] Feature 2
  - [ ] ...
- [ ] Merged and shipped

**Comment by mlbrgl** [comment]
_Status update - Oct 13_

- [x] wiring with Matt's work (see [lightning update announcement](https://owid.slack.com/archives/C03G5HF66DD/p1665665003529329))

This was the last remaining item in scope. PR opened: https://github.com/owid/owid-grapher/pull/1703
