### ISSUE TITLE
Apply style guide to topic and article pages

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1617]
Effectively, going through the pages on [Figma](https://www.figma.com/file/cZrEfEgWkpAQTeLLQyukDw/%5BDesktop%5D-Library-1.0?node-id=4%3A2) and implementing/overhauling each area.

There should be a 1:1 parity between Marwa's Figma naming conventions and our CSS such that it is trivial to apply "H4 Semibold" styles to any element and have it look exactly the same as it does in Figma.

I think accruing the changes on a staging server until it's all done and then merging into master might be the best way to go about it.

### Top priority Foundation tasks:
- [x] Typography (mixins for each of the 20 styles, all existing typography converted to use one of these mixins)
- [x] Colour (swap out all pre-existing colour variables and hexcodes in our CSS for ones from the new palette)
- [x] Grid (update our container sizes and convert column logic to use CSS grid instead, update grapher auto-sizing logic)

### Components:
- [ ] Icons
- [ ] Anchor
- [ ] Banner
- [ ] Breadcrumb
- [ ] Button
- [ ] Code Block
- [ ] Content Switcher
- [ ] Dropdown
- [ ] Editorial Components
- [ ] Link
- [ ] Lightbox
- [ ] Navigation
- [ ] Page Header
- [ ] Slideshow
- [ ] Tab
- [ ] Tooltip

**Comment by larsyencken** [comment]
@mlbrgl is this one safe to close off now?

**Comment by mlbrgl** [comment]
I think so. Article and topic pages - which constitute the largest part of our site - both have been revamped with the new design, and implementing them in gdocs mostly meant going through every element. This means the consistency with the style guide will improve automatically as more articles / topic pages are ported.
