### ISSUE TITLE
Medium-style urls

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#162]
Medium uses urls that have a user friendly slug with a unique id appended on the end:

https://medium.com/@mbostock/why-you-should-use-d3-ae63c276e958

The advantage of this is that you get nice urls while also not needing to care about tracking redirects at all, which simplifies the code a great deal, especially for charts where there are many urls. The post is resolved based on the unique id only.

Unfortunately, I'm not sure we can actually implement this with Netlify at the moment, because their redirect system is not as flexible as full regex. e.g. this doesn't work:

/*-ae63c276e958 /life-expectancy-ae63c276e958

But good to keep in mind for the future.

**Comment by breck7** [comment]
So the idea is an immutable file pointer. I'm going to say no on this for now and close it. Urls look ugly to me. But it's a neat idea and wouldn't oppose if someone reopened
