### ISSUE TITLE
Wordpress: Spurious changing container ids on every deploy

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1632]
## Description

We have [five pages](https://github.com/owid/owid-static/search?q=wp-block-group) that use a "Group" block in Wordpress (`wp-block-group`).
These are rendered together with a `wp-container-{id}`, where id seems to be a seemingly-random id.
This leads to these pages changing on every deploy (even if the post didn't change), which you can observe in owid-static. [The diffs look something like this](https://github.com/owid/owid-static/commit/07d7f3fc93cb34c58b4382ae14d43f3d56a253d0?diff=unified#diff-24d34f77b58a90026bd0f7a5c8663d57725cb3b00102aaae2dd788864f3e60a9):

```diff
- <div class="wp-container-630f1fa918f60 wp-block-group">
+ <div class="wp-container-630f21bd509e0 wp-block-group">
```

<details>
<summary>Example of a "Group" block</summary>

![image](https://user-images.githubusercontent.com/2641501/187645122-1f95eeba-d267-4f2e-976a-cd91fc69ff1d.png)

</details>

## Expected behaviour

Pages should be stable and not create any unnecessary diffs.

## Additional context

The easiest way to solve this is probably just to get rid of these `wp-block-group` blocks.

**Comment by danyx23** [comment]
Decided that this is not worth fixing any more since we aim to migrate away from wordpress soon
