### ISSUE TITLE
Bug(admin): "Is projection" option and line colouring

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#1642]
## Description

Trying to edit [this chart](https://owid.cloud/admin/charts/5960/edit) I found out that the checkbox "Is projection" unchecks itself when focussing elsewhere, and the colour pattern for the lines is not respected in the chart preview in the right panel.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Go to this https://owid.cloud/admin/charts/5960/edit)
2. Try setting all variables `.... - variant: medium` to "Is projection"

## Screenshots

https://user-images.githubusercontent.com/18101289/189323887-84b03012-fb5c-499b-99c9-b73d6ee3a9ff.mov

**Comment by marcelgerber** [comment]
Oh noes, I think this is a regression in #1623.

**Comment by lucasrodes** [comment]
so i think i found out some stuff:

- if I check the box, it actually checks it but it does not show it in the front end. So I have to click on it and then focus elsewhere.
- The colouring of the lines is weird, but that happened bc some metrics did not have a "Display name" assigned. If assigned, it behaves as expected.
