### ISSUE TITLE
Can't recreate yarn.lock file

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1644]
## Description

There is an issue that the current `yarn.lock` file can't be reproduced from scratch. 

## Expected behaviour

Removing and generating a new `yarn.lock` file should leave the project in a working condition but doesn't. 

## Steps to reproduce

1. Clone the repo
2. Run `rm yarn.lock`
3. Run `yarn`
4. Run `make up.full`
5. See error:

```
clientUtils/urls/Url.ts:9:9 - error TS2314: Generic type 'URLParse<Query>' requires 1 type argument(s).

9 ): Omit<urlParseLib, "query"> & { query: string } => {
          ~~~~~~~~~~~
``` 

## Environment

For desktop, provide:

-   OS: MacOS
-   Node Version: this occurs with both Node v16 and v18

## Additional context

Not an urgent problem, but we should fix it as it makes e.g. solving merge conflicts related to dependencies more difficult to resolve.

**Comment by danyx23** [comment]
This issue might have been fixed already on the esm branch - @ikesau or @marcelgerber do either of you remember fixing this already and can quickly do this on master again?
