### ISSUE TITLE
Package grapher separately to the OWID site

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1667]
## Problem

We currently have a single codebase that contains multiple related components, including grapher, the grapher admin, and our site. A person trying to work on grapher spins up a copy of our site in order to work on it, which is kinda crazy. Since grapher is packaged as a sub-part of our site, it's impossible for others to reuse without hard forking our codebase. This means that we lose out on substantial contributions, and can't even reuse grapher properly in internal projects.

## Context

We have tried separating out grapher once before, but became immediately bogged down in an ESM migration, which the team brought very far, but ultimately had to halt due to problems with Jest.

## Proposed solution

Split our codebase into two, high-level packaged projects, one for `grapher` and one for our `site`. Within those pieces, we can retain subfolders with submodules. Doing this split also means redoing top-level CI so that it runs on both projects. The grapher admin is proposed to live as part of the site, rather than part of grapher, since it is so tied to baking and data management.

## Proposed scope

- [ ] Move existing modules in to `grapher/` and `site/` folders
- [ ] Add independent packaging information to grapher
- [ ] Consume grapher in site
- [ ] Run both sets of tests in CI
- [ ] Update `Makefile` to work correctly for managing overall CI and developer experience

## Out of scope

- Substantially changing our developer experience this cycle
- ESM migration

**Comment by larsyencken** [comment]
From chat with @ikesau today about our audience:

- Journalism shops are unlikely to be users: either they are so big that they build their own in-house tools, or they just use DataWrapper (or similar)
- Massive institutions are possible but unlikely users: they have a fire under them to get better at data communication, and probably already have teams of graphic designers and consultants on these projects (e.g. WHO with https://data.who.int/)
  - We have probably missed this wave by ~2y
- But, there are very large civic open data projects that have very poor and barely-interactive data viz, that could be consumers of and contributors to our work

**Comment by ikesau** [comment]
`grapher/` directory would merge:
- `explorer`
- `grapher`
- `coreTable`
- `gridLang`

`site/` would merge:
- `adminSiteClient`
- `adminSiteServer`
- `baker`
- `db`
- `explorerAdminClient`
- `explorerAdminServer`
- `gitCms`
- `public`
- `serverUtils`
- `site`

`clientUtils`, `utils.ts` (possibly a third directory? depends on how much `site` and `grapher` share)

`devTools` likely stays top level (with refactoring)

`wordpress` remains its own thing

We will have to reconsider how we manage `settings`

Open question: what happens to types? 

[Reviewing tsconfigs](https://github.com/owid/owid-grapher/blob/master/devTools/project-dependencies.md) is a useful way to understand each directory's dependencies.

**Comment by larsyencken** [comment]
We've separated out grapher already, good enough for now
