### ISSUE TITLE
Assigning manual entity colors doesn't work on some distinct bar charts

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1671]
## Description

When you have a distinct bar chart and you set an entity color in the data tab the corresponding bar should have this color but instead it doesn't change color FOR SOME BARS (!)

## Expected behaviour

A bar with a manually assigned entity color should be drawn in that color

## Steps to reproduce

1. Open chart 1882 (e.g. here: https://staging.owid.cloud/admin/charts/1882/edit )
2. In the data tab change the color for Switzerland
3. The bar does not change color
4. Change the color for South Korea
5. The bar does change color

## Screenshots

![Screenshot 2022-09-20 at 15-08-10 owid-admin](https://user-images.githubusercontent.com/2772449/191266036-5b62701c-120f-4b85-9ba2-df7b32ad2d52.png)

## Additional context

I was suspecting that I introduced this bug as part of the #1611 issue but the problem seems to predate this. Maybe it is related to the PR #1623?

**Comment by marcelgerber** [comment]
This is not related to any recent change - it's also happening on `playfair` (51712f2) and `neurath` (1c7398f), which are both running on many-months-old changesets right now.

From a very first investigation, it looks like `entityIds` are being dropped somewhere in the table transform, probably in `interpolateColumnWithTolerance`.

![image](https://user-images.githubusercontent.com/2641501/191343812-089b7095-f1ff-4191-9a30-19e973026798.png)

**Comment by danyx23** [comment]
You make Sherlock Holmes look like Regular Holmes! Great that you uncovered where this came from, that is already very helpful.

**Comment by larsyencken** [comment]
Marked it as "nice to have" since it hasn't emerged as a prio for authors, but @marcelgerber if you believe it would be a quick fix you're welcome to have a shot after your other tasks.

**Comment by marcelgerber** [comment]
> but @marcelgerber if you believe it would be a quick fix you're welcome to have a shot after your other tasks.

Definitely not an easy one, sadly!

**Comment by larsyencken** [comment]
Bumping it back down to "nice to have" since it hasn't caused us any issues in the meantime and no authors are banging down our door
