### ISSUE TITLE
Concept: downloading data from grapher should give a zip file with a README alongside csv

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1682]
## Core problem

We want people to be able to reuse the data that we share wherever possible. To reuse the data properly, they need not only an interoperable format (a CSV file), but also information about:

- How to cite the data (see: https://github.com/owid/owid-grapher/issues/1137)
- What license the data is available under
- What caveats the data comes with
- A human-readable write-up of where the data came from (essentially, the Sources tab)

## Proposed solution

Generate, for every grapher chart, a zip file containing the current CSV file and alongside it a README either in plaintext, markdown or PDF, which contains at minimum the contents of Sources.

## Context

- Currently, there is no permalink to the CSV files provided by grapher charts, since the CSV files themselves are generated dynamically on the browser
- We could consider whether we can (or want to) dynamically generate this zip file, or whether we would prefer to bake it at site build time

**Comment by Marigold** [comment]
How about adding a python snippet for downloading the data programatically using owid-catalog-py?

**Comment by larsyencken** [comment]
> How about adding a python snippet for downloading the data programatically using owid-catalog-py?

Ah, that we could actually do much sooner! For many datasets, we could be baking that now.

**Comment by larsyencken** [comment]
To fold this in to our Browsable Data Catalog and Future of Publishing discussions.

**Comment by JoeHasell** [comment]
Some feedback motivating this issue:

We recently had long conversations with the poverty data team at the World Bank where we discussed if they were happy with how we are using their work and citing them.

They were in general very happy. Their only feedback to us was that the data downloads from charts leave people a bit in the dark. For instance the version of the data is something they are now taking care to communicate. We note the version in the dataset-level metadata. But someone looking at the data after they downloaded it from a chart doesn't know the version.
