### ISSUE TITLE
Support custom ordering in scatterplot legend

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1690]
[Requested](https://owid.slack.com/archives/C46U9LXRR/p1664866252742859) by @pabloarosado 

## Problem

The scatterplot legend is ordered alphabetically, which makes sense when it represents a nominal categorical variable (e.g. gender, region) but not when it represents an ordinal one. 

In the example below, rather than alphabetical order, the legend would be better ordered from "Low income" to "High income", or the reverse, with "Not categorised" at the end.

<img width="600" alt="Screen Shot 2022-10-04 at 11 03 01" src="https://user-images.githubusercontent.com/36012/193779787-eba12800-3c1f-4bbd-ba9d-bf1b2ce83a82.png">

Link: https://ourworldindata.org/grapher/consumption-co2-emissions-vs-population

## Technical context

- Scatterplots allow you to colour by a variable
- But variables are currently _untyped_, meaning that Grapher does not know even if they are categorical or numeric until it looks at the data, let alone whether the data is sequential or ordinal

**Comment by larsyencken** [comment]
From discussion with @danyx23 , it would be possible to solve this in the grapher admin, but even nicer would be to try to solve the general problem in the upstream data.

Marking as "nice to have" and estimating a 3d fix, which makes it unlikely we'll come to it soon.

**Comment by marcelgerber** [comment]
This issue came up again today [as a request by Joe](https://owid.slack.com/archives/C46U9LXRR/p1665516003901699).

**Comment by sophiamersmann** [comment]
This is one of the motivating example for getting data types into Grapher (which we really want to do), so I want to keep this issue open for now
