### ISSUE TITLE
Scatterplot rounding causes clipped coordinates in log plots

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1691]
Reported by @pabloarosado 

## Problem

In the example plot below, we see that the first four x positions that data points exactly match the rounded values (0.01, 0.02, 0.03, 0.04). This means that the data is being clipped to two significant figures, but this leads to an inaccurate layout for small data points when using a log plots.

<img width="1285" alt="Screen Shot 2022-10-04 at 11 09 56" src="https://user-images.githubusercontent.com/36012/193781177-0c1858f7-8a1a-4af0-bb01-963132d9611a.png">

Link: https://ourworldindata.org/grapher/consumption-co2-emissions-vs-population?time=earliest

**Comment by larsyencken** [comment]
Marking as "nice to have" since it affects only a few log scatter plots, and only some of the data on those plots.

**Comment by toni-sharpe** [comment]
Is this fixed @larsyencken 

[Current link](https://ourworldindata.org/grapher/consumption-co2-emissions-vs-population?time=2019)

<img width="800" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/08d2766a-c4e7-4248-87bb-24c0c1e4f2b6">

IOt's not getting flattenened off by the looks of it

<img width="373" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/af8bd4ed-43e1-44c2-b31b-58aa28e05f33">

Maybe another log level down qwould be nice: `if (vals need iy) { go to 0.001% }`

**Comment by danyx23** [comment]
@toni-sharpe true, this seems to be fixed by now :). Closing this
