### ISSUE TITLE
Concept: types in grapher data model

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1692]
## Problem

- The data processing in Grapher on the client is more complex than it needs to be because we don't know types
- Visualisation is more complex than it needs to be because we don't know types
  - E.g. we don't know hierarchy between categorical variables (World vs Europe vs Sweden)
  - E.g. we don't know that a categorical variable is in fact ordinal (Low Income, Middle Income, Upper Income)
  - E.g. we can't auto-pick the best color palette because we don't know enough about the categorical variable

## Proposed solution

- Add a type system to Grapher's data model that includes numeric, geo, and ordinal types (with optional ordering)

**Comment by larsyencken** [comment]
@pabloarosado Just a head up from the ETL side that this is something that we'd like to move towards.

**Comment by sophiamersmann** [comment]
Issues that would benefit from knowing data types:
- Treat columns with categorical data differently than numerical columns
    - https://github.com/owid/owid-grapher/pull/3094
    - https://github.com/owid/owid-grapher/issues/3044
- Use ordinal data to sort legends
    - In scatter plots: https://github.com/owid/owid-grapher/issues/1690
    - In maps: https://github.com/owid/owid-grapher/issues/2710
