### ISSUE TITLE
Line charts faceted by entity collapse to an invalid bar chart

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1695]
## Description

A multi-metric line chart can be plotted all together, faceted by entity (country) or faceted by metric. When faceted by entity, it collapses to an invalid single bar chart.

## Expected behaviour

It should collapse to a faceted bar chart, as it does when faceted by metric.

## Video example

https://user-images.githubusercontent.com/36012/193887799-2cd7afa6-9453-41a8-8f52-14712b8d647b.mov

https://ourworldindata.org/explorers/poverty-explorer?Metric=Share+in+poverty&Poverty+line=Multiple+lines&Household+survey+data+type=Show+data+from+both+income+and+expenditure+surveys&Show+breaks+between+less+comparable+surveys=false&country=NGA~MOZ~ZMB~BOL~KEN~BGD~BOL~GEO

## Technical notes

- For some reason faceting by country is disappearing from the `availableFacetStrategies` at this moment
- If we could work out why and enable it, the bug might resolve itself

**Comment by larsyencken** [comment]
cc @JoeHasell

**Comment by JoeHasell** [comment]
Could I get a sense of the time frame that this issue is likely to progress @larsyencken?

In case it helps inform prioritisation: This issue blocks somewhat a group of poverty and inequality explorers that we would like to publish in the coming weeks. We have a workaround – dropping some of the multimetric views, and deprioritising map views (that make the broken one-year factet more likely to be seen). But this makes the explorers somewhat less valuable.

**Comment by larsyencken** [comment]
Hey Joe, sorry for the slow response. Unfortunately, this is a slightly chaotic moment in engineering just pre-Sicily, with a bunch of carry-over from an ambitious previous cycle and a few people on leave this week.

It won't get picked up this week, but if it's pressing we can prioritise it for the week post-Sicily.

**Comment by larsyencken** [comment]
Tagging this one for next cycle

**Comment by marcelgerber** [comment]
Hey @JoeHasell, this is now fixed!
Your collapsed bar chart will look something like this going forward: https://ourworldindata.org/grapher/daily-new-estimated-infections-of-covid-19?time=2021-01-10&country=DEU~FRA
![image](https://user-images.githubusercontent.com/2641501/206799211-7c9c9bd1-6cfa-49a8-b0a0-b2ab470111d5.png)

So, this means that you can now add back these multi-metric views that you had to leave out for the initial launch. If you need help with anything or anything's unclear, please reach out :)
