### ISSUE TITLE
Mobile view of /energy/country page has charts that are too small to read

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1699]
## Description

There are some charts on e.g. https://ourworldindata.org/energy/country/united-states that are placed side-by-side when viewing on a mobile device. 

## Expected behaviour

The charts should be stacked vertically, rather than horizontally so that they are wide enough to see and read the chart. 

## Steps to reproduce

1. Go to https://ourworldindata.org/energy/country/united-states
3. Scroll down to 'What sources does the country get its energy from?'

## Screenshots

<img width="470" alt="Screen Shot 2022-10-07 at 8 28 31 AM" src="https://user-images.githubusercontent.com/1074773/194591381-0f09a033-9f67-432b-a392-c0b383bc1fb8.png">

**Comment by larsyencken** [comment]
@ikesau This looks like you already fixed it. If that's the case, we can close it.

**Comment by marcelgerber** [comment]
Yes, should've been fixed in https://github.com/owid/owid-grapher/commit/d4c13719ec2313ccafc125ab757e00a0afe8508d.
