### ISSUE TITLE
Tracking issue: details on demand

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1704]
## Overview

We have general concepts that we want to explain to users, but re-writing them often is both error prone and a maintenance nightmare. To attempt to solve this, we have two systems, Details on Demand (https://owid.cloud/admin/details) and the Glossary.

To properly make use of Details on Demand, we that it should be supported in Grapher charts, in Explorers, and that it should power the glossary function that we have experimented with in the past.

<img width="805" alt="Screen Shot 2022-10-13 at 12 53 56" src="https://user-images.githubusercontent.com/36012/195578509-5ed5e01d-a9ac-4151-97b9-f782ce155c59.png">

## Stakeholder

@JoeHasell 

## Issues

- [x] #1448 
- [ ] #1705
- [ ] #1706

## Technical notes

Some deeper thoughts are in this [Notion document](https://www.notion.so/owid/2022-10-21-Global-Details-on-Demand-fb8da90cb4f84c69a06735ed86901fc9).

### Finding examples

Here are a few examples:

- https://ourworldindata.org/grapher/number-un-peacekeeping-missions
- https://ourworldindata.org/grapher/supercomputer-power-flops

You can find charts that use details on demand by looking for the syntax:

```sql
select id, json_unquote(json_extract(config, '$.slug')) slug
from charts
where config like "%::%"
```

**Comment by danyx23** [comment]
@larsyencken seems like a very useful feature that would make DoDs more useful overall as well. Spoke with Ike about it and we think it makes sense to consider this for the cycle after Sicily or the first cycle of the new year.

**Comment by ikesau** [comment]
Spoke with @HannahRitchie 

As part of this work that could be considered DoD's V2: 
- Increase the content size limit in the DB from 1024 to ~1500
- Add a text character counter in the admin UI so authors know when they're approaching the limit

**Comment by marcelgerber** [comment]
As text length increases - or even today, actually - we need to think about how to make space for long texts in the UI.

https://ourworldindata.org/grapher/total-ghg-emissions is overflowing the grapher viewport on my 14 inch laptop already:
![image](https://user-images.githubusercontent.com/2641501/198010335-7bb69bdf-628d-465b-b76f-791babd2d435.png)

One option could be to make the DoD scrollable with a slight visual indicator, like we do for tooltips:
![image](https://user-images.githubusercontent.com/2641501/198010904-64bfdc27-13e9-4ef8-9fe4-89162fbdbaa3.png)

**Comment by edomt** [comment]
Not urgent at all, but nice to have: could we strip leading and lagging whitespace in details when they're saved in the admin? I spotted this one today: 

<img width="491" alt="image" src="https://user-images.githubusercontent.com/7103774/208613839-8e2a5526-84dd-4e39-9a07-ce1e56ae78b7.png">

(I've removed the lagging line break now.)

**Comment by larsyencken** [comment]
Global DoDs have now shipped, glossary has been removed.
