### ISSUE TITLE
Site-wide details on demand

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1705]
1. Details on demand have only been implemented in Graphers. 
2. Authors write subtitles and footer text differently depending on whether or not they can include DoDs.
3. Because Explorers don’t support DoDs, authors aren’t using them at all, as it increases the amount of FASTT they need to maintain.
4. We need to support DoDs in Explorers and articles. They could also replace the [current glossary feature.](https://github.com/owid/owid-grapher/blob/master/site/glossary.ts)

The simplest and most robust way of accomplishing this would be to load all DoDs on every page, and use a document-wide event listener that shows a tooltip whenever a user hovers/clicks an element with the appropriate attributes (`.detail-on-demand`,  `data-category`, and `data-term`)

We would still want to track whenever a DoD is referenced so that we can rebake the site as necessary whenever a DoD's content is updated.

Also, it would be nice to have nested DoDs so that authors don't have to fit every single bit of context in a single definition.

**Comment by larsyencken** [comment]
@ikesau Do you recall what was missing for explorers to have this support too? Would love a ballpark estimate for this (e.g. 1d vs 3d vs 1w)

**Comment by marcelgerber** [comment]
Closing this, implemented in #2114.
