### ISSUE TITLE
Use details on demand definitions for glossary

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1706]
## What

Replace the current glossary backend with details on demand in the grapher db.

## Why

The glossary visual design is well loved, but authors wanted a better experience before committing to using it more. Then after some time, details on demand emerged for Grapher charts, and supports a dedicated admin. But these two features as so related that we believe they can share the same data backend.

If the same definition could be used in text, in charts and in explorers, then it would be much more attractive for researchers to use across our site.

## What's involved

TBD (@mlbrgl do you have a sense on how hard this would be?)

**Comment by ikesau** [comment]
Would be roped in as part of #1705 . The only additional work would be removing the glossary code.

**Comment by mlbrgl** [comment]
Glossary code removed in #2206

**Comment by marcelgerber** [comment]
I think this is done, then?

**Comment by ikesau** [comment]
I guess so! I thought there was still work to migrate old glossary links to use dods but it [looks like we weren't using them anywhere anyway.](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select+%22https%3A%2F%2Fourworldindata.org%2F%22%7C%7Cslug+from+posts+where+content+like+%22%25ourworldindata.org%2Fglossary%25%22)

**Comment by marcelgerber** [comment]
Ah no, whether glossary feature was enabled or not was only specified in WP post metadata, and then it would automagically highlight all terms for which it has a glossary definition I think.

The 5 posts where the glossary feature was enabled are:
- Where in the world do people have the highest CO2 emissions from flying? https://ourworldindata.org/carbon-footprint-flying
- Maternal Mortality https://ourworldindata.org/maternal-mortality
- Child and Infant Mortality https://ourworldindata.org/child-mortality
- Climate change and flying: what share of global CO2 emissions come from aviation? https://ourworldindata.org/co2-emissions-from-aviation
- Fertility Rate https://ourworldindata.org/fertility-rate

<details>
<summary>SQL</summary>

```sql
SELECT t.*, wp.post_title, wp.post_name
FROM wordpress.wp_postmeta t
join wp_posts wp on t.post_id = wp.ID
WHERE meta_key = "owid_glossary_meta_field" and meta_value = 1
```

</details>

You can [see the feature in action here on this old staging server](https://jefferson-owid.netlify.app/child-mortality).

**Comment by mlbrgl** [comment]
I don't think anyone expects glossary terms to be ported over to dods and added manually to these pages, but maybe I'm missing some context here.

**Comment by ikesau** [comment]
Yeah I think my response was like, excessively completionist. I think we can close this issue. 😅
