### ISSUE TITLE
Endpoint `/admin/api/data/variables/data/*.json` doesn't run in parallel for data stored in parquet

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1711]
## Problem

Loading pages like [this one](https://owid.cloud/admin/datasets/5809) has huge latency. That is because DuckDB is blocking for some reason and admin app only runs in a single thread. I've experimented with various settings in DuckDB and nothing worked. The only way to run it in parallel is by using DuckDB from worker threads.

## Solution

There are couple of things we can do:

1. Fix [range requests in Cloudflare workers](https://github.com/owid/etl/issues/362) which should bring the latency down, but it'd still be sequential and potentially slow
2. Run our app in cluster mode (with multiple processes). I've experimented with it and DuckDB worked in parallel
3. Spawn ~worker thread~ process on every DuckDB query

**Comment by Marigold** [comment]
Using Cloudflare in front of S3 is about ~4x faster, but it still takes 15s to load all variables for an aviaition dataset. Running our app in cluster mode is probably the easiest option now.

**Comment by Marigold** [comment]
I've been experimenting with Cloudflare R2. The only advantage over S3 is that it's free. It's not globally distributed yet, so the latency is comparable to S3 (could be hundreds of milliseconds which is quite poor).

**Comment by danyx23** [comment]
@Marigold as we said yesterday, let's talk about this with @larsyencken on Wednesday or Thursday. Maybe going back to the Python base solution for this particular endpoint is a good option.

**Comment by Marigold** [comment]
Couple of notes for future us before we park this:

* `duckdb` doesn't work well with workerpool... the most recent updates might have fixed it, but we should still keep an eye for segfaults if we move ahead with it
* with parquet admin was too slow for some edge cases, e.g.
  * loading [chart with a lot of variables](https://owid.cloud/admin/charts/6196/edit) - range requests to parquet files on S3 take ~300ms minimum, it was seconds for this particular dataset. Chrome can make maximum 6 requests to one server and so requesting 20 variables gets really slow
  * same for [aviation dataset](https://owid.cloud/admin/datasets/5809) which loads a lot of variables in admin view
  * we have a few options here - make datasets smaller (GHE has 400MB total), cache range requests (not possible in Cloudflare), faster S3 / R2, bake `[variable_id].json` files separately, ...
* range requests to huge files with dimensions are inefficient, e.g. GHE dataset that has 400MB has indication as one dimension. To read a couple kbs of data we have to load the entire column (with all indications) and then filter it client-side

**Comment by marcelgerber** [comment]
Closing this now, since we're no longer using DuckDB and the API has also been reworked quite a bit.
