### ISSUE TITLE
Project: Port Wordpress pages content to ArchieML JSON

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1712]
We want to move fully to the new google docs based authoring flow but we have a lot of content still in Wordpress. This project is about automatically moving wordpress pages into google docs/ArchieML.

A substantial fraction of components that we have in Wordpress do not exist yet in google docs. Part of this project is then to get an understanding of what fraction of the wordpress content we are able to translate yet. At the end of the cycle we can then decide if we want to proceed with another push for automating the remaining conversions or resolve to doing some of them by hand.

The basic approach will be to translate the content field in the posts table in Grapher into a new column that stores json in the same (ArchieML) format as the content of the posts_gdocs table. As part of this statistics will be generated to track which % of posts can be translated already (either fully faithfully or with some missing blocks). When this is done to a satisfactory degree the next step will be to create google docs pages that generate the content from ArchieML (thus adding a reverse mapping from ArchieML json to google doc that might be useful for migrations etc in the future). Finally we will decide what to do with remaining untranslated sections and then turn off baking from wordpress and remove it from our infrastructure.

# Steps

- [x] #1728
- [x] Add new column on posts for ArchieML json and one for statistics (json object with keys for simplicity as this will be temporary)
- [x] Set up translation code that transforms from WP html with wp comments to ArchieML
- [x] Start iterative process of converting more and more blocks - aligning with the project to add more components to google docs authoring

### Details to check

(The remaining open details will be tracked in a new follow-up issue: #1870)

- [x] {ref} can start in a header and continue for a few paragraphs, then end in a {/ref}. This needs to be handled
- [ ] `<!-- formatting-options -->` need to be handled. Possible keys are enumerated in owidTypes.ts
- [ ] divs are currently eliminated. Some might contain class information that is relevant. Try to check if this is causing issues
- [ ] Author information needs to be transferred from wordpress to the grapher posts table so we can use it for the byline
- [x] Check that charts work after migration
- [x] Check that explorers work after migration
- [ ] not all tags are translated yet. These are the things still to do:
  - [x] ol
  - [ ] pre

**Comment by ikesau** [comment]
[Matthieu's glossary of CMS terms and components](https://www.notion.so/owid/067696ab94f54167a20f64d702a9e93d?v=09c7595411944e5ab0300c58adc2dd27) will be helpful here.
