### ISSUE TITLE
Refine "no data" hatching on maps 

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1713]
## Core problem

The current maps work quite well with the hatching pattern showing "no data" to help us visually distinguish countries for which values do or do not exist. 

However, [in certain cases](https://owid.cloud/admin/explorers/preview/global-health-copy?facet=none&country=OWID_WRL~CHN~ZAF~BRA~USA~GBR~IND&Category=Health+systems&Indicator=Community+health+workers+per+1%2C000&Metric=Rate&Source=WHO+%28GHO%29) where the data is very sparse the hatching can be kind of noisy and visually buzzy. We could consider a few other options for hatching patterns that are a little more subtle and would work even in cases with very little data. 

## Proposed solution

We'd need to experiment with some alternative shades and spacing to use in the pattern and find one that doesn't suffer from this issue.

## Alternatives

Alternatively we could keep the design as is, it isn't bad right now.

## Context

<img width="960" alt="Screenshot 2022-10-21 at 15 11 14" src="https://user-images.githubusercontent.com/1074773/197233069-7ad7877c-057c-498f-9ea9-ceb5928240dc.png">

**Comment by danyx23** [comment]
Decided to look into this briefly in the future of publishing working group and see if we can find a slightly nicer light gray for the hatching that still also works well for cases where only one small country has no data. If not it will be a wontfix
