### ISSUE TITLE
Controls on charts should be more clearly defined

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1714]
## Description

As a reader wrote, ```There is a need to define on each chart all terms used on that chart.  Like relative, what does that mean on a chart? [...]  Please define your terms on every chart.  I'm older, I don't remember.```

He's right - it isn't obvious what the button does. It's especially confusing when both relative and absolute values are showing %'s (e.g. in https://ourworldindata.org/grapher/age-dependency-breakdown). We could write it out more clearly instead of just saying "Relative", or have a tooltip or "?" icon that shows explanatory text.

**Comment by ikesau** [comment]
With "Global DoD" stuff fresh in my head, the Tippy instance method could handle this nicely. We could add all sorts of `detail::ui::relative-mode` type definitions and attach them to UI elements with just a little code telling Tippy to pay attention.

We'd probably want to exclude these definitions from the ones that get appended to the SVG export.

It's also not necessary to do this through DoDs, we could just add a bespoke tooltip to [this part of the code.](https://github.com/owid/owid-grapher/blob/master/grapher/controls/Controls.tsx#L62)

**Comment by danyx23** [comment]
This needs a bit of design (how should this look on mobile, how on desktop) and we should consider which of the options to do this for (all the controls we have are enumerated in [this file](https://github.com/owid/owid-grapher/blob/master/grapher/controls/Controls.tsx)). Once this is decided it's probably not a lot of work.

**Comment by marcelgerber** [comment]
I think this is part of #2486 now, anyways.

**Comment by sophiamersmann** [comment]
Resolved by the Grapher redesign
