### ISSUE TITLE
Line charts using a color scale (value mapping) can be too light to read

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1724]
## Description

Pablo A just reported this - this is a regression introduced by the color work in #1118 . As part of that work we switched away from manipulating colors in code and instead now have different color palettes optimized by Marwa for either line charts or area charts. But for line charts we sometimes use the color scale for the line color and then we should re-introduce this feature. For normal line charts this is not used that often but it is visible in all the tooltips for maps, which makes this a rather frequent issue.

![image (2)](https://user-images.githubusercontent.com/2772449/197998636-deb491b5-019d-44d6-98e2-26af8da7e0a3.png)

## Expected behaviour

Lines should be darkened for line charts when values are mapped via a color scale and the colors are very light.

**Comment by marcelgerber** [comment]
For future reference, the commit that removed this feature is https://github.com/owid/owid-grapher/commit/fd3cb0aab90bb2d2ce8284d75ea03f7bdba3b900
