### ISSUE TITLE
Tracking issue: ArchieML blocks for article pages

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1735]
Components that we know how to proceed on:
- [x] Grey section
- [x] Prominent link

We'd also like:
- [x] Article headers
- [x] A way to set different column layouts

Still waiting on design for additional information.

**Comment by danyx23** [comment]
@mlbrgl @ikesau I think we have all of those by now? Can we close this issue?

**Comment by ikesau** [comment]
Nearly - still need prominent links!
