### ISSUE TITLE
formatWordpressPost breaks columns if a static chart isn't found

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1736]
## Description

Discovered by @CGiattino as he prepared the AI chart review page. He embedded several grapher iframes into a page, and found that the column layout in the article preview didn't appear as expected.

## Expected behaviour

All these charts should show up in order, in the right column.

Instead, some of them were right, and some of them were side-by-side.

## Steps to reproduce

For now, an example of this glitch is on this page: https://owid.cloud/admin/posts/preview/54105

(A previous revision may have to be restored, as I intend on manually fixing the error for this page.)

## Screenshots

![image](https://user-images.githubusercontent.com/11844404/199091106-0672dc3f-841f-4ab0-af07-8b84b0638495.png)

## Additional context

This seems to be related to https://github.com/owid/owid-grapher/blob/master/baker/formatWordpressPost.tsx#L382

Specifically, the if-statement that requires `grapherExports` to exist, and a baked version of the chart to be present. 

This means that if we're embedding charts from staging (which, admittedly, we only ever do for internal advance-QA purposes), static versions of the charts may not exist in prod's assets directory and the layout will break.

Even though this is a rare event, this function shouldn't break the layout if a static export doesn't exist. Presumably the calls to `el.remove()` are responsible in some way. Maybe they're removing the sticky container? 🤷

**Comment by danyx23** [comment]
Since this is only happening for wordpress posts when they are using charts that do not have svgs baked yet (for example because they come from a staging server) we decided that this is not worth fixing anymore as we will switch to gdocs soon-ish
