### ISSUE TITLE
Toggle to show watt-hours/year as watts

### ISSUE THREAD

**Issue by probablykasper** [owid/owid-grapher#1756]
## Core problem

In charts like [Electricity production by source](https://ourworldindata.org/grapher/electricity-prod-source-stacked), it shows watt-hours produced by year. It would be great to have an quick way of knowing the production rate in watts, to compare with other numbers that are specified in watts.

## Proposed solution

An `Average rate (watts)` toggle

## Alternatives

Using a calculator

**Comment by larsyencken** [comment]
Thanks for the feedback Kasper!

It's not a quick thing for us to add a custom toggle like this, and we've standardised on terrawatt-hours for our energy related charts: https://ourworldindata.org/energy#explore-data-on-energy

You might have to use a calculator in this case, or download the data yourself and transform it in bulk.
