### ISSUE TITLE
Country profile nav overlaps with table of contents button

### ISSUE THREAD

**Issue by mathisonian** [owid/owid-grapher#1765]
## Description

On a 13" laptop screen the country selection nav overlaps with the table of contents button. See screenshot below.

## Expected behaviour

The two should not overlap. In this case a reasonable solution would be to make the "country selector" top bar less wide, so that it starts to the right of the contents button

## Steps to reproduce

1. Go to https://ourworldindata.org/energy/country/united-states on a laptop
2. Scroll down the page

## Screenshots

<img width="1409" alt="Screen Shot 2022-11-18 at 12 02 40 PM" src="https://user-images.githubusercontent.com/1074773/202690986-afc1b9d0-80e6-471c-884b-b57b1fd65c5b.png">

## Environment

For desktop, provide:

-   OS: MacOS
-   Browser Chrome
-   Version 107

**Comment by larsyencken** [comment]
Can you check it out when you have a moment @ikesau ?
