### ISSUE TITLE
Separate newsletter web-archives for each newsletter type

### ISSUE THREAD

**Issue by CGiattino** [owid/owid-grapher#1767]
## Core problem

Currently the newsletter [campaign archive on Mailchimp](https://us8.campaign-archive.com/home/?u=18058af086319ba6afad752ec&id=2e166c1fc1) doesn't distinguish between our two newsletters, the immediate update and the biweekly digest. They're listed all together, and while the Biweekly editions say "Biweekly digest," the Immediate updates don't say anything like that.

It would be nice if each newsletter type had its own archive so that we can provide a link to each archive as a preview of what people should expect when they are [signing up for a newsletter](https://ourworldindata.org/#subscribe).

## Proposed solution

A separate archive for each of our existing newsletters (Immediate and Biweekly) and the potential to add more if we create new newsletters.

## Alternatives

One archive, but different sections for our different newsletters that can be linked to.

## Context

Some more context on [Slack here](https://owid.slack.com/archives/C0149NKLZAM/p1666340117550549)

**Comment by CGiattino** [comment]
Perhaps an interim solution here is to link to the existing MC archive — the two newsletters are mixed together, but at least the Biweekly Digests are labeled, so users will be able to tell what to expect from that, and most can probably infer that the unlabeled newsletters are the other type (Immediate updates)

**Comment by mlbrgl** [comment]
Summary of how we could go about creating separate archives for immediate and biweekly newsletters:
- [ ] create "Immediate" and "Biweekly" folders on MC
- [ ] move the Immediate RSS campaign to the "Immediate" folder
- [ ] (recurring) manually move biweekly issues to the "Biweekly" folder as they are sent

This creates developer-facing archives:
- The last 10 biweekly issues are available through the [biweekly archive](https://ourworldindata.us8.list-manage.com/generate-js/?u=18058af086319ba6afad752ec&fid=18&show=10)
- The last 10 immediate issues are available through the [immediate archive](https://ourworldindata.us8.list-manage.com/generate-js/?u=18058af086319ba6afad752ec&fid=14&show=10)

Both these archives would need to parsed and exposed on ourworldindata.org URLs (e.g. https://ourworldindata.org/newsletter/biweekly) before they can be shown to readers.

**Comment by larsyencken** [comment]
If we can do it in a 1-day timebox, then it could be worth doing. Allocating it into the Xmas cooldown, but not yet assigned to anyone in particular. Could also check to see if Mailchimp already has a solution for something like this.
