### ISSUE TITLE
Quota exceeded for docs.googleapis.com

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#1769]
## Problem

We're getting a surprising out-of-quota message from our `/admin/api/gdocs/<hash>` endpoint:

```
Error: Quota exceeded for quota metric 'Quota group for read operations' and limit 'Quota group for read operations per minute per user' of service '[docs.googleapis.com](http://docs.googleapis.com/)' for consumer 'project_number:363269344442'.
    at Gaxios._request (/home/owid/live/node_modules/gaxios/build/src/gaxios.js:130:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async JWT.requestAsync (/home/owid/live/node_modules/google-auth-library/build/src/auth/oauth2client.js:382:18)
    at async gdocToArchieML (/home/owid/live/itsJustJavascript/db/gdocToArchieml.js:17:22)
    at async Gdoc.updateWithDraft (/home/owid/live/itsJustJavascript/db/model/Gdoc.js:48:30)
    at async /home/owid/live/itsJustJavascript/adminSiteServer/apiRouter.js:1791:9
    at async /home/owid/live/itsJustJavascript/adminSiteServer/FunctionalRouter.js:40:22
```

Our use of Google Docs is actually quite low still, so we should work out how we're using this API and what the limits are early on and use it to inform our design decisions.

**Comment by larsyencken** [comment]
cc @danyx23

**Comment by larsyencken** [comment]
Monitoring for the API requests can be found here: https://console.cloud.google.com/apis/dashboard?project=owid-articles&pageState=(%22duration%22:(%22groupValue%22:%22PT1H%22,%22customValue%22:null))

**Comment by larsyencken** [comment]
API limits are here: https://developers.google.com/docs/api/limits

<img width="880" alt="Screenshot 2022-11-22 at 10 46 40" src="https://user-images.githubusercontent.com/36012/203281460-088ea362-2c18-42c1-9c1e-bb59de44eab2.png">

**Comment by mlbrgl** [comment]
My understanding is that, since we're using a service account, that quota is shared amongst all internal users (authors and devs). With the preview refreshing every 5 seconds, this means every opened gdocs preview tab consumes (60/5) 12 requests / min out of the 300. With (300/12) 25 previews open simultaneously, we're out of quota.

**Comment by larsyencken** [comment]
Hmm... 25 concurrent live previews seems like a decent number, unless people just leave them running in open tabs for ages without working on them...

**Comment by larsyencken** [comment]
From discussion with @danyx23: could be we're making API calls at a strange time, e.g. during baking? He was thinking to try to dig in and understand the situations when we call out, to see if something like that could be the case.

**Comment by marcelgerber** [comment]
Another way we could go wrong is if we have a React hook somewhere that sets up the `setInterval`, and that is not properly cleared, potentially leading to multiple 5-second timers running at the same time.

That we can easily check for, of course, using the browser DevTools.

**Comment by larsyencken** [comment]
Marking it as "nice to have". If it comes up more, we can give it more love. If it stops magically, we can close this issue.

**Comment by danyx23** [comment]
I think we can close this, haven't seen this in quite a while
