### ISSUE TITLE
Show datasets as archived on the Datasets page when their namespace is archived

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1770]
## Core problem

The data team uses the `archived` column of the `namespace` table to archive namespaces after they're no longer in use. For example, Bobbie recently archived the namespace `wdi`. 

When `archived = 1`, the datasets belonging to the namespace have a label that says `ARCHIVED` in the search when creating scatterplots:

![image](https://user-images.githubusercontent.com/7103774/203534651-aba94fc6-9ded-4276-acc4-643e04939850.png)

But the same datasets are still visible without any particular label on https://owid.cloud/admin/datasets. This means that when searching for `WDI`, the user gets a list from which they can't know that some of them have been archived.

![image](https://user-images.githubusercontent.com/7103774/203535064-17b76327-bc1e-4f59-9e2f-8768d54d02dc.png)

## Proposed solution

Add the same `ARCHIVED` label from the scatterplot variable search to the list of datasets on https://owid.cloud/admin/datasets.

## Alternatives

Hide these datasets altogether from the search results on https://owid.cloud/admin/datasets.

**Comment by larsyencken** [comment]
It sounds like the data team is expecting the `isArchived` flag on `namespaces` to do something different to what it does. Right now, if a dataset is set as `isArchived`, then it is completely hidden from search, and also removed from the ETL and all backporting.

One quick fix is simply for the data team to do the join and archive the matching datasets when they archive the namespace.

Alternatively, we could try to make the admin UI (and the ETL machinery) respect a different concept of archiving, where something is archived if the flag is set on it or its namespace.

@edomt Do you have a preference?

**Comment by edomt** [comment]
I think the confusion is actually larger 😅 

I don't think we've been using the `isArchived` variable in `datasets` at all. So far our internal instructions are:

![image](https://user-images.githubusercontent.com/7103774/204519292-6c65cd42-0231-4fb0-bec5-ad01ccbd4b95.png)

Should (a) become this?

> Unpublish older datasets by setting them to isPrivate = 1 and isArchived=1

---

Separately, I can't seem to be able to access the SQL db on live:

```
owid@owid-live:~$ sudo mysql -D live_grapher
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by larsyencken** [comment]
> Separately, I can't seem to be able to access the SQL db on live:

Ah, we moved the db to a different instance a little while back, it's on `live-db` instead (`ssh owid@live-db.owid.io`).
