### ISSUE TITLE
Italics in source text not rendering correctly in Grapher static exports

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1771]
We're not correctly rendering Source text with HTML tags during the static export of charts.

# Steps to reproduce

1. [Go to this URL](https://ourworldindata.org/grapher/excess-nitrogen-per-hectare?country=CHN~IND~USA~GBR~BRA~JPN~SWE~NOR)
2. See _Science_ (italicised) in the source text
3. Click on the 'Download' tab
4. Click on 'Image'
5. Open the downloaded PNG file
6. See `<i>Science</i>`

![excess-nitrogen-per-hectare(1)](https://user-images.githubusercontent.com/11844404/203618248-a20d9384-3bb9-44b9-ac08-e54a8dfd485a.png)

# Additional context

We're using `TextWrap` without `rawHtml: true` in the [Footer sources method](https://github.com/owid/owid-grapher/blob/master/packages/%40ourworldindata/grapher/src/footer/Footer.tsx#L94). 

`<i>` is not a valid SVG tag so we can't just switch the flag. 

We'll need to use `MarkdownTextWrap` while updating the source text to use `_markdown italic syntax_` and updating a few bits of logic in the Footer that require the width of the text to be measured.

**Comment by ikesau** [comment]
The HTML tags seem to only be coming through when we're automatically generating the source text, seems they're set somewhere upstream.

**Comment by danyx23** [comment]
This was never really intended to be full HTML afaik - let's ask the data team where the text comes from?

I think we maybe shouldn't change anything about the rendering yet as we don't want to actually support raw HTML here

**Comment by ikesau** [comment]
We've fixed this at the source and have chosen not to support HTML in the source field.
