### ISSUE TITLE
Find a better way to represent missingness in charts with time on the x-axis

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1772]
## Core problem

In the current version of Grapher, missing data is handled by connecting the last-available and next-available data points together. 

In [this chart](https://ourworldindata.org/grapher/alcohol-consumption-per-person-us), for example, the prohibition of alcohol in the US means that there is no data available at all for the period 1920–1933. Grapher handles it by showing a downward slope between the two points, which gives the wrong impression about what happened (that alcohol consumption linearly diminished over the period).

![image](https://user-images.githubusercontent.com/7103774/203816183-d2cd8d94-b00f-40cb-856f-42ae71d45d3d.png)

The way we've fixed this in the past is by replacing `NA` values with `0`:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/7103774/203816507-cc84b1c3-e821-4c92-8af1-edec8aea7d97.png">

Visually this is a much better solution, but now the tooltip on hover shows a value of 0.00 – which is also misleading (it could give the impression that prohibition stopped alcohol consumption entirely).

## Proposed solution

I'm actually not sure – I don't think we've ever come up with a satisfying solution. We do want distant points to be connected in general; for example between 1850 and 1860 on that alcohol chart. But _sometimes_, because of contextual reasons, we want missingness to actually be shown rather than filled with linear trends.

**Comment by larsyencken** [comment]
From discussion with @danyx23: it seems that we want two kinds of NA values in this chart, one which it's fine and helpful to interpolate over, another that it's not. Or alternatively, we want as a kind of chart annotation to be able to mask over an entire time period and provide extra info on hover.

@mathisonian Heads up that this kind of situation came up. There's not an obvious solution right now.
