### ISSUE TITLE
Default admin password doesn't seem to work

### ISSUE THREAD

**Issue by makenoteshere** [owid/owid-grapher#1774]
## Description

hi, I was able to setup the local version. But the login creds of admin@example.com and admin as password aren't working

## Steps to reproduce

Followed the setup instructions, went to http://localhost:3030/admin/login?next=%2Fadmin%2F

<img width="394" alt="image" src="https://user-images.githubusercontent.com/7573744/204094011-46b4c150-b8ac-4d46-92d1-44c5f1525966.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/7573744/204094024-db9034cc-1fc7-4694-9c30-0ef0cd1a995e.png">

Am I missing something?

## Environment

For desktop, provide:

-   OS: Mac monterry
-   Browser Chrome

**Comment by marcelgerber** [comment]
Hi! Could you elaborate how you set up your local development environment?
Are you running things in Docker, [as described here?](https://github.com/owid/owid-grapher/blob/master/docs/docker-compose-mysql.md)

If you're running in Docker, then the startup script _should_ ensure that a database dump is imported into the database before it is started.

Alternatively, you can also try running the following SQL snippet to create the login credentials manually:
```sql
USE grapher; # or whatever your grapher DB is called
INSERT INTO users (`id`, `password`, `isSuperuser`, `email`, `fullName`, `createdAt`, `updatedAt`, `isActive`) VALUES (1, 'bcrypt$$2b$12$EXfM7cWsjlNchpinv.j6KuOwK92hihg5r3fNssty8tLCUpOubST9u', 1, 'admin@example.com', 'Admin User', '2016-01-01 00:00:00', '2016-01-01 00:00:00', 1);
```

**Comment by makenoteshere** [comment]
@marcelgerber thank you. I think sql import may have failed somewhere. I reimported the sql dump and worked. Thank you.
