### ISSUE TITLE
Details on demand tooltip breaks text wrapping in Safari (mobile & desktop)

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#1790]
Hellooo 👋 

## Description

On Safari, when the DoD tooltip shows up, every letter in the DoD term breaks into a separate line.

## Expected behaviour

The DoD tooltip shouldn't cause any text reflow.

## Steps to reproduce

1. Open (in Safari): https://ourworldindata.org/grapher/emission-factors-food-transport?country=Air~Rail~Road~Water
2. Hover or click on a DoD term

https://user-images.githubusercontent.com/1308115/205629950-a2be6848-8df0-4bf4-aaab-d14ef3660435.mp4

## Environment

Desktop:

-   OS: macOS Ventura 13.0.1
-   Browser: Safari 
-   Version 16.1 (18614.2.9.1.12)

Smartphone:

-   Device: iPhone 12
-   OS: iOS 16.1.1
-   Browser: Mobile Safari

**Comment by danielgavrilov** [comment]
Seems like a new Safari bug, didn't notice it before. Maybe rendering tippy outside the text (in a separate container) might fix it, or some magic CSS rule to avoid this behaviour in Safari.

**Comment by marcelgerber** [comment]
Hello gavrilov!

Yes, I just tested it and it indeed was fine back in Safari 15. (tested it in LambdaTest, to which only I have access at this point :/ )
