### ISSUE TITLE
Open external links in a new tab by default

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1791]
_raised by @CGiattino_
## Core problem

Inconsistencies in behaviour on link click if authors forget to set the target to a new tab.

## Proposed solution

We should have sensible defaults, that are overridable.

At the moment, no action by authors result in inconsistencies for external links, which then open in the same tab (as opposed to the recommendation of opening them in a new tab authors manually set act on sometimes).

## Context

Currently there is some soft norm for authors to set external links to open in a new tab and to set internal links to stay in the same tab. But as far as I (Charlie) can tell, this is not followed with any consistency or even at all.

This might be only addressed after the migration to google docs if it comes early enough and would make applying it to the current system only applicable for a short time.

**Comment by mlbrgl** [comment]
Discussed [here](https://www.notion.so/owid/e568f46704a246048ed888eafb88b83e#8ff3e3034eee4406bad73d2587182daf)

**Comment by ikesau** [comment]
Should be dead simple to add a function to our `link-span` that handles this.
