### ISSUE TITLE
Details on demand markup appearing in preview HTML

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1805]
## Description

Syntax that shouldn't be visible to the user is displaying on social media previews: https://twitter.com/AdemBdrByzd/status/1596439939864223747

## Expected behaviour

The `[contents](hover::general::fossilemissions)` syntax shouldn't display. It should just read as `contents`

## Steps to reproduce

1. Paste a link to [a standalone grapher page that features a detail on demand](https://ourworldindata.org/grapher/annual-co2-emissions-per-country) into twitter
2. The preview will include the DoD markup

## Screenshots

<img width="581" alt="image" src="https://user-images.githubusercontent.com/11844404/207109430-bc48e02e-4d8a-40e3-9758-fa8f63aa36f2.png">

**Comment by ikesau** [comment]
Simple fix. Make sure we parse `grapher.subtitle` to plaintext first.

https://github.com/owid/owid-grapher/blob/master/site/GrapherPage.tsx#L41

**Comment by danyx23** [comment]
Bumping this as it also affects search results (I assume it's the same underlying issue) - see [slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1675247426943029). Ike, if solving this for search would be very different then please feel free to create a new issue for that aspect.
