### ISSUE TITLE
feature: ignore population source when used as auxiliary variable

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#1806]
## Core problem
Whenever population variables are used in scatter plots (to size bubbles) or in Marimekko charts (to size bar widths), we should not list the source for the population in the chart footer.

Population variables are used as auxiliary variables in these cases and might add too much text to our charts. Note that the source for the population would still appear in the sources tab under the corresponding variable.

Currently, we have a [harcoded line](https://github.com/owid/owid-grapher/blob/abc26bb1883c1869b32624b5d6cbf35276efa318/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L1388-L1394) in Grapher that partially addresses this. However, this only works for scatter plots and will not work as we update the population variables (as variable IDs change too).

## Solution

We need a solution that smoothly works whenever we update population variables.

## Context

Find more context here: https://owid.slack.com/archives/C46U9LXRR/p1670855145129159

**Comment by marcelgerber** [comment]
This is now solved again, in a hacky way that will break next time around when the variable id changes.

We might want to move this to variable metadata at one point in the future.
