### ISSUE TITLE
We have some charts with `null` in `selectedEntityNames`

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1819]
## Description

We currently have 31 charts with a `selectedEntityNames` field that contains `null`.

## Expected behaviour

The field shouldn't contain nullish values, since Grapher's behaviour with that is not well-defined.
Additionally, the chart config schema should forbid these values.

## Steps

We should
- [ ] migrate these configs
- [ ] explore how these configs got created in the first place (through entities that have been dropped in data updates maybe?)
- [ ] ensure this doesn't get persisted in the future
- [ ] adapt the config schema

## Query to reproduce

```sql
SELECT id, config->>"$.selectedEntityNames", config->>"$.type"
FROM charts
WHERE config->>"$.selectedEntityNames" LIKE "%null%"
```

## Additional context

[First mentioned on Slack here](https://owid.slack.com/archives/CQQUA2C2U/p1670885085426849).
Closely related to #1245.

**Comment by ikesau** [comment]
Interesting that null seems to have  been a value in the schemas since 001. Seems straight forward enough to do and nice to get out of the way seeing as it can break the SVG tester.

**Comment by larsyencken** [comment]
@danyx23 Can we tie this in to the schema config compliance work that you're doing? If everything meets the schema, we'll never have these cases.

**Comment by larsyencken** [comment]
Closing this, subsumed by https://github.com/owid/owid-grapher/issues/2068
