### ISSUE TITLE
Gdocs: add support for breadcrumb

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1822]
<img width="1114" alt="Screenshot 2022-12-13 at 12 30 47" src="https://user-images.githubusercontent.com/13406362/207333412-99851119-5b8e-46c0-bd18-18de0e1eebcf.png">

**Comment by ikesau** [comment]
@mlbrgl do you have any ideas in mind for how you'd like to accomplish this? seems like we've got a pretty green field for rethinking how we want to handle categories. Might be best to get together with daniel and matt.

**Comment by mlbrgl** [comment]
@ikesau in the absence of a way to mass edit google docs, my current preference would be to keep this as a reference in the DB rather than a string in the frontmatter, similar to authors. We can always post-process that string and extract / migrate / validate, but this extra effort doesn't seem worth what we gain in portability. When and if we gain bulk editing capabilities over gdocs and a better editing experience over these frontmatter fields (smartchips?),  then I might sway the other way and favour a more uniform editing and processing flow, fully gdocs based.
