### ISSUE TITLE
Replace "Entries" tag with "Topics" in grapher admin

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1830]
## Core problem

"Entries" tag is now outdated.

## Proposed solution
<img width="1246" alt="Screenshot 2022-12-19 at 09 36 14" src="https://user-images.githubusercontent.com/13406362/208383293-b6a8ee09-7b5f-41e3-b6f5-4196e5a3baad.png">

- Rename "Entries" tag by "Topics" in grapher admin

- Rename post type in Algolia record 
  https://github.com/owid/owid-grapher/blob/82b76b1279285e96c3abb02f23bd38d1222c7d40/baker/algolia/indexToAlgolia.ts#L32
  https://github.com/owid/owid-grapher/blob/82b76b1279285e96c3abb02f23bd38d1222c7d40/site/SearchResults.tsx#L88

## Alternative
- Use tag id ("1640") instead of tag name ("topic") for a more "tag name agnostic" solution, although it is unlikely that this future-proofing would be more valuable than the code readability of "topic" vs "1640"

## Context

- "Entries" are being replaced by "Topic pages".
- Combine with or follow up to #1829

**Comment by devgarg2000** [comment]
Hey, let me know if I can contribute to make the correction. Seems quite doable to me.

**Comment by ikesau** [comment]
Hey @devgarg2000 , as in the other ticket we've decided to resolve this one internally. Thanks a bunch for your interest in helping out though! If you're still interested I could help you find something else to tackle 🙂
