### ISSUE TITLE
Topic pages are not being indexed properly in Algolia

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1845]
When searching for "Poverty", our topic page is not the first result, and the shown snippet is not a great representation of the article. 

Moreover, we would like to be able to display the fact that it is a Topic Page (similar to how we currently do with Entries (see #1829)) but currently they are only tagged as "Pages"

![image](https://user-images.githubusercontent.com/11844404/211031256-1a83c198-4878-4a1c-9fce-a8061f36f315.png)

**Comment by ikesau** [comment]
Topic pages can be identified via the `formatting-options` data that's set in wordpress: they must have `bodyClassName: topic-page` set.

**Comment by larsyencken** [comment]
This is prioritised for the current cycle with @marcelgerber taking a look at it.

**Comment by larsyencken** [comment]
🎉
