### ISSUE TITLE
Project: Static charts (illustrator graphics) as Grapher content

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1848]
## Core problem

Our authors create quite a few static charts in illustrator. These are then exported once and embedded in our website. Since they are not part of the "Grapher box" they don't have the benefit of different tabs. 

By moving all static image charts into a grapher frame we would get a sources tab, technical text linked to the image, share and download buttons with citation information and a better opportunity for serving different formats or responsive versions.

This could give us the following benefits:
- Sources tab for static images
- Table view for static images if it makes sense
- The ability to manage responsive versions of static charts (if we can author them)
- Share button
- Download button (both SVG and PNG)

See also the [image sequences project](https://github.com/owid/owid-grapher/discussions/1289) idea that we created for GSOC 2022 that describes a similar project.

## Proposed solution

Make static image charts a chart type in Grapher. A way of managing images would be required that the grapher admin is aware of (uploading, versioning etc). 

Linking variables could be useful so that the table view would work where appropriate (i.e. if we have the data in the ETL we should reference it so that users can download the data as per ususal)

One **big caveat** is that Grapher would need to be more flexible in terms of it's aspect ratio. Ideally Grapher would adjust to the content within certain boundaries and again ideally we would start authoring e.g. two versions of our charts, one for landscape aspect ratios (and bigger screens?) and one for portait (and smaller screens?)

## Alternatives

Keep using static images

## Context

Switching to Google docs for authoring necessitates "a solution" for managing images. It is probably worthwhile to have the needs of this project in mind for that work (cc @ikesau)

**Comment by ikesau** [comment]
As we're building up our own image management stuff, it may be simpler to build up an "Annotated Image" component which would allow us to build on all the Grapher-like functionality that we want to have for static images, without stacking up Grapher's house of cards any higher. (especially the aspect ratio changes)
