### ISSUE TITLE
Use country and region data from the ETL in Grapher

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1849]
## Core problem

Grapher has a weird relationship to geographic entities. It has maps ofc, but the mapping and identifiers that are used in the codebase are a bit all over the place. We use:
- numeric entity ids (internal legacy database ids)
- entity codes ([ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) codes for common entities plus custom OWID_ codes for other entities like World or historic countries)
- entity names

Some of these mappings are hardcoded in the codebase (some of them several times), as is the mapping to the geojson outlines we use for drawing maps. #1245 is a related issue that concentrates on cleaning up this mess for the purpose of selecting entities.

With the ETL we now have an authoritative place for storing information on countries along with names, other ids etc. We should either use a copy of this csv file directly (though it should probably be copied to our netlify assets) or derive a JSON file with the relevant information extracted and use that in Grapher instead.

This would give us the following benefits (with some additional work):
- Grapher could understand the hierarchy of World > Continent > Country and could selectively show only one of these levels
- It would be much easier to show different aggregates and also highlight them correctly in the map (e.g. countries grouped by income level) see #1350
- #1245 would benefit from this as the ids would be linked to additional information

## Proposed solution

- Use the information from countries_regions.csv and update it from the current ETL version during baking.
- Unify on using entity code as the default for selections and internal ids with entity name as the fallback if no entity code is available (so that in a fish stock dataset the entity name "Salmon" could be used without having to copy it to an entity code)
- Use the information from countries_regions as the sole source for understanding country hierarchy, get rid of manual legacy mappings
- Pick some then low hanging fruit like adding selection levels to only show lines from a given level of hierarchy (only continents, only countries etc) in one chart or the table view

## New scope (2023-04-12)

- Add a script to grapher that can parse region YAML data from the ETL and generating a static JSON or TS file in the Grapher codebase
- Use the static file to replace existing hard-coded country data where possible

**Comment by ikesau** [comment]
Pablo has written up the latest version of what we think this should look like here: https://github.com/owid/etl/issues/779

**Comment by larsyencken** [comment]
Reminder from our chat: the regions YAML might have different names for countries or regions than we use in Grapher for presentation. It's worth checking whether or not they're the same, and what to do if they differ.
