### ISSUE TITLE
Change detail on demand authoring to use Google Docs

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1863]
Relates to #1705 but could be done separately.

We implemented a custom table to track DoDs for the v1 implementation, but because DoDs are highly technical yet terse text, authors would like to discuss them better. Google Docs' comment functionality is a good place for this, so we would like to store DoDs there instead.

This would involve creating some specific Archie template to define the data with:

```
[.+dods]
{.dod}
title: Electricity
id: energy
[.+content]
Lorem ipsum

dolor amet.
[]
{}
[]
```

outputs:

```json
{
  "dods": [
    {
      "type": "dod",
      "value": {
        "title": "Electricity",
        "id": "energy",
        "content": [
          {
            "type": "text",
            "value": "Lorem ipsum"
          },
          {
            "type": "text",
            "value": "dolor amet."
          }
        ]
      }
    }
  ]
}
```

Authors would need to use the "Manually trigger a build" button whenever they updated the DoDs, and we'd ideally add a validation step here to ensure that no in-use DoDs had been deleted.

**Comment by marcelgerber** [comment]
Closing this, implemented in #2114.
