### ISSUE TITLE
Stacked bar charts should always show a linear x axis, even when there's missing data

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1865]
## Core problem

In the natural disasters explorer, which has a lot of sparse data, the x axis is currently all but linear:
![image](https://user-images.githubusercontent.com/2641501/213415789-e7f31824-eb3f-4b55-bdf3-7dfbf715bddd.png)

## Proposed solution

We want the x axis to always be linear.

## Technical details

We have some charts with decadal, biyearly, etc. data. For these, we want to only show labels for e.g. "1910, 1920, 1930" (with linear spacing between these), but nothing in between.
However, if we have sparse data with data points for years "1901, 1906, 1907", we want to show all of the years in between on the x axis.

To do that, we want to automatically determine the "minimum display interval" between two years. I propose to use a greatest common divisor computation for that. One example of that calculation:

```
given sortedYears = [1940, 1960, 1970, 1985]
compute deltas = [20, 10, 15]
compute gcd(deltas) = 5
=> the "minimum display interval" is 5 in this case
=> show 1940, 1945, 1950, 1955, 1960, 1965, ..., 1985 on the x axis
```

## Alternatives

We can currently achieve the same behavior by zero-filling all columns for all years.

**Comment by spoonerf** [comment]
Just noting that this was also recently an issue for me in the [flu explorer](https://owid.cloud/admin/explorers/preview/new-flu-explorer-draft) where we're using stacked bar charts quite extensively. 

I wanted to be able to show the same variable as both a [line chart](https://owid.cloud/admin/explorers/preview/new-flu-explorer-draft?time=2012-04-16..latest&facet=none&uniformYAxis=0&Confirmed+cases+or+Symptoms=Confirmed+cases&Interval=Weekly&Type=Influenza+A+H1N12009&Surveillance+type=All+types+of+surveillance&country=~OWID_WRL) and as a component in a [stacked bar chart](https://owid.cloud/admin/explorers/preview/new-flu-explorer-draft?time=2012-04-16..latest&uniformYAxis=0&Confirmed+cases+or+Symptoms=Confirmed+cases&Interval=Weekly&Type=Confirmed+influenza+cases+%28by+strain%29&Surveillance+type=All+types+of+surveillance&country=~OWID_WRL). To do this I created two versions of each variable, one with NAs and ones where the NAs had been zero-filled so they could be used in the stacked bar chart. 

Not a huge problem just thought it would be a helpful example for this issue.

**Comment by larsyencken** [comment]
I bumped it up from "nice to have" to "important", since I think it can be quite misleading to have a non-linear time axis.
