### ISSUE TITLE
Alignment issues for charts when rendered in sticky layouts (gdocs)

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1868]
## Description
<img width="1440" alt="Screenshot 2023-01-19 at 17 34 23" src="https://user-images.githubusercontent.com/13406362/213469898-49f5a9be-15a2-4f12-9d56-f9432b667d85.png">

<img width="1440" alt="Screenshot 2023-01-19 at 17 34 48" src="https://user-images.githubusercontent.com/13406362/213469997-a8416e4b-e781-406b-a518-7aa24bd40e82.png">

## Expected behaviour

Alignment with the grid

## Steps to reproduce

https://docs.google.com/document/d/1UOhC3dU2Zc1DEt2Yzqblfc3l9K1ZS27fcNHQa7uwnxI/edit#

## Might be worth fixing at the same time:
- [ ] [redundant `grid` class](https://github.com/owid/owid-grapher/blob/4c362aeb93ba7ed6d3f5758925c371662ab7919b/site/gdocs/ArticleBlock.tsx#L70)
- [ ] [conflicting `span-md-cols` classes](https://github.com/owid/owid-grapher/blob/4c362aeb93ba7ed6d3f5758925c371662ab7919b/site/gdocs/ArticleBlock.tsx#L82)
- [ ] is there a good reason to wrap a `<figure>` in a `<figure>` when rendering a chart? It seems to be allowed but it doesn't make a lot of sense to me.

**Comment by danyx23** [comment]
It looks like this one was fixed: https://ourworldindata.org/decline-lead-poisoning
