### ISSUE TITLE
Bake `country_latest_data`  without data_values

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1875]
Baking country profiles involves [updating `country_latest_data` table](https://github.com/owid/owid-grapher/blob/master/baker/countryProfiles.tsx#L80) with a very slow query that joins a lot of variables to `data_values` table. This is bad because it blocks our efforts of getting rid of the `data_values` table and it's slow.

Since all our data (if we ignore `Import CSV` which should be deprecated by fast-track) now goes through ETL and is upserted to `data_values` from there, we could efficiently update `country_latest_data` right after upserting values to DB.

### Update 

It turned out that doing this via the ETL would make the data balloon in size - Mojmir opted to do it with data json files instead (see discussion below)

**Comment by marcelgerber** [comment]
Since we want to move away from our current country pages, and we probably won't need the `country_latest_data` table for the new ones, this is probably not worth doing.

**Comment by danyx23** [comment]
The question is when we'll get around to redoing the country pages. @Marigold I think the idea is good - if we could do this in ETL without too much work it could be a nice way of unblocking another usage of data_values. How much work do you think it would be to do this in ETL?

**Comment by Marigold** [comment]
An hour of work or so, everything's almost ready on ETL side. I'll give it a shot then.

**Comment by Marigold** [comment]
Damn... implementation is easy, but the problem is that `country_latest_data` table would grow 10x from 180mb to about 1.8gb (gzipped MySQL metadata dump would grow from 50mb to 100mb). The thing is that right now we only update `country_latest_data` for variables used in charts. Since we don't in ETL which charts are gonna be updated, we'd have to update `country_latest_data` of **all variables**.

If we still had `data_values` table, we could create a trigger that would be updating `country_latest_data` on chart updates. However, with data stored as JSONs in S3 the only way I can think of is start saving "statistics" of a variable alongside it in a JSON file (there could be also used entities and years). Still, baking country profiles would need to scan ~1000 variables / files and need custom logic.

**Comment by Marigold** [comment]
Perhaps we can afford making DB dump 100mb instead of 50mb for now, given that with new country profiles we might be able to get rid of this table?

**Comment by Marigold** [comment]
Scratch that. I'm not gonna move this to ETL, but only slightly refactor it to use JSON data files. If we do it only for **new variables** and don't update `country_latest_data` for variables which are already there, it should fast enough. This is relatively safe assumption since our dataset data is immutable and we create new variable ids for new datasets (the exception is COVID data which is updated in-place).
