### ISSUE TITLE
Filter out aggregates in tables and only show countries

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1876]
## Overview

The table tab in Grapher shows all entities which is often not just countries but also aggregates like World or continents. It would be useful to easily filter those out because they tend to dominate tables if you sort by value. 

## Proposal

Add a small control to the table view that lets you hide aggregates.

## Technical notes

- For this it would be useful to have #1849 in place as it contains the necessary information.

**Comment by larsyencken** [comment]
Suggested faster approach is to simply look at `EntityCodes.ts` in grapher, take note of the very few aggregates that are in that list, and make a second list to allow exclusion of them.

Probably needs a small design change to the table view to allow it.

**Comment by samizdatco** [comment]
One option I've been playing with is keeping the aggregates around but grouping them together either at the top or the bottom of the table with a horizontal line separating them from the country-by-country rows.

To make this work, the sorting would have to reorder the two groups separately as well (i.e., the aggregate rows would always be on one end of the table, but within the group the rows would be ordered by the current sort column).

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/469523/228270728-39256d2b-ac21-45aa-916e-5da77762bbaf.png">
