### ISSUE TITLE
Add an 'Archive dataset' button to dataset pages

### ISSUE THREAD

**Issue by edomt** [owid/owid-grapher#1879]
## Core problem

The default process for data scientists has become to archive old datasets instead of deleting them entirely. But the current Grapher admin UI doesn't have an `Archive dataset` button.

## Example

https://owid.cloud/admin/datasets/2790

<img width="677" alt="image" src="https://user-images.githubusercontent.com/7103774/214870385-6f5633d8-2987-4594-892c-0db11c7cee9f.png">

## Proposed solution

Add an `Archive dataset` button in the "danger zone", next to the `Delete dataset` button.

The button should run `UPDATE datasets SET isArchived = 1 WHERE id = <DATASETID>`

(cc @spoonerf for tracking)

**Comment by Marigold** [comment]
(I could take a stab at this together with https://github.com/owid/owid-grapher/issues/1869)
