### ISSUE TITLE
Key insights starting with a number break the page

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1881]
<img width="1440" alt="Screenshot 2023-01-27 at 16 50 40" src="https://user-images.githubusercontent.com/13406362/215102729-78dc8acf-2ca0-45b2-b61f-5c18303eb524.png">

- create a "key insights" block, with a title starting with a number, e.g. "200 years ago, everyone lacked democratic rights. Now, billions of people have them".
- visit the page, click on the key insight tab to load it and update the URL (e.g. `https://ourworldindata.org/democracy?insight=200-years-ago-everyone-lacked-democratic-rights-now-billions-of-people-have-them#key-insights`)
- refresh the page

Error in the devtools:
```
DOMException: Failed to execute 'querySelector' on 'Element': '#200-years-ago-everyone-lacked-democratic-rights-now-billions-of-people-have-them' is not a valid selector.
```

Context: [bug report](https://owid.slack.com/archives/C46U9LXRR/p1674758441139179)

**Comment by ikesau** [comment]
Copying from slack for possible fixes:

We could either:
- Remove numbers at the start of these ID’s, e.g. `https://ourworldindata.org/democracy?insight=years-ago`
- Implement a number-to-english algorithm to transform it, e.g. `https://ourworldindata.org/democracy?insight=two-hundred-years-ago`
- Rework the key insights logic to not rely on ID's, use a `data-` attribute instead.
