### ISSUE TITLE
Broken link tool for GDocs-based publishing

### ISSUE THREAD

**Issue by CGiattino** [owid/owid-grapher#1884]
## Core problem

The tool in WordPress that we use to identify and fix **broken links** will become obsolete when we stop using WordPress. We'll need to develop a way to recapture its features.

## Proposed solution

Here is a list of the tool's features that it would be very helpful to have:
- It automatically identifies broken links
- The UI makes it easy to inspect and correct the link. For example, you can use it to:
  - Directly edit the URL
  - Remove the URL
  - Mark it as not broken
  - Recheck whether it's broken
  - View the page that the link is on
- It gives suggested replacement links (e.g., from WebArchive), which are often quite useful
- It fixes all instances of the broken link automatically

## Context

[Slack convo](https://owid.slack.com/archives/C46U9LXRR/p1675076378588699) between me and Matthieu 30 Jan 2023

![image](https://user-images.githubusercontent.com/7489781/215510798-2ce1cfc5-ec95-4757-ab96-f5cf0382e8ac.png)

**Comment by ikesau** [comment]
For internal links, we're hoping #1718 will be merged within the next month.

For external links, it seems like a script that matches all external links in our `gdocs_posts.content` column and pings them would be the brute-force way to automate this. We can run the script every $PERIOD` and show the output on a view in the admin.

@danyx23 saw https://github.com/asg017/sqlite-http and masochistically suggested we look into it as a potential tool to leverage.
