### ISSUE TITLE
Set up a daily pipeline to update 30d pageviews for posts and charts

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1885]
To discuss in a data group meeting - it probably makes sense to fetch this information from BQ on analytics and write it once a night or so into the live_grapher db. This information would be useful for sorting things by relevance in e.g. the grapher admin in a few places as well.

**Comment by Marigold** [comment]
We have DBT running on BigQuery, so we could use it to run aggregation queries and then just move the table from BigQuery to MySQL (not sure if we have something for that already).

**Comment by marcelgerber** [comment]
Also helpful for search ranking in the Algolia search!

**Comment by marcelgerber** [comment]
@Marigold I think this is fully fixed by https://github.com/owid/analytics/pull/70, right?

@edomt had mentioned that he would like a `views_365d` column, too, is that easy to do?
https://github.com/owid/owid-grapher/issues/1837#issuecomment-1439947896

**Comment by Marigold** [comment]
> @Marigold I think this is fully fixed by https://github.com/owid/analytics/pull/70, right?

Right.

> @edomt had mentioned that he would like a views_365d column, too, is that easy to do?

I'll take a look. This might need adding an additional column, but I hope it's not gonna be so hard.

**Comment by edomt** [comment]
For data analysis, we can go through BQ directly, so no need for this.

But I guess it could be helpful for other dev? @marcelgerber noted:

> Also helpful for search ranking in the Algolia search!

If we ever use page views for search ranking, we should probably use 365d rather than 30d (to avoid seasonal patterns).

**Comment by marcelgerber** [comment]
We're already using `views_7d` to rank search results; the rationale to go with a short time span is mainly so it doesn't take a long time for new charts/articles to bubble up in search. There are, of course, other ways how we could do that, but this one is the simplest and seems to work well enough.

And, if there are any seasonal patterns (which we should have pretty rarely), then it's not a bad thing to respect them in search ranking imo.

**Comment by marcelgerber** [comment]
Closing this now, since we also have a daily-updated `views_365d` now.
