### ISSUE TITLE
Remaining tasks for Gdocs publishing feature parity

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1921]
The Gdocs publishing pipeline allows us to publish articles now but there are small bits and pieces of our codebase that only take old wordpress posts into account, not the new gdocs ones. This issue tries to capture them all.

Note that for all of these issues when tackling them we should also make sure that the code handling old wordpress posts checks which posts are already published via gdocs and excludes them (so that they don't show up twice). The way to check this is to use the view post_with_gdoc_publish_status which augments the posts table with one column which is the published status from the joined posts_gdocs table (joined on the `posts.gdocSuccessorId= posts_gdocs.id`)

Roughly ordered by priority - it probably makes sense to do the small/easy wins first

- [x] #1988
- [x] #1894 
- [x] [The `/newsletterPosts.json`](https://github.com/owid/owid-grapher/blob/53f955178b143319abb749defb81c37b28344cd3/adminSiteServer/apiRouter.ts#L2214) endpoint does not regard gdoc posts
- [x] #2026
- [ ] #3334
- [x] #2049
- [x] Prominent links don't fetch the title and thumbnail from the content if they are not explicitly set; using prominent links this way is common so this will soon be a request. This used to be done at [site bake time](https://github.com/owid/owid-grapher/blob/bbfbbfb12e03c60581b315f1d99e55530c64b254/baker/siteRenderers.tsx#L436). Fetching this information entails resolving any redirects on the url that is used, checking if the link is an explorer or chart or post. For explorers this ATM means initializing the GitCMS but when implementing this we might already have the relevant information mirrored into the DB thanks to [this PR](https://github.com/owid/automation/pull/1). 
- [x] #2050
- [x] #1943
- [x] #1974 
- [x] #1871

**Comment by danyx23** [comment]
@mlbrgl Ike and I are just going through issues - it seems like this one will become quite important over the next 4 weeks or so. Do you think you could work on this next to your exploratory work on search in the next cycle?

**Comment by mlbrgl** [comment]
@danyx23 I can take a stab at some of these issues, but likely not all. My time seems to already be splitting three ways over the next cycle for planned work:
- #1874 (which is [going to overflow](https://owid.slack.com/archives/C04LNBUJM1P/p1676475348325499))
- continue search exploration
- gdocs publishing

I was thinking on spending some time in the cooldown on search already, so maybe that'll be enough for that part and I can focus more serenely on the other two. Otherwise we'll have to cut something off.

**Comment by danyx23** [comment]
We have done all but #3334 - so we created that follow up issue and are closing this one now.
