### ISSUE TITLE
Float values are detected as `type: "int"` in metadata

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1927]
## Description

Here's an example https://ourworldindata.org/grapher/population-density. It's [metadata file](https://ourworldindata.org/grapher/data/variables/metadata/525715.json) contains

```
...
type: "int"
...
```

Population density is clearly not an integer. I've [checked the code](https://github.com/owid/owid-grapher/blob/master/db/model/Variable.ts#L157) and the logic doesn't seem right, we only assign float if we encounter NaN values.

I have no idea if this has any real implications or not.

## Expected behaviour

Metadata should have correct type.

**Comment by marcelgerber** [comment]
> I have no idea if this has any real implications or not.

I'm pretty sure we're not consuming the type field right now, at least not in graphers and explorers.

**Comment by Marigold** [comment]
That makes sense, it was added only recently. I'm gonna keep this issue around for a while and either we replace it with metadata coming from ETL or we let it die.

**Comment by sophiamersmann** [comment]
I just checked the given [example file](https://ourworldindata.org/grapher/data/variables/metadata/525715.json) and the metadata `type` field reads `"float"`. Does that mean this bug got fixed or is there something I'm missing?

(Would be nice to fix before we start consuming this field in #2039)

**Comment by Marigold** [comment]
@sophiamersmann I think I fixed at some point. The example looks good now, so closing. Thanks for spotting this issue.
