### ISSUE TITLE
On Discrete Bar charts that are split by metric or product, the units are wrong when splitting by product

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#1928]
## Description

On charts that have the option to split by metric or by product (e.g. [this chart](https://owid.cloud/admin/charts/5525/edit)), when splitting by product, the units are wrong.

## Expected behaviour

When splitting by product, each row shown corresponds to a different metric, and hence should have a different unit.

## Steps to reproduce

1. Go to [this chart](https://owid.cloud/admin/charts/5525/edit).
2. Click on 'split by product'.
3. See that all metrics have the same units.

## Screenshots

![environmental-footprint-milks](https://user-images.githubusercontent.com/12246978/219005614-918d4c03-4c3c-42f9-94f2-d5fb8a284bec.png)

## Environment

Desktop:
-   OS: macOS Big Sur 11.6.4
-   Browser: chrome
-   Version: 109.0.5414.119 (Official Build) (arm64)

**Comment by sophiamersmann** [comment]
I've fixed this issue in commit 05b0eb418370b5c31f953c7ed3b1ad53669929a5 but I was wondering if this is actually something we would want to support as showing different units on the same axis usually isn't very meaningful.. That's why I have also opened this up to [discussion in the design channel](https://owid.slack.com/archives/C5BDCB2R3/p1677861957213109).

**Comment by pabloarosado** [comment]
Hi @sophiamersmann thanks for fixing this! I agree that it's not a very good design choice to have different units compared on the same axis. But this fix is still much better than showing the wrong units. Feel free to close the issue once the fix is applied (and we can keep the design discussion somewhere else).

**Comment by danyx23** [comment]
@pabloarosado in the [conversation in slack](https://owid.slack.com/archives/C5BDCB2R3/p1677861957213109) the consensus was that facetting should not be enabled if the short unit is not the same. I would be in favour for Sophie to implement this logic.

**Comment by pabloarosado** [comment]
Thanks @danyx23. True, I had not read that slack thread in detail. Yes, disabling "split by product" when the units do not coincide is a better solution.
