### ISSUE TITLE
Topic Pages with Google Docs

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#1943]
- [x] Header template functionality (topic | article)
- [x] Add support for subtitles to header
- [x] Intro section
- [x] Key insights
- [x] Sticky nav
- [x] All our charts
- [x] Research & Writing
- [x] Expandable paragraph
- [x] [Update Algolia sync script](https://github.com/owid/owid-grapher/blob/28e510d75678d3a143eebfda45430cdd5ca6d609/baker/algolia/indexToAlgolia.ts#L158)

**Comment by marcelgerber** [comment]
@ikesau I think this one can be closed?
