### ISSUE TITLE
Anchor 🔗 on heading goes onto next line creating extra vertical space

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1949]
_spotted by @bastianherre_ 

## Description
<img width="513" alt="Screenshot 2023-02-23 at 17 27 05" src="https://user-images.githubusercontent.com/13406362/220935661-8d0e7e53-7d26-48d7-9343-0bf098fd0cb8.png">

<img width="621" alt="Screenshot 2023-02-23 at 17 21 49" src="https://user-images.githubusercontent.com/13406362/220935389-92c351e3-2236-41ba-ab8b-596edaef477d.png">

This is dependant on the heading length and screen width.

## Expected behaviour

The 🔗 icon shouldn't be breaking off to a new line on its own.

## Context

If I remember correctly, we moved those 🔗 icons from the beginning to the end of headings to accommodate for headings in key insights blocks. They don't seem to be used / visible there anymore though.

**Comment by ikesau** [comment]
This was fixed for gdocs, fyi 🙂
