### ISSUE TITLE
Spacing missing between "Our latest work" and header on /blog on mobile

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1971]
## Description

<img width="607" alt="Screenshot 2023-03-02 at 20 06 42" src="https://user-images.githubusercontent.com/13406362/222500882-7fcbe5f6-3921-4f69-8eed-b1c49befdac2.png">

## Steps to reproduce

Go to https://ourworldindata.org/blog on mobile

**Comment by chetan-v** [comment]
hello everyone can I do that

**Comment by mlbrgl** [comment]
hey @chetan-v, sorry for the late reply, sure!
