### ISSUE TITLE
Style bleed on links in embedded explorers in the faceting dropdown

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1975]
_Raised by @marcelgerber_ 

## Description

_In embedded explorers, the link underline affects the faceting dropdown, too (which you can access by pressing the F key)_

<img width="761" alt="image" src="https://user-images.githubusercontent.com/13406362/223134116-0ea32c02-c5f9-4892-84bc-37bf28d90f68.png">

**Comment by larsyencken** [comment]
@mlbrgl Hey, with a style bleed issue like this, is it something that belongs on the publication side to fix, or is it something you'd like us to look at on the data viz side?

**Comment by mlbrgl** [comment]
@larsyencken I would say this has to be fixed at the component level by overriding the default umbrella link style. There might be a future in which those global styles are not applied indiscriminately but rather injected into every component somehow (utility classes?) but for now, an approach similar to the one below is probably a good solution: 

https://github.com/owid/owid-grapher/blob/17262c2a6cf481d7514eb69d6c54933a2cc4e060/packages/@ourworldindata/grapher/src/core/grapher.scss#L37-L45
