### ISSUE TITLE
Bulk chart editor is slow and can time out for some charts

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#1978]
## Description

Updating some charts with bulk chart editor is extremely slow and can sometimes time out. For instance updating `/sourceDesc` of the [following chart](https://staging-owid.netlify.app/grapher/varieties-democracy-vdem?country=ARG~AUS~BWA~CHN) in [bulk chart editor](https://staging.owid.cloud/admin/bulk-grapher-config-editor?filter=%28AND+%28CONTAINS+%2FsourceDesc+%22v13%22%29%29) takes ~30s. Here's screenshot of processes running in MySQL

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/1550888/223192020-c57411e5-70e2-4aeb-9705-32044b89ab24.png">

Strangely, updating `users` table takes more than 20s. I'd expect tens of milliseconds. If you drag a cell and try editing more charts like this, you might get `QueryFailedError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction`.

User would see this error in the admin

![image](https://user-images.githubusercontent.com/1550888/223192991-b9fdb835-486c-47a2-a22b-83323df6170f.png)

The initial hypothesis was that querying S3 could time out, but I tried firing 300 parallel requests to `api/data/variables/data/419309.json` endpoint and never got an error.

## Expected behaviour

Better performance, no timeouts.

## Steps to reproduce

1. Go to https://staging.owid.cloud/admin/bulk-grapher-config-editor?filter=%28AND+%28CONTAINS+%2FsourceDesc+%22v13%22%29%29
2. Try changing `/sourceDesc` from v12 to v13 or vice versa for multiple charts

@danyx23 any idea why could it be happening? I've tried firing parallel queries to `users` table, but that was pretty fast.

**Comment by Marigold** [comment]
It hasn't been a problem for me recently. Perhaps it was a side effect of some other bug that got fixed. I'm happy to close this if no one else experiences this.

**Comment by larsyencken** [comment]
Nobody else was blocked on it, closing it for now.
