### ISSUE TITLE
In SVG exports, use a font selection that is better suitable for Wikipedia

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#1993]
## Description

Currently, we export our svgs with the following fonts specified:
* Title: `"Playfair Display", Georgia, "Times New Roman", serif`
* Everything else: `Lato, 'Helvetica Neue', Helvetica, Arial, sans-serif`

When uploading a svg chart to Wikipedia, the charts are auto-converted to a .png version.
However, their servers have none of these installed and just use the `serif` and `sans-serif` directives, [which map to](https://commons.wikimedia.org/wiki/Help:SVG#fallback) `DejaVu Serif` and `DejaVu Sans`, respectively.

The problem there is that the DejaVu fonts are pretty wide, and so it can happen that the title overlaps other elements or overflows.

We can pretty easily fix this by specifying another level of fallback font [that is available on their servers](https://noc.wikimedia.org/conf/fc-list).

I tried this out a bit already (this is all using Wikipedia's png rendering already), here's a comparison:

<details>
<summary><h3>What Wikipedia currently uses (DejaVu fonts)</h3></summary>

![image](https://user-images.githubusercontent.com/2641501/224451018-093330d3-6d26-474f-a4e5-33a51684cd7c.png)

</details>

<details>
<summary><h3>Using Noto fonts (Noto Sans, Noto Serif)</h3></summary>

![image](https://user-images.githubusercontent.com/2641501/224451061-aa9037a4-7953-4aa2-becb-d0b0081bb54d.png)

</details>

<details>
<summary><h3>Using Liberation fonts (Liberation Sans, Liberation Serif)</h3></summary>

![image](https://user-images.githubusercontent.com/2641501/224451201-8c8d1553-45bf-412d-810f-82ab5ea26763.png)

</details>

Additional note: I also noticed that the generated pngs have transparent backgrounds, we should also add a `fill="white"` directive to the root svg element, since Wikipedia doesn't seem to consider the `background-color: white` style we have.

**Comment by danyx23** [comment]
Sounds like a good plan with no real downsides for us - nice!

**Comment by marcelgerber** [comment]
So, we're just gonna have to decide between Noto and Liberation, then.
I prefer Liberation, not least because it gives us some "breathing room" - with Noto I can imagine some charts where a long title and the logo overlap, but with Liberation there's lots of space and that shouldn't happen.
It's a bit weird that with Liberation, the title is not much larger than the subtitle, but oh well.

**Comment by mathisonian** [comment]
+1 for adding the Liberation fonts. Thanks for jumping on this @marcelgerber!

**Comment by marcelgerber** [comment]
To any Wikipedians that may be reading this: The change is now deployed, and our svg exports should work better for Wikipedia now.
If you are still facing problems, feel free to reach out to marcel@ourworldindata.org
