### ISSUE TITLE
Project data pages: Extend Grapher embedding to work with variable level partial grapher configs

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1995]
## Overview

Enable Grapher to be embedded in a data page from given a variable id alone, and any partial Grapher config that variable has in its metadata.

## Config inheritance model 

```mermaid
graph TB

defaults["Default grapher settings"] --> variable-meta["Partial config from variable"] --> archieml-config["Partial config in ArchieML"] --> grapher["Rendered grapher"]
```

## Background

To clarify what this issue is about, let's start with a look at how Grapher configs and embedding works today:

Our website is static HTML and our grapher is a React based Javascript widget that needs a bit of json as its configuration. How exactly we run Grapher is a bit different depending on where it is used - the main uses are:
* On our main website. The baking process produces a `<figure>` element containing a static thumbnail. The grapher config is persisted into the HTML of the standalone /grapher/ pages [in a script tag](https://github.com/owid/owid-grapher/blob/4a9c8bf7c32f73c85f4301adde84425744995630/site/GrapherPage.tsx#L65C3-L70) that stores the config in a global JS variable. When a visitor comes to our site the siteFooter scripts set up an IntersectionObserver instance that trigger when one of these figures comes into view (on desktop) and then replaces the thumbnail with a new Grapher instance. This instance is saved as a React ref so that the heavy, stateful Grapher is not reconstructed all the time (this is not very React idiomatic of course and something we might want to change). The grapher config is extracted either from the same site if it is a standalone /grapher/ page or by fetching the html of that standalone grapher page.
* Google docs articles are hydrated as a whole. Currently they rely on the same method as above to get instantiated but there is a [useEmbedChart hook](https://github.com/owid/owid-grapher/blob/179f2f7cb1e165993039bfe194238d141c69708b/site/hooks.ts#L59) that we'll probably use instead soon (see #1974). 
* The grapher admin and some other admin components like the bulk chart editor have an `@observable.ref grapher = new Grapher()` and an `@observable.ref grapherElement?: JSX.Element` that they keep around - i.e. this is an instance of Grapher that is kept around and which is refreshed using functions like  and then the element is included in the render function.

For the data pages project (but also more generally for GDocs posts), we've starting creating a new `variable-chart` component. It is superficially similar to the `chart` component but instead of referencing a chart config it references a variable id. It has 2 sources of information for the config: a few properties on the `variable-chart` component like e.g. the variable to plot - and the partial grapher configs that we now start storing on the variables table (as of 2023-03-14 this is the `grapherConfig` column that is controlled via the admin; the other half that is controlled via the ETL will be added in a migration in the next few weeks).

This means that an ArchieML component (or the data page) would build a component like this:
```archieml
{.variable-chart}
variable: 123
chartType: DiscreteBar
hideTabs: true
{}
```

What is still needed now however is a way to make the variable level partial grapher configs available to this component when it renders. I think it will make sense to use the attachment strategy again that @ikesau developed for images and linked documents. This means that at the point when the server assembles the document it would scan for variable-chart components, collect their variable ids, fetch all the partial grapher configs for those variables from the database, stack them together (with the new mergeGrapherConfigs function in GrapherInterface.ts which is just using `_.merge({}, ...configs)`), and them store them as a new kind of attachment (probably as an object of variable ids as keys and grapher configs as values). Because the archieml pages are hydrated as a whole and the entire article JSON is available for hydration this should be enough so that the render function of the variable-chart component has access to everything it needs to render the Grapher.

**Comment by larsyencken** [comment]
@danyx23 I tried to make the top of this more readable, please fix it if I've misunderstood!
