### ISSUE TITLE
Legend displays bins with one value in a slightly confusing way

### ISSUE THREAD

**Issue by bastianherre** [owid/owid-grapher#2003]
## Core problem

In some charts it makes sense to have a bin that is just one value. Examples are our chart on [Experience with electoral democracy](https://ourworldindata.org/grapher/experience-with-electoral-democracy) or on the [Share of women in parliament](https://ourworldindata.org/grapher/share-of-women-in-parliament-vdem?country=ARG~AUS~BWA~CHN~OWID_WRL). A country that was never a democracy, or a parliament without any women, are special cases that deserve their own category.

Unfortunately, the legend does not handle this well: by default it displays the same value twice in the legend, at the start and end of the bin (as in the first example). This may confuse some users, as they may think there could be some rounding of values going on, etc.

![image](https://user-images.githubusercontent.com/2641501/225701222-eeb62448-a262-4a13-aaf2-1570deea835e.png)

## Proposed solution

A neat solution for these cases would be for the Grapher to recognize these one-value bins, and to provide clearer labels (as in the second example).

![Screenshot 2023-03-30 at 12 11 05](https://user-images.githubusercontent.com/36012/228818318-2abb096f-3e8d-4753-95c3-ef81e47f99fc.png)

## Alternatives

One alternative is leaving the Grapher as is. Few users may be genuinely confused, and it may be fine accepting that.

Another alternative is to do what I did for the second example. Here I added clear labels to each bin. It's a bit more work, but would do the trick just fine (as long as the labels don't get longer).

## Context

Max encouraged me to bring this to your attention when he saw me adding labels to the women-in-parliament chart.

Please let me know if you have any questions! Thank you!

**Comment by marcelgerber** [comment]
I think this should be relatively easy to do as Bastian suggested, I added "internal-onboarding" for now
