### ISSUE TITLE
Change chart title automatically when switching between absolute and relative view

### ISSUE THREAD

**Issue by bastianherre** [owid/owid-grapher#2004]
## Core problem

In some charts it would be ideal if the chart title changed if the user switches between absolute and relative view. Examples are our chart on [Countries that are democracies and autocracies](https://ourworldindata.org/grapher/countries-democracies-autocracies-row?country=~OWID_WRL) and [Countries in which a woman is government's chief executive](https://ourworldindata.org/grapher/countries-with-woman-chief-executive?country=~OWID_WRL). It would be most clear, and perhaps also better for SEO, if the title said "Share of countries [...]" when in relative view, and "Number of countries [...]" when in absolute view.

## Proposed solution

Ideal would be to change the Grapher such that the title changes depending on whether the relative toggle is marked or not. If it is not marked, it could default to "Number of [...]". If it is, it could default to "Share of [...]". Or the Grapher would add fields to customize what should be displayed for each.

## Alternatives

One alternative is leaving the Grapher as is. The chart titles may not be as clear, and SEO perhaps slightly worse, but this may not be worth the work to implement the proposed solution.

Another alternative is creating two charts: one with the absolute view, toggle deactivated, and the title of "Number of [...]"; and another with the relative view, toggle deactivated, and the title "Share of [...]." I originally did this for many charts on democracy, where we deemed precise chart title particularly important. But it was a lot of work, and we recently felt it was not worth all the effort, and that having one chart with the toggle would be more useful.

## Context

The issue came up a few times in 2021 and 2022 when I worked on democracy charts, and now has come up again with human-rights charts. So Max proposed I bring this to your attention to maybe find a technical solution.

Please let me know if you have any questions! Thank you!

**Comment by larsyencken** [comment]
After checking a bunch of existing titles for charts with relative toggles, it would seem that naively changing the title only works in 25-50% of the cases, and in the other cases titles don't really work with "Number of" and "Share of" appended to the front. E.g.

- World population living in extreme poverty (❌ number of, ✅ share of)
- Projected world population by level of education (❌ number of, ✅ share of)

Some other cases already use the words "Number of" or "Share of" in the existing title, though they could be upgraded.

I think this is not especially low-hanging fruit, best to stick with the status quo.
