### ISSUE TITLE
Prune historical Wordpress users and alumni from the database

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2006]
## Overview

On our live database, we have a lot of historical users who no longer have access to log in, but who still have Wordpress accounts. We'd like to prune them.

## Caveats

We should not prune any users who have published posts, since then their account is being used for authorship.

**Comment by ikesau** [comment]
We'd have to make sure that this wouldn't mess up media metadata either. Probably a bit more work than we'll ever be able to justify to ourselves, tbh.

**Comment by toni-sharpe** [comment]
### Get authors out of WP

Even if there's several of them on an article, just a fixed set iof those who published

This SQL pulls everyone out of the `posts` table that has an author credit, so shouldn't be pruned given they've published:

```SQL
SELECT 
  -- no dupes, of course
  distinct wp_auths.auth
FROM 
  posts, 
  -- this is needed to get the arrays that are stored in the author field into an RDMS structure
  JSON_TABLE(
    -- this pulls out the authors themselves from the array
    JSON_EXTRACT(posts.authors,"$[*]"),
      -- then we define a column that stores all those individual array elems
      "$[*]" COLUMNS (
        auth VARCHAR(255) PATH "$"
      )
    ) 
  wp_auths;
```

The following list on my dev machine (seeded data?) I don't actually know - still, it's a proper list.

```
Antoinette Finnegan 
Bastian Herre       
Bernadeta Dadonaite 
Bobbie Macdonald    
Brian Nolan         
Cameron Appel       
Cameron Hepburn     
Charlie Giattino    
Daniel Bachler      
Daniel Gavrilov     
Diana Beltekian     
Edouard Mathieu     
Ernst van           
Esteban Ortiz-Ospina
Fiona Spooner       
Guest Authors       
Hannah Behrens      
Hannah Ritchie      
Ike Saunders        
Jaiden Mispy        
Joe Hasell          
Julia Broden        
Julia Murphy        
Lars Yencken        
Lucas Rodés-Guirao  
Marcel Gerber       
Marco Molteni       
Matthew Conlen      
Matthieu Bergel     
Max Roser           
Mohamed Nagdy       
Nicolas Lippolis    
Our World           
Pablo Arriagada     
Pablo Rosado        
Saloni Dattani      
Samantha Vanderslott
Sandra Tzvetkova    
Sophie Ochmann      
Stefan Thewissen    
Veronika Samborska  
Yanmin Choo         
ZdenekGeographics   
```

**Comment by ikesau** [comment]
We no longer use WP, and the grapher admin is safe behind tailscale so there's no security need to do this - and the few small places where we still reference Grapher users (e.g. the admin charts page) make this an annoying amount of tinywork for no discernible gain.
