### ISSUE TITLE
Static links to page `how-to-use-our-world-in-data`, which is a redirect

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2013]
## Description

We have three places in code where we link out to the page `how-to-use-our-world-in-data`, which no longer exists and now links out to `faqs`:
- In the page Footer (`SiteFooter.tsx`), a "How to use" link
- At the end of every article and every Gdoc article (`LongFormPage.tsx` and `OwidArticle.tsx`), linking to `/how-to-use-our-world-in-data#how-to-embed-interactive-charts-in-your-article`, where the anchor doesn't exist in the FAQ

## Solution

Either:
- Change the links to point to the correct page
- Or, create a _more specific_ FAQ page that is more about "How to use OWID" than our current, general FAQ

**Comment by armughan11** [comment]
Hi @marcelgerber / @ikesau is this still available? Happy to work on this!

**Comment by marcelgerber** [comment]
@armughan11 Yes, for sure!
