### ISSUE TITLE
Make an 'archive' or status warning component for articles

### ISSUE THREAD

**Issue by JoeHasell** [owid/owid-grapher#2019]
## Core problem

In the new article design, we have no way of giving an article an 'archived' flag, or signalling other similar status caveats (for example if the data is especially out of data in some way). This means we are tempted to delete articles that are not really wrong, just a bit old. Or articles that are misleading if they are read as being an up-to-date presentation of the latest research.

We need a way to signal 'Yes this is out of date in some significant ways, but it's still live because there's nothing really wrong with it'.

## Proposed solution

Make a new archie component that allows us to signal these kind of 'not so fresh' statuses.
 

## Context

In Wordpress, for some articles [Joe did](https://ourworldindata.org/extreme-poverty-in-brief) something a bit similar to this by repurposing the 'help' block: 

<img width="558" alt="Screenshot 2023-03-17 at 19 55 03" src="https://user-images.githubusercontent.com/41148640/226017489-32c0257c-e6c9-4f51-a44d-b890b4c2f5dc.png">

It's worth noting that Max really doesn't like what Joe did here – he finds it too big and bulky a warning. He worries it tells people 'don't read this thing, it's wrong'. When the whole purpose is to say the opposite ('this thing is fine, but you should be aware of X').

Related to https://github.com/owid/owid-grapher/issues/2020.

**Comment by JoeHasell** [comment]
I remember that Marwa has been working on designs for a more specific block: https://owid.slack.com/archives/C5BDCB2R3/p1683276446233739. Which would be nice I think!

We can use the general purpose callout for now though.

**Comment by ikesau** [comment]
This is the option that the authors preferred, and would be easy to implement as an "alert" variant of the callout block. Probably wouldn't add the icon though.

![image](https://github.com/owid/owid-grapher/assets/11844404/cc714c3b-2844-4e37-87e8-ceffc1a5b3d7)

**Comment by ikesau** [comment]
@danyx23 this seems relevant to the better 404 pages project 🙂

**Comment by ikesau** [comment]
Superseded by https://github.com/owid/owid-grapher/issues/3900
