### ISSUE TITLE
Create an 'archived' status for charts

### ISSUE THREAD

**Issue by JoeHasell** [owid/owid-grapher#2020]
## Core problem

There are cases where we have an interactive chart with very old data that we will never update – say because it relates to a one off academic study, or because we have decided that it isn't important enough to keep updated. The data is not wrong in any way, but, in the context of our other regularly-updated content, this can be a bit misleading or look broken.

It is tempting to delete such charts. We don't really want them to show up in search say. And we also don't want to spend lots of time managing them in the admin. But this may end up breaking one of our old articles (or someone else's website).

## Proposed solution

We would like to be able to set an 'archive' status to a chart. This would add some kind of visual warning to the chart that signals 'this is a bit out of date, and is no longer being actively managed by us'. Archived charts would not be returned by search. And possibly they would separated out somehow in the database, so that it is easy to identify and ignore them for data management purposes.

## Alternatives

Another strategy would be to replace such charts in our articles with static versions, and then delete the interactive chart. For many cases this would work well. However it's a bit laborious for the D&R team. Also it seems an unnecessary loss of functionality of the chart. And it would still break other people's websites if they are embedding the chart that we delete.

## Context

Related to https://github.com/owid/owid-grapher/issues/2019.

**Comment by ikesau** [comment]
Not sure how much of a priority this is (@JoeHasell) but here's a query that shows how many of these stale charts we have: https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select+slug%2C+lastEditedAt+from+charts+order+by+lastEditedAt+asc+limit+101

This could be scoped as:
1. new column in the charts table
2. DB migration
3. grapher admin UI to mark charts accordingly
4. exclude affected charts from search indexing

**Comment by JoeHasell** [comment]
Thanks @ikesau – I think the priority you added there is about right.
