### ISSUE TITLE
confused about compiling and embedding Explorers locally

### ISSUE THREAD

**Issue by Zoophobus** [owid/owid-grapher#2023]
Part of the problem is that I don't have that much experience with typescript or HTML. (My experienced is with Python, which includes a bit with both Django and Dash apps.) What I am trying to understand is how to compile the explorer scripts locally and then embed them within an HTML page. What I have tried is to use the tsconfig file within the explorer directory to compile the typescript files (for example the Explorer.sample.tsx) and embed the corresponding javascript objects within the web page.

However, I have been unable to get the explorer object to render within the HTML and am not sure where I am going wrong (I suspect it is in the embedding process). I would appreciate any help you can offer, including links

**Comment by Zoophobus** [comment]
Hi @marcelgerber,

thanks for replying. I would agree that this issue is a rather annoying one, I wouldn't blame you for interpreting it as a sorry, but I didn't leave enough time to do my homework, issue.

So the idea was to try and utilize an explorer for the data and enable a full level of functionality. I definitely don't understand your baking process (as the first message definitely shows) and am too stupid with typescript to get very far in comprehending where our limits are. The core of our problem is that we would like to utilize our own data with the owid-grapher, however I guess that's not really possible without being a contributor, is that correct?

**Comment by larsyencken** [comment]
Closing this for now.
