### ISSUE TITLE
Add relative toggle inside data explorers views

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#2028]
## Core problem

Currently, explorers and grapher charts share the feature of selecting absolute or relative numbers for some types of charts, but they work differently: only grapher charts include a toggle inside the view (via the `hideRelativeToggle` parameter). Explorers use the `stackMode` parameter, which allows to transform the data between absolute and relative values, but this is fixed for each view.

## Proposed solution

Feature parity between both grapher and explorers, including `hideRelativeToggle` and replacing `stackMode`.

## Alternatives

There is a way to implement a relative toggle in explorers with the same functionality, by adding a checkbox named Relative change (as a `Relative change Checkbox` column in graphers), but it reduces the space for other menus when we have several.

## Context
This is how `hideRelativeToggle` works in grapher:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/63430031/226607856-bf4ebb3f-310d-4510-8475-a0ae55b8c4d9.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/63430031/226607896-6a363519-c6cb-47e4-9edd-2194845ea7a5.png">

In explorers it is possible to implement a toggle for `stackMode`, but the menu gets too crowded and we would like to include an additional menu.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/63430031/226608156-bf62ea76-5c6e-4cd6-a0c6-4ba73c7ef4fb.png">
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/63430031/226608298-a265183f-ea82-472e-9a49-dd8b62ea7342.png">

**Comment by larsyencken** [comment]
Thanks for reporting it Pablo! We're just walking Christian and Sophia through explorers today, I think this could be a good issue for one of them.

**Comment by sophiamersmann** [comment]
Fixed in #2384
