### ISSUE TITLE
Centered Article style touchups

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2032]
From Marwa's excellent design audit:

- [x] Extra 12px between the title and the top edge of color.
![image](https://user-images.githubusercontent.com/11844404/226731127-14f7ac8c-490f-4c78-8973-dab216c57532.png)

---

- [x] Space between the title and the subtitle should be 24px
![image](https://user-images.githubusercontent.com/11844404/226731306-c6c1efde-18c1-4555-bd33-39cc5f87dfef.png)

---

- [x] Book icon missing from the “Cite this article” link
![image](https://user-images.githubusercontent.com/11844404/226731361-51211f77-2f4a-4236-8475-24b9eeef69ac.png)

---

- [x] Body text for articles should be Body 1 Regular (18/28)

---

- [x] This title should be H1 Semibold 32/40 and left-aligned (possibly an issue in the gdoc)
![image](https://user-images.githubusercontent.com/11844404/226731575-43a02931-abc6-4d9a-9a3d-49994354ce77.png)

---

- [x] Line should be in-between sections across 6-col with a 48px margin on either side
![image](https://user-images.githubusercontent.com/11844404/226731683-dac3dc7d-7a6c-4b6c-b4e6-a958d58579f9.png)

---

- [x] 24px between title and body (here it’s 12)
![image](https://user-images.githubusercontent.com/11844404/226731743-0d42d256-5fc8-4943-aa8f-df68bc78e15a.png)

---

- [x] Tooltips should not cover the text
![image](https://user-images.githubusercontent.com/11844404/226731821-4fd99559-c950-488a-8c7e-de57442d50f0.png)

---

- [x] Image captions aren't styled correctly
![image](https://user-images.githubusercontent.com/11844404/226731901-f0578117-7273-485c-9d9f-f2aa63f67d6c.png)

---

- [x] This title should be an H2 Bold (24/32) left-aligned with 24px between it and the following body text
![image](https://user-images.githubusercontent.com/11844404/226731972-46c8db39-027d-4399-b894-71796b80c24b.png)

---

- [x] Only the line under poverty is in our visited color
![image](https://user-images.githubusercontent.com/11844404/226732052-658ef49d-867b-4fb4-95df-01f160fc2730.png)

---

- [x] More space is needed between the text and img/chart. Right now it’s 16px and feels tight. Maybe 32px would feel better
![image](https://user-images.githubusercontent.com/11844404/226732125-d5876023-23c3-4795-ad2f-dd933f299635.png)

---

- [x] Option for wide images to extend beyond text column
![image](https://user-images.githubusercontent.com/11844404/226732614-401106b6-fe3c-4142-b896-aa1e2f50e42f.png)

---

- [x] Update note component doesn't exist (Resolved by #2045 )
![image](https://user-images.githubusercontent.com/11844404/226732723-d45dd23c-78e4-434f-bf13-a1e7e7b44d4e.png)

---

- [x] Endnotes styled incorrectly
![image](https://user-images.githubusercontent.com/11844404/226732773-580317ec-7f03-4277-897a-397362cf2491.png)

**Comment by marcelgerber** [comment]
@ikesau There are two items above where the checkbox is not checked yet; can this issue be closed?
