### ISSUE TITLE
Sharing button not clickable at the bottom of charts at the bottom right of the viewport 

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2038]
_reported by @paarriagadap on [slack](https://owid.slack.com/archives/C46U9LXRR/p1679573453685009)_

## Description

Sharing button in the bottom right corner of charts not clickable when the chart is at the bottom of the viewport. This comes from the "Jobs" and "Feedback" buttons shadowing it, despite visually disappearing on scroll.

## Expected behaviour

Sharing button clickable as usual.

## Steps to reproduce

1. Go to https://ourworldindata.org/illicit-drug-use#interactive-charts-on-opioids-cocaine-cannabis-and-illicit-drugs
2. Resize your browser window to ~ 1440px
3. Bring the bottom of the chart to the bottom of the viewport
4. Try and click on the sharing icon: it doesn't get a cursor and is not clickable.

## Screenshots
<img width="1440" alt="Screenshot 2023-03-23 at 14 30 35" src="https://user-images.githubusercontent.com/13406362/227220631-d232ef60-3c77-492a-8d7e-0bcd11ae997d.png">

**Comment by larsyencken** [comment]
@mlbrgl Do you have a theory on why it's happening?

**Comment by mlbrgl** [comment]
@larsyencken I think there are two issues here:
- there is a wrapper (`.site-tools`) and its content. When we scroll down, the content is translated down but the wrapper is still in the same place and captures click
- the content is not translated fully out of the view so those buttons continue to capture clicks (but the result is not visible since the opacity has been reduced to 0). Hiding through opacity is done for the aesthetic of the transition, and is not an issue in absolute terms, but compounds the problem here
<img width="224" alt="Screenshot 2023-03-31 at 12 52 09" src="https://user-images.githubusercontent.com/13406362/229101790-f48e32a9-5113-4740-a9be-4e9788b27005.png">

**Comment by ikesau** [comment]
I think adding a mouse-events none to the container when it disappears should fix this.
