### ISSUE TITLE
Variables coming from ETL should have non-editable metadata

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2042]
Original issue in ETL https://github.com/owid/etl/issues/893#issuecomment-1485023491

Datasets pushed via ETL should be non-editable. Otherwise users might change metadata manually and ETL could then overwrite it back on next automatic (or manual) deploy. An easy "fix" is to make all fields non-editable. This would mean that all metadata changes would have to come from ETL (by changing YAML metadata that triggers automatic deploy).

Whether to do this for fast-track is an open question (if we did it, we'd have to probably disable them in automatic deploys), but I'd start by making it non-editable and then we'll see whether it's a problem for authors.

An example is [this variable](https://staging.owid.cloud/admin/variables/576757) that has currently editable fields like `Display name` or `Number of decimal places`. 

A variable is from ETL if `variables.shortName` in MySQL is not null (or if `datasets.sourceChecksum` is not null). We could make a virtual column for it

```
ALTER TABLE variables
ADD COLUMN source BOOLEAN GENERATED ALWAYS AS (
  CASE WHEN shortName IS NULL THEN "etl" ELSE NULL
) VIRTUAL;
```

**Comment by ikesau** [comment]
@danyx23 and @Marigold will chat about this in an upcoming data architecture meeting.

**Comment by marcelgerber** [comment]
@Marigold is this implemented already?

**Comment by Marigold** [comment]
It's [work in progress](https://github.com/owid/owid-grapher/pull/2480).
