### ISSUE TITLE
Load assets from host-relative URL rather than from absolute URL

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2112]
## Description

Currently, we load our JS & CSS assets using absolute URLs, like `<script src='https://ourworldindata.org/assets/owid.mjs' />`.
However, we could just as well load them from `<script src='/assets/owid.mjs' />`.

In particular, this would properly enable viewing Netlify deploys. Right now that's broken, because even in the preview URL, the browser will just load the most recent assets.

## Careful

We need to take care that the `embedCharts.js` file, which we currently use for the SDG Tracker, keeps on using absolute URLs.

## Additional context

[Discussion on Slack, roughly a year ago.](https://owid.slack.com/archives/CQQUA2C2U/p1652780988271109)

[An earlier PR that did this...](https://github.com/owid/owid-grapher/pull/267)

[... and then was reverted](https://github.com/owid/owid-grapher/commit/cffdbf8bd99471e86888d4c9974337d64c36d965)

**Comment by ikesau** [comment]
If we publish the new SDG's soon we won't have to worry about the conditional path thing anymore and can go ahead and make it relative everywhere.

**Comment by marcelgerber** [comment]
As Ike said above, this has gotten easier now that sdg-tracker.org is a thing of the past.

I think this is worthwhile doing, I'll have a look to see if it can be done easily.
