### ISSUE TITLE
Admin: Changing "x axis override year" is not reactive

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2115]
## Description

When creating a scatter plot, changing the "x axis override" option doesn't live-update the preview.

A save & reload of the chart, however, works.

## Steps to reproduce

See video below

## Screenshots

https://user-images.githubusercontent.com/2641501/232719162-ec5d923f-ae43-4c84-9ae7-b8b5998740a8.mov

## Additional context

[Joe brought this up in Slack.](https://owid.slack.com/archives/C6C0MCXU0/p1681805417362409)

There is some table transform that is not properly re-running.
If in doubt, it would be fine to totally reload the grapher preview, if that helps in fixing this issue.

**Comment by danyx23** [comment]
It seems like this wasn't a very intense pain point. Closing the issue.
