### ISSUE TITLE
Faceting: Shared axis not visible if first chart in row has no data

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2127]
## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/life-expectancy?time=earliest..1930&facet=entity&country=WLF~FRA~SWE~ASM
2. Notice that the first row doesn't have an axis on the left, since there's no data for Wallis and Futuna.
3. Also notice that it's hard to see the scale being used for France in this case.

## Screenshots

![image](https://user-images.githubusercontent.com/2641501/233996221-aabc08ec-4033-464f-8f06-394b37cf6489.png)

## Additional context

In shared axis mode, we have a rule that the leftmost chart in each row renders the vertical axis, and its neighbouring charts don't display one.

**Comment by sophiamersmann** [comment]
I think this is similar to #1341 in the sense that in both cases we would need to know whether en entity can be rendered with some data _before_ actually running `transformTable`.
