### ISSUE TITLE
StackedArea charts shows "No matching data" for all-0 series

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2129]
## Description

In StackedArea charts, all-0 series are not plotted. This makes sense if multiple entities are selected (see [Slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1620298486013800) and #906) but if a single entity is selected, showing "No matching data" is misleading. For example:

<img width="714" alt="Screenshot 2023-04-24 at 15 13 30" src="https://user-images.githubusercontent.com/12461810/234007715-1fda3c57-a670-4e47-b56c-94eb9442c5ba.png">

This is misleading as coal, for example, does have data (but all data points are zero). The StackedBar charts shows this accurately:

<img width="772" alt="Screenshot 2023-04-24 at 14 37 00" src="https://user-images.githubusercontent.com/12461810/234011622-39e0303c-0925-4050-83f8-361c08e5de67.png">

Another slightly weird side effect of this implementation is that – based on a selected time frame – we sometimes mention a 0-value for a variable in the tooltip, but other times we don't.

In the chart below, J&J and Novavax are listed with 0-values as later on, these variables do have non-zero entries:

<img width="736" alt="Screenshot 2023-04-24 at 15 25 03" src="https://user-images.githubusercontent.com/12461810/234011859-3f1b7c65-fe91-45e9-984e-aa53f6594d37.png">

But in this chart, we make no mention of J&J and Novavax (even though we know they reported 0 doses for this day)

<img width="736" alt="Screenshot 2023-04-24 at 15 25 36" src="https://user-images.githubusercontent.com/12461810/234011864-27110b14-cf51-4e44-be18-3a662b0c83ea.png">

## Proposed solution

I think rather than excluding an entity without data entirely, we could consider listing it with a 0-value in the tooltip. (We would continue to now show any visual element though).

**Comment by marcelgerber** [comment]
Yes, makes sense.
The small line that was visible in the above Slack conversation was the border, so we should take care that we don't render a border in this case.
Otherwise, it's a good idea to include explicit zero values in the tooltip.
