### ISSUE TITLE
Redundant legend in faceted mode

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2152]
## Problem

In some charts, split by metric leads to a legend that's completely redundant. We should hide the legend in this case.

## Example

<img width="969" alt="Screenshot 2023-04-26 at 13 58 02" src="https://user-images.githubusercontent.com/36012/234582088-f5d0a163-cab5-4f7e-8e91-7fbc8e16d57b.png">

https://ourworldindata.org/grapher/eat-lancet-diet-animal-products?facet=metric

**Comment by marcelgerber** [comment]
Agreed. I think this is a by-chart-type type of thing.
We probably never want to show the legend for StackedDiscreteBar charts.

**Comment by sophiamersmann** [comment]
For now, I submitted a hot-fix that hides legends for StackedDiscreteBar charts that are split by metric. but we should probably also check this for other chart types
