### ISSUE TITLE
Poor choice of colours in faceted StackedArea charts

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2155]
## Description

Sometimes, the choice of colours for the selected entities is suboptimal.

## Expected behaviour

Grapher picks entity colours that are easy to differentiate.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/child-deaths-by-life-stage?facet=metric&country=OWID_WRL~AFG
2. Note that both countries are coloured blue

## Screenshots

<img width="1216" alt="234569272-810f09ef-4d6c-4f48-9e09-2cbf4d494e08" src="https://user-images.githubusercontent.com/12461810/234633243-7b7a9ddd-97ea-4696-b267-1179f932279f.png">

**Comment by marcelgerber** [comment]
Ahh, just realized that this is _another_ config issue:
There is a custom entity color set for "World" (which is pretty nonsensical):
![image](https://user-images.githubusercontent.com/2641501/234667671-35734898-2dc1-4955-85bf-815414031ed4.png)

I just removed it from the chart config.
