### ISSUE TITLE
Redundant bar labels in faceted DiscreteStackedBar charts

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2157]
## Description

When faceted, StackedDiscreteBarCharts render bar labels twice, once inside of the bar, once outside of the bar.

## Expected behaviour

Only show one label.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/frequency-depressive-symptoms-us?facet=metric
2. (If your screen is big enough) Note that some bar labels are rendered twice

## Screenshots

<img width="936" alt="Screenshot 2023-04-27 at 10 00 33" src="https://user-images.githubusercontent.com/12461810/234798519-abd7bd92-53c0-49b6-80be-20fa1a2a19fd.png">

## Additional context

This is in fact expected behaviour for discrete stacked bar charts. The label within the bar is the label of that item and the label at the end of the (usually stacked) bar is the total. When faceted and bars are in fact not stacked, I think it'd be nice to render only one label because it can look a little crowded. (But Grapher could also stay as is.)

**Comment by marcelgerber** [comment]
Agreed, it'd be nicer to only render one of these.

Looking at your screenshot, I'd choose the label on the outside (to the right of the bar), because it can always be rendered. For the inside label, we can run into scenarios where there isn't enough space.
