### ISSUE TITLE
StackedArea: Can't go back to relative mode after faceting when relative toggle is hidden

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2158]
## Description

For StackedAreaCharts with relative mode enabled, clicking on "Split by metric" shows facets in absolute mode (which makes sense), but switching back to the default view doesn't bring back relative mode. If the chart does not have a relative mode toggle, then the reader has no way to go back to relative mode.

## Expected behaviour

Re-apply relative mode when going back to the default view

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/parents-who-agree-with-spanking-to-discipline-a-child
2. Notice that the chart is in relative mode
3. Click on 'Split by metric'
4. Notice that facets are in absolute mode (which makes sense)
5. Click on 'All together'
6. Notice that the chart is in absolute mode and there is no way of going back to relative mode since the toggle is hidden

## Screenshots

Default view (relative mode):

<img width="735" alt="Screenshot 2023-04-27 at 12 00 06" src="https://user-images.githubusercontent.com/12461810/234829449-3e7b347b-5068-495a-b005-bef2a4788dae.png">

Faceted (absolute mode):

<img width="735" alt="Screenshot 2023-04-27 at 12 00 12" src="https://user-images.githubusercontent.com/12461810/234829462-59e2a564-e23a-4ed0-aae5-93f308504c9c.png">

End view (absolute mode):

<img width="735" alt="Screenshot 2023-04-27 at 12 00 17" src="https://user-images.githubusercontent.com/12461810/234829465-feb894cc-77a9-4bae-aa6d-1b5431bec034.png">

**Comment by sophiamersmann** [comment]
Made worse by #2176 

Examples:
- https://ourworldindata.org/grapher/share-of-world-merchandise-trade-by-type-of-trade
- https://ourworldindata.org/grapher/distribution-of-global-merchandise-exports-by-region-of-origin

**Comment by larsyencken** [comment]
Looks like this line is wrong: https://github.com/owid/owid-grapher/blob/master/packages/@ourworldindata/grapher/src/core/Grapher.tsx#L2084-L2091

We shouldn't be changing the `stackMode` setting there. Instead, it should happen in the computed `isRelativeMode()` method. Then when you go back to the old view, `stackMode` is preserved.
