### ISSUE TITLE
x-axis not aligned in faceted StackedBar charts

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2160]
## Description

Sometimes, the x-axis is not aligned when StackedBar charts are faceted. This is especially noticeable when data is missing for some variables.

## Expected behaviour

The x-axis should be aligned.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/lighting-sources-uk?facet=entity
2. Notice that each facet has their own x-axis

## Screenshots

<img width="736" alt="Screenshot 2023-04-27 at 12 18 04" src="https://user-images.githubusercontent.com/12461810/234834288-c92d3201-d76f-4603-a066-41076b8867f5.png">

Note: Faceting has been turned off for the example chart but the issue persists.

**Comment by marcelgerber** [comment]
I just looked into this a bit.
Stacked bar charts are not using our usual `DualAxisComponent` which takes care of all of this, but instead they self-roll the placement of values on the horizontal axis. I think the reason for that is that we don't want the min value all the way on the left as we would with `DualAxisComponent`, but we want it spaced out by a bit so we can display a centered bar on top of the year number.

This rendering, however, is only based on the number of distinct x values per subchart, and is not taking `horizontalAxis.domain` into account at all.

Fixing this is rather tedious, it would probably require a partial refactoring of StackedBarCharts.

**Comment by sophiamersmann** [comment]
Luckily this bug doesn't affect a lot of charts. If we don't plan to fix this soon-ish, then I'll go ahead and turn off faceting for the given example chart.

**Comment by larsyencken** [comment]
Closing this as won't fix. It's not that we wouldn't like the axes to be aligned, but there's probably just a lot more we'd like to do first.

Feel free to pick it up in a cooldown!

**Comment by sophiamersmann** [comment]
Another example: https://ourworldindata.org/grapher/natural-disasters-by-type?facet=entity

**Comment by sophiamersmann** [comment]
Re-opening since this would be nice to fix for the climate charts that Veronika and I work on at the moment

**Comment by danyx23** [comment]
Has been fixed by @sophiamersmann as part of the climate chart work on stacked bar charts
