### ISSUE TITLE
Explorers don't respect the entity type in all places

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2170]
## Description

Explorers use a given entity type in the search field on the left ("Type to add a ....[type]...") but don't use it in the "Split by ..." dropdown within the chart.

## Expected behaviour

Use the entity type in all appropriate places

## Steps to reproduce

1. Go to this https://ourworldindata.org/explorers/fish-stocks?facet=none&country=Albacore+tuna+North+Pacific+Ocean~Albacore+tuna+South+Atlantic~Atlantic+bluefin+tuna+Western+Atlantic&Metric=Fish+stocks+%28biomass%29&Total+or+Relative=Relative+to+Max+Sustainable+Yield
2. Click on "All together" and note that the dropdown says "Split by country" while the search field on the left says "Type to add a fish stock"

## Screenshots

<img width="1140" alt="Screenshot 2023-04-28 at 12 15 45" src="https://user-images.githubusercontent.com/12461810/235159058-1d28149f-05c1-44b5-93cd-2ad0d5f979b3.png">

The entity type is specified here:

<img width="1140" alt="Screenshot 2023-04-28 at 15 15 13" src="https://user-images.githubusercontent.com/12461810/235158981-78b12416-0140-42a2-8e63-66388d2e56cc.png">

**Comment by marcelgerber** [comment]
This is maybe related to https://github.com/owid/owid-grapher/issues/1008, but not sure?
