### ISSUE TITLE
Bug: Map view does not change when using slider (variable admin page)

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2171]
## Description
On the variable preview page, the values on hover on the map don't change as I change the year. It looks like the latest data point is shown.

## Expected behaviour
When hovering over a country, it should reflect its values for the selected year.
## Steps to reproduce

Steps to reproduce the behaviour:

1. I am using `Population (future projections)` variable: https://owid.cloud/admin/variables/597932
2. Hover over any country on the map preview, change the year with the time slider
3. Values don't change

## Screenshots

https://user-images.githubusercontent.com/18101289/235181342-a958c269-6a92-4891-b60a-7e8af9b3f215.mov

## Environment

For desktop, provide:

-   OS: macOS
-   Browser Brave (chromium)
-   [Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by lucasrodes** [comment]
It is working locally on my end. If it helps, I'm at commit 4b01bc0c3 (I haven't pulled for now in case it is a bug that was added later on).

**Comment by marcelgerber** [comment]
Thanks for the hint on this being a recent regression; it is indeed and a bisect points to a33cb090928628a197a29ef059288c6fa93debd5 (#2075). It's probably the change to `GrapherFigureView` in there.

Crucially, this is not only an issue with the variable page, but also on our site search in the preview chart.

**Comment by lucasrodes** [comment]
duplicate of https://github.com/owid/owid-grapher/issues/2168

**Comment by marcelgerber** [comment]
Fixed in https://github.com/owid/owid-grapher/commit/fe215d111c4bc6c26b96606df5e6a0e20de2d119 🤞🏻
