### ISSUE TITLE
Gdoc parsing error when copy / paste from site

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2190]
## Description

Copying text from an article on ourworlindata.org into a google doc for previewing generates an error

## Expected behaviour

No error.

## Steps to reproduce

1. Go to this https://ourworldindata.org/co2-dataset-sources#why-are-consumption-based-emissions-only-available-from-1990-why-are-they-not-available-for-all-countries
2. Copy the heading and its preceeding paragraph (starting at "Unless specified as consumption-based...")
3. Paste it into a new google doc
4. Preview
5. `Error: Pattern matching error: no pattern matches value {"type":"level","value":"4"}`

## Screenshots
<img width="708" alt="Screenshot 2023-05-05 at 15 35 27" src="https://user-images.githubusercontent.com/13406362/236472360-1058dba1-82c3-4f43-884c-47012379e52e.png">

## Workaround

"Clear formatting" on the pasted text solves the issue.

**Comment by ikesau** [comment]
It's not pasting the content with the ideal tags, but the parsing issue has been fixed by https://github.com/owid/owid-grapher/pull/2429
