### ISSUE TITLE
Install error: Could not connect to grapher database

### ISSUE THREAD

**Issue by makenoteshere** [owid/owid-grapher#2195]
Hi, I'm trying to setup the grapher instance but running into this error. I've cleaned the docker setup and tried to reinstall, but still running into this issue. Any ideas how do I fix this? I'm following the setup instructions from this guide https://github.com/owid/owid-grapher/blob/master/docs/docker-compose-mysql.md

```
TypeError: Cannot read properties of undefined (reading 'unlisted')
    at Gdoc (~/owid-grapher/db/model/Gdoc.ts:23:39)
    at EntityMetadata.create (~/owid-grapher/node_modules/typeorm/metadata/src/metadata/EntityMetadata.ts:563:23)
    at EntityMetadataValidator.validate (~/owid-grapher/node_modules/typeorm/metadata-builder/src/metadata-builder/EntityMetadataValidator.ts:211:47)
    at <anonymous> (~/owid-grapher/node_modules/typeorm/metadata-builder/src/metadata-builder/EntityMetadataValidator.ts:43:18)
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (~/owid-grapher/node_modules/typeorm/metadata-builder/src/metadata-builder/EntityMetadataValidator.ts:42:25)
    at DataSource.buildMetadatas (~/owid-grapher/node_modules/typeorm/data-source/src/data-source/DataSource.ts:724:33)
    at DataSource.initialize (~/owid-grapher/node_modules/typeorm/data-source/src/data-source/DataSource.ts:259:13)
    at Object.getConnection (~/owid-grapher/db/db.ts:20:25)
    at OwidAdminApp.OwidAdminApp.connectToDatabases (~/owid-grapher/adminSiteServer/app.tsx:230:13)
Could not connect to grapher database. Continuing without DB...
WORDPRESS_DB_NAME is not configured -- continuing without Wordpress DB
WORDPRESS_API_URL is not configured -- continuing without Wordpress API
owid-admin server started on http://localhost:3030
```

Running on Mac. However I can see mysql is up on 3307 port and can connect via dbeaver.

I can't tell if this is Gdoc related issue. And I'm assuming gdoc setup is optional?

**Comment by marcelgerber** [comment]
Hm, that's weird.
Yes, as you say Gdocs is (well, should be) optional, and I hope that's not the reason for your error message.

Did you install the project using `yarn`?
Could you post the output of `yarn --version` and `node --version`?

**Comment by makenoteshere** [comment]
@marcelgerber thanks for checking. Here are the versions. I was using `make up` which internally calls `yarn install`, so I'm guessing deps are installed by yarn. I've retried `yarn install` and seeing the same error.
```
➜  owid-grapher git:(master) ✗ yarn --version
3.3.0
➜  owid-grapher git:(master) ✗ node --version
v19.6.0
```

**Comment by makenoteshere** [comment]
Turns out I had to remove `itsJustJavascript` and rebuild it. Working now.

**Comment by makenoteshere** [comment]
I seem to have hit into another error. Charts are not rendering and it's running into localhost:3030/headerMenu.json 404 (Not Found). I was under impression, I could run this without needing wordpress or graphql setup. I could do this few months ago.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/7573744/236619921-e860b411-1c78-4562-9214-38e36479d100.png">

**Comment by ikesau** [comment]
Hey there @makenoteshere 🙂 

The `headerMenu.json` 404 is expected and shouldn't be a blocker. It's used in the site header, but doesn't affect Graphers rendering.

If you initialized this project a while ago, it's possible that your DB is outdated. Try running `yarn runDbMigrations` and see if that fixes things.

If not, then you may want to try refreshing your DB entirely with `make refresh` which will download an export of our live DB and import it into your local DB. (Pull down from master first as I just committed a fix for grapher-only setups)

Let me know how it goes!

**Comment by makenoteshere** [comment]
Thanks @ikesau, I actually deleted the grapher database, repo, docker artefacts and recreated the whole setup. It seems like the data api is hung? The request is pending state for close to minute. I can see this variable's data is available in data_values table.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/7573744/236636604-b61aa028-5762-40f9-9f98-05de724b6d16.png">

Not sure what the issue, can't see any logs in admin console.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/7573744/236636697-585e4a9a-983f-472c-8f94-54d4b5a0b11f.png">

Is there anything I can do to provide more details?

**Comment by makenoteshere** [comment]
I'm wildly guessing based on limited understanding of code flow, is it due to getVariableData / fetchS3Values in Variable.ts?

**Comment by makenoteshere** [comment]
It looks like it gets hung at `fetchS3ValuesByPath`. I was able to trace the datapath `https://catalog.ourworldindata.org/baked-variables/live_grapher/data/418320.json`, I can open this in the browser. Not sure if something is blocking to access inside `fetch` in `fetchS3ValuesByPath`

**Comment by makenoteshere** [comment]
Looks like a node DNS bug. I switched the node to use ipv4first `"startAdminServer": "node --enable-source-maps --dns-result-order=ipv4first ./itsJustJavascript/adminSiteServer/app.js",` it's working now.

**Comment by ikesau** [comment]
Solid effort, @makenoteshere ! Feel free to reach out again if you run into any more roadblocks 🙂
