### ISSUE TITLE
Google Documents aren't publishing consistently

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2196]
I suspect something to do with the `useAutoSaveDraft` is creating a race condition where the document can immediately unpublish itself after pressing Publish.

To reproduce: try publishing a document several times and occasionally it will unpublish again.

**Comment by marcelgerber** [comment]
For additional context, this happened yesterday when two users were looking at the same document in the admin at the same time. One user hit publish, and then the autosave of the other user (potentially) set it to unpublished again.

**Comment by ikesau** [comment]
I believe this is PUT logic is also responsible for these errors that @paarriagadap has been getting.

![image](https://github.com/owid/owid-grapher/assets/11844404/e4ae599a-70fe-45ec-a4e4-e0ad284e2448)

So addressing the root cause of this ticket should also fix that.

**Comment by danyx23** [comment]
@ikesau @mlbrgl let's use this issue as a checkpoint to revisit the gdocs related api endpoints for race conditions together
