### ISSUE TITLE
Sticky nav container highlights when search bar is focused

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2200]
## Description

The sticky nav is getting highlighted (or, rather, not properly faded into the background) when the search bar is focused.

## Steps to reproduce

1. Go to https://ourworldindata.org/energy
2. Click the search bar

## Screenshots

<img width="1421" alt="image" src="https://github.com/owid/owid-grapher/assets/2641501/9c318cb2-3da6-4fb8-9323-043f602412dc">

## Environment

Edge 113.0.1774.35

**Comment by ikesau** [comment]
This is getting fixed in https://github.com/owid/owid-grapher/pull/2104

**Comment by marcelgerber** [comment]
Fixed now.
