### ISSUE TITLE
migrateWpPostsToArchieMl is migrating images incorrectly

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2214]
Some img src tags in WP have a size appended to the filename, so that even after we get the filename with `path.basename` it stores `Healthy20height20growth20curves-633x550.png`

We need it to just be: `Healthy20height20growth20curves.png` because that's the name of the file we've backed up to Drive.

**Comment by larsyencken** [comment]
Is this still an issue Ike?

**Comment by ikesau** [comment]
Fixed by https://github.com/owid/owid-grapher/commit/8a9c105810ba6581ade46e3ec869dab34bc57f66
