### ISSUE TITLE
Narrative charts in ArchieML articles

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2215]
## Motivation

We currently use explorable grapher charts throughout our articles to make various points. Often, the exploration is only a side-effect, mainly we want to demonstrate an insight into the data in that moment.

## Proposal

We propose to allow authors to create "narrative charts" in ArchieML articles.

A narrative chart is a normal chart whose title changed in its article context to give the insight that the chart conveys. Controls for the chart are disabled, meaning that the chart is interactive but "read-only".

On hover, an "Explore" control appears which links to the grapher page for that chart; the grapher page has the usual title and controls for that chart.

The ArchieML block would look like this:

```
{.chart}
url: https://ourworldindata.org/grapher/life-expectancy?country=~SWE
title: Life expectancy has doubled in Sweden since the 1800s
{}
```

## Scope

- [ ] Override title for chart from ArchieML
- [ ] Disable controls when title is overridden
- [ ] Add "Explore" button on-hover, linking to Grapher page

## Open questions

- Should we also disable the tabs at the bottom of the chart?

**Comment by larsyencken** [comment]
@mathisonian Is this a fair summary of what we imagined here?

**Comment by mathisonian** [comment]
Yeah, I think this captures it, although we should think about exactly what options to expose here. We should probably also support: 

- overriding the `subtitle`
- showing any subset of tabs at the bottom (or no tabs)
- enable/disable interactive controls (including timeline, entity selection, relative, region selection, faceting, log/linear). again it would be nice to enable/disable any subset of these features (or none).

**Comment by mathisonian** [comment]
We should also make sure to have reasonable defaults so it isn't a slog to manually set all these options if they aren't needed.
