### ISSUE TITLE
feature: set 'Infinity' or '-Infinity' from admin in `Selection start` and `Selection end` fields

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2234]
## Core problem

In charts, whenever we want to anchor the year to the latest (or earliest), it’d be nice if we could do this from the admin without hardcoding the year (like in [this example](https://owid.cloud/admin/charts/2237/edit)).

## Proposed solution

Instead, if we could type “Infinity” in both `Selection start` and `Selection end`, that’d be great. This would be very helpful in our chart revision process, where we update some fields in the chart configuration (e.g. new variable may have more recent data). For these cases, it is hard to assess whether the values for `minTime` and `maxYear` in the chart config should be updated (anchoring was done to show the latest data) or not (anchoring was done to display a particular year).

## Alternatives

At the moment, a workaround is to drag the slider beyond the limits of the chart to set it to "Infinity."

https://github.com/owid/owid-grapher/assets/18101289/c03b502d-04b4-431b-bf8a-0ed4e63fbb1e

cc. @sophiamersmann

**Comment by sophiamersmann** [comment]
Selection start & end fields are number fields and I'm hesitant to allow string values like "Infinity" or "-Infinity". If we only handled this specific use case and added a toggle labelled "Always show latest time point" (or similar), that sets start and end time to "Infinity", would that be enough? Or would you want more control than that?

**Comment by lucasrodes** [comment]
100% that would be perfect!

Unsure if we needed something similar for the "earliest" part. I don't think there are that many charts set to "oldest date". So not a priority.

**Comment by sophiamersmann** [comment]
Do you know if there is a particular reason that this chart is a line chart and not a discrete bar chart?

**Comment by lucasrodes** [comment]
Unsure why it is a Linechart. It used to show all the years, but then I collapsed it to the last year because the trends were almost constant. We may sometimes want to show constant trends, but I don't think this is valuable here.

However, leaving the chart as a line chart leaves it up to the user if they want to explore ranges instead of a particular year.

> (I'm asking because – in the general case – setting "Always show latest time point" on a line chart probably shouldn't make the chart collapse into a bar chart by default, right?)

I see your point and the motivation to switch these charts to discrete bar charts. I see how this can also apply to "ScatterPlots" (and other types), where we have two options to visualise the data: single year or year range.

Going back to you proposal, I like the idea of having the option "Always show latest time point", which should set `maxTime="latest"`. Now, what to do with `minTime` I am unsure. Maybe an additional option like "Collapse start time with end time"? This would set `minTime` to whatever value `maxTime` has.

Unsure how user-friendly this would be, but something along this lines could work?

**Comment by larsyencken** [comment]
@lucasrodes From discussion with Sophia, it seems like we found a solution in the admin where you can flick the time slider right and get it pinned to the latest year. Pre-collapsing charts like this seems an uncommon use case. Is this good enough for now?
