### ISSUE TITLE
Scatter plot: x-axis ticks misaligned on smaller screens

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2273]
## Description

For [this chart](https://ourworldindata.org/grapher/comfort-speaking-vs-knowing-friends-family-with-anxiety-depression), the x-axis ticks overlap with the domain line on smaller screens. 

## Expected behaviour

x-axis should be correctly aligned.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/comfort-speaking-vs-knowing-friends-family-with-anxiety-depression
2. Set window size to 375x667 (iPhone SE)
3. Note that the x-axis are not correctly aligned

## Screenshots

<img width="352" alt="Screenshot 2023-06-01 at 13 18 49" src="https://github.com/owid/owid-grapher/assets/12461810/f3c8b94d-a9c9-438c-b343-75c2ab62ec4b">

## Environment

On Chrome

---

Reported by Lucas on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1685613075031389)

**Comment by lucasrodes** [comment]
perhaps the long x-axis label has something to do with it?

**Comment by sophiamersmann** [comment]
oh, I didn't even notice how long that is! yeah, good idea, that might be it
