### ISSUE TITLE
🐛 Color scheme "Continents" assigning wrong colours in Stacked Area chart

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2288]
## Description

This [stacked area chart](https://owid.cloud/admin/charts/401/edit), assigning the colour scheme "continents", sets the colours to the wrong continents. 

The loaded colour palette is correct, but colours are not assigned to the correct continents. For now, I've manually set the colours to the countries, so not a blocker.

<img width="753" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/fa2b787c-0cb2-42f1-86d6-e7e644e9fd0b">

**Comment by sophiamersmann** [comment]
We currently have [four stacked area charts](https://datasette-public.owid.io/owid?sql=select%0D%0A++id,%0D%0A++slug%0D%0Afrom%0D%0A++charts%0D%0Awhere%0D%0A++type+%3D+'StackedArea'%0D%0A++and+config+-%3E%3E+%22$.baseColorScheme%22+%3D+%22continents%22) that use "continents" as color scheme

**Comment by marcelgerber** [comment]
Stacked charts never do any "automatic" color assignment to entities, i.e. the colors will have to be manually assigned to the entities for this to work.

It therefore probably doesn't make sense to use the Continents color scheme for stacked charts.

**Comment by marcelgerber** [comment]
Yes; the automatic assignment in ScatterPlots is based on a categorical variable, i.e. it is a color dimension with a dedicated variable for the color scheme.

In the stacked case, though, these are entity colors.

**Comment by lucasrodes** [comment]
I see, thanks for clarifying @marcelgerber.

So Grapher loads the correct colour palette yet can't assign the specific colours to the entities for this kind of chart.

**Comment by larsyencken** [comment]
This is a specific sub-ask of https://github.com/owid/owid-grapher/issues/2297

Closing this and we can take any discussion on the other there.
