### ISSUE TITLE
Support pulling metadata from variables for explorers

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2313]
## Problem

A large number of small charts can be difficult for people to work their way around, so we create explorers in order to give people helpful navigation between related charts.

Today, you can create explorers two ways:

- CSV data and bring-your-own FASTT defined in TSV explorer config (e.g. Global Food Explorer [explorer](https://ourworldindata.org/explorers/global-food) [tsv](https://github.com/owid/owid-content/blob/master/explorers/global-food.explorer.tsv))
  - Then the FASTT gets templated in code, but has to be templated all over again and duplicated if we want any part of this in the Grapher/MySQL ecosystem
  - Today we often add some charts to the Grapher ecosystem to given them an SEO page
  - Today there are lots of places we surface charts outside explorers as being different to charts inside explorers, so it's often motivating to have it both ways
- Grapher charts and FASTT as overrides (e.g. Democracy Explorer [explorer](https://ourworldindata.org/explorers/democracy) [tsv](https://github.com/owid/owid-content/blob/master/explorers/democracy.explorer.tsv))
  - Then you have two places on our site (explorer + chart) for users to find information, which is not ideal
  - For a large dimensional dataset (e.g. Global Burden of Disease), it could mean making 1000 charts or more just for one multi-dimensional variable

## Proposed solution

We want to reduce duplication on our site by making it possible to create explorers from variables.

This has the same benefits as using charts, but avoids duplicate content on our site.

## Technical notes

- We would like to use the new data API that Mojmir has been working on to fetch data and metadata lazily one variable at a time
- We should borrow as much as possible from the way the `grapher` blocks in explorers work now
- We may need to override parts of the inherited grapher configs from variables to customize the charts generated by explorers

**Comment by larsyencken** [comment]
@sophiamersmann @danyx23 Please review when you have a few moments!

**Comment by larsyencken** [comment]
Sophia's notes in Notion: [Cycle 2023.6 (Sophia): Create explorers from indicators](https://www.notion.so/owid/Cycle-2023-6-Sophia-Create-explorers-from-indicators-93652bd93b94432696afad1c1b439d31?pvs=4)

**Comment by larsyencken** [comment]
@sophiamersmann Was there an open question around bake-time vs render time pulling in of variable metadata?

**Comment by sophiamersmann** [comment]
Yes, specifically, we need to decide if we want partial Grapher configurations to be a part of the JSON metadata file (which is pulled in later) or if we want partial Grapher configs to be embedded on the Explorer page. I'm in favour of the latter, but I'll reach out to Daniel today to make sure we're on the same page.
