### ISSUE TITLE
Gdoc article Grapher embeds don't have SVG fallbacks

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2354]
I noticed this today after browsing our site with NoScript enabled.

https://ourworldindata.org/population-projections

![image](https://github.com/owid/owid-grapher/assets/11844404/9a1d9902-13f9-4cb4-9c39-47ee719b3feb)

It's still working with our WordPress articles, so this is due to how our Chart component renders charts.

**As part of this, we should also restore the "Tap to load" functionality on mobile where it only loads the SVG by default.**

**Comment by marcelgerber** [comment]
For reference: The code that makes this work for WP baking is this one here: https://github.com/owid/owid-grapher/blob/b0e64244f64b8d772402144ce925000df5adb03e/baker/formatWordpressPost.tsx#L383-L392

And then there's also some code ensuring that we have a svg version for every variant that we embed, i.e. the concrete query params that are being used in an embed.

**Comment by danyx23** [comment]
When implementing this make sure to also check this for data pages and topic pages

**Comment by danyx23** [comment]
The issues #2992 is also related to this one and should probably fixed at the same time

**Comment by rakyi** [comment]
> **As part of this, we should also restore the "Tap to load" functionality on mobile where it only loads the SVG by default.**

@ikesau why would we want to do this? It makes me less likely to use the interactive chart as a user if I have to click to load it, and subjectively I'd prefer to be able to interact with the chart ASAP.

**Comment by rakyi** [comment]
Now [I see](https://github.com/owid/owid-grapher/blob/acbfb58fccf39cc075dc1be0e044d9d4eec12195/site/multiembedder/MultiEmbedder.tsx#L55) that some less powerful devices are probably not handling it well, fair enough.
