### ISSUE TITLE
Narrative Grapher: emphasise a bar or line contextually

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2358]
## Problem

We have drafted a key insight that looks like this:

<img width="1204" alt="Screenshot 2023-06-22 at 12 50 37" src="https://github.com/owid/owid-grapher/assets/36012/26b63476-13e2-4c6d-ab37-b853e1f494db">

We want to emphasise that diarrheal diseases are one of the top causes of death of children under five. But the chart is so busy that it's hard for the reader to immediately spot the relevant bar of the chart.

## Proposed solution

Let us assume we are using a new GDocs Topic page. Then in this scenario, we would like to use a narrative Grapher customisation to emphasise the indicator "Diarrheal diseases" no matter what configuration of the chart the user makes.

In bar chart form, the author could give a custom colour for that indicator.

In line chart form, the line could be thicker.

## Technical notes & questions

- Do we want to do this in a semantic way ("Please emphasise this indicator") or an imperative way ("Please make this indicator orange")?

**Comment by sophiamersmann** [comment]
As part of #3381 we'll be thinking about a "focus" mode for lines/bars.
