### ISSUE TITLE
Use as a charting or plotting library

### ISSUE THREAD

**Issue by ashim95** [owid/owid-grapher#2372]
Hi,

First of all, thanks a lot for putting all the data and code in the open domain (and that too with MIT license). 

I really like the visual presentation of the charts on your website and would like to use them for my visualization in my work. I have used either `matplotlib` or `seaborn` for static charts. I want to know if there is a way to similarly use this library. Just to clarify I don't necessarily want to produce dynamic, interactive visualizations but simple charts and plots that I can use as images. 

Thank you,

**Comment by larsyencken** [comment]
Hi Ashim!

We've made some efforts to allow you to use Grapher in similar way to Matplotlib or Seaborn, and that's the [owid-grapher-py](https://github.com/owid/owid-grapher-py/) project. However, the project is quite experimental, and it's not currently working.

Best to stick with other well-supported data viz libraries for now!
