### ISSUE TITLE
Empty lines formatted as "Heading xx" generate a parsing error

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2376]
## Description

Previewing a gdoc with an empty line formatted as "Heading xx" generates a parsing error.

## Expected behaviour

Empty line should be ignored when parsing. No parsing error should be generated.

## Steps to reproduce

1. Create an empty gdoc and preview it
2. Format an empty line as "Heading 1"
4. See parsing error in preview

## Screenshots
<img width="1440" alt="Screenshot 2023-06-28 at 06 57 12" src="https://github.com/owid/owid-grapher/assets/13406362/a9f09cfa-6fee-45f7-833f-c9c826577976">

<img width="1440" alt="Screenshot 2023-06-28 at 07 07 29" src="https://github.com/owid/owid-grapher/assets/13406362/b5a5ba13-477d-4a58-9ad0-7b8ae4135d03">

**Comment by ikesau** [comment]
It's a feature not a bug 😉
