### ISSUE TITLE
Additional `VariableMeta` fields

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2383]
This will be an implementation of the new [VariableMeta proposal](https://www.notion.so/owid/2023-06-26-Proposed-metadata-structure-that-enable-data-pages-83b3602d12004796a2034fc870911137). The steps are pretty straightforward:

1. Extend class `VariableMeta` by fields from the [proposal](https://www.notion.so/owid/2023-06-26-Proposed-metadata-structure-that-enable-data-pages-83b3602d12004796a2034fc870911137) (`VariablePresentationMeta` in particular) **except of fields tags and faqs** that will be added in a future PR
2. Add new columns to `variables` table in MySQL (migration in owid-grapher repo)
3. Propagate those fields to metadata.json in S3
4. Test it on a [single WDI indicator](https://github.com/owid/etl/pull/1256)

**Comment by danyx23** [comment]
Completed in https://github.com/owid/etl/pull/1246
