### ISSUE TITLE
Add Origins to Grapher and extend variables DB classes and variable metadata

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2392]
After the database has gained new fields on the variables, the datasets table and new relationship tables were added in #1286 and #2481, we need to bring the the grapher DB types into alignment again.

- [x] add OwidOrigin
- [x] add new fields on OwidVariable
- [x] add/update the database classes
- [x] make Grapher use Origin in the current designs so that Origin-only indicators will still render correctly

**Comment by larsyencken** [comment]
@danyx23 This one is all ticked off, should it be closed?

**Comment by danyx23** [comment]
@larsyencken I'll close the issue when the PRs are merged which should happen later today, finally :)
