### ISSUE TITLE
Timeline overlaps with footer text on smaller screens

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2400]
## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-up-to-30-dollars
2. Resize window width to <438px
3. Note that footer text and timeline overlap

## Screenshots

<img width="384" alt="Screenshot 2023-07-05 at 09 40 48" src="https://github.com/owid/owid-grapher/assets/12461810/214f4264-ccc4-4b6c-b090-661097b18b36">

Another example: https://ourworldindata.org/age-structure#countries-with-lower-median-age-tend-to-have-higher-population-growth-rates

**Comment by larsyencken** [comment]
Expected to be fixed by the new designs

**Comment by pabloarosado** [comment]
A smaller related issue that I don't know if you are considering (and may possibly be a separate issue) is that, when pressing the play button, bubbles with the minimum and maximum years appear. It would be better if they did not cover the source.
![Screen Shot 2023-08-04 at 10 41 16](https://github.com/owid/owid-grapher/assets/12246978/07f9c0aa-5cae-4354-8fe4-f2f69afbc77d)

**Comment by sophiamersmann** [comment]
The timeline is above the source in the new designs :)
