### ISSUE TITLE
SDG tracker: implement new URL scheme

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2422]
## What

We want our new SDG tracker to use a friendly URL scheme, so that `/no-poverty-sdg` becomes `/sdgs/no-poverty` instead.

## Proposed URLs

https://docs.google.com/spreadsheets/d/1eAnuAEOBJcDCOEMuspp-6jOO6ebaEUgTW-ynL5PhwPc/edit#gid=0

**Comment by ikesau** [comment]
`energy` and `economic-growth` both have slugs that collide with current slugs we use for topic pages. 

The first way I'll look into doing this is allowing slugs to be paths instead so that we can save these pages as `sdgs/energy` for example.

**Comment by larsyencken** [comment]
Ed suggested a few changes, so the exact URLs for some goals just got updated in the spreadsheet.

**Comment by ikesau** [comment]
Resolved by #2425
