### ISSUE TITLE
Support custom x-axis label for stacked bar charts

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2433]
See [Slack](https://owid.slack.com/archives/C46U9LXRR/p1689324451536219)

## Core problem

Stacked bar charts don't seem to support custom x-axis labels. Other chart types that have time on the x-axis do (e.g. line charts or scatter plots). It can be useful, as Charlie pointed out, to specify what the time actually refers to (e.g. "publication year"). See  [Slack](https://owid.slack.com/archives/C46U9LXRR/p1689324451536219) for examples.

## Context

Do stacked area charts support custom x-axis labels?

**Comment by marcelgerber** [comment]
> Do stacked area charts support custom x-axis labels?

Yes, they do:
<img width="1399" alt="image" src="https://github.com/owid/owid-grapher/assets/2641501/98dfce25-080b-4c91-9d85-ceb37ffdf068">

I think this essentially comes down to StackedBar not using our normal `HorizontalAxis` component, but rather a custom implementation. It's similar to #2160 in that way.

**Comment by larsyencken** [comment]
Chatting with @sophiamersmann, seems like it would be nice to solve this by using the same axis component here too, as you say Marcel.

**Comment by danyx23** [comment]
@sophiamersmann has removed the old, customized legacy axis for stacked bar charts and streamlined this with our normal axis component. Currently we don't show the control to override the x-axis label in the admin but that should now be a relatively easy thing to do.
