### ISSUE TITLE
Saving a Gdoc is happening in a race condition, reverting the save right after (sometimes)

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2461]
## Description

There is a race condition in saving condition which, when hit, can lead to:
- A gdoc being saved upon user request (e.g. published)
- The same gdoc being _unpublished_ right after, since it is overwritten by a periodic refresh from Google Docs: https://github.com/owid/owid-grapher/blob/9b1028b49e23dae1ee254a2bf19bdbe3b8481d3b/adminSiteServer/apiRouter.ts#L2504-L2506

From my own experience, I would say this behavior happens in about 30% of cases.

## Additional context

Possible solutions:
- Only call `.save()` if the gdoc `revisionId` has changed (easy; there's still a chance we erroneously overwrite it although far less likely)
- Check that `updatedAt` hasn't changed before updating the record in the DB (easy; there's still a chance we erroneously overwrite it although far less likely)
- Only update fields like `content`, and not `slug` or `published`

**Comment by danyx23** [comment]
We're not doing the automatic preview anymore so this one is no longer relevant.
