### ISSUE TITLE
All Charts blocks are changing the title of the Topic Page

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2465]
Scrolling down on https://ourworldindata.org/poverty changes the title from `Poverty - Our World In Data` to `Share of population living in poverty, 2019` once you scroll close enough to the all charts block.

This appears to be due to the MultiEmbedder creating its config for the embedded grapher by merging in the config from https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty (which has `bindUrlToWindow: true`)

https://github.com/owid/owid-grapher/blob/4db902b942a7ea0c330274d48a73f829786e9114/site/multiembedder/MultiEmbedder.tsx#L220

I'm not sure what the best way to fix this will be without introducing regressions for the rest of the site, especially datapages 🤷

**Comment by marcelgerber** [comment]
It's important to note, too, that this is only happening when the offending chart in the all charts block is a data page.
