### ISSUE TITLE
Source text generates a line jump between the source and footnote

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#2479]
## Description

We have charts where the text of the source generates a space between itself and the note.

## Expected behavior

There should be no space between them

## Steps to reproduce

1. Go to charts in the Multidimensional Poverty Index Dataset ([1](https://owid.cloud/admin/charts/5948/edit) [2](https://owid.cloud/admin/charts/5997/edit) [3](https://owid.cloud/admin/charts/5952/edit))
2. See the space between source and footnote
3. Try to edit the footnote and see how the space disappears.

## Screenshots
![multidimensional-poverty-index-mpi (1)](https://github.com/owid/owid-grapher/assets/63430031/bc2cea8d-8368-42ac-a7c3-3adb2ce6c204)

See how the space disappears when I "edit" the source text (without changing any text):

https://github.com/owid/owid-grapher/assets/63430031/dba832c7-b2ce-4707-8f3b-cda1383bc387

## Environment

For desktop, provide:

-   OS: macOS Ventura 13.4.1
-   Browser Chrome 
-   Version 114.0.5735.198 

## Additional context

[Posted on Slack](https://owid.slack.com/archives/C46U9LXRR/p1690192177740269).

This could be related to the construction of the sources [here](https://github.com/owid/etl/blob/master/etl/steps/data/garden/ophi/2023-07-05/multidimensional_poverty_index.meta.yml): I created three different sources with the same name, but referring to different papers.

**Comment by larsyencken** [comment]
The layout of the footer is going to change with the new designs, so marking this as blocked until then
