### ISSUE TITLE
Investigate Cloudflare Images as an alternative to our `bakeDriveImages` baking step

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2485]
We currently bake gdocs images by pulling down the original versions from S3, resizing them multiple times, and uploading all the images to Netlify. 

This is an inefficient process because we do the resizing every single time, instead of caching the efforts anywhere which is protracting our deploy times.

But before we improve that, we'd like to check and see if [Cloudflare Images](https://www.cloudflare.com/products/cloudflare-images/) would be a better way to solve the entire problem.

This issue is an invitation for a team member to mess around with Cloudflare Images and try to answer the following questions:
- Approximately how much would it likely cost us to use in production?
- What would the Gdocs implementation look like?
- What would the WordPress implementation look like?
- How would it work with local development and staging environments?

If I'm not the one to do it, feel free to reach out to me to ask questions about the current baking process 👍 

Update 2024-03-12: At this point this is mostly a nice to have for us devs because the image workflow is pretty complicated and occasionally breaks in annoying ways. #3199 was a motivation to reopen this issue and we still think that this and the simplification of the codebase would be worth a few days of dev time.

**Comment by larsyencken** [comment]
Closing this for now, we can still investigate further later.

**Comment by ikesau** [comment]
We could do some nice things like content graph integration and GPT alt text if we started uploading images via the admin instead.

Technically these features could be implemented with Google Drive, but it would be more complex and annoying. Google Drive doesn't allow us to configure an event handler for file uploads (only per-minute polling), so the flows would become more complex for little gain.

We should evaluate all the important user stories for the image workflow to make sure the admin implementation handles them nicely. 

Here are some that I can think of:
- As an author, I want to be able to upload an image and see it in my preview article
- As an author, I want to be able to upload a new version of an image and trigger rebakes of the articles that use it
- As an author, I want to be able to search for images by filename and type
- As an author, I would like to be able to see where an image is used
- As an author, I would like to know that my featured images are the correct aspect ratio
- As an author, I would like to know that my source images aren't too large or too small
- As an author, I want uploaded images to have alt text automatically suggested when I upload a new image
- As an author, I want to be able to regenerate alt text when I upload a new version of an image
- As a reader, I want to be able to download the source image in a widely-supported file format (i.e. PNG or JPEG)
- As a reader, I want to load the smallest image for my display

**Comment by ikesau** [comment]
[Here's a datasette query showing all our posts with featured images with aspect ratios that are more than 0.1 off our target of 1.9](https://datasette-public.owid.io/owid?sql=SELECT%0D%0A++%22https%3A%2F%2Fourworldindata.org%2F%22+%7C%7C+p.slug+AS+url%2C%0D%0A++%22https%3A%2F%2Fourworldindata.org%2Fimages%2Fpublished%2F%22+%7C%7C+%28p.content+-%3E%3E+%22%24.featured-image%22%29+AS+featuredImage%2C%0D%0A++originalHeight%2C%0D%0A++originalWidth%2C%0D%0A++%28%0D%0A++++CAST%28i.originalWidth+AS+FLOAT%29+%2F+CAST%28i.originalHeight+AS+FLOAT%29%0D%0A++%29+AS+aspectRatio%0D%0AFROM%0D%0A++posts_gdocs+p%0D%0A++JOIN+images+i+ON+p.content+-%3E%3E+%22%24.featured-image%22+%3D+i.filename%0D%0AWHERE%0D%0A++--+ideal+aspect+ratio+is+1.9%2C+showing+all+images+that+are+more+than+0.1+away+from+that%0D%0A++ABS%28aspectRatio+-+1.9%29+%3E+0.1)

Not required for this feature, but it would be nice if we could design it in such a way that bulk updating all these images to ones with correct aspect ratios would be possible.

**Comment by larsyencken** [comment]
Closing this issue and moving this to the P&D project board: https://www.notion.so/owid/A-new-image-backend-d2a80049b8ce43a7abfa822c2d8c7c60
