### ISSUE TITLE
WP->Gdoc migration trips on unclosed WP comment tags

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#2487]
This issue has two parts. One is that there seems to be a wordpress page that either has an unclosed comment tag or where the parsing trips up. In either case, this throws an exception as [can be seen in this slack message](https://owid.slack.com/archives/C5JJW19PS/p1690243296624009).

The other issue is that we are process all wp posts in every run but at the moment the try catch block is outside the loop - this means that if there is an error, the posts that came after (by id) are not updated. This should be fixed first as it means none of the items after the failing ones are migrated every night.

**Comment by ikesau** [comment]
We're _pretty sure_ this is fixed 👍
