### ISSUE TITLE
Onboard data scientists to the changes to how we work

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#2494]
- [x] Do a presentation for the data and research team to show them the new metadata
- [x] Update the documentation for the new metadata fields on the [Notion page](https://www.notion.so/owid/2023-06-26-Proposed-metadata-structure-that-enable-data-pages-83b3602d12004796a2034fc870911137?pvs=4) of the metadata proposal
- [x] Record a short video showing where to find information, examples and what the new metadata gives you (once the data page preview is merged)

**Comment by larsyencken** [comment]
@danyx23 Would you call this done, or will you need another session once everything is merged?

**Comment by danyx23** [comment]
@larsyencken I extended this point a bit with two more checkpoints I'd like to do to call this done
