### ISSUE TITLE
⏩ Clean up old slide decks

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2502]
## Context

We keep slide decks at https://slides.ourworldindata.org/ and in the repo https://github.com/owid/slides. But many have become out of date.

## What

We would like to remove many of the out-of-date slide decks and redirect to the OWID homepage instead. For some, we would like to get an Internet Archive snapshot before removing them.

The list of slides to archive and to remove is here: https://docs.google.com/spreadsheets/d/1TLg80XuZqhqHKo3PgDkBoLW9h8qKl6-el0N5grEDqaI/edit#gid=0

**Comment by ikesau** [comment]
We should keep in mind that all of these will go away when we switch from Netlify.
