### ISSUE TITLE
New Gdoc type for administration/org pages

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2552]
For Gdoc document types, we currently have `topic-page`, `article`, and `fragment`

This mostly controls what the header of the page looks like, and also affects [some business logic throughout the site](https://github.com/owid/owid-grapher/pull/2545).

@CGiattino would like to make a job posting template in Gdocs that has the appearance of our [old job ads.](https://web.archive.org/web/20230306235835/https://ourworldindata.org/human-resources-manager)

The only way to get that style heading at the moment is to set `type: topic-page` in a Gdoc's front-matter, which we don't want to do in this case because it's not actually a topic page.

I suggest we add a new type, `organization` (or a better name)

This would:
- Have a grey banner like topic pages
- Be indexed in Algolia with a different content type
- Hide the citation, reuse, and bibtex sections (now partially covered by https://github.com/owid/owid-grapher/pull/2693)
- Need a subnav component (likely manual/explicit for now - e.g. `{ items: [title: "blah thing", url: "/blah-thing" ] }` as opposed to deriving it from metadata) 
- Need to be excluded from the atom feeds
- Included in sitemap

**Comment by CGiattino** [comment]
Any maybe these should be called "Utility" pages — that's what we call them on the [KPI Dashboard](https://owid-in-data.streamlit.app/KPIs?kpi=Home) e.g.

**Comment by danyx23** [comment]
@mlbrgl implemented a barebones version of this in cycle 2024.1. This does not yet include any subnav component but it is unclear if we really need this anyhow. Closing this issue now.
