### ISSUE TITLE
Show static chart while interactive chart is loading

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#257]
**NOTE**: testing and implementing this requires setting up Wordpress locally. We unfortunately don't yet have instructions and/or public resources to make this possible.

---

We currently serve server-generated static SVG charts on initial page load, so that users on slow connections can see the charts before all JavaScript loads and executes.

But, when the scripts load, they remove the static chart and replace it with a loading indicator while the data for the chart is fetched.

The phases roughly look like this:

![chart-loading-phases](https://user-images.githubusercontent.com/1308115/64704325-0a102280-d4a6-11e9-9af3-3bfeb8c36f38.png)
(Static chart on left, interactive on right)

Ideally, we should remove the middle phase where a loading indicator is shown without the chart. The static chart should be shown up until all dependencies for rendering the chart are ready and the interactive chart is successfully rendered, and then immediately swapped with the static chart.

Note that this is the behaviour we want for embedded charts – the thumbnails for those are rendered with the URL params considered. But for standalone charts the page thumbnail does not consider URL params (since we are a static site), so showing the thumbnail may be misleading... we will have to test it out.

Maybe the ideal solution is that the thumbnail should only be kept if it matches the query params, otherwise a loading indicator can be shown.

**Comment by danielgavrilov** [comment]
The phases have now changed (see https://github.com/owid/owid-grapher/pull/302) – we now load and show the chart title, subtitle & notes as soon as the chart metadata is loaded (it's always loaded first). Before it used to be the case that you see a loading indicator until both metadata & data are fully loaded. 

It would still be great to keep the preview (as long as the query params match) and seamlessly transition from preview to interactive chart without a loading state.

**Comment by andrewramacher** [comment]
Hey I was hoping to help with this project so I wrote the code for this feature and created a branch, but I am unable to push due to a permissions error. When running `git push --set-upstream origin replace-loading-chart-with-static` I get the error `ERROR: Permission to owid/owid-grapher.git denied to andrewramacher.` Is there another way I can go about uploading the fix?

**Comment by shaahmad** [comment]
Hey Andrew,

Thanks for reaching out. I will give you a call to handle this.

Thanks,
Shahid

**Comment by breck7** [comment]
I think the new behavior is good enough. Closing.
