### ISSUE TITLE
Stacked area charts should not be facetable by metric

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2577]
## Core Problem

In stacked area charts, we stack multiple indicators together. Whenever we do that, we've determined that that aggregation makes sense. But, if we facet by metric and stack across entities, it seems to not make sense.

For example:

- When the indicators use % as a unit, we cannot facet by metric (see [Slack example](https://owid.slack.com/archives/C03NV9Z3YSV/p1692913141364249))
- Stacking a mix of aggregates and countries on top of each other doesn't make sense (e.g. stacking France, Europe, and World means that France is counted three times, https://ourworldindata.org/grapher/above-or-below-extreme-poverty-line-world-bank?facet=metric&country=FRA~Europe+and+Central+Asia~OWID_WRL)

## Proposed Solution

Disallow faceting stacked area by indicator.

**Comment by larsyencken** [comment]
Another [example](https://ourworldindata.org/grapher/above-or-below-extreme-poverty-line-world-bank?facet=metric&country=Sub-Saharan+Africa~BGD) reported by Este in [Slack](https://owid.slack.com/archives/C46U9LXRR/p1697844233815379)

**Comment by danyx23** [comment]
@sophiamersmann can you write a follow up issue please? Thanks!

**Comment by sophiamersmann** [comment]
This issue has been resolved, with the exception of forbidding non-sensical stacking, which is transferred to [this follow-up issue](https://github.com/owid/owid-grapher/issues/3608)
