### ISSUE TITLE
Share menu should include 'Link'

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#258]
<img width="285" alt="Screenshot 2019-09-11 at 15 24 53" src="https://user-images.githubusercontent.com/1308115/64706026-cb2f9c00-d4a8-11e9-9139-968cff4cae26.png">

The share menu should include a 'Link' option for copying the URL of the interactive chart. This link is available by clicking on the chart title, but that's not obvious.

One option is that clicking on 'Link' automatically copies the URL to the user's clipboard, and we need to show some kind of notice that this has been done, otherwise users may think nothing is happening.

An alternative, less preferred option is to show an input field populated with the URL and having a copy button, though that wouldn't work so well to keep the menu clean and small.

**Comment by MarcelGerber** [comment]
In my testing on an iPad running iOS 13, https://clipboardjs.com/ worked flawlessly (https://github.com/zenorocha/clipboard.js). I guess it'll also work on other platforms then?

**Comment by danielgavrilov** [comment]
Hmm, possibly the issue was fixed in iOS 13! It didn't work on iOS 12.2:
- https://github.com/zenorocha/clipboard.js/issues/633
- https://github.com/zenorocha/clipboard.js/issues/625

I think it's fine to use the library, but also feels like a good idea to have a link/input field that shows the link and would work even if the library happens to fail. In general it's good to know what you're copying, though I haven't thought of a good design that would work even if the URL is quite long...

**Comment by willstott101** [comment]
I reckon it's fine to cut off a link, as long as focusing the textbox automatically highlights the full content. Users who don't understand how to navigate the link within the box, also probably don't understand anything in the link other than the domain name anyway (which also happens to be the only important part). ![image](https://user-images.githubusercontent.com/335152/77951560-28aefd00-72c2-11ea-975c-901076afcf9d.png)
