### ISSUE TITLE
Getting 502 errors from automated staging servers

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2585]
Builds for our automated staging servers started failing because of 502 errors like this

```
Error: Error fetching metadata from S3 for https://api-staging.owid.io/staging-site-use-nocache-in-admin/v1/indicators/650610.metadata.json: 500 Internal Server Error Error: 502 error from R2
--
  | at handleRequest2 (index.js:49:13)
  | at fetchS3MetadataByPath (/home/owid/owid-grapher/db/model/Variable.ts:437:15)
  | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | at async Promise.all (index 1)
  | at getVariableData (/home/owid/owid-grapher/db/model/Variable.ts:164:30)
  | at <anonymous> (/home/owid/owid-grapher/db/model/Variable.ts:179:23)
  | at async Promise.all (index 3)
  | at getDataForMultipleVariables (/home/owid/owid-grapher/db/model/Variable.ts:181:41)
  | at bakeGrapherToSvg (/home/owid/owid-grapher/baker/GrapherImageBaker.tsx:104:21)
  | at concurrency (/home/owid/owid-grapher/baker/GrapherImageBaker.tsx:175:24)
  | at async /home/owid/owid-grapher/node_modules/p-map/index.js:57:22
```

The problem is that our build is firing thousands of requests to R2 in a very short period of time. Optimizing it and rebaking only files that are needed would certainly help with this.

It doesn't happen every time. R2 seems to have good and bad periods when either all builds work or all fail.

I've confirmed that these errors indeed come from R2 and not from Cloudflare Worker in front of it. (Fallback redirects we're doing in worker aren't a problem either). Incidentally, this seems to always happen just to a single automated staging server, the others are fine.

We could try [binding R2 bucket to our worker](https://developers.cloudflare.com/r2/api/workers/workers-api-usage/#4-access-your-r2-bucket-from-your-worker) rather than getting data with fetch requests, but I'm not sure how will it affect performance or bandwidth.

**Comment by danyx23** [comment]
Hey @Marigold we think this issue is no longer relevant - if you disagree, please feel free to reopen!
