### ISSUE TITLE
Some charts are tagged with bulk import tags

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2621]
_from [slack](https://owid.slack.com/archives/C05PE883448/p1694019863859179?thread_ts=1694005153.514949&cid=C05PE883448)_

![Screenshot 2023-09-06 at 18 47 27](https://github.com/owid/owid-grapher/assets/13406362/74f7311a-bdba-44cf-8d4e-188faa86e866)

### Problem
Some charts are tagged with bulk import tags:
Literacy, Smoking, Land use, Malaria

Only datasets should receive bulk import tags.

### Clues

1. These bulk import tags have homonymous non-bulk import tags. For instance:
- Literacy (regular tag) https://owid.cloud/admin/tags/302
- Literacy (bulk import tag) https://owid.cloud/admin/tags/465

2. Malaria has more than one bulk import tag of the same name.

3. The [query that powers the tag selector widget](https://github.com/owid/owid-grapher/blob/59588867979043d460607270fc2c6d264a0cef64/adminSiteServer/apiRouter.ts#L2202-L2205) does currently exclude bulk import tags. Has the root cause been fixed but not the data?

### Charts tagged with bulk import tags (as of Sept 7 2023)
http://datasette-private/owid?sql=select+charts.id%2C+slug%2C+tags.name+as+tagName%2C+tags.id+as+tagID+from+charts%0D%0Ajoin+chart_tags+on+charts.id+%3D+chart_tags.chartId%0D%0Ajoin+tags+on+chart_tags.tagId+%3D+tags.id%0D%0Awhere+tags.%60isBulkImport%60+%3D+1
```
id,slug,tagName,tagID
216,global-malaria-deaths-by-world-region,Malaria,1480
300,literate-and-illiterate-world-population,Literacy,465
769,share-of-women-who-are-smoking,Smoking,917
771,comparing-the-share-of-men-and-women-who-are-smoking,Smoking,917
772,share-of-men-who-are-smoking,Smoking,917
773,share-of-adults-who-are-smoking-by-level-of-prosperity,Smoking,917
970,children-sleeping-under-treated-bednet,Malaria,1480
971,malaria-prevalence-vs-gdp-per-capita,Malaria,1480
985,land-use-over-the-long-term,Land Use,1445
1046,land-use,Land Use,1445
1210,share-of-the-population-with-basic-numeracy-skills-by-birth-decade,Literacy,465
1212,literacy-rates-of-younger-vs-older-population,Literacy,465
1214,ratio-of-the-literacy-rate-between-young-women-and-men,Literacy,465
1215,literacy-rate-of-young-men-and-women,Literacy,465
1304,piaac-mean-adult-numeracy-proficiency-2012-2015,Literacy,465
1305,numeracy-vs-literacy-skills-of-adults,Literacy,465
1306,numeracy-skills-of-adults-young-adults-and-adults,Literacy,465
1469,number-of-deaths-from-tobacco-smoking,Smoking,917
1513,students-in-grade-2-who-cant-read-a-single-word-ca-2015,Literacy,465
1807,smoking-and-secondhand-deaths,Smoking,917
1808,secondhand-smoke-deaths-by-age,Smoking,917
1809,smoking-deaths-by-age,Smoking,917
1811,malaria-death-rates-by-age,Malaria,1480
1821,incidence-of-malaria,Malaria,1480
1822,malaria-death-rates,Malaria,1480
1825,malaria-deaths-comparisons,Malaria,1480
1827,malaria-deaths-by-region,Malaria,1480
2247,mode-of-reporting-literacy-rates,Literacy,465
2248,literacy-rate-source-type,Literacy,465
2251,sales-of-cigarettes-per-adult-per-day,Smoking,917
2253,consumption-per-smoker-per-day,Smoking,917
2255,consumption-per-smoker-per-day-bounds,Smoking,917
2266,daily-smoking-prevalence-bounds,Smoking,917
2272,number-of-daily-smokers-gender,Smoking,917
2273,number-of-total-daily-smokers,Smoking,917
2335,literacy-by-years-of-schooling-us-1947,Literacy,465
2336,literacy-rates-vs-average-years-of-schooling,Literacy,465
2338,average-literacy-score-piaac-test-vs-national-literacy-rate-cia,Literacy,465
2470,historical-literacy-in-england-by-sex,Literacy,465
2471,estimated-historical-literacy-rates,Literacy,465
2617,cross-country-literacy-rates,Literacy,465
2671,taxes-as-share-of-cigarette-price,Smoking,917
2672,affordability-cigarettes,Smoking,917
2674,share-of-cancer-deaths-attributed-to-tobacco,Smoking,917
2675,enforcement-of-bans-on-tobacco-advertising,Smoking,917
2676,support-to-help-to-quit-tobacco-use,Smoking,917
2677,share-of-tobacco-retail-price-that-is-tax,Smoking,917
2705,literacy-rate-adult-total-dhs-surveys-vs-unesco,Literacy,465
```

**Comment by ikesau** [comment]
@mlbrgl was this cleaned up as part of the automatic tagging process, per chance?

If not, can we delete the bulk import tags?

**Comment by mlbrgl** [comment]
Not sure what fixed it, but the [query mentioned above](http://datasette-private/owid?sql=select+charts.id%2C+slug%2C+tags.name+as+tagName%2C+tags.id+as+tagID+from+charts%0D%0Ajoin+chart_tags+on+charts.id+%3D+chart_tags.chartId%0D%0Ajoin+tags+on+chart_tags.tagId+%3D+tags.id%0D%0Awhere+tags.%60isBulkImport%60+%3D+1) now returns an empty result set. 

Additionally, given 3. above:

> The [query that powers the tag selector widget](https://github.com/owid/owid-grapher/blob/59588867979043d460607270fc2c6d264a0cef64/adminSiteServer/apiRouter.ts#L2202-L2205) does currently exclude bulk import tags.

I think this can't happen anymore and we close the issue.

**Comment by mlbrgl** [comment]
Actually, [Fiona did it manually](https://owid.slack.com/archives/C05PE883448/p1694076640962029?thread_ts=1694005153.514949&cid=C05PE883448).
