### ISSUE TITLE
:tada: Update UI of `/admin/datasets` and `/admin/variables`

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2645]
Datasets and variables in Admin still show sources (in a very confusing way...). Now that we have origins, we should rethink what should be displayed in the UI. The most basic version is showing dataset / variable metadata (with 1:1 mapping to ETL metadata if possible) and origins.

Currently, all metadata fields are non-editable and must be changed in ETL. We could possibly take this even further, make them editable and commit updates to ETL to the grapher YAML file. (It's not clear how useful would it be, though. Editing on Github might be easier in the end).

**Comment by ikesau** [comment]
Duplicated by https://github.com/owid/owid-grapher/issues/2523
