### ISSUE TITLE
Negative "number of decimal places" doesn't work any more

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#2652]
## Description

We advertise that a negative number in the "number of decimal places" will round integers; however that feature doesn't work any longer.

![CleanShot 2023-09-25 at 11 43 42](https://github.com/owid/owid-grapher/assets/2641501/d8dd4038-94c3-41f1-a872-5b3e2ea6138d)

## Context

I'm pretty sure this hasn't worked ever since https://github.com/owid/owid-grapher/pull/1376 landed, over a year ago.

## Additional context

Brought up by @pabloarosado [on Slack](https://owid.slack.com/archives/C46U9LXRR/p1695303032840369).

**Comment by larsyencken** [comment]
We should remove the text in the admin for now.

For this feature, do we have any good examples where we wish we had it?

**Comment by danyx23** [comment]
We had a longer discussion on this topic here: https://github.com/owid/owid-issues/issues/918

**Comment by larsyencken** [comment]
Subsumed by #1851
