### ISSUE TITLE
Indicator-based explorers should accept column specifying the number of decimal places

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#2662]
## Core problem
Indicator-based explorers don't accept a column specifying the number of decimal places.

## Proposed solution
We can currently specify this from ETL, by defining `display: numDecimalPlaces`, but it would be convenient to be able to define this parameter directly from the explorer, as a new column.

## Context
This feature could be used, for example, in some of the indicators of [the animal welfare explorer](https://owid.cloud/admin/explorers/animal-welfare).

**Comment by ikesau** [comment]
@pabloarosado are you aware if we have any other display fields which we can overwrite in this way? 

Just trying to get a sense if there's any existing code we can append to or if this would be a new flow. 🙂

**Comment by pabloarosado** [comment]
Hi @ikesau, there are a few fields that may come from display and seem to be accepted by indicator-based explorers, namely:
* `tolerance`, `color` (likely to come from display),
* `name`, `description`, `unit`, `short_unit` (these may come from some other of the indicator's metadata fields).

I hope that helps.
