### ISSUE TITLE
Place x-axis tick labels consistently

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2690]
It would look a bit nicer if the outermost x-axis tick labels were also centered around the tick line. Check out the tick labels that are pointed to. The first one (1996) could be moved a little to the left and the last one (2022) could be moved a little to the right (such that both are centered around their resp. tick line)

This came up in the Grapher redesign bug bash.

Link: https://ourworldindata.org/grapher/eggs-cage-free

<img width="1202" alt="Screenshot 2023-10-03 at 10 44 22" src="https://github.com/owid/owid-grapher/assets/12461810/4d5e28c6-094b-4efa-bb25-1ba56ae6a5de">

**Comment by Anubhav-2003** [comment]
@sophiamersmann I would like to work on this issue. Thank you

**Comment by marcelgerber** [comment]
This is not quite as trivial as initially thought, since there are some cases where we want to keep the current behaviour to avoid overlapping or cutting off labels.

Way more context, and some screenshots of the issue, can be found in #2843.
