### ISSUE TITLE
Make it possible to copy data from our tables into a spreadsheet

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2691]
## Core problem

Some users like to copy the data from our tables into a spreadsheet. That doesn't work well at the moment (see screenshots)

## Alternatives

We do have a download option for that purpose.

## Screenshots

![Screenshot 2023-09-27 at 17 15 19](https://github.com/owid/owid-grapher/assets/12461810/505176ec-e7d2-48c4-8e77-854695aecfae)
![Screenshot 2023-09-27 at 17 17 00](https://github.com/owid/owid-grapher/assets/12461810/4215360c-5ad5-4009-b820-d151a73872b8)

**Comment by ikesau** [comment]
@danyx23 wanna test this on PC? Just excel and sheets I guess

**Comment by marcelgerber** [comment]
Just tested copying to Excel on macOS, that also works fine.

**Comment by ikesau** [comment]
Thanks! 🙂 

@sophiamersmann what's your screenshot from? Windows Excel?

**Comment by sophiamersmann** [comment]
Don't know. It's a screenshot that Max shared - I'll ask him

**Comment by danyx23** [comment]
@sophiamersmann I have windows and Excel, don't bother Max :)

This is what it looks like in Windows Excel rn:
![grafik](https://github.com/owid/owid-grapher/assets/2772449/52c650a2-0df0-4796-956f-fac30b8f0a87)

**Comment by danyx23** [comment]
Should we add a floating copy button like we do with code windows? Then we could just write the code that copies the whole table into the clipboard in a consistent format. Or add a more prominent copy button in the header?

**Comment by sophiamersmann** [comment]
This reminds me of this issue about copying a png to the clipboard (https://github.com/owid/owid-grapher/issues/1441). Maybe we should do both things in concert and add a "copy to clipboard" button in the share menu: If on the chart or map tab, the png is copied; if on the table tab, the table is copied.

**Comment by ikesau** [comment]
I think discoverability might be tricky there. What about intercepting the copy event and formatting it then?

https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

**Comment by marcelgerber** [comment]
> I think discoverability might be tricky there. What about intercepting the copy event and formatting it then?

It seems that the handler cannot read what the user copied, so if they only copied over a few rows and not the whole table, then it would also be tricky for us to match that behavior.
