### ISSUE TITLE
Categorical axes are wrong in tooltip hover

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2695]
Reported by @paarriagadap 

## Problem

In the chart [Human Development Categories](https://ourworldindata.org/grapher/human-development-index-categories) (id: 7210), we see that that we have an ordinal categorical axis. It should go from Low to Very High, but instead it goes from Low to Medium. This means that the axis does not correctly represent the full range of that variable.

<img width="1058" alt="Screenshot 2023-10-03 at 16 36 40" src="https://github.com/owid/owid-grapher/assets/36012/74f947e9-d1ef-4a89-96cf-b612966fcaf5">

☝️ Full chart for context

<img width="324" alt="Screenshot 2023-10-03 at 16 38 23" src="https://github.com/owid/owid-grapher/assets/36012/ed84b0e3-2516-4c4b-aedc-3de61b9b0438">

☝️ Problematic axis label on hover

## Prevalence

Unclear whether other similar charts have this problem

**Comment by larsyencken** [comment]
@samizdatco Do you have any insight as to where the problem might be arising?

**Comment by samizdatco** [comment]
> @samizdatco Do you have any insight as to where the problem might be arising?

Just confusion on my part about how to make sense of the custom color scheme fields in the config (and particularly how to find the 'max' value that's actually present in the data):
<img width="310" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/ba0240a8-1d0b-4e0a-aad9-a084bcf2a0d3">

**Comment by marcelgerber** [comment]
Don't despair, Marcel's got you covered!
