### ISSUE TITLE
country selector: limit options surfaced to the user

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2704]
## Core problem
In some charts, we want to limit the entities that the user can select from.

## Context
Sometimes, we plot more than one indicator together. It can be that there is missing data for some of the indicators for some entities, and hence we don't want to show data for that entity. 

For instance, in the joint plot of `Population` vs `GDP`, it could be that `GDP` for Holy See is unavailable, but `Population` is. In that case, we would prefer not to allow users to choose "Holy See" (because the chart would only show one of the relevant indicators: `Population`).

This was raised by Saloni here: https://github.com/owid/owid-issues/issues/1217#issuecomment-1748390214, in the context of a line chart that plots both `cohort life expectancy` and `period life expectancy` to compare them. Demo of the problem:

https://github.com/owid/owid-grapher/assets/18101289/b3f08a25-5f57-4132-851e-355c3a3d0b5e

## Proposed solution
It would be nice to have some flexibility in choosing the entities that are surfaced to the users. Maybe something similar to what we have for "Data to show" section, where we select the countries selected by default: 

<img width="520" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/0c9f8de1-de25-4d84-a94b-e6182b53fdc4">

And (or) we could have an option (a checkbox?) with something like "show only entities that have data for all indicators shown in the chart".

**Comment by sophiamersmann** [comment]
Is the Missing data section visible in the Data tab? If yes, does that solve the issue?

<img width="473" alt="Screenshot 2023-10-05 at 13 24 26" src="https://github.com/owid/owid-grapher/assets/12461810/6903dde3-b8a2-4f2d-af36-0edae388314b">

**Comment by lucasrodes** [comment]
Hi @sophiamersmann!
I tried setting that option, but it does not get there.

It now recognises that there is missing data (one of the indicators is missing), but it still shows the entity in the selection menu:

<img width="888" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/e43d0199-70c7-4af5-809f-9797c027e0ab">

**Comment by sophiamersmann** [comment]
Ahh, I understand. This is an annoying bug that is tracked [here](https://github.com/owid/owid-grapher/issues/1341). We really want to fix it! (And will hopefully do so soon-ish)

I'll close this issue in favour of https://github.com/owid/owid-grapher/issues/1341. Thanks for reporting!
