### ISSUE TITLE
SVG is not properly escaped and conversion to png raises an error

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2707]
## Description

SVG of this [chart on plastic waste](http://staging-site-mojmir/admin/charts/7221/edit) contains the following tag
```
<text x="606.129" y="497.23305925518" font-size="11.700000000000001" fill="#aaa"><1%</text>
```
the text contains `<1%`, but `<` is not escaped and we get an error when opening SVG or trying to convert it to PNG. This **breaks baking**.

## Expected behaviour

It should be escaped and SVG should be valid.

## Steps to reproduce

Download SVG from [this chart](http://staging-site-mojmir/admin/charts/7221/edit) and open it in the browser.

## TODO

* [ ] undo this [hotfix in ETL](https://github.com/owid/etl/commit/8a431b38a65570b4da81650630df6a9ff12e7ad5)

**Comment by danyx23** [comment]
Fixed via #2709
