### ISSUE TITLE
Tooltip content not nicely formatted when variable name is long and a time notice is displayed

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2714]
The tooltip content is weirdly formatted when the variable name is long and a time notice is displayed.

## Steps to reproduce

1. Go to https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&country=BHR~BRA~CHL~FRA~DEU~HUN~IND~ISR~SRB~TUR~GBR~USA~URY~ESP~ITA~ARE~MEX~RUS&pickerSort=desc&pickerMetric=population&hideControls=true&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false&Metric=People+vaccinated+%28by+dose%29
2. Hover over the "Italy" bar
3. Note that the tooltip content is not formatted nicely

## Screenshots

<img width="971" alt="Screenshot 2023-10-09 at 16 11 57" src="https://github.com/owid/owid-grapher/assets/12461810/d08ca53e-ca51-46e3-ac2c-12b506656a60">

**Comment by ikesau** [comment]
@samizdatco is this just a matter of some max-widths here and there? famous last words but that seems simple enough?

**Comment by sophiamersmann** [comment]
Sure!

**Comment by parthiv360** [comment]
Hey @sophiamersmann can you please suggest how to traverse to this page in localhost. Thank you

**Comment by ikesau** [comment]
If your [localhost route](http://localhost:3030/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&country=BHR~BRA~CHL~FRA~DEU~HUN~IND~ISR~SRB~TUR~GBR~USA~URY~ESP~ITA~ARE~MEX~RUS&pickerSort=desc&pickerMetric=population&hideControls=true&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false&Metric=People+vaccinated+%28by+dose%29) isn't loading for you (or any explorer, for that matter) you might be missing https://github.com/owid/owid-content 

Clone it into the same directory that contains this repo and then restart your local server 🙂

**Comment by parthiv360** [comment]
Okay Thanks.

**Comment by parthiv360** [comment]
Hey @ikesau I have gone through this issue and was trying to correct it. I have tracked the pages were the potential changes need to be done. 

I have a confusion that do I need to change the container size to adjust the time or adjust the time or something keeping the size of container fixed.

Thank you.

**Comment by parthiv360** [comment]
Hey @sophiamersmann I have raised a PR. Can you please review it and suggest any changes required? Thank you.
