### ISSUE TITLE
Improve Gdocs index page searching

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2727]
Now that we have 200+ Gdoc articles, we should improve the index page view a little.

Check with the authors if they'd prefer substring matching to fuzzy matching, and add some more facet options (published/unpublished, author, topic)

![image](https://github.com/owid/owid-grapher/assets/11844404/d66584ee-0889-40d3-9ea2-16c3f88f213d)

**Comment by danyx23** [comment]
@ikesau this was starting to annoy me too much so I did a small version in #2779

**Comment by larsyencken** [comment]
Ike, from your perspective is the new change good enough for now?

**Comment by ikesau** [comment]
I'd like to add a facet for published status still 🙂
