### ISSUE TITLE
Video archie component

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2728]
For our upcoming Grapher redesign article, we want to include some animated content to showcase the new UX, but we currently don't have a way of publishing the type of content.

We should add a `video` tag that allows us to publish mp4 videos. This is preferable to gifs because they come with native play/pause controls (which is important for WCAG) and smaller file sizes.

The videos should be hosted in Drive and mirrored somewhere during baking.

**Comment by marcelgerber** [comment]
I think this is done now? #2731
