### ISSUE TITLE
ScatterPlot: Extra line in legend if no colour legend is displayed

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2735]
## Description

In scatter plots, the colour legend and the size legend are separated by a line. If the colour legend is missing, the separator line is not needed. It shouldn't be displayed.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/marriage-rate-1990-vs-2010
2. Note extra line above size legend

## Screenshots

<img width="744" alt="Screenshot 2023-10-11 at 10 14 23" src="https://github.com/owid/owid-grapher/assets/12461810/e9ae5b0f-5ab2-486d-9cf8-b9a97db65dc4">

**Comment by Anubhav-2003** [comment]
Hey @sophiamersmann I want to work on this issue. Thank you.

**Comment by sophiamersmann** [comment]
Hey @Anubhav-2003, you're welcome to work on this!

**Comment by Anubhav-2003** [comment]
@sophiamersmann I have solved the issue. Please assign me so that I can officialy create a PR. Thank you.

**Comment by marcelgerber** [comment]
Hi @Anubhav-2003, you're free to create a PR already, no need for us to assign you.

Just mention this issue (i.e. #2735) in the PR description and we'll know what it is that you're fixing. Thank you!

**Comment by Anubhav-2003** [comment]
@sophiamersmann Kindly review my PR. Thank you.
