### ISSUE TITLE
Project: CloudFlare Pages post-migration

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2751]
## Background

We have just migrated our site from Netlify to CloudFlare Pages, in order to reduce costs, kill tech debt, and lean more into CloudFlare's awesome ecosystem.

## Goal / this cycle

Clean up our migration and ensure that when the Netlify contract ends we are fine. Remove Netlify code from our stack.

## Rabbit holes / open questions

<details><summary>Small sites - NICE TO HAVE</summary>
<br>

- We have small sites that we keep on Netlify, do we need to migrate them too?
- We believe that small sites are going to be fine on our free Netlify plan
  - Provided we can verify that, we can probably leave them
</details>

<details><summary>Netlify functions - IN SCOPE</summary>
<br>

- We have two Netlify functions that need migrating to CloudFlare (donations & feedback)
- We have agreed that they are in scope
</details>

<details><summary>Old staging servers - OUT OF SCOPE</summary>
<br>

- We have old staging servers that use Netlify
- We would tear them down, but they are the only ones that have a running Wordpress admin
- For that reason, we'll leave them unless we can get the Wordpress admin working on new staging servers
  - That's beyond the scope of this cycle
</details>

<details><summary>Post-contract Netlify plan - LARS TO CLARIFY</summary>
<br>

- We need to understand more clearly what our Netlify situation will look like after our contract ends
- Lars will clarify the contract details
</details>

## Issues

(Marcel to clarify)

**Must have**

- [x] Re-engineer redirect situation to keep us below the limit of 2,000 static redirects https://github.com/owid/owid-grapher/pull/2826
- [ ] Migrate functions to CloudFlare Pages
  - [ ] Migrate donations function
  - [x] Migrate feedback function https://github.com/owid/cloudflare-workers/pull/16
- [x] Migrate https://covid.ourworldindata.org https://github.com/owid/covid-19-data/issues/2819
- [x] Migrate https://slides.ourworldindata.org/
- [x] Migrate https://global-change-data-lab.org
- [x] Migrate https://africaindata.org
- [x] @larsyencken: clarify post-contract situation with Netlify
- [x] #2819 

**Nice to have**

- [x] Remove existing Netlify deploy code #2781
- [ ] Enable preview deploys
- [ ] https://github.com/owid/owid-grapher/issues/2502
- [ ] Set up `owid-static` again

**Comment by larsyencken** [comment]
Just a heads up, Daniel and I are chatting to Netlify tomorrow, we'll clarify anything we need to then.

**Comment by marcelgerber** [comment]
This is now done, and we're almost fully off of Netlify.

The one exception is that the `owid-donate` Netlify function is still running on Netlify. This decision was based on the assumption that the function would be deprecated after the donor page redesign, but with changes in that project it now looks like v1 of the donor page redesign will still rely on a worker of some sort. So, it might be worth reconsidering this in the future.

I plan to work on #2502 next week (waiting for some feedback from Natasha), which would then mean that almost all of the things on this ticket got finished.
