### ISSUE TITLE
Data pages: fix rendering and wording issues

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#2755]
* [x] Following [Ed's suggested](https://owid.slack.com/archives/C0193RW5E2J/p1695720931545929?thread_ts=1695717004.876169&cid=C0193RW5E2J) (it seems we already decided about it at some other time in the past) scatter plots should not show population in the footer of the chart, but they should show population in the sources tab (in "Data published by").
* [x] The heading of the text section "What you should know about this data" should change to something less strong when showing something other than the description_key field and be hidden if we have no text.
* [x] Bullet points from description_key are not picked.
* [x] I have the text `How the producer of this data - undefined - describe this data?`
* [x] Collapse snapshot origins into a single one when they refer to the same data product.
* [x] The text in the full citation is faded too early (see screenshot in comments below)
* [x] Instead of mentioning Twitter (in "How to cite this data"), we should say "social media".
* [x] We should not say "OWID" anywhere (as it happens in "How to cite this data").
* [x] It seems like the link we provide in the full citation is the download link. I suppose it should instead be the main url of the source.
* [ ] ~Also, should we include URLs? (e.g. What happens if it's very long and messy? How to ensure links won't break?)~
* [x] We should show the date of next expected update. This should be based on `dataset.update_period_days` and the current date (if it's passed, increase it by a month).
* [x] Currently, the short and full citation seem to use the format "Producer 1; Producer 2" and "Producer, data product title; Producer 2, data product title 2". Maybe they should instead use the indicator's `attribution_short` and `attribution`.
* [x] Change the wording of "processed" or "adapated" by under the chart to "with minor/major processing by Our World In Data"
* [x] The slugify function that creates links from topic tags (so that clicking the topic tags in the top right links to the topic page) needs to be able to handle & and ' characters
* [x] If the time range for an indicator includes negative years (like our long run population data does), then show `10000 BCE to 2020 CE` instead of `-10000-2020`
* [x] Last updated date should render as a formatted date instead of a raw date string
* [x] If there are multiple producers, use "[Main source] and other sources - Processed by Our World in Data"

### The following issues will be fixed by switching to a new markdown engine

This work is tracked in #2758 and will fix these issues that were tracked here:
* [x] The processing description is not rendered properly (e.g. bullet points are put together without line breaks).
* [x] Jump lines and bullet points are not respected in the content of the same section (Note: this will need a new markdown renderer)

### Other work
Another point that was tracked here is implementing the new designs for the "About this data" section below the chart. It was promoted to the tracking issuse #2733
* [x] Wait for new designs for the section below the chart that is more flexible for when descriptionShort and descriptionKey are missing, then implement them

**Comment by paarriagadap** [comment]
Found here https://github.com/owid/etl/pull/1790:

- [ ] When `presentation.attribution_short` is not defined, one section becomes `How does the producer of this data - undefined - describe this data?`. There should be fallbacks, like `origins.producer`
- [ ] When using both `presentation.title_variant` and `presentation.attribution_short` with the same name they are shown repeated in the title of the data page, as in
<img width="601" alt="image" src="https://github.com/owid/owid-grapher/assets/63430031/458bcf85-7b4b-473d-876e-3bd9c19e4e31">

**Comment by danyx23** [comment]
@paarriagadap On the first point of your comment: I don't think we can very well fall back to producer here - there may be several origins and it would be unclear where the text comes from. Maybe we could fall back to producer if there is only a single one? Should we fall back like this maybe? `presentation.attribution_short -> origin.attribution_short -> origin.producer` but the origin related ones only if it is a single origin?

On the second point - I can deduplicate this but I would argue that having the same text here is pretty weird. V-Dem should probably only be the attribution_short in this case and title_variant empty?

**Comment by paarriagadap** [comment]
Hi @danyx23, sorry for replying late. Yes, that sequence makes sense.

Regarding the second point, it was only a migration/conversion confusion from json, so there's nothing to change there. Thanks!
