### ISSUE TITLE
Data table: Separator lines have gaps sometimes

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2767]
## Description

Small visual glitch in data tables where sometimes segments of vertical separator lines are missing.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/maddison-data-gdp-per-capita-in-2011us-slopechart?tab=table
2. Note that some of the vertical separator lines have gaps (see screenshot)

## Screenshots

<img width="739" alt="Screenshot 2023-10-16 at 09 57 02" src="https://github.com/owid/owid-grapher/assets/12461810/c4f71f22-2f21-4d48-88e8-f09327f8735a">

**Comment by parthiv360** [comment]
Hey, @sophiamersmann  can you please assign this issue to me? Thanks a lot.

**Comment by sophiamersmann** [comment]
Hey @parthiv360, you're welcome to work on this!

**Comment by parthiv360** [comment]
Hey @sophiamersmann , during the local set-up of owid-grapher repository via vs-code dev-container, I could set up the tmux terminals containing all the panels. But opening the localhost 3030 shows nothing after that, and going to pane 0 shows this output. Thank you.
![Screenshot from 2023-10-19 21-51-32](https://github.com/owid/owid-grapher/assets/78601801/de3caee9-7abf-46e4-a4ad-bf200ee36c80)

**Comment by parthiv360** [comment]
Hey @sophiamersmann , I have been able to locally set-up the source code. Can you please assist on which code-files do we need to make changes? Thank you

**Comment by parthiv360** [comment]
Hey @sophiamersmann I have raised a PR for this issue. Please review. Thanks
