### ISSUE TITLE
colours are wrongly assigned for each continent

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2770]
## Description

The"Continents" colour scheme is not working for [this chart](https://owid.cloud/admin/charts/7249/edit).

## Expected behaviour

We should assign the correct colours to each continent's curve.

## Steps to reproduce

1. Go to https://owid.cloud/admin/charts/7249/edit
2. Click on "Customize" tab.
3. Go to "Color scheme" section
4. Select "Continents" scheme.

## Screenshots
Colours are wrongly assigned.

<img width="1517" alt="image" src="https://github.com/owid/owid-grapher/assets/18101289/7a960eaf-429b-4542-8387-2b1641f6636d">

**Comment by marcelgerber** [comment]
Ah, this is probably a misunderstanding of how these work, which is fair enough.

The "Continents" color scheme specifies the colors we should use for continents, but it doesn't have any knowledge about which color to use for which world region.
If the Continents are sorted alphabetically (e.g. in a scatterplot) then that usually works fine by default, but if the continents are in a random order then the colors will be assigned pretty much at random.

I think what you're asking for is pretty much #2297, and also related to #1673.
