### ISSUE TITLE
Always set `tab` as query param in embed code

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2805]
## Description

- The embed code we offer to users (see screenshot below) sets the iframe's source to the current URL
- But the current URL relies on defaults
    - For example, when the chart is configured to be the default view, then the canonical url without query params shows the chart; if the map is configured to be the default view, it shows the map
- As a result, if an author changes the config of a chart, embeds on foreign sites might change unexpectedly; for example, we encountered an issue where Jason embedded chart views, that silently changed into map views when authors changed the config

## Expected behaviour

~Don't rely on defaults for query params when constructing an embed code.~

Always specify the `tab` query param in the URL that is included in the embed code.

## Screenshots

<img width="737" alt="Screenshot 2023-10-19 at 14 53 58" src="https://github.com/owid/owid-grapher/assets/12461810/d4fe4aa3-a400-4479-b6f8-ae9aa4733418">

**Comment by danyx23** [comment]
I think the strong version that you describe above is not actually desirable - most of the time we *do* want embeds to follow along with changed defaults. The shown tab is a special case though, so I think  I'm in favour of the small version of just putting the tab in the embed code always

**Comment by armughan11** [comment]
Hi @sophiamersmann / @larsyencken is this still available? Happy to work on this!

**Comment by sophiamersmann** [comment]
Hey @armughan11, sure, you're welcome to work on this.

**Comment by armughan11** [comment]
Thanks, will be creating a PR soon :)
