### ISSUE TITLE
Tables do not respect tolerance and show misleading data

### ISSUE THREAD

**Issue by CGiattino** [owid/owid-grapher#2831]
Below is Charlie's originally reported issue but we have since found that the problem is actually quite a bit worse and more urgent. In the [Objects launched into space chart](https://ourworldindata.org/grapher/yearly-number-of-objects-launched-into-outer-space?tab=table) there is no tolerance but every country that has had an object launched into space in any year is shown with a value of one in 1957. Clearly we should fix this quickly to only show values if they are within the tolerance range (or only at the exact year if tolerance is not set or 0)

## Description

The year tolerance is not being enforced for tables, even when it's set for that indicator (on the Grapher admin under Basic > opening the drop-down for that indicator). When the tolerance has not been set manually, it would be useful to have a sensible default.

As you can see in the screenshots below, this makes it so that country-years are shown in the table when they are hundreds or even thousands of years different from the year shown in the table column.

## Expected behaviour

Authors should be able to set the tolerance in the Grapher admin of which years should be shown if the target year is missing. When it's not set manually, there should be a sensible default tolerance value — but it's important to ensure that the default doesn't cause problems of its own.

Country-year values outside of the tolerance range should not be shown in the table (nor should associated "Absolute" and "Relative" change be shown for these outside-tolerance values)

## Steps to reproduce

Example charts:
- https://ourworldindata.org/grapher/population?tab=table
- https://ourworldindata.org/grapher/maternal-mortality?tab=table

## Screenshots

![image](https://github.com/owid/owid-grapher/assets/7489781/2cea5699-64f3-4afb-9383-3c0a15afdc4a)

![image](https://github.com/owid/owid-grapher/assets/7489781/d3473192-6229-4eec-ae13-100b148bf881)

![image](https://github.com/owid/owid-grapher/assets/7489781/6fc5a308-5ebf-4ec9-a0e0-9e51e00da5a8)

**Comment by danyx23** [comment]
I just realized that the issue is quite a bit worse - if no tolerance is set, the table shows data with tolerance matching indicators.

On the [objects launched into space chart](https://ourworldindata.org/grapher/yearly-number-of-objects-launched-into-outer-space?tab=table) there is no tolerance but we show the closest value (1) in the first year (1957) for every country
