### ISSUE TITLE
Scatter plot: y-axis label is not perfectly centered

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2850]
## Description

The y-axis label is not perfectly centered in scatter plots (and other chart types?)

## Screenshots

Example: https://ourworldindata.org/grapher/infant-mortality-by-sex

![infant-mortality-by-sex (2)](https://github.com/owid/owid-grapher/assets/12461810/0ad045b8-c6a8-47c0-b1b7-49885e37b5c2)

## Additional context

Might apply to other chart types as well.

**Comment by parthiv360** [comment]
Hey @sophiamersmann, I have worked on this issue and have solved it. Can I raise a PR?

**Comment by parthiv360** [comment]
Hey @sophiamersmann  I have raised a PR for this issue. Can you please review this. Thank you
