### ISSUE TITLE
Index our content with Algolia at deploy time

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2852]
## Problem

Our Algolia setup currently does a bulk reindex once a week, due to cost/quota considerations.

## Impact

- Work that we publish and advertise can't be found on our search -- it is too new
- We lose the ability to iterate on and improve our search, e.g. by QA'ing at the time something goes how whether it is indexed the way we would like it to be
  - Over time this reduces the quality of our site search from where it could be

## Proposal

Algolia has multiple synchronisations strategies, including full-index updates (which we use) and the capability to update [individual documents](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/in-depth/the-different-synchronization-strategies/#:~:text=Whenever%20you%20add%2C%20update%2C%20or,of%20the%20record%20to%20update.) in the index.

We should switch to a document update strategy, which would allow our work to be indexed live as it goes out.

**Comment by marcelgerber** [comment]
This is still unsolved for charts and explorers.
