### ISSUE TITLE
Data tables appear to be empty for charts with sparse data

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2876]
## Description

- [We recently made Grapher's data table respect tolerance](https://github.com/owid/owid-grapher/pull/2859) (prev. tolerance was essentially set to +/- infinity for data tables in range mode)
- As a result, we often show empty cells where previously we would have showed a value from another year
- This is usually ok but if dealing with sparse data, the default table view might be completely empty, and it is quite difficult to "find" a data value using the time slider
    - We sometimes have weekly/monthly data that is encoded as daily data (because there is no other way currently) – such data is by definition very sparse

## Expected behaviour

The data table view should be useful for all charts, including charts with sparse data.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/covid-vaccine-by-age?tab=table
2. Note that the default view of the table is empty

## Screenshots

<img width="722" alt="Screenshot 2023-10-30 at 12 16 17" src="https://github.com/owid/owid-grapher/assets/12461810/9b52d00f-10cc-4dc6-a77d-48dbf609e083">

## Additional context

It might be better to solve this issue on the data side, i.e. set appropriate tolerance values when necessary.

**Comment by danyx23** [comment]
Decided that since you can set tolerance, this is probably not worth the effort rn (given that covid is also less important than it used to be)
