### ISSUE TITLE
SlopeChart: Entities without plottable data offered for selection

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2878]
## Description

- Selecting "Germany" in [this slope chart](https://ourworldindata.org/grapher/child-mortality-1960-vs-latest-slope?country=~DEU) does nothing
- Looking at the underlying data, Germany doesn't have data for the selected start and end year, which means that we can't draw a line, hence there is nothing to highlight
- If dragging the start time handle to the right, at some point Germany does have data and the chart highlights Germany appropriately

- The chart is also in a weird state if nothing is highlighted although it should be. The lines are coloured, but the legend is greyed out.

## Expected behaviour

Maybe we could jump to the closest start/end years with data?

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/child-mortality-1960-vs-latest-slope
2. Select Germany
3. Note that nothing is highlighted
4. Set the start time handle to 2000
5. Note that Germany is highlighted now

## Screenshots

<img width="817" alt="Screenshot 2023-10-31 at 16 38 20" src="https://github.com/owid/owid-grapher/assets/12461810/75e5f944-dd95-4097-88cc-dd3c0354f51a">

<img width="817" alt="Screenshot 2023-11-01 at 09 24 14" src="https://github.com/owid/owid-grapher/assets/12461810/aad86692-6030-4449-8372-bcece7765802">

## Additional context

- Likely also happens for scatter plots (but I haven't checked)

**Comment by danyx23** [comment]
Discussed this today in the data viz meeting - it probably would be best if all lines are drawn in gray if the current selection is invalid for a given time range. This would also fit with the color legend which is grayed out in this case.

**Comment by sophiamersmann** [comment]
Exreme case of the same bug: https://ourworldindata.org/grapher/share-of-total-deaths-in-both-sexes-aged-all-ages-years-that-are-from-cardiovascular-diseases
