### ISSUE TITLE
Make details on demand easier to maintain

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2882]
## Background

We've been using Dods a lot now and like them. The current solution is based on a single, special DoD document that contains all terms (~360 or so as of June 2024). 

## Problems

Having all of these in one GDoc and not having any admin UI support for them comes with a few downsides:
- There is no support for structuring DoDs into groups by topic
- There is no visibility into how many views different DoDs get, which makes it hard to prioritize which ones to tweak
- Conceptually there is a problem that only a single person should be working on any one document at any time and hitting publish. For most GDoc articles this is not a problem but for the big DoD document with lots of small pieces of content we could actually run into a case where two people edit the document simultaneously and one person hits publish and thus publishes an unfinished DoD the other person was editing.
- There is no clear concept of ownership - probably topic groupings will help with that but we could also go further and have explicit authors for each Dod.

### ⭐ Quick and easy

- [x] Ensure you can have headings in the DoD document and that they are stripped in `dod.json`
- [ ] #3757
- [x] Add analytics for DoDs
  - [x] Add a new show event for DoDs
  - [x] Visualise show events
- [ ] Improve clicks explorer to make time comparisons easier (see: [Notion](https://www.notion.so/owid/Clicks-explorer-add-other-time-comparisons-66e8e13386db49dabb5e373336d7be10))
- [ ] ~~(optional) Add an optional author field for coordination~~

### More elaborate solution 

- Change the internal one document approach to a new DoD document type of which you could have multiple, e.g. per topic
- Create a new admin space where you search for Dod terms and open the correct doc
- In this view also show uses of DoD terms and aggregated pageview counts

**Comment by danyx23** [comment]
We chatted about this and it seems that the main problem that we want to alleviate is that publishing the one DoD doc is problematic (others might be in the middle of editing in another place).

One solution to that problem would be to change the system so that instead of one "hardcoded" id that is the DoD document we would create a new `type` (that should be visible as such in the GDocs admin) so that we can have a handful of DoD docs (e.g. one per topic area).

**Comment by ikesau** [comment]
Also see: https://github.com/owid/owid-issues/issues/1251

**Comment by rakyi** [comment]
We added [analytics to track usages of DoDs](https://owid.slack.com/archives/C014N17DHEC/p1718095537869489).

**Comment by larsyencken** [comment]
Closing this one as done, and tracking the two follow-up issues instead.
