### ISSUE TITLE
When deleting content (WP/Gdocs/charts), set up a redirect to ensure immediate inaccessibility

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#2896]
Cloudflare can cache content for a while after it is no longer part of our bake. If we want to ensure that content is no longer reachable immediately after we delete it we should make sure to set up redirects from the old slug to the homepage or a better redirect target.

## Original problem description

We recently made some old job postings private in Wordpress, but they did not get removed from the bake.

e.g. [Data analyst](https://ourworldindata.org/data-analyst-econ), [Comms manager](https://ourworldindata.org/communications-outreach-manager-q4-2023)

## Expected behaviour

When you change the visibility of a post, it should be excluded in the next bake.

/cc @CGiattino

**Comment by Marigold** [comment]
[Data analyst](https://ourworldindata.org/data-analyst-econ) returns 404, but I'm not sure what's going on with [Communication manager page](https://ourworldindata.org/communications-outreach-manager-q4-2023). The file is not in dist anymore and [dev page](https://37c62d4e.owid.pages.dev/communications-outreach-manager-q4-2023) returns 404 too, but it still shows up in https://ourworldindata.org/communications-outreach-manager-q4-2023.

I've found [some mentions](https://community.cloudflare.com/t/pages-how-long-do-removed-files-stay-alive/399142) that deleted files might stay in cache for 7 days. They mention it in [their docs](https://developers.cloudflare.com/pages/platform/serving-pages/#asset-retention) too

> Asset retention
> We will insert assets into the cache on a per-data center basis. Assets have a time-to-live (TTL) of one week but can also disappear at any time. If you do a new deploy, the assets could exist in that data center up to one week.

**Comment by larsyencken** [comment]
The answer there was that if we want to delete the page and have it happen immediately, we have to do our own redirect to a 404 page.

**Comment by rakyi** [comment]
I started working on this, hoping that [purging a single file](https://developers.cloudflare.com/cache/how-to/purge-cache/purge-by-single-file/) will work, but didn't get to try it, yet. It requires a real deployment with a custom URL to get a proper zone ID instead of just using https://pages.dev.

**Comment by marcelgerber** [comment]
> It requires a real deployment with a custom URL to get a proper zone ID instead of just using [pages.dev](https://pages.dev).

Feel free to set up the `owid-staging` project (or a new one, if you feel like that's gonna make things easier) behind a `owid.io` domain, e.g. `pages-staging.owid.io`.
