### ISSUE TITLE
viz: table sorting of non-mappable entities

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2902]
## Core problem
In a chart, when sorting the rows by a column, the rows corresponding to _non-mappable entities_* are not very visible to the user.

*non-mappable entity here refers to an entity not mappable in OWID charts. I'll use this name, but probably we should use a better one.

## Context
It might be hard for a user to get the information that some non-mappable entities have specific values. This is because these are at the very bottom of the table view. Watch the demo below for a deeper walkthrough of the issue.

https://github.com/owid/owid-grapher/assets/18101289/09653602-a514-45dc-a333-e6d39e8c72f8

## Proposed solution
Marwa proposed something like [combining the sorting](https://owid.slack.com/archives/C5BDCB2R3/p1699358075780119?thread_ts=1699357589.069139&cid=C5BDCB2R3) of mappable and non-mappable entities.

I think something like the following could work:

|                | indicator |
|----------------|-----------|
| Mappable A     | 10        |
| Mappable B     | 9         |
| Mappable C     | 9         |
| Non-mappable A | 8         |
| Mappable D     | 7         |
| Non-mappable B | 3         |
| Mappable E     | 0         |

This should have some signal to differentiate mappable from non-mappable containing rows. E.g. rows with mappable entities should be more prominent, bolding or some icon. In addition, the user could have a checkbox to "filter non-mappable entities" or "show also non-mappable entities" to have more freedom on what is shown in the table.

**Comment by danyx23** [comment]
Discussed this in data viz - Christian suggested that we could have the "Other" separator row be sticky at the bottom until it scrolls into view (at which point it would scroll and then be sticky at the top). It should also be clickable to be able to jump to this section.

**Comment by sophiamersmann** [comment]
Closing this as it would be solved by https://github.com/owid/owid-grapher/issues/3335
