### ISSUE TITLE
Lightning deploys cause broken pages

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#2906]
On Wed, Nov 8 2023 in the morning, Marcel realised that the topic page for child mortality was broken (see https://a42dfb10.owid.pages.dev/child-mortality). The reason seems to be that the related items in the content graph are not correctly filled into the context of the page and then the charts (and images?) are unavailable when baking and the page is then rendered in a broken state.

Until this is fixed, Marcel disabled lightning deploys for prod on buildkite by [commenting out the part of the scripts](https://github.com/owid/owid-grapher/commit/ab2b183b166d808f034d245ff8bb3061ed0aa583) that runs lightning deploys for buildkite.

Apart from fixing the concrete issue that caused this, I think we should do two additional things:
- Make sure that topic page bakes on prod fail more easily (no charts is very likely to be an error on a topic page?)
- Add a test suite that can verify that the result of a full bake of selected pages and a lightning bake lead to identical results

**Comment by marcelgerber** [comment]
What was happening here, in a nutshell, is that there are two code paths to bake a gdoc.

`bakeGDocPosts` is used by "full" deploys, and it populates properties of the gdoc like `gdoc.linkedDocuments`, `gdoc.imageMetadata`, etc.

However, lightning deploys instead use `bakeGDocPost` directly, and on that code path we don't populate these fields in any way.

See #2907 for more details, where I attempt a fix of this.
