### ISSUE TITLE
Search clicks for charts and explorers aren't being tracked properly

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2932]
Este noted that our Algolia analytics are showing implausibly low clickthrough rates - 0% almost everywhere. Presumably this is because clicks aren't being tracked and not that people aren't clicking things. We need to verify this data is being tracked properly for Charts and Explorers.

**Comment by marcelgerber** [comment]
Indeed, assigning it to myself.

**Comment by larsyencken** [comment]
I added another related thing to the cycle under "Could do" which is to log our own clickthrough data to GA, which would pipe it to BigQuery. That would be helpful if we find Algolia doesn't give us access to the data ourselves.
