### ISSUE TITLE
Fixed y-axis target year appearing in scatter plot

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#2934]
## Description

After editing a scatter plot with an overridden x-axis year (and disabling the option), the chart stays with a fixed y-axis year that can't be edited on admin.

## Expected behaviour

The chart should not have this fixed y-axis year, so it could show all the circles in the database.

## Steps to reproduce

1. Go to [this URL](https://owid.cloud/admin/charts/335/edit)
2. Check in the debug version that
```
"dimensions": [
    {
      "property": "y",
      "variableId": 816306,
      "targetYear": 2013
    },
```
3. See that the tooltips are shown like a connected scatter plot only for the variable in the x-axis
4. See that South America is grayed out

## Screenshots
The chart with the error is looking like this:
![image](https://github.com/owid/owid-grapher/assets/63430031/b6308430-7623-4f0b-af0d-609aa591937c)
![image](https://github.com/owid/owid-grapher/assets/63430031/aaa97144-b5b6-4b1b-978c-da317be29c5e)

This is how it should look
![image](https://github.com/owid/owid-grapher/assets/63430031/c6bef917-fb3c-4b5b-8a72-e89519cfc9e3)

## Environment

For desktop, provide:

-   OS: macOS Sonoma 14.1.1
-   Browser: Chrome 119.0.6045.159

## Additional context

I have created a new chart that shows the data the right way, [here](https://owid.cloud/admin/charts/7381/edit).

**Comment by danyx23** [comment]
@paarriagadap this has been a while but we just opened this for triage now - could you try to reproduce this issue and see if reloading the admin after saving fixes the issue? This is probably some relatively tough to debug bug of the admin code and if there is a reasonable workaround we might close this as wontfix. Thanks!

**Comment by paarriagadap** [comment]
Hi @danyx23. No, it's not fixing it. But this might be a very niche problem to solve anyway. Last November, I created [this chart](https://owid.cloud/admin/charts/7381/edit) from scratch with the same data and it works. I saved the draft to understand the problem, but if it is tough to solve and there are no other cases, I think this can be closed as wontfix. Thanks!
