### ISSUE TITLE
🐛 chart: tooltip not showing unit when short unit is set

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#2935]
## Description
The indicator unit in the tooltip disappears whenever I add a short unit to the indicator, even if the unit is set.

## Expected behaviour

If a unit is given, it should be displayed regardless of whether the short unit is set or not.

## Steps to reproduce

- Go to [chart edit](https://owid.cloud/admin/charts/2948/edit)
- Edit the "Short (axis) unit" in the dropdown menu for an indicator, e.g. for `Life expectancy difference (f-m) - Type: period - Sex: both - Age: 0`.
- Add text (and remove it) for the short unit and see how the tooltip behaves on the chart.

## Demo

https://github.com/owid/owid-grapher/assets/18101289/789d29af-0442-4d59-852e-fa1ea34b1d4d

**Comment by lucasrodes** [comment]
The motivation for this might have been that the unit is shown next to the indicator's value on the tooltip. Hence it'd be redundant.

![image](https://github.com/owid/owid-grapher/assets/18101289/5de2bb3c-96fe-4510-9873-8d0af76165c9)


Feel free to close this issue.

[See slack discussion.](https://owid.slack.com/archives/C46U9LXRR/p1700666922238819)

**Comment by danyx23** [comment]
I think that unless there is an indication that this is causing problems of understanding I would leave this as is. This heuristic is pretty sensitive and touching it would require looking at a lot of charts. Feel free to reopen if you find a compelling case for it though!
