### ISSUE TITLE
Grapher: World map is sometimes cropped at the top

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2941]
## Description

- Grapher sometimes crops the world map at the top (see screenshots)

## Screenshots

Example charts:
- https://ourworldindata.org/grapher/tomato-production
- https://ourworldindata.org/grapher/autopsy-rate

### Today's Grapher (after redesign)

Example of a chart that is cropped:

<img width="1059" alt="Screenshot 2023-11-24 at 12 47 27" src="https://github.com/owid/owid-grapher/assets/12461810/f01fecc6-84a4-4f14-8ab6-6edbc2464abc">

Example of a chart that is not cropped:

<img width="1203" alt="Screenshot 2023-11-24 at 12 47 54" src="https://github.com/owid/owid-grapher/assets/12461810/2a50be7a-b43b-4e6b-955f-ee4ffacb04c2">

### Before redesign

Small screen (cropped):

<img width="680" alt="Screenshot 2023-11-24 at 12 46 15" src="https://github.com/owid/owid-grapher/assets/12461810/a9e8393f-bb64-4b4e-9175-bde053bed95b">

Larger screen (not cropped)

<img width="1126" alt="Screenshot 2023-11-24 at 12 46 39" src="https://github.com/owid/owid-grapher/assets/12461810/1210ce09-5f4a-4bac-bc41-d44f3ea7fcb6">

**Comment by danyx23** [comment]
We're calling this 3h and this is also about our max appetite for this.
