### ISSUE TITLE
Project: migrate donor flow to cloudflare (#proj-donor-page v2 option 1)

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#2947]
- [scope (slides)](https://docs.google.com/presentation/d/15C05XgSaq9UbuxYE9Mm5VPSxc5sjCfhn9nfvnBWfFcQ/edit#slide=id.g29d49afaa30_1_98)
- [background (notion)](https://www.notion.so/2023-10-30-Updated-donor-flow-c54fe6a6fcbf48119e8b2feec152cc20)
- related: 
  - #2737
  - #2908

**Comment by marcelgerber** [comment]
@mlbrgl I think this is done, right?

**Comment by mlbrgl** [comment]
yes!
