### ISSUE TITLE
Life expectancy at birth Marimekko chart not displaying correctly

### ISSUE THREAD

**Issue by spoonerf** [owid/owid-grapher#2955]
## Description

In the [life expectancy at birth Marimekko chart](https://ourworldindata.org/grapher/life-expectancy-marimekko) all countries are showing as pale, suggesting something not visible is selected.

![Screenshot 2023-11-27 at 17 03 14](https://github.com/owid/owid-grapher/assets/10774728/2b278b54-9c5e-45d9-aff7-8a33120b3ef5)

## Expected behaviour

The countries should show in a 'fuller' colour, for example in [this marimekko](https://ourworldindata.org/grapher/child-mortality-rate-marimekko).
![Screenshot 2023-11-27 at 17 02 52](https://github.com/owid/owid-grapher/assets/10774728/7adb169f-266e-49a5-97c7-66516f5cdfbf)

## Steps to reproduce

1. Go to this URL https://ourworldindata.org/grapher/life-expectancy-marimekko

## Environment

For desktop, provide:

-   OS: Mac
-   Browser: Chrome
-   Version: 119.0.6045.159 (Official Build) (arm64)

**Comment by danyx23** [comment]
Fixed this
