### ISSUE TITLE
Refactor Grapher's modal CSS to use shared styles (and remove `baseFontSize` dependency)

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#2966]
- Since we're now sharing CSS between the site and Grapher, it would make sense to use shared styles in Grapher's modals
- But also...
- Grapher's modal currently take the `baseFontSize` into account
  - The `baseFontSize` is used to scale the font size down on smaller screens
  - To make this work, modals use `em` units throughout
  - This makes it difficult to maintain/update/reason about the code
  - A better strategy for responsiveness is to use media queries

**Comment by danyx23** [comment]
Closing this as we decided that this should be done whenever we do substantial work on one of the modals, one modal at a time.
