### ISSUE TITLE
Improve bake times

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#2971]
Our bake times currently take >15min, which is quite annoying. I think there's a lot of low-hanging fruit that could speed it up. We should also refactor some parts of baking. Here are some ideas:

* [x] Increase `MAX_NUM_BAKE_PROCESSES` from default 4 to 32. It should be [added here](https://github.com/owid/owid-grapher/blob/master/ops/buildkite/build-code#L47)
* [ ] ~Bake GDocs async~, [this is sync](https://github.com/owid/owid-grapher/blob/master/baker/SiteBaker.tsx#L367) at the moment and takes ~2min
  * this is not a bottleneck, async doesn't help
* [x] Baking gdrive images takes 5min now, why so long? We're also [getting 404s](https://github.com/owid/owid-grapher/issues/2953) from DO
  * it turned out etag caching wasn't working and we were fetching **all images every time**
* [ ] Stop spamming logs with useless info (this is annoying in buildkite which is truncating logs)
* [ ] ~Parallelise other steps?~
  * Unhelpful, tried it here https://github.com/owid/owid-grapher/pull/2972
* [ ] Cache grapher charts? This could be tricky, but perhaps we could get hashes of all ingredients now for caching? (i.e. etag of JSON file in S3, we didn't have that back then)

**Comment by rakyi** [comment]
Current average bake times are 8.4 min, which we think are good enough, except we still want to improve baking of images, see https://github.com/owid/owid-grapher/issues/2485

Closing this one.
