### ISSUE TITLE
Improve spacing between articles in newsletter

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#2982]
## Description

Articles are too tight between each other in newsletters, and it looks as if the pictures belong to the next title.

## Expected behaviour

They should look more separated for increased readability.

## Steps to reproduce

1. Go to this URL https://us8.campaign-archive.com/?e=0cbc7debad&u=18058af086319ba6afad752ec&id=2958687226
2. See how the titles are too tight with the previous picture

## Screenshots

![image](https://github.com/owid/owid-grapher/assets/63430031/c9ef901d-0195-4c03-bfcd-55d47b2fa35f)
![image](https://github.com/owid/owid-grapher/assets/63430031/9d852afc-fecd-40c5-a64a-d3f3fcd60087)

## Environment

For desktop, provide:

-   OS: macOS Sonoma 14.1.1
-   Browser Chrome
-   Version 119.0.6045.159

## Additional context

[Conversation in Slack](https://owid.slack.com/archives/C5BDCB2R3/p1701447462683669)

**Comment by danyx23** [comment]
Matthieu commented this in slack: 

> yep, I agree. I've possibly fixed it on the preflight but it's not straightforward to test 2 articles there. So in case I can't get to it before the next time this happens, we at least have a test stacked up on the preflight (and we have one hour to replicate on the live version).

**Comment by danyx23** [comment]
@mlbrgl said this is really annoying to fix - closing this as wontfix for now but we'll revisit newsletter soon
