### ISSUE TITLE
GDocs authoring: Change guideline for length of excerpt 

### ISSUE THREAD

**Issue by natasha-ahuja** [owid/owid-grapher#2983]
## Core Problem
The current 150-character limit for excerpts in the Google Docs admin is artificially restrictive, and it doesn't need to be as restrictive as it currently is.

## Proposed Solution
@maxroser & I would like the character limit for the excerpt field in the Google Docs admin to increase from 150 characters to 175 characters. 

## Alternatives
We could remove the guideline entirely, but I believe it's essential for maintaining the neatness of our latest page.

## Context 
(Mainly for @edomt, so he can inform his team)

Excerpts don't have a hard character limit. In the GDocs admin, we now have a 'soft limit' of 150. In WordPress, there wasn't even a guideline, but the small box size encouraged short excerpts.

![Screenshot 2023-12-01 at 21 11 07](https://github.com/owid/owid-grapher/assets/68027090/f514b694-057c-47ec-8adf-a64fee8da2a5)

In Google Docs, you now see a warning sign if you go over 150 characters. Having a long excerpt is more likely in GDocs because excerpts are written within the GDoc rather than the box in the preview.

![Screenshot 2023-12-01 at 21 12 28](https://github.com/owid/owid-grapher/assets/68027090/3d3f7dd3-c6b3-4fdb-a73d-483c47f5541a)
![Screenshot 2023-12-01 at 21 14 18](https://github.com/owid/owid-grapher/assets/68027090/134313b7-6d93-4841-911f-0a68daf9fd08)

**Where do excerpts appear? What is the optimal number here?** 
Excerpts currently appear in Google search results, social media cards, and the /latest feed.

- **Google** -- Previously, it was the main thing people saw in Google search descriptions under the name of the topic/article, but now Google isn't as consistent about what appears here. The number of characters that would appear on Google was 150 characters, which is where the number comes from. 
- **Social Media** -- The display varies a lot ([see Esteban's Slack message for examples](https://owid.slack.com/archives/C5BDCB2R3/p1701269632329839)), but typically shows no more than 75 characters.
- **/Latest Page** -- Under the title in the card, you see the excerpt. This is the most relevant destination for excerpts _now_, so authors should know that this is mainly what they are writing the full excerpt for. 

**Optimal Size**: 
Given that the /Latest page is what we are optimizing for, we need to look at what affects the height of the row of cards here. What we _don't_ want is something like this:

![long-excerpt](https://github.com/owid/owid-grapher/assets/68027090/44e8a169-2306-4a99-80a6-8ba946c39200)

The height of the row of cards is determined by three factors: excerpt size, title length, and author list of the tallest card (since the thumbnail size is fixed). Note that we do not have a guideline for title length or the list of authors, and we don't intend to change those. 

Since the objective is just to have a neat page, and row lengths don't need to be identical, we just need to have a rough guideline for the excerpt size. After discussing with Matthieu, it falls between 130 and 175 characters (shorter if the title or list of authors is very long, and in some cases it is probably fine to be longer too).

So authors should know that we need not be overly strict about excerpt length. It might also be It's also useful for them to understand the origin of this guideline. 

When a dev has some time, someone on the team will adjust the warning to trigger only when authors exceed 175 characters, relaxing it by about 25 characters. But even then, it might be okay to go a bit over. 
Note that it may take time for a dev to implement this change. 

**PS**: In the migration process, Max and I decided on leniency. I will not be shortening excerpts unless they are excessively long. I will also inform Charlie of this.

**Comment by natasha-ahuja** [comment]
@edomt @CGiattino, when the WP migration project is over, we should let @danyx23 know so that he can re-enable compulsory excerpts for new articles. 

Currently he had disabled that feature on my request because a lot of old articles didn't have excerpts and we didn't want to add time to the migration project by requesting authors to write excerpts for old articles.

**Comment by edomt** [comment]
@danyx23 As explained above by Natasha, can you please re-enable compulsory excerpts for new articles, now that the WP migration is over?

**Comment by danyx23** [comment]
@edomt Sure, I can do it when I'm back from vacation - if you have a reason to want it earlier than April 15 then please ping Ike about it, it's a simple thing

**Comment by danyx23** [comment]
@edomt I have a PR up to make the excerpt mandatory again. There are currently [5 articles that don't have an excerpt](http://datasette-private/owid?sql=select%0D%0A++%27https%3A%2F%2Fadmin.owid.io%2Fadmin%2Fgdocs%2F%27+%7C%7C+id+%7C%7C+%27%2Fpreview%27+as+admin_url%2C%0D%0A++slug%0D%0Afrom%0D%0A++posts_gdocs%0D%0Awhere%0D%0A++JSON_EXTRACT%28content%2C+%27%24.excerpt%27%29+is+null%0D%0A++and+published+%3D+1%0D%0A++and+JSON_EXTRACT%28content%2C+%27%24.type%27%29+%3D+%27article%27). These 5 could then only be republished once an excerpt is added. I guess this is fine and I can go ahead and merge this? Or do you want to add a simple excerpt first or postpone this PR?

**Comment by edomt** [comment]
Thank you @danyx23 - yep, it's okay to go ahead, we'll just write these excerpts as needed if we ever edit these articles.
