### ISSUE TITLE
Datapages do not render without Javascript

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2992]
Found while investigating the archive.org issue:

![image](https://github.com/owid/owid-grapher/assets/11844404/634b45b9-9f12-451c-9173-095946f66140)

Our regular grapher pages still work:

![image](https://github.com/owid/owid-grapher/assets/11844404/558b0adb-bb30-4f2e-815e-14a03515dc84)

**Comment by ikesau** [comment]
Similarly, static collections do not work without JS.

We should make something similar to `Grapher.renderSingleGrapherOnGrapherPage` 

i.e. `GrapherFigure`, which can SSR the figure and fallback img

**Comment by mlbrgl** [comment]
Similarly grapher charts are not rendered in gdocs w/o JS
### with JS
<img width="1440" alt="Screenshot 2024-02-08 at 18 13 32" src="https://github.com/owid/owid-grapher/assets/13406362/7c0f72b3-555f-43ae-a3ed-736b50bf465b">

### without JS
<img width="1440" alt="Screenshot 2024-02-08 at 18 13 00" src="https://github.com/owid/owid-grapher/assets/13406362/211091b4-8533-4bf2-b1d0-eedddd619091">

**Comment by mlbrgl** [comment]
Consider expanding `getChartEmbedUrlsInPublishedWordpressPosts` to include embeds from gdocs posts if we want to bake them the same way as embeds from Wordpress posts (see https://github.com/owid/owid-grapher/pull/3182/files#r1488425502)

**Comment by danyx23** [comment]
This seems related to #2354
