### ISSUE TITLE
Links are parsed as markdown in "Learn more about this data"

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#3047]
## Description

In the "Learn more about this data" section of a Grapher chart, the "Links" section is not displayed properly for some links, due to markdown formatting.

## Expected behaviour

Links should be working regardless of their format and not interpreted as markdown elements.

## Steps to reproduce

1. Go to [this URL](https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-historical)
2. Click on "Learn more about this data"
3. See in "Links" how the link is not working (not underlined completely, not working)

## Screenshots
The problem in this specific case is that the link contains the text `_csp_`, interpreted as a text in italics
<img width="606" alt="image" src="https://github.com/owid/owid-grapher/assets/63430031/a96b0a0f-26d4-4658-bcb2-4e1732e37a1b">

## Additional context

In the [dataset page](https://owid.cloud/admin/datasets/5756) the link is properly displayed:
https://www.oecd-ilibrary.org/sites/3d96efc5-en/1/3/9/index.html?itemId=/content/publication/3d96efc5-en&_csp_=2c2e680562193998e9d20ed6a45a9242&itemIGO=oecd&itemContentType=book

**Comment by sophiamersmann** [comment]
fixed in #3050
