### ISSUE TITLE
Full citation only cites one indicator of a multi-indicator chart

### ISSUE THREAD

**Issue by pabloarosado** [owid/owid-grapher#3098]
## Description

In multi-indicator charts, the full citation (that we see on the sources tab) only cites one indicator used in the chart.

## Expected behaviour

The full citation should cite all indicators (if that's the expected format of the full citation).

## Steps to reproduce

1. Go to the sources tab of: https://ourworldindata.org/grapher/nuclear-weapons-proliferation
2. Scroll down to see that the full citation is only citing one of the indicators.

## Additional context

I suppose this is happening because the format of the full citation was defined in the context of data pages (which currently have only one indicator). But then the full citation was also used in all grapher charts, even multi-indicator ones.

**Comment by JoeHasell** [comment]
Hey @pabloarosado, I don't understand the bug here.

In the example you give, the stacked area chart has three indicators: Number of countries considering/pursuing/possessing. Each indicator has its own tab in the 'Learn more about this data' overlay, and there is a full citation in the case of each. 

In terms of the overall layout, this to me is expected behaviour. Sorry if I'm missing something, or misunderstanding you.

I note that they are all the same in each indicator – is that the problem? Should they not be based on what you know of this data?

**Comment by pabloarosado** [comment]
Hi @JoeHasell, thanks, you are right, this is not a bug, rather a feature request.

I think we have the following problems:
1. On data pages, we provide a way to cite the data page ("How to cite this page"), but on charts, we don't. I can imagine that users who want to properly cite our charts may end up citing the first thing they see as "full citation", which is the citation of the first indicator.
2. More generally, the format of the full citation (both for data pages and for indicators) needs to be improved. For example, the `[dataset]` after the indicator's title is confusing and takes unnecessary space. And if I look at any other full citation, it's usually long, repetitive, hard to understand, and poorly formatted, e.g. for [this data page](https://ourworldindata.org/grapher/hydropower-consumption):

> Ember - Yearly Electricity Data (2023); Ember - European Electricity Review (2022); Energy Institute - Statistical Review of World Energy (2023) – with major processing by Our World in Data. “Electricity generation from hydropower” [dataset]. Ember, “Yearly Electricity Data”; Ember, “European Electricity Review”; Energy Institute, “Statistical Review of World Energy” [original data]. Retrieved January 15, 2024 from https://ourworldindata.org/grapher/hydropower-consumption


 I'll close this issue, but add it for discussion on the data architecture call.
