### ISSUE TITLE
Search shows an article that hasn't existed for a few months

### ISSUE THREAD

**Issue by spoonerf** [owid/owid-grapher#3113]
## Description

When you search 'How do we reduce antibiotic resistance from livestock?', which previously existed as an article, it still comes up in Search; when you click it, it redirects to [a chart](https://ourworldindata.org/grapher/antibiotic-usage-in-livestock). 

## Expected behaviour

The article, which no longer exists, should not show up in Search. The redirect is old, I think from at least Sept 2023 ([according to wayback machine](https://web.archive.org/web/20230928042529/https://ourworldindata.org/antibiotic-resistance-from-livestock)), so it's not the case that it just hasn't been reindexed yet. 

## Steps to reproduce

1. Go to this URL - https://ourworldindata.org/
2. Click on 'Search'
3. Type 'How do we reduce antibiotic resistance from livestock?' (title of an [old article](https://ourworldindata.org/antibiotic-resistance-from-livestock))
4. See that it comes up in Search

## Screenshots

https://github.com/owid/owid-grapher/assets/10774728/d04c3fdb-ea53-477f-8580-8f0533655f05

**Comment by marcelgerber** [comment]
That article is, in fact, [still published in WordPress](https://owid.cloud/wp/wp-admin/post.php?post=14806&action=edit).

It seems that it is just "hidden" behind a redirect, i.e. no longer accessible because of the redirect being in place.

**Comment by mlbrgl** [comment]
Thanks @marcelgerber, I'm seeing this too.

@spoonerf a [gdoc](https://docs.google.com/document/d/1esjLn_CQNca_dDBEAFguAbJYrpFysltoxHNOCNp3F98/edit) has been created for this article ([preview](https://owid.cloud/admin/gdocs/1esjLn_CQNca_dDBEAFguAbJYrpFysltoxHNOCNp3F98/preview))

Let me know if you want to remove the article from the ["latest" section](https://ourworldindata.org/latest/page/17) by:
- unpublishing the [Wordpress posts](https://owid.cloud/wp/wp-admin/post.php?post=14806&action=edit)
- (optional) deleting the [ported gdoc](https://docs.google.com/document/d/1esjLn_CQNca_dDBEAFguAbJYrpFysltoxHNOCNp3F98/edit)



![Image](https://github.com/owid/owid-grapher/assets/13406362/fd97af32-887a-4228-b484-288f5a97cde8)

**Comment by spoonerf** [comment]
Ah okay, sorry for the delay in getting back to you guys. I think it best to unpublish the WordPress article. That would prevent it from showing up in Search, right?

**Comment by mlbrgl** [comment]
@spoonerf yes. I've just unpublished https://owid.cloud/wp/wp-admin/post.php?post=14806&action=edit now. Let's check from next Monday that it has effectively been removed from search and close the issue.

**Comment by spoonerf** [comment]
Looks like it's worked - the article is no longer showing up in Search. Will close this now, thanks!
