### ISSUE TITLE
"Books" entry has diagram with broken OWID logo

### ISSUE THREAD

**Issue by MarcelGerber** [owid/owid-grapher#312]
Sadly, I don't know exactly where to report this since its not an issue with the grapher itself.

Anyway, the first and second diagram linked in https://ourworldindata.org/books uses a OWID logo that can't be found. The diagram itself is hosted at https://www.maxroser.com/owidUploads/nvd3/nvd3_BarChartFromCSV_Manuscripts/nvd3_BarChartFromCSV_Manuscripts.html, and the image is supposed to be at https://www.maxroser.com/owidUploads/maxstyle_for_d3/Our-World-in-Data24high.png.

![image](https://user-images.githubusercontent.com/2641501/74066451-62b4fe80-49f7-11ea-81c2-f5ec72a99117.png)

**Comment by jasoncrawford** [comment]
Thanks @MarcelGerber! We're looking into this

**Comment by mlbrgl** [comment]
Closing in favour of [discussion here](https://owid.slack.com/archives/CK0RKGGSC/p1624612468001800)
