### ISSUE TITLE
Wordpress tables surrounded with <p> are stripped out during ArchieML migration

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3133]
## Core problem

When running `migrateWpPostsToArchieMl`, HTML tables wrapped in `<p>` tags are stripped out by https://github.com/owid/owid-grapher/blob/2b4bba146d7c4eaf18894b07d733fbe3ae9f34aa/db/model/Gdoc/htmlToEnriched.ts#L1193-L1197

These tables come from the dereferencing of table shortcodes in #3130.

✅ 3604 fertility rate: table inside shortcode comment block
```
<!-- wp:shortcode -->
[table id=59 /]
<!-- /wp:shortcode -->
```
[Edit table](http://localhost:8080/wp/wp-admin/admin.php?page=tablepress&action=edit&table_id=59)

❌ 14007 polio: table surrounded by standard p tags block
```
<!-- wp:paragraph -->
<p>[table id=75 /]</p>
<!-- /wp:paragraph -->
```

❌ 52066 democracy data: table surrounded by p tags block with classes
```
<!-- wp:paragraph {"className":"wp-block-full-content-width"} -->
<p class="wp-block-full-content-width">[table id=133 /]</p>
<!-- /wp:paragraph -->
```

❌ table inline with content

## Proposed solution

1. Find all occurrences (< 10)
```
SELECT * from wp_posts where post_content like "%<%>[table id=% /]</%>%" and post_type<>"revision"
```
_If any of these have already been migrated, it is unnecessary to fix tables in their content_

2. Manually replace offending tables in Wordpress content with shortcode version.
3. Run `node itsJustJavascript/db/syncPostsToGrapher.js`

## Alternative

Do nothing pro-actively, and deal with it when and if necessary when migrating articles on a case-by-case basis:
- copy HTML in post.content source
- paste it within a `html: ... :end` archieml block

## Context

#3130

**Comment by mlbrgl** [comment]
@danyx23 will give this a quick stab, otherwise I'll mention those articles to Natasha and Charlie for manual migration as proper gdocs tables (as opposed to doing the manual work of fixing the syntax in WP, then some time down the line needing to convert them again to proper gdocs tables)

**Comment by danyx23** [comment]
@danyx23 tried to solve this at some point and it was tricky because cheerio refused to parse tables inside p tags properly (block vs flow level content). Now that the articles have been migrated to GDocs this seems a lot less relevant.
