### ISSUE TITLE
Failed to download wordpress package

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [owid/owid-grapher#3146]
Error happen when start owid, the wordpress package looks need password to be downloaded

Error Picture
![image](https://github.com/owid/owid-grapher/assets/88485337/86409e4c-4c5b-4400-9a97-9466121b3fc5)

this is the command for downloading wordpress sql

ssh owid@live-db.owid.io "sudo mysqldump --default-character-set=utf8mb4 live_wordpress -r /tmp/live_wordpress.sql && sudo gzip -f /tmp/live_wordpress.sql"
rsync -hav --progress owid@live-db.owid.io:/tmp/live_wordpress.sql.gz $FOLDER

**Comment by danyx23** [comment]
Running the full setup is only supported for staff members. Use `make up` if you want to run the Grapher project without wordpress etc.
