### ISSUE TITLE
Support a log scale on DiscreteBar

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#316]
Selecting a single year on the timeline of a line chart turns it into a bar chart. But if a log scale is used on the line chart, then the bar chart is broken: https://ourworldindata.org/grapher/historys-hockey-stick-gross-domestic-product-per-capita-using-the-ratio-scale-1990?year=730&time=2016&country=BWA+ZAF+USA

Ideally, DiscreteBar should also support a log scale.

**Comment by breck7** [comment]
Pushing a branch with a fix. Adding a screenshot of current behavior:

![Screen Shot 2020-03-17 at 2 33 48 PM](https://user-images.githubusercontent.com/74692/76913888-6d677c80-685c-11ea-935e-59f763675a44.png)

**Comment by breck7** [comment]
And the same issue on the Corona charts:

![Screen Shot 2020-03-17 at 2 35 52 PM](https://user-images.githubusercontent.com/74692/76913952-a0aa0b80-685c-11ea-8dbb-91ef39aa73f6.png)
