### ISSUE TITLE
Grapher's data table sometimes doesn't show all plotted data

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3174]
## Description

- In case of [this StackedBar chart](https://ourworldindata.org/grapher/annual-reported-ai-incidents-controversies), the data table only shows the start and end year – but there is no way to view intermediate years

## Expected behaviour

- Either show the timeline on the table tab, so that one can select other years
- Or rethink our table in such cases

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/annual-reported-ai-incidents-controversies
2. Note that it shows data from 2012-2021
3. Switch to the table
4. Note that data for 2012 and 2021 is shown, without the possibility to view intermediate data points

## Screenshots

<img width="877" alt="Screenshot 2024-02-06 at 10 25 48" src="https://github.com/owid/owid-grapher/assets/12461810/8693bacf-8cc4-49e7-8e22-5d17e2fcc9a5">

<img width="877" alt="Screenshot 2024-02-06 at 10 26 02" src="https://github.com/owid/owid-grapher/assets/12461810/74449d98-781c-4ad4-aa22-36b963d9ee71">

**Comment by danyx23** [comment]
Probably revealing the timeline slider on the table tab would be the way to go here
