### ISSUE TITLE
refactor: rewrite getRelatedChartsForVariable query

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3203]
This is an optimization of the query listing related charts on data pages.

> I think it's better to join on the chart_dimensions table rather than this json_contains (normal tables are much faster to filter than nested json in MySQL)

_Raised by @danyx23 in https://github.com/owid/owid-grapher/pull/3176#discussion_r1488142975_

**Comment by ikesau** [comment]
Not a big enough of a perf hit to ever be a priority, realistically
