### ISSUE TITLE
Use correct Semibold font weight in static chart titles

### ISSUE THREAD

**Issue by samizdatco** [owid/owid-grapher#3210]
## Description

The design calls for chart titles to be set in Playfair Semibold (weight 600), but the PNG-generation code does not preload that weight and was not properly rendering exports when the style was updated. As a stopgap, the title weight was reverted to 500. 

The actual fix would involve:
- [ ] adding the semibold weight to the [list of pre-loaded fonts](https://github.com/owid/owid-grapher/blob/43e5d471af8c1a332f63fdefb46074339a285f1f/packages/%40ourworldindata/grapher/src/captionedChart/StaticChartRasterizer.tsx#L50-L54) in the rasterizer (i.e., add a `600` to the front of the playfair font definition)
- [ ] replacing `PlayfairDisplay-Medium` with `PlayfairDisplay-SemiBold` in [the script](https://github.com/owid/owid-grapher/blob/43e5d471af8c1a332f63fdefb46074339a285f1f/devTools/fonts/make-faces.py#L142) that generates `embed.css` 
- [ ] regenerate the `embed.css` file by running `make && make install` in the `devTools/fonts` directory
- [ ] updating the title weight to 600 as in #2970

There's also the issue of creating fresh exports after making these changes since currently the baking process only generates new ones if the config has changed since the previous bake. 

To get around this, try:
1. hard-coding the [`chartIsSameVersion` function in GrapherBaker.ts](https://github.com/owid/owid-grapher/blob/fd511a1b6c254f12a08ffa2c20906b70f981220a/baker/GrapherBaker.tsx#L384-L396) to return `false`
2. triggering a bake
3. restoring the normal lazy behavior of `chartIsSameVersion`

#### Slack discussions
- [updating the font weights used by the rasterizer and embed.css](https://owid.slack.com/archives/C066XRSRMNC/p1704367149580029)
- [fixing existing static charts that use medium or bold weights for their titles](https://owid.slack.com/archives/C04VBQ00HQR/p1707933834755059)

**Comment by sophiamersmann** [comment]
@samizdatco Running `make && make install` errors out for me and gives the following error:

```
unzip -jo .env/build/lato.zip -d .env/build/lato '*/*/*/Lato-*.woff2' && touch .env/build/lato/*
Archive:  .env/build/lato.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of .env/build/lato.zip or
        .env/build/lato.zip.zip, and cannot find .env/build/lato.zip.ZIP, period.
make[1]: *** [.env/build/lato] Error 9
```

When I look at `.env/build/lato.zip`, it contains a plain text HTML file (uncompressed). Is it possible we're accidentally unzipping twice?
