### ISSUE TITLE
Newsletter subscribers cannot reply directly via the newsletter to newsletter@ourworldindata.org (the sender)

### ISSUE THREAD

**Issue by CGiattino** [owid/owid-grapher#3213]
## Description

Replies to mailchimp newsletter issues are not delivered or end up in spam.

```mermaid
sequenceDiagram
    Mailchimp->>Subscriber: Send campaign ✅
    note right of Subscriber: the subscriber hits "reply"<br>in their mail client (e.g. gmail).<br>This copies the content of<br>the campaign below their<br>actual reply.
    Subscriber->>Our World in Data: reply to ❌
```

1. newsletter is sent by Mailchimp (reply-to: newsletter@ourworldindata.org)
2. subscriber receive newsletter
3. subscriber hits "reply"
4. email is sent to newsletter@ourworldindata.org
5. email is not delivered (or end up in spam)

Charlie tried this multiple times and it was never delivered.

It seems to be something with the newsletter content itself — Charlie copied the newsletter contents to a fresh email to newsletter@, and it also was not delivered. But simply emailing newsletter@ a test email without any newsletter contents does work.

As a baseline, sending the email to both newsletter@ourworldindata.org and a disposable email at the same time:
- newsletter@ourworldindata.org: not received ❌
- disposable email: received ✅

More [slack discussion here](https://owid.slack.com/archives/C46U9LXRR/p1708071483994309)

## Expected behaviour

Replies to the newsletter get delivered to us.

## Context
- recent updates to sender guidelines by google: https://support.google.com/a/answer/81126?sjid=16638308369703138256-EU
- maybe: https://support.google.com/a/answer/13198639?sjid=16638308369703138256-EU

**Comment by mlbrgl** [comment]
@CGiattino partially rewritten description and shared with Mailchimp support

**Comment by mlbrgl** [comment]
Their reply:

> So after running a few test it looks like youre domain is fine. What I do see id you have a few free domains attached to account, it may be best to remove the google domains, as they do carry limitations
> Limitations of Free Email Addresses: https://eepurl.com/dyil9c
> Also if you if you see specific adresses effected this process may help those contacts as well, 
> Use Safe Sender Lists to Stay out of Spam Folders: https://eepurl.com/dyikij,

**Comment by CGiattino** [comment]
huh, so besides the several spelling/grammar errors, what do you make of their reply — some things to investigate that might help with this?

**Comment by mlbrgl** [comment]
Skipping a back-and-forth for clarification, Mailchimp support suggested a possible workaround, by letting Mailchimp manage replies:

> So this would be using the the domain that is sent with to manage replies. We also have a great way to manage campaign replies within Mailchimp as well. If you take a look at this page here: Set Up Your Mailchimp Inbox: https://eepurl.com/hcaXDr
 
> This will allow you to have your own inbox within Mailchimp to manage replies that come in from your sent content.

Worth evaluating the cost/benefit. This would require some workflow adjustments.

**Comment by ikesau** [comment]
Without doing anything this seems to have been fixed 🤷
