### ISSUE TITLE
WP post resurrected after being shadowed by gdocs post

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3229]
## Core problem

This is a potential problem for later:
- `/demo-post` published as a WP post
- `/demo-post` published as a gdoc post -> this overrides the WP post sharing the same slug
_Some amount of time later_
- gdoc post unpublished, with the assumption that /demo-post won't show anything
- `/demo-post` now shows the published WP post

An unintentional [variation of this happened for /urbanization](https://owid.slack.com/archives/C46U9LXRR/p1708541128369189?thread_ts=1708536644.027349&cid=C46U9LXRR).

**Comment by mlbrgl** [comment]
_triage_

@danyx23 @ikesau cron job that depublishes all Wordpress posts currently shadowed  by a gdoc post (i.e. sharing the same slug).

**Comment by ikesau** [comment]
Once the about pages are done we'll probably be able to unpublish almost every single WP page which will prevent this from ever happening again.
