### ISSUE TITLE
Table of contents on linear topic pages et al should grey out other content

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3234]
Occluding content is bad. Can we maybe translate these wide components to the right when we know the sidebar is open?

![image](https://github.com/owid/owid-grapher/assets/11844404/fc570586-df10-4a60-a38e-0eecc09aefdd)

![image](https://github.com/owid/owid-grapher/assets/11844404/68258166-1954-4297-b0f6-9be4b1188d70)

**Comment by toni-sharpe** [comment]
[The page in question](https://ourworldindata.org/tetanus#new-tetanus-cases-by-country)

**Comment by mlbrgl** [comment]
_triage_

It doesn't only affect wide components: on narrower screens, the regular content column is also masked, and there isn't any horizontal space left to shift content to.

<img width="832" alt="Screenshot 2024-02-27 at 15 48 51" src="https://github.com/owid/owid-grapher/assets/13406362/54853b2c-60a8-4c8f-a939-7ea72a95d919">

@mrwbkrm We could treat this as a temporary overlay, that readers open, navigate through and close before continuing reading.

<img width="1440" alt="Screenshot 2024-02-27 at 15 44 45" src="https://github.com/owid/owid-grapher/assets/13406362/2955fb99-b3a7-4112-b493-68fa5879489c">

We are already one step into that pattern, given that the sidebar closes when clicking on a nav item.

Triaging as "nice to have".

cc @danyx23 @ikesau

**Comment by toni-sharpe** [comment]
## Yes

Ah, I had this written but not published! So, yes, I `+1` but I'll drop in my reasoning.

And I suggested the same, asking: is the user opening the menu to see something else? If so, how much does it matter that something current is covered? Probably not much (ask them, you have a lot I believe). I don't ever like to assume the user's behaviour, but opening a menu probably means the content has served its purpose. 

However, IMO, some focus shading would be good in this case as suggested above - I'll show the darker shade here as a different example.

<img width="600" alt="Screenshot 2024-02-27 at 04 20 38" src="https://github.com/owid/owid-grapher/assets/10499070/2f6a06c0-c7ad-4bea-9511-c721400947ad">

## Another possible refinement

Another option here might also be to `:hover` the chart, allowing the uyser to see it if they wanted to, ie, you could still access a chart with the menu open

<img width="600" alt="Screenshot 2024-02-27 at 10 45 39" src="https://github.com/owid/owid-grapher/assets/10499070/024e6fd1-3011-4512-af2d-dba3c2ba48ea">

Sneaky `box-shadow` hack ... 

```
:hover {
  z-index: 5;
  box-shadow: 0 0 0 500px rgba(0,0,0,0.6);
}
```

**Comment by mlbrgl** [comment]
@toni-sharpe thanks for the feedback! 

I would be careful about triggering such a shift on a casual mouse hover, but that's nevertheless an interesting and creative take on this problem, nice!

**Comment by mrwbkrm** [comment]
Works for me @mlbrgl ! Once the user clicks on a section, the overlay closes automatically as it does now, correct?

**Comment by toni-sharpe** [comment]
@mlbrgl tbh, i don't think I'd do it. The option we agree on, that's the pattern to explore. I'm leaning heavily towards "the user opened the menu because they are finished with the content".

And hover has problems outside the mouse context too, on top of as being a big shift in this case, as you mention.

**Comment by mlbrgl** [comment]
@mrwbkrm yep!

**Comment by danyx23** [comment]
Being discussed with Marwa...

**Comment by JoeHasell** [comment]
I discussed this with Max and Ed. We're all agreed that the current situation is pretty bad. If the choice in the short term is between:
1) the transient ToC with greyed out background solution that Ike, Matthieu and Marwa have suggested;
2) leaving the status quo.

... then it is clear that option (1) is the way to go and we are all on board with that.

(That's on the assumption that it is a reasonably small engineering task and not some major investment that we then might end up going back on in the longer term.)

**Comment by mlbrgl** [comment]
@JoeHasell @mrwbkrm I have been working on a prototype ([link](http://staging-site-demo-bcn/age-structure)) related to this issue:

https://github.com/owid/owid-grapher/assets/13406362/814d8409-b838-48a8-acef-69944683a505

@mrwbkrm let me know if you want to pursue this further, and I'll look into smoothening some of the rough edges (e.g. [all charts page](http://staging-site-demo-bcn/charts))

demoed to @danyx23 and @rakyi today

**Comment by mrwbkrm** [comment]
Thanks for the update @mlbrgl! I think this might be easier to discuss in a call. I'll send you an invite! @JoeHasell let me know if you want to be there too.

**Comment by JoeHasell** [comment]
Hi @mlbrgl and @mrwbkrm, thanks for your thoughts on it!

Yes please do add me to the invite and I'll see if I can make it.

I think we should separate out a 'quick fix' solution from a great solution. 

As a quick fix, the solution Matthieu [first proposed](https://github.com/owid/owid-grapher/issues/3234#issuecomment-1966909402) I think does a good job and is much better than the status quo. If it's a very quick thing to implement, I think we should just do it (or, rather, keep it listed in the [batch cycle](https://github.com/owid/owid-grapher/issues/3562) and prioritise against the other things there.)

_If_ we were to decide to spend more energy on this and try to find a great solution, I would rather that energy go into a more general definition of the problem space. There are many related things not working well with linear and modular topic pages that could perhaps be resolved with some creative thinking around the layout and ToC. E.g.
- the all charts block in linear topic pages doesn't feel very discoverable; 
- sometimes it would be nice to have a related research and writing block also in linear topic pages; 
- similarly, there are topic pages where we have an explorer that we are not currently linking out to _at all_ from the linear topic page (Global Health and Air Pollution come to mind – possibly there are more).
- the 'related topics' in linear pages are often presented poorly; 
- the intro + key insight format in modular topic pages isn't working so well for the D&R team (and is basically broken on mobile) – we would like to be experimenting with more flexible, linear formats for modular topic page intros;
- overall, I think it's not so nice that we have these two very different layouts for our topic pages, modular and linear.... 

I have some ideas and have been speaking about it with Marwa in the past weeks. She and I are planning on brainstorming solutions at some point in the week 13-16 May when Marwa will be visiting Oxford.

I think it'd be great to have you involved in that discussion Matthieu, and overall my preference would be to have your energy in that more general discussion than on pursuing the prototype you shared in isolation from those other problems.

Hopefully I can make your call and we can chat more then.

**Comment by danyx23** [comment]
The decision on this one is to go ahead with the simple solution and grey out the non-TOC content while the TOC is open. The other solutions are still interesting and promising but should get a new issue once they have evolved far enough on the design side.

**Comment by toni-sharpe** [comment]
@mlbrgl yes, I will take ownership of this change. All three pages are loading for me nicely at `:3030`.

## Response

The colour: no problem, consistent UX > my example.

The second two scenarios: in those cases, the menus don't click away, therefore I assume the background should never show and should check for that.

Finally, what should happen with this space/the header in general when scrolled up to the page top?

My _feeling_ is it shouldn't cover the heading at all, whereas following the "search box" example _exactly_ would result in only the larger bottom portion of heading being overlaid; but, maybe UX/design folk at your end have a definite answer. 

I'll see what the first, simplest iteration produces and share those images early.

![image](https://github.com/owid/owid-grapher/assets/10499070/f90f5f92-3de7-4152-99f2-11c00b0f24ab)

## Background notes

I'm currently in a pretty hard job-hunting phase and my pattern is roughly: Mo, We and Fr - lots of applications then look here for things to help with/contribute to and/or other stuff. Then Tu and Th work on my self-guided learning projects.

There area also other Marimekko problems I had my eye on, partly because I think it would let me have use of Graphite which seems to be a tool for stacking PRs (hopefully with a free tier) and I [have one open already](https://github.com/owid/owid-grapher/pull/3581) in that code. Note: I am not taking ownership of those issues, nor suggesting the above shouldn't be merged because I want to try Graphite, just sharing my thinking.

**Comment by mlbrgl** [comment]
Great, thanks @toni-sharpe! 🙏

> The second two scenarios: in those cases, the menus don't click away, therefore I assume the background should never show and should check for that.

We can disregard the current specificities of /charts and /entries-by-year, and match the design and behavior of the sidebar on /age-structure. This means the sidebar on /charts and /entries-by-year could be opened and closed, even on larger screens, and show the overlay accordingly. It also means that the sidebar on these pages on larger screens will be hidden on page load.

> My feeling is it shouldn't cover the heading at all

I agree. Something like that:

![Frame 1](https://github.com/owid/owid-grapher/assets/13406362/1584f23a-b7b8-4da2-bd41-e8f812a2354f)

Thanks for the heads up about your availability. On our end, we were thinking of pushing this out in the next two to three weeks. If that seems unrealistic, let me know. For now, I'll assign you to it.

Yes, we've had good experiences with Graphite so far, something to experiment with, definitely!

**Comment by toni-sharpe** [comment]
@mlbrgl draft raised with the styles applied https://github.com/owid/owid-grapher/pull/3597

Note that the second commit stops the overlay appearing on the pages that will be changed to match the `/age-structure` page.

**Comment by toni-sharpe** [comment]
@mlbrgl Update on this:

I'm well into getting the styles consistent - the CSS was across two files

/owid-grapher/site/gdocs/components/centered-article.scss
/owid-grapher/site/css/sidebar.scss

By taking everything from `centred-article.scss` and putting it in `sidebar.scss` I've got most of the way there, but, there are various little bits that aren't right

![image](https://github.com/owid/owid-grapher/assets/10499070/a18153b0-873f-4a81-bbfd-e7ded388ab8e)

The margin between header and content on /charts and /entries-by-year is less than it is on /age-structure, so I think the margin should be the same, allowing a single code definition of scss to apply, and with the contents button fitting into this margin, as it does at narrow widths on /age-structure. Pulling the two different pages wider would just make them stretch, as they do currently with the fixed sidebar. 

I'm aware of the earlier comments that imply a larger design/style effort to come, so would probably go with a few margin edits here and there and tidy up/reduce the CSS taking the quick fix approach.

Also I see on the production site that there are designer/UX folk available on your side, plus also previous commenters here that might want some input, look at screen-shots etc.

## browser hacked and taken right down to 340 X 570 px

![image](https://github.com/owid/owid-grapher/assets/10499070/5db9eccd-6c57-4107-821a-6e3fb1184133) 

## current code based, so a bit more padding needed

![Screenshot 2024-05-13 at 00 45 02](https://github.com/owid/owid-grapher/assets/10499070/d7cd58c1-4751-439c-9772-0287b43dbde8)

**Comment by mlbrgl** [comment]
@toni-sharpe thanks for the update and your contribution! I'm currently looking at what you submitted a few days ago, and that looks good. Let me give you a few comments on your PR, and we can see from there if further adjustments or refactoring is necessary.

**Comment by toni-sharpe** [comment]
@mlbrgl no problem, I'll look at the review then move on from there.

I do note this extra work goes beyond the initial issue, and we could just roll-back a couple of commits and merge to add the overlay as per the issue suggestions.

**Comment by mlbrgl** [comment]
@JoeHasell: @toni-sharpe took care of this one on all the pages where this component is present:

- https://ourworldindata.org/age-structure
- https://ourworldindata.org/co2/country/united-states
- https://ourworldindata.org/entries-by-year
- https://ourworldindata.org/about
- https://ourworldindata.org/charts

Thanks again Toni!
