### ISSUE TITLE
Fix spacing between headings and columns

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3240]
## Problem

We don't like the alignment of our headings, which are parallel with our content rather than above them.

## Details

This is a common layout we use:

![image](https://github.com/owid/owid-grapher/assets/11844404/fb41f124-edf3-457b-a28e-a62db3cc7e8c)

The image should align with the text, not the heading.

### Manually fix in markup

There are a few ways we could do this, one of the simplest ways could be to add a new property to heading elements

```
{.heading}
level: 1
text: I am a heading
margins: sticky-left | sticky-right | left-side | right-side
{}
```
which you would use like so:

```
[+body]
{.heading}
level: 1
text: I am a heading
margins: sticky-left
{}

{.sticky-left}
[.+left]
Blah blah blah
[]
[.+right]
{.image}
filename: image.png
{}
[]
{}
[]
```

### Automatically do it

Client-side? Server-side in ArchieML rewriting?

If this is too annoying to write out we could also try and solve it programmatically by detecting when the content is like this (`left[0].type == "heading" && right[0].type === "image"`) and automatically calculating a margin-top to add to the heading based on the current height of the heading.

## Open questions

- Do we want to do this for all articles, or just for some?
  - Our intuition is that we _probably_ want this for all articles

**Comment by toni-sharpe** [comment]
## Is this what you're after?

I've found this technique very handy using `flex-box`. But it changes how you do things, so I understand maybe it's just curious, but, I have the time and it was interesting. Having got the app running I was looking for an issue I can fix too.

<img width="725" alt="Screenshot 2024-02-24 at 13 56 17" src="https://github.com/owid/owid-grapher/assets/10499070/cad9b959-7200-406e-b713-d7b3495b3b43">

https://owid-demo.brainstem-research.pages.dev/

Roughly, I read the "no styles" rule. It's solution based.

And my graph is just there to check the interchangability and interaction capabilities as the oithers are just images.

## This I do a lot

`flex-box` paradigm for the win. Flex and Grid both say "parents control the layout of the children". Grid then gives us a gap, but is just too griddy. Flex-box is perfect, but no `flex-gap`. margin T/F aren't the answer IMO.

### Advantages

* The little article components are completely self-contained, no invisible elbows forcing `marginLeft: true` default props etc. IMO, a golden rule of sorts, is that the edge of a conponent should be visible.
* That makes them syndicatable, ie, you could just put that anywhere, it gets taken out of it's parent list, which is handling it's layout.
* Then the folk writing content shouldn't ever have to define a margin unless they are thinking of the concept of margin from their professional context. IMO, it's better abstraction, like I don't need to do anything with electrical motors to make my washing machine work
* Which leads me on .... it's gonna be easier to translate. By which I mean, it's going to be easier for another set of pros whose key jobs are not code
* The [HTML is cleaner](https://github.com/toni-sharpe/brainstem-research/pull/308/files#diff-90427e4941b3de8149bf3576011cb8e2561bcd295d93410e8a632deb4d9caa9cR24-R36) - there's only one `div` doing layout, the layout, IMO a CSS concern, is in the CSS.

## I guess this from the MD style you're using

Less is good?

```
[+body]
{.heading}
level: 1
text: Heading
{}
{.details}
text: Lorem ipsum dolor et sumit
{}
{.image}
filename: image.png
{}
[]
```
