### ISSUE TITLE
Too few ticks labelled for log axis

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3249]
## Description

- For [this chart](https://ourworldindata.org/grapher/sex-ratio-at-birth-vs-five-years-old?yScale=log&xScale=log), if the y-axis is in log mode, Grapher displays a single tick label only, which makes it difficult to read the chart

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/sex-ratio-at-birth-vs-five-years-old?yScale=log&xScale=log
2. Note that both axes are log-axes
3. Note that the y-axis shows a single label, with many grid lines being unlabelled

## Screenshots

<img width="733" alt="Screenshot 2024-02-27 at 09 08 23" src="https://github.com/owid/owid-grapher/assets/12461810/5fb855eb-4722-4a1b-96b5-bb14b4899cda">

## Additional context

The responsible code is here: https://github.com/owid/owid-grapher/blob/553270fa7ea385663dfd19fb492b5ee25896ad59/packages/%40ourworldindata/grapher/src/axis/Axis.ts#L195

**Comment by danyx23** [comment]
This might still be an issue but the referenced chart was not a legitimate use of log scales. Fixed the chart, closing this issue for now.
