### ISSUE TITLE
Lightbox: Add more features like "Open in new tab"

### ISSUE THREAD

**Issue by MarcelGerber** [owid/owid-grapher#325]
For the new Lightbox preview for embedded pictures (which is great, btw!), I would like some more helpful features.
A great example implementation is the Mediawiki Media Viewer, which can be enabled for Wikipedia. A demo of it can be found here: https://www.mediawiki.org/wiki/Lightbox_demo

* Instead of only being able to download the file, also enable the user to open the actual picture in a new browser tab (it is currently not possible to right-click the image and view it in a new tab; that would help too!)
* Maybe show some kind of title or caption along with the image? Some of the OWID images are already captioned, and these may include important information to understand the context of these images.
* Maybe allow the user to navigate between images, like Mediawiki does?
* We could also show a Share button which makes it easy to copy or send the URL of the image.

When I find some free time (which is quite sparse at the moment), I could look into implementing these features. But maybe we can start a conversation here first.

tagging @mlbrgl because he implemented the Lightbox in the first place.

**Comment by MarcelGerber** [comment]
This is where the suggested features can be found in the Mediawiki example (https://www.mediawiki.org/wiki/Lightbox_demo#/media/File:RhB_Ge_4-4_II_Wiesener_Viadukt.jpg):
![image](https://user-images.githubusercontent.com/2641501/76161646-90e04800-6135-11ea-8b81-914f7d73c098.png)

**Comment by mlbrgl** [comment]
hi @MarcelGerber thanks for your suggestions!

> Instead of only being able to download the file, also enable the user to open the actual picture in a new browser tab (it is currently not possible to right-click the image and view it in a new tab; that would help too!)

What use case are you thinking about?

> Maybe show some kind of title or caption along with the image? Some of the OWID images are already captioned, and these may include important information to understand the context of these images.

I agree

> Maybe allow the user to navigate between images, like Mediawiki does?

Related to your previous suggestion, I actually decided against this to keep a stronger connection between images and their written context. Maybe if we could close the lightbox with the page scroll positioned where the image is in the text, that would create a more bi-directional navigation.

> We could also show a Share button which makes it easy to copy or send the URL of the image.

Yes sharing is being considered, but not to the file itself. As images are often charts, we want to promote them to the first class artefacts that their interactive counterparts are, which will probably require a page of their own.

**Comment by MarcelGerber** [comment]
> What use case are you thinking about?

Hm, I like being able to use the browser features for images, like being able to copy an image to the clipboard without the need to download it.

> Related to your previous suggestion, I actually decided against this to keep a stronger connection between images and their written context. Maybe if we could close the lightbox with the page scroll positioned where the image is in the text, that would create a more bi-directional navigation.

Yes, I think this makes sense since our images are most likely charts (which are, furthermore, mixed with "actual" HTML chart) and so navigating between them might skip some, and will put them out of context because the corresponding text is not displayed.

**Comment by mlbrgl** [comment]
> Hm, I like being able to use the browser features for images, like being able to copy an image to the clipboard without the need to download it.

I see. This is actually not something I chose to disable, my guess is this is a side-effect of how this library intercepts and handles clicks (see demo): https://prc5.github.io/react-zoom-pan-pinch/

**Comment by mlbrgl** [comment]
closing, tracking this internally: [Lightbox feature suggestions](https://www.notion.so/Lightbox-feature-suggestions-76b4e31b66f84c55a6ceb3bf39bfbc81)
