### ISSUE TITLE
Confirm that "baking on change" hangs on staging due to slack notification authentication failing

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3260]
_Needs to be confirmed, saw this in passing_

## Steps to reproduce

1. Edit an article on a staging server
2. Hit publish
3. Is the article published after 5 - 10 min (/admin/deploys)?
4. Check error log `pm2 logs deploy-queue`

**Comment by danyx23** [comment]
Close if it doesn't come up again by March 12
