### ISSUE TITLE
⏳ Add screenshot-based testing

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#3278]
It would be great if we had a tool similar to the svg tester for our main website. Screenshot testing has existed as a preliminary prototype since the Offsite 2023 but we don't have a proper buildkite pipeline step that runs screenshots against the staging server of a PR (of a bunch of important sites, not every single page). 

We should add such a buildkite step and make sure that it reports the status back to github so that image diffs in important pages are something that you are warned about (but can ignore of course if the change was intended)

**Comment by toni-sharpe** [comment]
In a similar space, but not the same

Have you seen [this tool - Chromatic](https://www.chromatic.com/) for StoryBook? I've used it for my site, I think it's quite new, maybe buggy, but does seem to provide a visual comparison across all stories.

(note, these links may break, so the screen-shots will help)

My site is well storied.

It's [pricey](https://www.chromatic.com/pricing) but you're also a charity, an educational institution, open source and open access. Plus, I'm just using the free version and it's showing me errors.

Here's my initial, [actual, sharable StoryBook](https://667670df0aad8c9ddd0c7476-xmbhsqwapl.chromatic.com/?path=/story/sections-histogram--this-could-get-silly-but-useful) focused on a purposefully broken visual (also useful).

<img width="1637" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/c23f082e-d91b-4a86-a7fa-f1d8d223133a">

Here it is now [saying it found visual changes](https://www.chromatic.com/build?appId=667670df0aad8c9ddd0c7476&number=4). I undid my deliberate mistake that removed Histogram colours. That's caused 11 errors, [Here's an example](https://www.chromatic.com/test?appId=667670df0aad8c9ddd0c7476&id=667675f474bfb3167cf8f624)

There's an option "Diff" to toggle difference highlighting which I have turned off so my Histogram appears with hue alternated bars as it should.

<img width="1634" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/8c686f21-086d-48e3-b8d6-80d032bd90b4">

With diff on, the green shows what is actually wrong:

<img width="1634" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/97f493ca-d2c6-4d3f-a82d-40ccb9a8a926">

**Comment by rakyi** [comment]
We implemented a rudimentary version of the screenshot tool: https://github.com/owid/site-screenshots

We'll track improvements in https://github.com/owid/owid-grapher/issues/3921

**Comment by toni-sharpe** [comment]
Hi there Martin, I was not able to view https://github.com/owid/site-screenshots @rakyi

**Comment by danyx23** [comment]
@toni-sharpe the repo was private but not for any good reason - I made it public now.
