### ISSUE TITLE
Baking fails with `TypeError: Cannot read properties of undefined (reading 'toFixed')`

### ISSUE THREAD

**Issue by Marigold** [owid/owid-grapher#3283]
## Description

Baking throws the following error. Seems to be happening to chart `sources-population-dataset`.
```
TypeError: Cannot read properties of undefined (reading 'toFixed')
_HorizontalAxis.place (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/axis/Axis.ts:387:46)
<anonymous> (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx:471:33)
Array.map (<anonymous>)
DiscreteBarChart.render (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx:462:25)
Object.allowStateChanges [as _allowStateChanges] (/home/owid/owid-grapher/node_modules/mobx/lib/mobx.js:991:15)
/home/owid/owid-grapher/node_modules/mobx-react/index.js:851:28
trackDerivedFunction (/home/owid/owid-grapher/node_modules/mobx/lib/mobx.js:776:24)
Reaction.track (/home/owid/owid-grapher/node_modules/mobx/lib/mobx.js:1806:22)
DiscreteBarChart.reactiveRender [as render] (/home/owid/owid-grapher/node_modules/mobx-react/index.js:845:16)
DiscreteBarChart.makeComponentReactive (/home/owid/owid-grapher/node_modules/mobx-react/index.js:915:27)
```

## Steps to reproduce

1. `ssh owid@staging-site-mojmir`
2. `rm ~/live-data/bakedSite/grapher/*.html`
3. `rm ~/live-data/bakedSite/grapher/exports/*`
4. `yarn buildTsc && yarn buildLocalBake http://staging-site-mojmir /home/owid/live-data/bakedSite --steps embeds charts`

Feel free to mess up the staging server as you like. I changed the baking script to only run for the problematic chart.

**Comment by larsyencken** [comment]
Fixed by @sophiamersmann's PR!

**Comment by marcelgerber** [comment]
I went into a bit more of a dive into this, and here is my investigation:

- In `tableAfterAuthorTimelineAndActiveChartTransform`, the chart instance transforms _don't_ run if we're not on a chart or map tab:
https://github.com/owid/owid-grapher/blob/2f1fd031f307e3864a6deefc0fdc06934f0a9761/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L744-L749
- In `StaticCaptionedChart`, we _always_ call `renderChart()`, even when on the table tab (as opposed to `CaptionedChart`, where we call either depending on the tab): https://github.com/owid/owid-grapher/blob/2f1fd031f307e3864a6deefc0fdc06934f0a9761/packages/%40ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx#L611
- `renderChart` can render chart or map, but it will always render one of these two, even if we're on a table tab: https://github.com/owid/owid-grapher/blob/2f1fd031f307e3864a6deefc0fdc06934f0a9761/packages/%40ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx#L231-L232

Will try to fix this at the source.
