### ISSUE TITLE
Homepage – small tweaks

### ISSUE THREAD

**Issue by JoeHasell** [owid/owid-grapher#3290]
Here we are keeping a list of small tweaks we'd like to make to the new homepage design.

- [x] mission statement + remove separators ([Slack](https://owid.slack.com/archives/C06CWPLE3QE/p1709137500754539))
- [x] ~'Latest' button spacing on mobile~ ([Slack](https://owid.slack.com/archives/C06CWPLE3QE/p1710498056726269)) 
  - Ike: we can't fix this, see slack thread
- [x] A solution to make the the behaviour on mobile more intuitive – i.e. that issue that you have to click again to type in the search box
   - [Slack discussion](https://owid.slack.com/archives/C06CWPLE3QE/p1709251496930519)
   - One possible solution would be that we keep the hint text in the search box
   - But perhaps there are other solutions we should consider? That the search box has an outline or something to make it clear that it is an input field? (I'm wondering if it will be weird if the hint text stays exactly the same – that people will just think it's broken?)
- [x] Use sentence case in the hint text ([Slack](https://owid.slack.com/archives/C06CWPLE3QE/p1709628587042409?thread_ts=1709573436.539279&cid=C06CWPLE3QE))
- [x] Round number of charts appropriately when mentioned under 'Explore our data' ([Slack](https://owid.slack.com/archives/C03NV9Z3YSV/p1709144905955409))
- [x] Replace charts count with 'chart + explorer views' count ([Slack](https://owid.slack.com/archives/CQQUA2C2U/p1710348753860539))

**Comment by danyx23** [comment]
@JoeHasell in what timeframe do you think these should be fixed? Is this a "please do it in the next two weeks" or a "let's consider this for a future batch project"?

**Comment by JoeHasell** [comment]
Hey @danyx23, while none of it is extremely urgent, I was thinking it could make sense for Ike to spend ~ 1 day of work max. to tick a few off – either before getting into search in earnest, or in cracks of time during the project.

**Comment by danyx23** [comment]
@ikesau can this issue be closed?

**Comment by larsyencken** [comment]
Closing this as all todos have been done.
