### ISSUE TITLE
Tracking issue: metadata editing improvements

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3303]
_A home for follow-on work after https://github.com/owid/owid-grapher/pull/3106._

- [ ] No visual indicator of success on successful edit (e.g. success text)
- [x] No feedback on whether an "instant edit" or "eventually consistent edit" has been made
  - For "eventually consistent edits", we want to tell someone that their edit could take a few minutes to be reflected in the admin
  - Ideally we could mark the indicator as dirty and prevent further edits until the first one went through

**Comment by Marigold** [comment]
I had to [disable it](https://github.com/owid/owid-grapher/pull/3325) after merging. There are two more issues with metadata edits:

1. Browser doesn't allow fetching from HTTP (http://etl.owid.io/api/v1/health), which means we'll have to put it behind https first and use Cloudflare auth
2. Changing chart type triggers form submit for some reason (need to investigate more)

**Comment by ikesau** [comment]
Hey @larsyencken is this still a tracking issue? If so, I removed `needs triage`. If not, can you please triage it? 🙂

**Comment by Marigold** [comment]
It's ready, and I'm about to announce it. I haven't implemented "No visual indicator of success on successful edit", but loading indicator is enough in my opinion (you get a modal with error on failure).
