### ISSUE TITLE
Discover: add explorer views into search index

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3332]
## What

Experiment with adding all explorer views to the search index and returning them as search results. Decide whether this is a plausible direction for us to pursue this cycle.

## Why? Why now?

- We want search to be able to reach all of our work
  - For some of our charts, the only place they exist is as an explorer view
- With multi-dimensional indicators, we intend to have less charts and more explorer views

## Technical notes

- We may need good explorer-view-level pageview data in order to rank them well
- Some explorer views are also available as standalone Grapher charts
- Some explorer views are duplicated by standalone Grapher charts

**Comment by larsyencken** [comment]
@marcelgerber I think we could call this discovery done. This is now something that looks worthwhile to do, I'll add a cycle task for implementing it, but that one will be blocked on design for now.

**Comment by marcelgerber** [comment]
For future reference, the main outcomes of this discovery phase has been:
- #3350, which does the indexing to Algolia
- [An Algolia UI demo](https://dashboard.algolia.com/interface-demos/8332179b-12f0-4d87-82a9-ebf459618d3f?utm_medium=page_link&utm_source=dashboard) of that interface, running off the `staging.explorer_views` index
- A prototype search interface that includes explorer views, up at http://staging-site-search-explorer-indexing-algolia/search
