### ISSUE TITLE
Hide "Align axis scales" toggle if faceted charts have different units

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3336]
## Description

- In [this faceted chart](https://ourworldindata.org/grapher/weather-forecast-spending), one metric is measured in $, the other one is measured in %
- We show a toggle to align axis scales, but a shared axis doesn't make sense for different units

## Expected behaviour

Don't display the "Align axis scales" toggle in such cases

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/weather-forecast-spending
2. Click on Settings
3. Toggle "Align axis scales"
4. Note that the view doesn't make sense

## Screenshots

<img width="1094" alt="Screenshot 2024-03-13 at 09 13 31" src="https://github.com/owid/owid-grapher/assets/12461810/ad3dd948-3931-4143-a173-a25f599dc5d0">

**Comment by danyx23** [comment]
Probably not worth the effort
