### ISSUE TITLE
Images do not render in local dev environment

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3339]
## Problem

When you spin up a local dev environment with `make up` or `make up.full`, you get a working site but without any working images.

This is not great, since our dev environment is where we work and test the site; we want it to be a faithful reproduction of the live site.

<img width="1624" alt="Screenshot 2024-03-13 at 15 13 06" src="https://github.com/owid/owid-grapher/assets/36012/4c8e328f-439d-444b-bfd0-251fc4b6a2b1">

**Comment by larsyencken** [comment]
A potential workaround in: https://github.com/owid/owid-grapher/pull/3241

**Comment by mlbrgl** [comment]
related [slack](https://owid.slack.com/archives/CQQUA2C2U/p1710329413341919)

**Comment by ikesau** [comment]
You have to run `make sync-images` and then `yarn buildLocalBake --steps gdriveImages` then they'll be there
