### ISSUE TITLE
Cycle 2024.2: Entity selector

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3349]
[Project outline](https://docs.google.com/presentation/d/1ePEn9c-W-phi9TdFDr9a0Su4xgDgnZ2kKE1GNPrPXXk/edit#slide=id.g2c0c459a70a_2_172) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)

### Must do

- [x] (prep) Always use the popup for chart settings (don't use the slide-in drawer)
- [x] Rearrange Grapher's layout on Grapher and Data pages
    - [x] On larger screens, show the entity selector to the right of Grapher
    - [x] On smaller screens, use the slide-in drawer for the entity selector
        - Reuse the slide-in drawer that we used to use for settings
    - [x] On narrow screens, render the entity selector into a modal (similar to the current behaviour)
- [x] Update the entity selector's visuals and add smaller new features
- [x] Add a dropdown to sort by entity name or by indicator
    - [x] Draw a bar graph in the background for each entity if a quantitative indicator is used for sorting
- [x] Add population and GDP per capita to the dropdown if applicable

### Should do

- [x] Fix #3393 for the explorer's and grapher's entity selector

### Could do

- [x] Highlight the user's current location

### Won't do

- Render Grapher into a 12-column grid on Grapher pages (or, if that turns out to not actually be desirable, improve Grapher dimensions in other ways)
- Queries that match known region names include all countries within that region

### Stack (ongoing work)

- (reviewed) https://github.com/owid/owid-grapher/pull/3353
- (reviewed) #3373  
- (reviewed) #3434
- (reviewed) #3435
- (reviewed) #3436
- (reviewed) https://github.com/owid/owid-grapher/pull/3447
- (reviewed) https://github.com/owid/owid-grapher/pull/3452
- (reviewed) https://github.com/owid/owid-grapher/pull/3466
- (reviewed) https://github.com/owid/owid-grapher/pull/3490
- (reviewed) https://github.com/owid/owid-grapher/pull/3500
- (reviewed) https://github.com/owid/owid-grapher/pull/3501

**Comment by larsyencken** [comment]
Done! \o/
