### ISSUE TITLE
Gdrive images replaced with same filename don't get rebaked

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#3355]
see [slack](https://owid.slack.com/archives/C6C0MCXU0/p1710506566596149?thread_ts=1710500397.081089&cid=C6C0MCXU0) for 2 failures (and a mention of a third)

Workaround: deleting all image variants in `owid-cloudflare-prod:live-data/bakedSite/images/published` and rebaking manually.

Should be revisited as part of https://github.com/owid/owid-grapher/blob/ee360374cc36846f7332923dbce72e2321ed51fe/baker/GDriveImagesBaker.tsx#L31-L38

People started using [workarounds to bypass the "cache"](https://owid.slack.com/archives/C6C0MCXU0/p1710510961474529?thread_ts=1710500397.081089&cid=C6C0MCXU0) and @mrwbkrm [might need to update more featured images](https://owid.slack.com/archives/C6C0MCXU0/p1710515651326769?thread_ts=1710500397.081089&cid=C6C0MCXU0) - so this probably needs more immediate attention.

Issue compounded by #3364

**Comment by ikesau** [comment]
Gdrive images never rebaked the site when images changed, you had to manually rebake the site

I think the etag name only including the filename is biting us here, though. if we included the gdrive id in the tag this would work correctly again.

**Comment by danyx23** [comment]
We anticipate that we'll switch to CF Images in the near future - we therefore think we should not invest time in fixing this issue in the current setup.
