### ISSUE TITLE
Allow date spans that are not covered by the data

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3387]
## Problem

If you embed a number of charts in a page, and you are speaking about the same time period with all of them, you want to use the same time period in all charts.

However, if you use `?time=2000..2025` in all charts, you will find that the x axis of the chart does not properly clip to the time range, unless it's a subset of the time range.

E.g. if the most recent data is 2015, the x axis max will remain at 2015

## Impact

Impact of this issue is low, it's mainly helpful for external embedding, since in our articles we prefer to show the full time series of each indicator rather than a fixed period of common decades in our reporting.

I'm mainly reporting it here as optional polish.

**Comment by danyx23** [comment]
Discussed this in triage - this would probably require a special flag as the current timeline logic trimming is pretty deeply engrained in the table logic. Decided to close this for now but feel free to petition for it again :)
