### ISSUE TITLE
Data pages sometimes don't preview in staging

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3415]
## Problem

These two indicators have the same fields, but this one does not render as a data page:

http://staging-site-improve-faostat-metadata/grapher/almond-yields

but this one does:

http://staging-site-improve-faostat-metadata/grapher/cereal-yield

## Replicating it

It doesn't happen on local grapher or in prod.

**Comment by danyx23** [comment]
I'll check if this is still happening so we can properly triage it

**Comment by danyx23** [comment]
Couldn't repro this on http://staging-site-wasm-notebooks/, closing the issue for now, feel free to reopen if it happens again

**Comment by sophiamersmann** [comment]
I think this is what happens on my staging site: http://staging-site-table-timeline/grapher/natural-disasters-by-type
