### ISSUE TITLE
Implement new designs for explorer views in search results

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3416]
## What

![CleanShot 2024-04-03 at 17 57 36](https://github.com/owid/owid-grapher/assets/2641501/3284c403-340a-4b0f-971d-9b00765a39ec)

[Figma styles here.](https://www.figma.com/file/36r4ZDrt0c4YdOGVduSjQm/Search-1.0-%2B-1.1?type=design&node-id=1340%3A18843&mode=design&t=C9SqsZz9KItY5Tm4-1)

- [ ] Desktop styles
	- [ ] Full-width card with 2 columns, 2 rows
	- [ ] If view subtitle is missing, add placeholder line
	- [ ] Truncate subtitle at end of line
	- [ ] "Explore ... indicators" link in the top-right
	- [ ] Only show first explorer, unless clicking through to the Explorers tab
- [ ] Mobile styles
	- [ ] Full width, single column card
	- [ ] Only show first 2 views on card
	- [ ] Hide subtitle

**Comment by marcelgerber** [comment]
Completed in #3429 and merged with #3497.
