### ISSUE TITLE
Store customizations locally?

### ISSUE THREAD

**Issue by peteruithoven** [owid/owid-grapher#343]
Especially for a page like the [Coronavirus](https://ourworldindata.org/coronavirus) one where there are frequent updates I'd love it if the grapher would remember my customizations. I'm mostly thinking about selected series (countries), but maybe also the selected time period (slider). 

Maybe this could be saved locally in localstorage or IndexDB? 

I understand this has some limitations, it will get removed when the computer needs the space or when the user clears his browser data. It's also impossible to share to other computers.

**Comment by MarcelGerber** [comment]
While this may still be useful, there's another way to achieve a similar effect.

If you click through to a chart, you can see how each added country, each timeline change, etc. is reflected in the page URL. You can then copy/bookmark this URL and will receive the exact same chart.

For example, https://ourworldindata.org/grapher/total-cases-covid-19-who?yScale=log&country=OWID_WRL+DEU+ITA+NLD+USA+CHN will show you a (logarithmic) chart of the total Covid19 cases worldwide and in Germany, Italy, the Netherlands, USA and China.

**Comment by peteruithoven** [comment]
Ah! Very handy! 
I didn't realize because I only customized the graphs on the large page. 

No clue how you would clarify that this is possible. This could only use clarification when a graph is used in a bigger page. Maybe an extra link / tip can appear after a customization?

**Comment by MarcelGerber** [comment]
One thing to keep in mind here, though, is that this feature request is most useful for the Covid pandemy with its ever-changing datasets. In more normal times, OWID provides more "stale" datasets that are not updated daily, and where it doesn't really make sense to check back each and every day.
While Covid is the most-visited page at the moment, hoepfully it will not stay this way and the world (and OWID) will return to a more normal state soon.

Btw, if you click the Share button on an (embedded) chart, it automatically shares the full URL of it, so you get the exact same chart config once the link is clicked on Twitter/Facebook.

**Comment by MarcelGerber** [comment]
I'm going to close this issue now.

There have been a few usability improvements in the meantime, most notably:
* a big page-wide country selector at the top of pages like https://ourworldindata.org/covid-deaths, which makes selecting a country in _all_ charts on a page way easier
* the new data explorer (https://ourworldindata.org/coronavirus-data-explorer), which lets you build your own chart and where you can click through different metrics and configurations quickly. In it, the URL also contains the whole configuration, just as for other charts.
