### ISSUE TITLE
Grapher chrome malformed on mobile Safari

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3461]
## Problem

We had a surprising and persistent case of grapher being broken on mobile Safari:

<img src="https://github.com/owid/owid-grapher/assets/36012/06bf51c7-c75a-4de1-9c18-aba9154f7a5e" width=300 />

It happened on an iPhone 14 running iOS 17.3.1.

## Impact

We could not reproduce it on:

- Desktop Safari (17.4.1, on Sonoma 14.4.1)
- Desktop Chrome (123.0.6312.107 arm64, on Sonoma 14.4.1)
- Mobile Safari (iPhone 11, iOS 17.3.1)
- Mobile Chrome (123.0.6312.52, iPhone 11, iOS 17.3.1)

This suggests that it's an unusual situation that caused the issue.

**Comment by marcelgerber** [comment]
I'm not entirely should how this would happen: I checked, and we're sending out `owid.css` with `Cache-Control: public, max-age=0, must-revalidate`, meaning that Safari should've checked owid.css for staleness in either case. But, in actuality, it seems to have re-used a cached version of the asset.

It could've been some caching server on the route? I don't think it's gonna be CF, especially not many hours after the deploy - but could've been your ISP, maybe. That's my best explanation, anyway.

**Comment by danyx23** [comment]
This was probably a cache issue - closing this issue
