### ISSUE TITLE
Factor out Country name standardizer

### ISSUE THREAD

**Issue by abitrolly** [owid/owid-grapher#348]
**Country name standardizer** is used by at least https://github.com/owid/covid-19-data#ecdc-data and I couldn't find a public interface for it to repeat the manual operation described there. As a dependency for another project, it deserves a separate project page with `README.md` and command line interface. 

I came for it, because there is some problem with linefeeds in repository data and it is not possible to check who is guilty without repeating the steps - https://github.com/owid/covid-19-data/commit/2ed20b1802175d60b1341bff313ddac2a63ed507#diff-6f46ed18121f7c246acefd9f58a920dc - ideally the Python pipeline should be able to handle the errors in console. Although without describing what this tool really does it is hard to replicate this functionality.

**Comment by danyx23** [comment]
Hi @abitrolly! Sorry for the late reply, we're just cleaning up issues here and making some improvements to the issues. We have it on our roadmap to improve the standardizer but it will probably be a while before this is useable standalone. If you have found another solution by now then please close this issue, otherwise you can keep it open and we can add here when we get to implementing this

**Comment by larsyencken** [comment]
@abitrolly This has now been implemented in a different repo: https://github.com/owid/etl/blob/master/etl/harmonize.py

You would generate the mappings by doing something like:

```
git clone --recurse-submodules https://github.com/owid/etl
cd etl
make .venv
# do interactive country name harmonization on myfile.csv
.venv/bin/harmonize /path/to/myfile.csv country_column /path/to/output.json
```

The country renamings then appear in the `output.json` you created.

**Comment by abitrolly** [comment]
I don't quite remember why I needed this. I guess it was messing with this dashboard (https://city.opendata.by/). Good it is finally fixed.

**Comment by larsyencken** [comment]
It turns out we needed a better flow anyway :)
