### ISSUE TITLE
Allow unbounded parameters in time URL argument

### ISSUE THREAD

**Issue by abitrolly** [owid/owid-grapher#349]
This is a request to support partial ranges in `time` argument in URL.

[https://ourworldindata.org/grapher/covid-cases-by-source?**time=35..**&country=BLR](https://ourworldindata.org/grapher/covid-cases-by-source?time=35..&country=BLR)
[https://ourworldindata.org/grapher/covid-cases-by-source?**time=..**&country=BLR](https://ourworldindata.org/grapher/covid-cases-by-source?time=..&country=BLR)
[https://ourworldindata.org/grapher/covid-cases-by-source?**time=..53**&country=BLR](https://ourworldindata.org/grapher/covid-cases-by-source?time=..53&country=BLR)
[https://ourworldindata.org/grapher/covid-cases-by-source?**time=..**&country=BLR](https://ourworldindata.org/grapher/covid-cases-by-source?time=..&country=BLR)

---

The default time frame for widget is 2020-02-22 to 2020-03-17. Today is 2020-03-24. Is it calculated dynamically or configured?
https://ourworldindata.org/grapher/covid-cases-by-source/?country=BLR

![image](https://user-images.githubusercontent.com/8781107/77387956-db9dc900-6d9f-11ea-8643-ec41aff05e95.png)

I'd like to embed graph with latest info and for that I need to drag the time handles manually. This changes the link to https://ourworldindata.org/grapher/covid-cases-by-source?time=1..62&country=BLR

I tried replacing **`time=1...62`** with partial range **`time=35..`** to make the end of period unbounded and that doesn't work.
https://ourworldindata.org/grapher/covid-cases-by-source?time=35..&country=BLR

![image](https://user-images.githubusercontent.com/8781107/77388494-5c10f980-6da1-11ea-9ec1-ed28f7424a85.png)

The URL is reset to a single day and even barchart doesn't show https://ourworldindata.org/grapher/covid-cases-by-source?time=35&country=BLR (well it appears that bar chart is shown, but because vertical axe is in the center instead of being positioned right near the labels, it looks like a bug in widget).

**Comment by abitrolly** [comment]
https://github.com/owid/owid-grapher/blob/22fcd6b3dd0e1aa5a7270c29412e137ce97116de/charts/ChartUrl.ts#L227-L235

**Comment by danielgavrilov** [comment]
This is a great idea @abitrolly, thanks for suggesting. 

We have implemented it and it will be deployed sometime in the next 3 hours.

**Comment by abitrolly** [comment]
@danielgavrilov thanks! You may see it in action here - https://city.opendata.by/ 

By the way, do you know how to prevent iframe caching? I had to press `Shift-F5` to get the dashboard even though the rest of the static page was updated successfully. Is it something controlled on the server side?
