### ISSUE TITLE
Automatically clean up unused Algolia staging indexes

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3563]
## Context

When you do search work, and use `-algolia` in a branch name, you will get staging Algolia indexes created for your branch.

## Problem

When you are finished with your branch, your staging server will get cleaned up, but the staging Algolia indexes will not be pruned -- they will linger on in Algolia.

## Workaround

We periodically just go and click delete on a bunch of out of date indexes there.

**Comment by mlbrgl** [comment]
(yes that's true about apps, but not sure about indexes)

**Comment by danyx23** [comment]
@Marigold would it be easy to add deleting algolia indexes when the staging servers are deleted? That would probably be the best way of solving this.

**Comment by danyx23** [comment]
@Marigold ping :)

**Comment by Marigold** [comment]
Uh, where can I find these indexes, please? I've [created a PR](https://github.com/owid/owid-grapher/pull/3687) with name `algolia-delete-index` which should create algolia index, but I don't see any in [Algolia UI](https://dashboard.algolia.com/apps/ASCB5XMYF2/indices) (I even ran `make reindex` from the staging server). @marcelgerber what am I missing?

**Comment by marcelgerber** [comment]
@Marigold you need to be looking at the `owid-staging` Algolia application, not `live`. You have access to both under same account.

This link should bring you directly to it: https://dashboard.algolia.com/apps/74GKBOIDJQ/indices

**Comment by Marigold** [comment]
Fixed by https://github.com/owid/owid-grapher/pull/3777
