### ISSUE TITLE
Remove Wordpress from the dev setup

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3565]
## Context

We have just eliminated Wordpress from our stack, but we have not yet removed it from our dev environment.

## Proposed improvement

Remove Wordpress db fetching and spin-up from the `make up.full` step.

If this makes `make up.full` basically empty, prune `make up.full`.

## Technical questions

- Do we want to preserve a different Makefile flow between the public and staff
  - E.g. should `.env.example-full` become `.env.example-staff` ?
- Is it clear what .env variables and what data you need for a full local dev experience for staff?

**Comment by larsyencken** [comment]
@rakyi I think this could be a good one for you, since it involves ensuring our dev setup is actually coherent for both the public and for staff.

**Comment by marcelgerber** [comment]
There's some work on this already happening at #3520.
