### ISSUE TITLE
Charts get stretched to full-width on a laptop, looking weird

### ISSUE THREAD

**Issue by MarcelGerber** [owid/owid-grapher#358]
On my laptop, every chart I'm looking at is stretched to full width, which looks very weirdly stretched out.

![image](https://user-images.githubusercontent.com/2641501/77805992-af29cb80-7083-11ea-9588-0567683bc453.png)

My 14" laptop is set to a 1920x1080 resolution and is set to 125% display scaling in the Windows settings.

---
I've traced this issue down to the following:
`ChartView.fitBounds` returns true because of this check (with `containerBounds.height = 529, authorHeight = 600`):
https://github.com/owid/owid-grapher/blob/c37e39205e3e29288c79b04599f9b2741c00d6ff/charts/ChartView.tsx#L165

Therefore, `renderWidth` goes with the full container width:
https://github.com/owid/owid-grapher/blob/c37e39205e3e29288c79b04599f9b2741c00d6ff/charts/ChartView.tsx#L195-L198

The limited available height comes from this rule:
https://github.com/owid/owid-grapher/blob/c37e39205e3e29288c79b04599f9b2741c00d6ff/site/client/css/pages/chart.scss#L10-L12

---
I don't know what the ideal solution to this issue should be, but maybe we can impose a maximum width on the chart?

**Comment by danielgavrilov** [comment]
You are again spot on @MarcelGerber, we've received this feedback 3-4 times just in the last few weeks.

I think the ideal fix is that all sizing logic is defined in one place, but I've nevertheless created a PR that does the opposite: #375

Let me know if you have any ideas how it can be solved better!
