### ISSUE TITLE
Change the position of the newsletter signup form on the homepage

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3587]
In the recent homepage redesign, we moved the newsletter susbcription form further down the screen and this has affected signups.

![image](https://github.com/owid/owid-grapher/assets/11844404/50d316e7-a614-4f97-92d5-fd8e2cbea566)

We should move find a place further up to move it and see if that affects signup rates. 

This entails creating a `newsletter-signup` component in archie so that we can position it betwixt the rest of our content (possibly between the intro block and data insights?)

We may want to redesign it so that it's only the newsletter signup and not the socials, though, because no one clicks on those social buttons anyway.

**Comment by danyx23** [comment]
Joe doesn't want us to spend time on this rn - will maybe reconsider in the future
