### ISSUE TITLE
Homepage article thumbnails are full sized

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3590]
For some reason, the homepage article thumbnails are loading the source image instead of the resized source. This is a waste of bandwidth and is probably hurting our core web vitals score.

https://github.com/owid/owid-grapher/assets/11844404/99676b7b-1f8f-4e6c-a9e2-cea70551cc83

**Comment by toni-sharpe** [comment]
That's not what I'm getting, below is FireFox and Chrome, same video as above, cache disabled in the inspector with inspector open so it's definitely affecting the page, plus a cmd+shift+R full cache reload performed before each video (so I have the latest live version).

## Firefox (shows 850px)

https://github.com/owid/owid-grapher/assets/10499070/4e9cc9c3-405f-40ab-9610-5e1dec16bce5

## Chrome (shows 350px)

https://github.com/owid/owid-grapher/assets/10499070/27ec1e3e-92a3-4474-b4b6-29cd4665a813

I've noticed some more modern image types, picture tags, srscsets and other good perf. stuff, but it's not so easy as an img tag, and browsers don't behave alike, necessarily. Maybe that's somewhere to look?

[This article comes from the Calibre perf. newsletter](https://frankstall.one/blog/faster-websites-with-the-picture-element/), maybe it is useful.

Locally images aren't loading for me (yet) so I'll need to fix that first to look really deeply.

**Comment by ikesau** [comment]
Ah sorry everyone, I fixed this in #3487 yesterday, forgot to link this issue. Thanks for the support 🙂 

https://github.com/owid/owid-grapher/pull/3487/commits/4e25054581c5eef1dfe727a4771291107898a9f2#diff-66cf2bf35b952b9935f6f2b4557fc3872c89e4ddad51a64d5e9eb0f049f8ab38R77
