### ISSUE TITLE
What examples are there of the React element?

### ISSUE THREAD

**Issue by davidbernat** [owid/owid-grapher#362]
I am interested in using the React elements for chart rendering without the SQL backend. From the Readme of this repository that seems possible. But, I actually wouldn't even know where to start. 

What are the primary classes and objects in the React library?

Thank you for this level-zero question! :-D

**Comment by breck7** [comment]
The immediate answer is that this is not currently possible but there is agreement that this would be nice to have (https://github.com/owid/owid-grapher/issues/84).

Is there one chart in particular you would really like to reuse?

**Comment by davidbernat** [comment]
There are two that really stand out to me:

This geospatial dataset that can be scrolled through time:
<iframe src="https://ourworldindata.org/grapher/children-per-woman-UN" style="width: 100%; height: 600px; border: 0px none;"></iframe>

And a similar one with line graphs.
<iframe src="https://ourworldindata.org/grapher/child-mortality-around-the-world" style="width: 100%; height: 600px; border: 0px none;"></iframe>

It seems like as of right now the process for creating these is to upload the data into the SQL database, then request a chart, and the system will produce a src data file. Is the simplest approach to go that offline and then use a data url as a drop-in?

Separate question: what would be necessary to make React library? How many hours?

**Comment by breck7** [comment]
> It seems like as of right now the process for creating these is to upload the data into the SQL database, then request a chart, and the system will produce a src data file. 

Yes that's currently the process.

> Is the simplest approach to go that offline and then use a data url as a drop-in?

It might be a bit tricky because the interface we currently use for defining our data is very hard-wired to the SQL schema.

> what would be necessary to make React library? How many hours?

I've started a branch https://github.com/owid/owid-grapher/tree/tabular where I am working on adding support to simply use tabular data with our charts, as well as easier support to use the Grapher client charting library standalone. I don't have an ETA yet but could be relatively soon.

**Comment by davidbernat** [comment]
Hi Breck,

Thank you for your response. I haven't yet inspected the code, so this is
me operating on a hunch. Is it possible that you (knowing the system well)
could use an in-memory SQL-like module in Python to simply mock up the
necessary SQL database directly in Python from in memory data (such as a
CSV or Pandas object, etc).

Is the SQL database required for rendering the chart? In other words, does
the src link produced by the process you describe render an endpoint that
the points to the server to make an SQL database operation? Or is it
possible to transmit the data directly in the src url such as using a data
URI <https://en.wikipedia.org/wiki/Data_URI_scheme> schema.

Thank you so much!
David

**Comment by breck7** [comment]
Hi David,

Technically you can now load a Grapher chart without the SQL database by defining, in a chart config object, one of the following alternative data sources: externalDataUrl, owidDataset, or tabularData. The first 2 require a JSON object in our domain specific variable interface, though technically the SQL database is no longer required.

The third `tabularData` option would take in something akin to a Pandas object or CSV, but I would call it "pre-alpha" as it's only used for debugging at the moment and hasn't been fully developed or documented .

So there really is not a good way yet to do what you want to do, but I agree it would very nice to have and wanted to update you that we are hopefully inching our way in that direction.

-Breck

**Comment by breck7** [comment]
Consolidating these requests to https://github.com/owid/owid-grapher/issues/756
