### ISSUE TITLE
Decrease size of public JS bundle

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#367]
Currently, `commons.js` is ≈2.0MB non-compressed, ≈734KB compressed.

We only care about reducing `commons.js` and `owid.js`, the rest are not public.

To visualise the **webpack JS bundle**, run:

    ./node_modules/.bin/webpack --json --cache false --mode production > webpack-bundle-stats.json

Then drag and drop stats.json into https://chrisbateman.github.io/webpack-visualizer/

<img width="760" alt="Screenshot 2020-03-31 at 12 01 38" src="https://user-images.githubusercontent.com/1308115/78019386-8afe1100-7347-11ea-9941-da5622405487.png">

Lodash appears to be the heaviest of all – it's likely that with tree-shaking we can reduce the size. Likewise for other modules – we are likely not using a lot of the code in the bundle.

**Comment by MarcelGerber** [comment]
Btw, there's been another improvement on this front: [Netlify now has Brotli compression enabled by default](https://www.netlify.com/blog/2020/05/20/gain-instant-performance-boosts-as-brotli-comes-to-netlify-edge/), which brings text assets down a few percent more and is supported in basically all browsers.

This now brings `commons.js` down to 414KB compressed.
