### ISSUE TITLE
Topic page featured images are not consistent with current design

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#3674]
## Description

There are several topic pages using custom-made featured images that are not consistent with the current design. These were made before such definition.

## Expected behaviour

All the topic pages thumbnails should look consistent.

## Screenshots
This is an example of the current design of featured images for topic pages:
![image](https://github.com/owid/owid-grapher/assets/63430031/993232be-bfdc-4688-beaf-532fac2e5cd5)

These designs are some of the ones that are custom-made
![image](https://github.com/owid/owid-grapher/assets/63430031/790b9f68-fa0b-4ad3-862b-7564ea41b113)
![image](https://github.com/owid/owid-grapher/assets/63430031/9e6f8045-a3aa-4539-add1-67ff229de680)
![image](https://github.com/owid/owid-grapher/assets/63430031/591e95d8-16a0-4b9a-8d25-3dc919eda91c)
![image](https://github.com/owid/owid-grapher/assets/63430031/901081da-240c-429c-8474-a774a6aa7c43)

## Additional context

- [Conversation in Slack](https://owid.slack.com/archives/C5BDCB2R3/p1716231313861679).
- In the conversation it seems that not all the cases have been captured, so we need to review the complete list of topic pages.

**Comment by danyx23** [comment]
@ikesau is this still relevant or have you done something about this already?

**Comment by ikesau** [comment]
Painful lack-of-owner scope creep here. Originally all I'd wanted to do was update the LTPs that had random cropped charts as their featured images! 

Marwa was fine with these custom thumbnails I think, but I've updated them to the standard ones so that we stop having to think about this at all 😅
