### ISSUE TITLE
Remove `citation_author`meta tags for author pages

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3682]
Not only is the Max Roser fallback wrong in this case, these aren't pages that should have citations at all

**Source:**
<img width="900" alt="image" src="https://github.com/owid/owid-grapher/assets/11844404/9dc82b04-d94d-44e5-9c34-ae8bb9bf9bf3">

**Google result:**
<img width="631" alt="image" src="https://github.com/owid/owid-grapher/assets/11844404/24d16ea6-644a-43e9-b7e1-07b3652ed591">

**Comment by bnjmacdonald** [comment]
@ikesau – looks like author pages still have this issue on Google, despite the removal of the `<meta name="citation_*" ...>` tags. 

<img width="653" alt="Screenshot 2024-07-04 at 2 41 13 PM" src="https://github.com/owid/owid-grapher/assets/11767602/e84834d6-385c-46ae-a147-6f8df31cfe70">

Google Search Console says the page was last crawled on July 3rd, and the crawled page doesn't have the `<meta name="citation_*" ...>` tags. 

<img width="1352" alt="Screenshot 2024-07-04 at 2 39 20 PM" src="https://github.com/owid/owid-grapher/assets/11767602/e3be632b-6a06-4aa5-b5d0-c6d102aab58f">

So am not sure if this is just something we need to continue waiting on Google to reflect the changes or if anything else needs to be done.

**Comment by rakyi** [comment]
I don't have experience with this, but after a brief search, one option might be to request removal of author pages from the search results temporarily. We could also try contacting Google about this. Hopefully Ike will know more.
