### ISSUE TITLE
Cloudflare apps support discontinued for africaindata.org

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3696]
<img width="614" alt="Screenshot 2024-06-07 at 14 18 07" src="https://github.com/owid/owid-grapher/assets/36012/ce0f7e38-8f65-4f45-9436-7df264d80e12">

**Comment by marcelgerber** [comment]
I don't think that's a big issue; only thing is that we won't receive Google Analytics any more.
If we want to keep getting analytics data, we can set it up another way.

**Comment by larsyencken** [comment]
No worries, I'll close it then.
