### ISSUE TITLE
Grapher style leak in key indicator collection

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3701]
There is a style leak in the Sources modal for Graphers that embedded in a key indicator block:

<img width="1288" alt="Screenshot 2024-06-10 at 16 36 49" src="https://github.com/owid/owid-grapher/assets/12461810/9c799a97-a834-44eb-9a1e-630f6fef7aaf">

**Comment by toni-sharpe** [comment]
@marcelgerber could I have a little more detail on this one, I could fix it I think :-)

**Comment by danyx23** [comment]
@toni-sharpe the styling in grapher's sources panel is wrong when embedded on the main website in the featured data block. We have these kinds of css issues with some regularity - you can see some previous PRs that fixed similar issues here: https://github.com/owid/owid-grapher/pulls?q=is%3Apr+is%3Aclosed+style+leak

**Comment by toni-sharpe** [comment]
@danyx23 can I get an example of what it should look like?

**Comment by toni-sharpe** [comment]
1. I go here: https://ourworldindata.org/
2. Scroll to: What share of children die before their fifth birthday?
3. Look in the graph on the right for "Learn more about this data"
4. Click that, so the screen looks like this

<img width="666" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/d41f3428-46f2-45e5-a3aa-438434d12943">

**Comment by toni-sharpe** [comment]
Hope [this is fixes it](https://github.com/owid/owid-grapher/pull/3754), it's what I could find.
