### ISSUE TITLE
Track requests to our atom feed endpoints

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3706]
It would be handy to see how many requests are being made to our atom feeds

https://ourworldindata.org/atom.xml
https://ourworldindata.org/atom-data-insights.xml

Cloudflare Analytics doesn't give us enough information to calculate this, so I think we'll need to make a worker for it.

![cloudflare network analytics](https://github.com/owid/owid-grapher/assets/11844404/91e1d2bf-4583-4fee-8e92-720bf1f11564)

**Comment by marcelgerber** [comment]
Hi @ikesau, I don't think we do, we can do this with Cloudflare Analytics filters:

https://dash.cloudflare.com/078fcdfed9955087315dd86792e71a7e/ourworldindata.org/analytics/traffic?path=%2Fatom.xml
https://dash.cloudflare.com/078fcdfed9955087315dd86792e71a7e/ourworldindata.org/analytics/traffic?path=%2Fatom-data-insights.xml

Only problem there is that apparently, we can only see Analytics data for the last 7 days...

**Comment by ikesau** [comment]
Oh, great! I can't even find it again but my CF analytics view had no ability to filter or anything.

I think for our purposes (newsletter improvements) a 7d view is fine 👍
