### ISSUE TITLE
yarn fails with: The engine "node" is incompatible with this module. 

### ISSUE THREAD

**Issue by abitrolly** [owid/owid-grapher#372]
```
$ yarn
yarn install v1.22.4                                                                
[1/5] Validating package.json...                                                    
error @2.0.0: The engine "node" is incompatible with this module. Expected version "12.13.1". Got "12.16.1"
error Found incompatible module.                                                    
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I found that the version is hardcoded in `package.json`. Do you know how to instruct `apt-get` to install the exact version of `nodejs` specified in `package.json`?

**Comment by abitrolly** [comment]
`yarn` installation required `git`, `make`. Still trying to install.

**Comment by MarcelGerber** [comment]
Hi @abitrolly.

You can use [nvm](https://github.com/nvm-sh/nvm#installing-and-updating), a Node version manager that allows you to easily manage multiple installations on your device.
After installing it, you can run `nvm use` in your `owid-grapher` directly and it will automatically use Node 12.13.1.

**Comment by abitrolly** [comment]
@MarcelGerber I managed to install `node` and `yarn` correctly using this command
```
set -x \
      && apt-get update && apt-get install -y curl jq git make g++ \
      && NODE_VERSION=$(jq -r .engines.node /app/package.json) \
      && DEB_FILE="nodejs_${NODE_VERSION}-1nodesource1_amd64.deb" \
      && curl -sLO "https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/${DEB_FILE}" \
      && apt-get install -y ./"${DEB_FILE}" && rm "${DEB_FILE}" \
      && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
      && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
      && apt-get update && apt-get install -y yarn \
      && rm -rf /var/lib/apt/lists/*
```

I executed `yarn` from project folder, it downloaded dependencies, and then it hung and never completed. I think I aborted after 10 minutes. How much time should the process take?
```
[1/9] ⠄ bcrypt
[9/9] ⠄ core-js-pure
[6/9] ⠄ sharp
[4/9] ⡀ node-sass
^C/9] ⡀ waiting...
```

**Comment by MarcelGerber** [comment]
It's not exactly fast, but I don't think it should take 10 minutes.
Maybe you can install `build-essential` (via apt) as well, I know that's required for many package builds.

**Comment by obains** [comment]
Maybe it could be worth updating the versioning in the package.json
from: 
```
"engines": {
        "node": "12.13.1"
    }

```
to:

```
"engines": {
        "node": ">=12.13.1"
    }
```

I wouldn't 100% trust my answer, but it worked for me. Let me know if I should submit a pull request.

**Comment by danielgavrilov** [comment]
Thanks for reporting, and sorry that it took us a while to resolve this. We have finally [relaxed the Node version constraint](https://github.com/owid/owid-grapher/commit/73f0e2af7fe452bdc4e5805c7b498d30d05774f8). 

We relied on the `package.json` version in the past to keep the version strictly in sync between our servers, but we now have NVM installed on all so we can relax this constraint.

I will close this, but please report if you still run into issues!

**Comment by abitrolly** [comment]
May give it a try one day. My original intent was to see how to feed this diagram - https://ourworldindata.org/covid-sources-comparison - with latest data to see how sources continues to match. but it became less actual in recent weeks.

**Comment by danielgavrilov** [comment]
@abitrolly Yes I'm interested to know that too, it just hasn't been a priority to find out.

The WHO now publishes a [**dashboard**](https://covid19.who.int/) that exposes a JSON file that should be easy to parse: https://dashboards-dev.sprinklr.com/data/9043/global-covid19-who-gis.json

And Johns Hopkins still have their stable CSVs: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

You can find our data transformation for the Johns Hopkins dataset in our Jupyter Notebook: https://github.com/owid/covid-19-data/blob/master/scripts/notebooks/jh_generate.ipynb

I think it requires aggregating some regions into countries, which we last recorded a while ago [in a spreadsheet](https://docs.google.com/spreadsheets/d/1Da_QNRmBiIsV9F6w5A3AEEUlKxLZhsN5uDxFHmeQmZs/edit?usp=sharing) that may need to be updated.

Anyway, let us know if you get around to this! We'd be curious what the differences are.

**Comment by abitrolly** [comment]
@danielgavrilov if the diagram could be used from Jupyter Notebooks directly, it would solve all my DevOps problems. ) While it possible to use `matplotlib` for that, its interface and parametrization is far from being friendly for developers who are not scientists.
