### ISSUE TITLE
Link authors without an author page to the team page

### ISSUE THREAD

**Issue by saloni-nd** [owid/owid-grapher#3721]
## Core problem

On some topic pages and articles, some authors don't have an author page, so their names don't have an underline. 

It looks a little odd, and their names could be linked to the team page.

## Context

Example of Marcel's name not underlined on the topic page for Population Growth.

We discussed this in Slack [here](https://owid.slack.com/archives/C06KFK86HST/p1718698416469359).

![image (144)](https://github.com/owid/owid-grapher/assets/31684905/0d1a3f85-b49b-4204-954d-edd07102838f)

**Comment by ikesau** [comment]
We can quickly fix this by changing https://github.com/owid/owid-grapher/blob/c44dec69ec69884b4a38a5e7d7a246cdc615937a/site/gdocs/components/LinkedAuthor.tsx#L33 to return an <a> tag linking to /teams (even if that's the wrong **[destination for external contributors](https://ourworldindata.org/former-team-members)**)

**Comment by ikesau** [comment]
Fixed by https://github.com/owid/owid-grapher/pull/3826
