### ISSUE TITLE
Links at the bottom of data insight detail are not stable over time

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3765]
## Problem

The links at the bottom of the data insights detail page take you back to the feed, in particular they link to a position in the feed rather than to the item itself.

This means if you have them in a tab and click on them later, you will be taken to a different insight altogether (e.g. offset by one, two or more).

<img width="1192" alt="Screenshot 2024-07-03 at 14 22 25" src="https://github.com/owid/owid-grapher/assets/36012/a01d97eb-5875-4526-b32c-d2ab93d505d2">

Reported by Hassan

**Comment by ikesau** [comment]
This would be quite a lot of work to fix (either by auto-refreshing the cards at the bottom of the page, or having the index page be more dynamic) and so is wontfix for now, but could be reconsidered if we change the site to more easily support more dynamic behaviour.
