### ISSUE TITLE
Author pages are not on the sitemap

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3775]
## Problem

We have baked new author pages, but they are not on our sitemap, which may have implications for efficient indexing.

See: [Datasette: team urls on the sitemap](http://datasette-private/analytics?sql=select+*+from+sitemap+where+url+like+%22%25%2Fteam%2F%25%22) (staff-only)

## Impact

Low, since the Google crawler is still picking these pages up: 
https://www.google.com/search?q=site%3Aourworldindata.org%2Fteam%2F&oq=site%3Aourworldindata.org%2Fteam%2F

It would however make analytics easier if the sitemap included all our URLs, since then we could use it as a whitelist for filtering out junk non-OWID urls.

See: [Datasette - most viewed URLs that are not on the sitemap](http://datasette-private/analytics?sql=select+*+from+pages+left+join+sitemap+using+%28url%29+where+sitemap.url+is+null+order+by+views_365d+desc) (staff-only)

**Comment by ikesau** [comment]
Should be very simple to add this to https://github.com/owid/owid-grapher/blob/a45a799a9aa46cbd4b9eea9cb95c5274727f4d7e/baker/sitemap.ts#L65
