### ISSUE TITLE
Use default `yAxisMin` value of 0

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#3797]
This is a feature request by Max.

## Core problem

Almost every chart can benefit from `yAxis.min: 0`, and it should be an active choice to _not_ have it set like so.

Currently, the authors need to remember to set it like so.

## Proposed solution

Instead, we could make `yAxis.min: 0` the default behavior.

One thing we need to take care of is that `yAxis.min: null` might not be a good idea in order to explicitly unset this default.
Instead, one way to solve this would be to use a string/number hybrid setting, like so:
- special value `auto` - use `yAxis.min: 0` for line charts, and don't use a default for other chart types like scatter or slope charts.
- special value `unset` - no min value set up
- normal values `0`, `1` etc. - work as before

## Additional information

If we change this default, then some extra care needs to be taken for explorers. Many of these have an explicit `yAxisMin	0` set already, but there may be some that don't have this set for a good reason.

## Context

Currently, 3735 of 4594 published charts have `yAxisMin: 0` set, and only 684 have a `null` value.

[Datasette query (internal only)](http://datasette-private/owid?sql=WITH+nulled+AS+%28%0D%0A++SELECT%0D%0A++++COALESCE%28config+-%3E%3E+%22%24.yAxis.min%22%2C+%22%28NULL%29%22%29+as+n%0D%0A++FROM%0D%0A++++charts%0D%0A++where+config+-%3E%3E+%22%24.isPublished%22+%3D+1%0D%0A%29%0D%0ASELECT%0D%0A++n%2C%0D%0A++COUNT%28*%29%0D%0AFROM%0D%0A++nulled%0D%0Agroup+by%0D%0A++n%0D%0Aorder+by%0D%0A++COUNT%28*%29+DESC)

**Comment by toni-sharpe** [comment]
Thios charts for the local host:

[3735: Number of child deaths from malaria, 2021](http://localhost:3030/admin/test/embeds?ids=3735&comparisonUrl=https%3A%2F%2Fourworldindata.org)
[4594: Number of trees per km², 2014](http://localhost:3030/admin/test/embeds?ids=4594&comparisonUrl=https%3A%2F%2Fourworldindata.org)

**Comment by sophiamersmann** [comment]
@marcelgerber I assume Max's request is about line charts, but not scatter plots?

**Comment by marcelgerber** [comment]
@sophiamersmann Yes, I assume so too, but it might be good to double-check with him.
