### ISSUE TITLE
Add A11y support to StoryBook

### ISSUE THREAD

**Issue by toni-sharpe** [owid/owid-grapher#3804]
**Note**: I've raised this to have it recorded because it's useful, there's no need or expectation for action on this, I understand the team may be busy.

## Core problem

Elsewhere we refer to accessibility improvements. No-one is arguing against the improve of web accessibility anywhere, it's frankly terrible, made worse by how often the following back-up point needs to be used and is the one that swings the debate: "but, improving accessibility for these folk improves it for all the able bodied folk too" </ rant>

Something that can be done help in that respect is to add the [A11y addon](https://storybook.js.org/addons/@storybook/addon-a11y) to StoryBook. Automation isn't the complete solution but it does get quite a bit and it trains developers to think about it and the solutions. You'll see the "More info ..." links in the screen-shots below, they go to [Deque University](https://dequeuniversity.com/) who maintain a tool called [AXE](https://dequeuniversity.com/rules/axe/4.9). That's a commercial, US tool, which does worry me a bit, but I think they're at the good end of the scale. [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility) also cover the topic in detail. MDN is my go to resource for accessibility, it's got the right balance of detail and conciseness.

## Proposed solution

It's pretty easy, just needs to be [added in here](https://github.com/owid/owid-grapher/blob/master/.storybook/main.js#L7) and the correct rebuild run (not sure which one that is). Then of course those errors need fixing. It can be [enforced as part of CI](https://github.com/storybookjs/storybook/issues/8845) and tbh, this is what I mean by "first class concern" we need to treat accessibility like it's part of the most important set of things and a failure should break CI. I just sat and went through them on one jobless day, it took about ten hours for [my site](https://data-visualisation.pages.dev/), before the WorldMap was added I think.

It did find 100s of things, though typically there was one or two leaf components with single problems that were setting flags all over.

An example of one thing it did do was if my component (for example) had `<li>` as the root (invalid HTML, potentially), that got thrown as an error if it was just in the standard `<div>` in SB. Having got over the insult, I actually considered this to be good. Really, my list items should be usable outside of a list context, maybe in `<article>` tags, so the error was fair to throw, though the quick fix, which I did use here and there, was just to put `<ul>` in the StoryBook.

## Screen-shot examples

Here's a few screen-shots from my own StoryBook that show the action. The Button was small and quite easy to break, so that's the example:

### My Button is brilliant

<img width="400" alt="image" src="https://github.com/user-attachments/assets/f6789d57-9814-4745-b91d-af4180e403d2">

### Here's one of those paths opened up

So you can see details of brilliance. Because this is in the "pass" tab of course means that it's information, not an error message.

<img width="676" alt="image" src="https://github.com/user-attachments/assets/3ff85a5b-bf95-4c02-840e-2a00e0a914c7">

### The option to highlight

Amusingly Apple's scroll-bar gets in the way of the checkbox, which can be used to mark the exact point of brilliance.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/63fd4e7b-c42e-43de-bbf5-1b5683647ca9">

### Not so brilliant

The error is obvious, contrast, here it is shown to us that there is a mistake

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/945912b7-24a0-4002-9ded-674be06a1d5b">

### And that can shown

With red, like a bad mark (there is some chatter [about using red for error](https://ux.stackexchange.com/questions/16317/is-the-color-red-really-appropriate-for-form-validation-errors) because of this, on the Stack Exchange where I have the highest of my SE scores, curiously)

<img width="656" alt="image" src="https://github.com/user-attachments/assets/78029fce-a4c8-48c2-85b7-6cd36c7625b3">

### Finally, the intermediate level

It has a middle level, I've got all the serious ones, but still have a few of these

<img width="976" alt="image" src="https://github.com/user-attachments/assets/6e30ada3-8495-4312-8cc6-426c953f96ca">

**Comment by marcelgerber** [comment]
We don't currently use Storybook, and so we don't think this is worth doing for now.
