### ISSUE TITLE
Add interactive helper for setting up a .env file for staff

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3810]
## Context

To run the full `owid-grapher` codebase for a site, you run `make up.full`. That copies `.env.example-full` to `.env`, and starts the services.

However, there are many non-optional environment variables needed to set up the environment.

## Problem

It's not clear where to get those variables from (as in, not documented), and not smooth to fill them in one by one.

## Proposal

Add an interactive helper that helps you add one by one the missing environment variables that are not marked optional, until you have all you need to spin up the local server successfully.

**Comment by toni-sharpe** [comment]
I'd like to note here that it sounds like "staff" could also be "open source contributors" - is this correct? Maybe we need a distinction, or to be careful with language/definitions with the vision to have a full open-source project?

**Comment by larsyencken** [comment]
H

> **Question** it sounds like "staff" could also be "open-source contributors" - is this correct? Maybe we need a distinction, or to be careful with language/definitions with the vision to have a full open-source project?

"staff" means folk that work at OWID. The `make up.full` recipe is one that only staff can run, since it needs a bunch of credentials that `make up` doesn't.
