### ISSUE TITLE
`gdocs_posts.updatedAt` is often set to the unix epoch

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3832]
## Context

We use a timestamp model for `gdocs_posts` which includes a few fields, such as:

- `createdAt` 
- `updatedAt`
- `publishedAt`

By design, we expect `updatedAt` to be `NULL` if no updates have happened post create. This is how it is defined in MySQL.

## Problem

A number of rows in `gdocs_posts` (e.g. with `slug = 'fiona-spooner'`) have the Unix epoch (`1970-01-01`) set instead of `NULL`.

## Impact

It only seems to have been a problem for:

- https://github.com/owid/owid-grapher/issues/3775

## Technical notes

After checking the schema, this must be happening on the JS side rather than the MySQL side. We can fix the rows, but it would be nice to fix the JS model to avoid this scenario.

**Comment by marcelgerber** [comment]
It's probably this line here?: https://github.com/owid/owid-grapher/blob/2b79d4baf8ebb3a01f5e0b83f05f1cdcc4317c8f/db/model/Gdoc/GdocFactory.ts#L66
