### ISSUE TITLE
Create a custom event for every chart view (in grapher, not explorers)

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3834]
## Context

- We currently count chart views for a chart `<slug>` by looking at Google Analytics pageviews for `https://ourworldindata.org/grapher/<slug>`
- Since many minor interactions with a chart trigger new pageview events, we look at the referrer and eliminate events that share the same chart as referrer

## Problem

- This approach under-counts chart views, since many of them will be embedded in articles
- This approach makes it harder for us to define what we think a significant chart view is, which may become more relevant as multi-dimensional indicators are added at `/grapher/<slug>`
  - Switching dimensions would change the chart enough to count as a significant new pageview

## Proposed solution

- Create our own chart view event
  - Fired on first load of a Grapher page or Grapher embed
  - Not fired when the chart is interacted with, despite GET parameter changes
- (in analytics) Use the new chart view event as the source of truth for future chart views

**Comment by danyx23** [comment]
Grapher views seem especially important. For explorers it would be great to spike this a bit and draft a map of how we would tackle this (what is the payload of the event?)
