### ISSUE TITLE
help wanted ....Registrtaion page not showing

### ISSUE THREAD

**Issue by sibtaincs** [owid/owid-grapher#385]
Hi any one help me how to 
access registeration page 
i want to create users for logins 
this page not works 
@
help wanted

**Comment by mlbrgl** [comment]
hi @sibtaincs, sorry for the delayed response. We've update the local installation process described in the [README](https://github.com/owid/owid-grapher/blob/master/README.md) since your request. Might be worth taking a look if this is still current?
