### ISSUE TITLE
Cycle 2024.5: Launch friendly data catalog

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3861]
[Previous cycle](#3781) | [Demo](http://staging-site-data-catalog-algolia-client/charts)

- [x] Dark launch the catalog
- [ ] ~~Include explorers and MD indicators~~
- [x] Integrate analytics events
- [ ] ~~Launch the catalog~~

**Comment by danyx23** [comment]
@larsyencken seems we can close this issue?
