### ISSUE TITLE
Key indicator collection is messing up anchor links on the home page

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#3863]
We can't link to https://ourworldindata.org/#subscribe atm because the animation of the key indicator collection is causing the height of the page to change after the scrollTop has already been set.

In this video I paste the link and press enter, which results in the undesirable behaviour. Scrolling to the correct position and hitting refresh works correctly. Opening a new tab and pasting the link works correctly for some reason, so there's a non-deterministic aspect to this.

https://github.com/user-attachments/assets/0d925ca1-1613-4576-a299-25de50c6fe3a

**Comment by marcelgerber** [comment]
Just noting that this doesn't seem to be an issue on Chrome/Edge, just on Firefox.
