### ISSUE TITLE
Direct link to embed screen/chartid output

### ISSUE THREAD

**Issue by toni-sharpe** [owid/owid-grapher#3906]
## Core problem

The embedded chart coparison screen is something I find really useful. ❤️ 

But currently it doesn't seem to have a link on the chart list

## Proposed solution

Already exists, the [PR was rejected](https://github.com/owid/owid-grapher/pull/3798) - speculative improvements to the chart list and @danyx23 explained that they don't suit the team; however, in amongst that was [this commit](https://github.com/owid/owid-grapher/pull/3798/commits/8952aef1f9257c66404e5cdaf27012dfad9ef42d).

All it does is make the chart ID into a link to that screen.

Pretty simple so I'll just leave it at that, if the team feel this a good one, I can make a quick PR no problem.

## Second commit

A second thing in there was this commit that [adds the chartid to the output HTML](https://github.com/owid/owid-grapher/pull/3798/commits/3f0b3fb321dd8834154a12c5e506c2fcb61c6b48) 🌳 - this closes the loop a bit from seeing a chart live and actually finding it in admin.

Again the commit is really simple and atomic

Please respond with ❤️ for the link and 🌳 for the id in the output. Voting for both is cool. I can do both if there's interest.

Alternatively if someone just says "do it" then it will happen.

(I put too many things in that one, it was all bit exploratory and broke something important, however, I think both these have merit individually)

**Comment by danyx23** [comment]
Hey Toni! Thanks for this! These admin pages are primarily built for staff members and we don't really experience the issues that you describe here. For example, after logging in to the admin and registering as staff, a direct edit link is available to staff members in the share menu of a chart (i.e. it takes you to the admin).

As such we'll close this issue.
