### ISSUE TITLE
Topic-specific country profile pages don't show data for the country

### ISSUE THREAD

**Issue by rakyi** [owid/owid-grapher#3931]
## Description

On topic-specific country profile pages, charts use the default country selection instead of the specific country. For example, [here](https://ourworldindata.org/energy/country/spain) charts should show the data for Spain.

It seems to work correctly for explorers.

## Additional context

* Related [Slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1725613179393189)

**Comment by ikesau** [comment]
Looks like this was introduced via https://github.com/owid/owid-grapher/pull/3793

Bug is present in its deployment: https://035fd218.owid.pages.dev/energy/country/spain

But not in the prior deployment: https://e7fd384b.owid.pages.dev/energy/country/spain

**Comment by sophiamersmann** [comment]
Probably related to https://github.com/owid/owid-grapher/issues/1473
