### ISSUE TITLE
search: non-alphabetical characters are not bolded in results even if there is a match 

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#3949]
## Description
In search, matching numbers between query and result titles are not bolded.

## Expected behavior
Just like alphabetic characters are bolded when they match between the query and result texts, non-alphabetical ones should probably also be bolded.

## Steps to reproduce

1. Go https://ourworldindata.org
2. Click on search bar
3. Type "Biweekly change in confirmed COVID-19 deaths"
4. Note the '-19' is not bolded.

## Screenshots

Site: 

![image](https://github.com/user-attachments/assets/7fe82406-0afe-48b5-9b80-7729c86dff91)

HTML:
![image](https://github.com/user-attachments/assets/694b6ec9-01c8-4290-9bc2-046a042202ce)

Also happens in the complete search result page

![image](https://github.com/user-attachments/assets/47eade06-3396-41f2-8116-ddaeadedba60)

## Environment

For desktop, provide:

-   OS: Arch Linux (Manjaro)
-   Browser: Firefox
-   Version: 125.0.1-1

**Comment by toni-sharpe** [comment]
### Problem

I think "valid code" is the problem: removing the `-` yields:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/2b260ee8-4263-4b5f-9d0a-02948f8c7d17">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/cdd441bb-be5b-4fd4-b0a3-e02d434ec2b4">

### Code

Referencing head of main at time of writing: [7ba120224](https://github.com/owid/owid-grapher/blob/7ba12022425336e7fcfa703f73a289db89a18dca) ¶.

[This line](https://github.com/owid/owid-grapher/blob/7ba12022425336e7fcfa703f73a289db89a18dca/site/search/Autocomplete.tsx#L182) is interesting as the `key` prop in React _should_ be string and is explicitly cast. Perhaps @marcelgerber is well placed as the [owner of the PR](https://github.com/owid/owid-grapher/pull/2626) where this line was added. Unfortunately I'm not getting search locally.

[Perhaps, on 178](https://github.com/owid/owid-grapher/blob/7ba12022425336e7fcfa703f73a289db89a18dca/site/search/Autocomplete.tsx#L178):

```
const itemTitle = String(item[mainAttribute])
item[mainAttribute] = itemTitle
```

¶ new idea, given a context where patience matters I want my comments to stick to the code, worst case scenario: you see what to search for in six months time. I think this will be really handy in the case of moved/renamed files.

**Comment by danyx23** [comment]
Doesn't seem important enough to fix but if there is an example where the search results are wrong because of this, please feel free to share that and we'll re-evaluate!

**Comment by lucasrodes** [comment]
hi @danyx23,
Where is a good place to track these minor issues, which I agree are not urgent, yet they point to something that is not working as expected? I think it is good to keep a list of them.
