### ISSUE TITLE
Spurious carriage returns break image sync in staging server deploys

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3952]
## Problem

In our internal staging servers, the `.env` file for `owid-grapher` is being somehow configured with windows-style newlines (`\r`), which appears as `^M` at the end of every line if opened in `vim`.

Since we use shell interpolation to join the r2 bucket path during image sync, this adds a carriage return character in the middle of r2 urls, breaking image sync. The carriage return appears as the ␊ character in Buildkite logs.

## Expected behaviour

There should be standard unix newlines only (`\n`) in `.env` files in staging and elsewhere.

## Technical notes

- The `.env.example` and `.env.example-full` appear to be clean
- For an `-algolia` branch, the algolia variables had healthy newlines
- The newlines of `.env` on `staging-site-master` appear to be just fine

**Comment by ikesau** [comment]
It seems to only happen on `-algolia` branches, so we should examine that full workflow.

**Comment by ikesau** [comment]
We should revert this (ineffective) commit from an earlier debug attempt once all is said and done: https://github.com/owid/ops/commit/1e314f126b53598454b06557f681e2c8ef6e2282

**Comment by Marigold** [comment]
Fixed and reverted that debug attempt. Big respect for finding this!

**Comment by rakyi** [comment]
Thank you for reporting and fixing this! rclone prints a helpful error message where you could see the L/F character, which helped a lot with debugging.
