### ISSUE TITLE
Grapher accepts additional countries in GET parameters, even when in single entity only mode

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3965]
## Problem

When getting to Grapher charts via search, it's natural to add multiple entities, both in thumbnailing and in the eventual Grapher link.

However, some charts are so unreadable as multi-entity charts that the author has decided they should be single-entity in the config.

E.g. https://ourworldindata.org/grapher/ghg-emissions-by-sector

## Proposed solution

Grapher should either render just one of the entities, the first one, or it should facet. But it should refuse to render all of them when a multi-selection is made in violation of the config.

**Comment by danyx23** [comment]
Thumbnailing in search makes this more important than it used to be

**Comment by sophiamersmann** [comment]
@marcelgerber do our thumbnails in search ever include entities for a Grapher that are not actually in the data?

**Comment by marcelgerber** [comment]
> do our thumbnails in search ever include entities for a Grapher that are not actually in the data?

No, they do not.

But yes, regarding this issue, it actually is the case that search can show single-entity charts with multiple entities selected, e.g. here:
![Image](https://github.com/user-attachments/assets/542862e9-3922-4c64-a228-0077585ec893)

**Comment by sophiamersmann** [comment]
ok, thanks! In that case, faceting is the right thing to do then for charts like the one you highlighted :)
