### ISSUE TITLE
Minimum range for y axis scale

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#3983]
## Problem

Some charts are not meaningful to interpret, because the entire y axis range is so small.

For example: https://ourworldindata.org/grapher/share-of-population-in-extreme-poverty?tab=chart&country=~GBR

<img width="975" alt="Screenshot 2024-09-25 at 13 00 52" src="https://github.com/user-attachments/assets/bf882480-6c36-4d55-a6c4-03359d323e34">

## Proposed solution

We would like to keep the y-axis auto-scaling, but set a minimum for the ymax, e.g. 5% for the chart above, which would keep it relevant no matter the selection.

**Comment by marcelgerber** [comment]
We can already do this! Just setting Y Axis max to 5 here does this already: It will show up to `max(5%, max_visible_data_point)`.

**Comment by larsyencken** [comment]
Ah, fantastic! Of course, I forgot that we never clip, so the y-max is a "soft y-max"
