### ISSUE TITLE
Line break in a static chart not respected by Figma

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#3992]
## Description

When [this chart](https://ourworldindata.org/grapher/solar-share-energy?tab=chart) is imported into Figma, then the subtitle's line break is not respected: 

"substitution method" happens to be a DoD. Removing the DoD fixes the issue.

<img width="614" alt="Screenshot 2024-10-01 at 12 16 39" src="https://github.com/user-attachments/assets/4a73d4f1-330e-4655-b92b-01badb3899f4">

## Additional context

Seems like a weird Figma bug. Probably not worth fixing it.

**Comment by danyx23** [comment]
Seems rare enough that is not worth fixing.
