### ISSUE TITLE
Grapher should fix the position of tooltips to the bottom on mobile

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4001]
On mobile, the tooltip window would be more useful if it would just stay fixed at the bottom of the chart. @sophiamersmann has worked on this before and there is an unfinished PR at #3679. We'd like to finish this work.

**Comment by marcelgerber** [comment]
Marking this as nice-to-have, since currently the main workaround is to single-tap the chart rather than tap-and-holding it.
But we agree that this is quite annoying for tap-and-holding on mobile.

**Comment by larsyencken** [comment]
@sophiamersmann This one is marked as "Blocked", is there a reason? Or should we change it back to "Todo"?

**Comment by larsyencken** [comment]
> Ah sorry, I used a view of the engineering board during the batch cycle – and I sometimes moved items to "Blocked" while I was waiting for someone's review. I didn't realise that would be reflected here. I changed it to "In Progress" now.

That's totally correct use of the board 🙂 Basically it's not blocked anymore.
