### ISSUE TITLE
Cycle 2024.6: Start publishing Multidimensional Datapages

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4007]
_Publish multidimensional datapages on our website so our users can understand complex, dimensional data_

Previous cycle issue: #3877
Tracking issue: #3874

## Motivation

With #3877 we managed to put in place all the core pieces to build multidimensional datapages - we can now assemble them easily in the ETL, they are saved in the database and then we can preview them in the admin. Baking also exists but is currently feature-flagged. 

The public cannot see these multidimensional data pages yet though. We have a few blocking items still on our list before we are comfortable with shipping them.

## Proposed scope

We want to be able to start shipping multidimensional datapages on our website. To do this we need to implement the must do items below.

**Must do**

- [x] #4009
- [x] #4010
- [x] #4011
- [x] #4012
- [ ] #3987

**Could do**

- [ ] #4040

## Technical notes

#4013 (create fully merged configs for mdim views addressed by UUID) is closely related and probably a very useful/necessary prerequisite for #4012 (embed single mdim views)

**Comment by larsyencken** [comment]
@rakyi Shall we close this as done and allow any remaining issues to enter the backlog?

**Comment by rakyi** [comment]
That makes sense to me. The last open Must do https://github.com/owid/owid-grapher/issues/3987 has an open PR already.
