### ISSUE TITLE
Mdims: Allow overriding metadata for mdim views

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4009]
## Motivation

Today, everything surrounding the chart (i.e. the data page content except for the chart and the top section) is powered by the indicators metadata json file ([example](https://api.ourworldindata.org/v1/indicators/815264.metadata.json)). 

We sometimes have views that are assembled from several indicators (e.g. [stacked area charts to provide an overview](https://admin.owid.io/admin/grapher/mdd-demo-poverty?country=~OWID_WRL&povertyLine=all&metric=share)) - for these cases especially we need something better than just showing the metadata from the first Y indicator (especially the content directly below the chart).

![Image](https://github.com/user-attachments/assets/6f68c27c-4615-44a9-82b0-af4e219c5602)

## Solution

In the mdim config section it should be possible to specify variable metadata (using the same schema as that for a single variable) either once for all views, or for per view. 

This would allow us to override e.g. the descriptionKey that powers the bullet points under the chart either for all views in the same way or for a single view (like the multi-indicator example above). The JS object of the variable metadata would simply be merged first with the all views override and then the view specific override (if they exist).

**Comment by larsyencken** [comment]
We chatted briefly about the "Learn more about this data" link that pops over the same info as in the data page, but as an overlay in embed scenarios. Ideally it's the same code path for describing the chart and its variables in either case.
