### ISSUE TITLE
Mdims: Lessen the content flash when switching indicators

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4010]
## Motivation

Currently the behavior when switching views is a bit jarring - grapher resets and often briefly shows a number in the title, then grapher updates and the rest of page pops into existence again. 

## Solution

It would be nice if we could lessen this - ideally with our own loading indicator that initially leaves the old content visible on the screen so we can swap it out without an empty intermediate state if the new content arrives within, say, two seconds.

How far we want to go with this is a bit of a polishing question - the list below tries to give some sense for various parts, roughly sorted by complexity involved.

**Must do**
- [x] Stop rendering the numeric variable as a title (this is the weirdest part of this content flash and it's no longer necessary since we always have some title-ish text that we can display unless for the case where nothing for an indicator is loaded - but then an empty title is the better text).

**Can do**
- [ ] Make grapher aware of the fact that the config is not yet available. Currently, grapher thinks the almost empty grapher config that only specifies a dimension so it knows what to load is all there is and so it starts attempting to draw itself. It would arguably be better to just show a loading spinner until we have at least the grapher config (if not the indicator data/metadata)
- [ ] Add some loading indicator with a timeout that communicates to the user that we are fetching new stuff but while we wait we still show the current content to avoid a premature white screen-out. If loading takes longer than a set amount (e.g. 2 seconds) then the honest thing is probably to start showing the white screen so the user isn't too confused about why the selection at the top is not reflected below.

**Comment by rakyi** [comment]
Must do is fixed via https://github.com/owid/owid-grapher/pull/4061

Will return to the can dos if there is time left in the cycle.
