### ISSUE TITLE
Mdims: Make it possible to embed single mdim chart views in articles

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4012]
## Motivation

One of the reasons why we wanted MDims was to have less of a need for many standalone charts (i.e. those that you see in the admin in the charts section and that live in the `charts` table in the DB). Instead of having 20 standalone charts you would now have one Mdim with 20 views. 

This works fine today for standalone MDims, but our authors want to be able to embed charts in articles and so they will want to embed views from MDims in charts.

## 

Eventually we will want to be able to embed single views as iFrames and probably also the entire mdim chart + mdim controls in iFrames, but for now we only want to make it possible to embed single views in articles (or other gdoc content).

Either the `chart` gdoc component or a new, similar component should take the url (including the query params to select the right view) as a parameter and then render the correct interactive chart that would also be shown in the mdim page (just the chart, none of the surrounding metadata).

**Comment by rakyi** [comment]
Relates to https://github.com/owid/owid-grapher/issues/4013

**Comment by rakyi** [comment]
Prerequisites:
* https://github.com/owid/owid-grapher/pull/4090
* https://github.com/owid/owid-grapher/pull/4096
