### ISSUE TITLE
Edit option for explorers redirects to a broken link

### ISSUE THREAD

**Issue by paarriagadap** [owid/owid-grapher#4033]
## Description

The Edit option available from a live explorer view shows a broken link in the form `https://ourworldindata.org/undefined/admin/explorers/name-of-explorer`

## Expected behaviour

The link should be something like `https://admin.owid.io/admin/explorers/name-of-explorer`

## Steps to reproduce

1. Go to https://ourworldindata.org/explorers/poverty-explorer
2. Click on the share icon
3. Click on `Edit`
4. See 404 page: https://ourworldindata.org/explorers/undefined/admin/explorers/poverty-explorer

## Screenshots

The Edit option is available by pressing the share button:
![Image](https://github.com/user-attachments/assets/9a7c176d-ee25-4803-a7e3-a1b79e22a92f)

## Environment

For desktop, provide:

-   OS: macOS Sequoia 15.0.1
-   Browser: Google Chrome
-   Version 129.0.6668.90 (Official Build) (arm64)

**Comment by sophiamersmann** [comment]
Would make sense to tackle this when working on #3987
