### ISSUE TITLE
Solicit and incorporate final feedback on server side CSV generation

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4060]
Now that #3613 (and some follow-up PRs) have been merged, the basic feature of downloading csv files from a URL works - but the ergonomics of the server side csv could do with a final round of polish. To this end, interview, triage and incorporate the feedback from

- [ ] Our data managers
- [ ] Lars and the other devs
  - Lars already provided some immediate feedback in [this slack thread](https://owid.slack.com/archives/CQQUA2C2U/p1728652285735709)
- [ ] Joe (especially regarding the contents of the zip file and the importantce of an Excel file)
- [ ] Este (especially regarding the wording in the readme file that touches licensing-ish questions)

**Comment by larsyencken** [comment]
@danyx23 Carrying this through to our new cycle.
