### ISSUE TITLE
Staging workflow for writing on embargoed data

### ISSUE THREAD

**Issue by larsyencken** [owid/owid-grapher#4089]
Reported by @spoonerf 

## Core problem

When we work on embargoed data, we have a decent process where charts and data are published automatically upon merge of the staging branch. However, we often do updates of our writing or even new articles based on the embargoed data, and they are drafted in prod, and are difficult to incorporate viz into until the embargo is lifted and the data is merged.

## Impact / severity

Few datasets are embargoed, but when they are they are often very important datasets for us. It's slightly unclear how much time is lost due to managing writing on embargoed topics.

## Proposed solution

We could potentially queue up writing on the staging branch, and ship writing and data together when it's ready. That would require us to have something like chart diff, but for GDocs articles.

**Comment by danyx23** [comment]
@spoonerf you can already today register a gdoc on a staging server. This allows you to preview the writing on the staging server using all the new or updated charts with embargoed data. You can even already register it on prod as well. When the data is published, the main thing you have to do is click publish in prod.

You can also do the same for updated articles for which an old version is already published on prod.

Does that tackle the main pain point here? Maybe we are missing something but for now we don't see what the big advantage of this system would be, given that we usually only write/update a handful of articles? Happy to hear more about this though and then we will re-triage!

**Comment by spoonerf** [comment]
Hi @danyx23, sorry for the delay in getting back to you. 

What you've said makes a lot of sense. I had just gotten the sense that this process was a bit fiddly, but I think the advantage of adding anything more would be fairly small, given that we currently have relatively few embargoed datasets (UN WPP, OPHI, LPI, and Global Carbon Project are the only ones I know about and as you mention the number of articles affected is relatively small. 

Thanks for triaging it!

**Comment by danyx23** [comment]
@spoonerf great, thanks for your feedback! Feel free to re-open this one or create another one when you have a more concrete idea for something that is annoying in this workflow and could be improved.
