### ISSUE TITLE
Improve explorer view titles in the data catalog

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#4130]
# Problem
At the time of indexing, we [only have access to an explorer's metadata](https://github.com/owid/owid-grapher/blob/master/baker/algolia/utils/explorerViews.ts#L489) to derive its title, leading to situations like the following: 

![Image](https://github.com/user-attachments/assets/92c0bf1a-a1ba-4b1e-8a7f-fc3cb868cba4)

The thumbnail loads the Explorer config and fully instantiates a Grapher, so it has a much more informative title than the title of the record in Algolia.

It would be nice if we could derive these titles during indexing to avoid this difference.

# Impact
I sampled 1000 records and compared their `viewTitle` attribute to the `$("#title").innerText` of the corresponding SVG from Cloudflare and found that almost all the time the only difference was date information appended to the end.

So I think the impact of this is actually very low, but that we should still consider improving the display of these ChartHits to include source information, or group them by title when we have [multiple views with identical titles](https://github.com/user-attachments/assets/fae6de49-bff7-45ad-a95d-2d0771efaa71)

# Notes
This might best be accomplished by refactoring `indexExplorerViewsToAlgolia.ts` to fully instantiate each Explorer and iterate through its views that way, instead of only instantiating the DecisionMatrix.

[The Grapher displayTitle method](https://github.com/owid/owid-grapher/blob/7ae5c21df8f7688f7e3ee205cf8a83e155017304/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L1538) 
[The explorer view initialization](https://github.com/owid/owid-grapher/blob/master/baker/algolia/utils/explorerViews.ts#L350)
[The enriching step where we'd want access to the Grapher method](https://github.com/owid/owid-grapher/blob/master/baker/algolia/utils/explorerViews.ts#L472)

An alternative is that we duplicate/lift the Grapher title logic into a function that has access to indicator data and the DB to work out what the full display title should be, so that we don't have the full Explorer footprint in the indexing code.

**Comment by rakyi** [comment]
We were not able to find many views and impact of this is very low.
