### ISSUE TITLE
Data downloads / chart API should include information about filtering

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#4163]
## Core problem

Our new Chart Data API and the new zip file data package allows filtering data to only the currently visible subset. This is great, but once you have downloaded things you might forget that this is filtered data and/or how it was filtered. 

## Proposed solution

3 things:
- details TBD but something like the filename of the zip file should end with "-full-data" or "-filtered-data"
- the metadata should include the main query params that change the data:  entities, timeline selection, chart type and relative mode
- this same information should also be stated in the readme

## Alternatives

Don't do anything

**Comment by marcelgerber** [comment]
PR open: #4229

**Comment by marcelgerber** [comment]
Fixed by #4229.
