### ISSUE TITLE
Algolia Explorer Views' `availableEntities` is inaccurate

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#4188]
## Impact
A (currently unknown) number of explorer view records say that they have data for countries that they can't actually render. This means in the data catalog you might filter for records that have `Equatorial Guinea` data and get back results that _can't actually render Equatorial Guinea_

e.g. https://ourworldindata.org/data?topics=Violence+and+War~War+%26+Peace&q=Death+rate+in+armed+conflicts&countries=Equatorial+Guinea

## Context
When creating records for CSV- and indicator-based explorers, `availableEntities` is derived by concatenating all available entities for all indicators used by each view

[CSV code](https://github.com/owid/owid-grapher/blob/c236dca43c35334b87f9bd8bc1c8d5c99798713c/baker/algolia/utils/explorerViews.ts#L443)

[Indicator code](https://github.com/owid/owid-grapher/blob/c236dca43c35334b87f9bd8bc1c8d5c99798713c/baker/algolia/utils/explorerViews.ts#L481)

This misrepresents the truth of the matter for things like scatterplots, where we may have an entities' data for _one_ of the indicators, but not the other.

The truth is more complicated than the intersection of sets, however, as it depends on the `MissingDataStrategy` for each view, and will require further analysis to find the ideal strategy for each case.

**Comment by marcelgerber** [comment]
This one is tricky, and solving this nicely would be quite expensive (e.g. instantiating every explorer view).
On the other hand, there are probably also some low-hanging fruits that we could fix.

The user impact of this is also quite low, at least if it doesn't happen _too_ often.
We're closing this until we hear about this again...
