### ISSUE TITLE
Only 1 record for the covid explorer is currently indexed

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#4190]
On https://ourworldindata.org/data?topics=Health~COVID-19, the only covid explorer result is `Estimated cumulative excess deaths during COVID-19` (go to page 3, where you would expect to see the rest and instead see none)

In the index itself, if you temporarily add `objectID` as a searchable attribute and search "covid-", only this record shows up.

For some reason, the rest weren't indexed.

If I run the script locally, it correctly generates all the records, so presumably something is going / has gone wrong when running during the cron job, though I can't see any issues in Bugsnag that would explain why.

**Comment by marcelgerber** [comment]
I ran into some problems while doing that, and will re-attempt once #4191 is merged.

**Comment by marcelgerber** [comment]
Re-indexing finally worked, and it seems that this issue is now resolved.
