### ISSUE TITLE
Migrate configs in R2 on chart config migrations

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#4218]
I blanked on R2 while working on [this chart config migration](https://github.com/owid/owid-grapher/pull/4159). The code that I pushed didn't handle the old config format, which meant that embedded charts were rendered incorrectly until the syncing script did its job (and Marcel figured out a caching issue).

As a small solution, we should run the R2 syncing script automatically when charts configs have been migrated. (Or just run it regularly, like hourly).

If we can come up with a way to do this that doesn't force us to write code that handles the old and new config format simultaneously, that would be even better.

**Comment by danyx23** [comment]
Did this
