### ISSUE TITLE
Disable single-year discrete bar charts for single-entity line charts

### ISSUE THREAD

**Issue by sophiamersmann** [owid/owid-grapher#4234]
## Description

Line charts turn into discrete bar charts when a single year is selected. Usually that's sensible, but if the line chart only has a single entity (i.e. a single entity is selected and the user can only change the entity, not add entities), then the discrete bar chart view is not helpful and might be confusing for users. 

One example is [population growth rates](https://ourworldindata.org/grapher/population-growth-rates) where the projected data makes it even more confusing...

## Expected behaviour

Grapher could either be smart about it and not show a bar chart in such cases or we add a new piece of config.

## Steps to reproduce

1. Go to this https://ourworldindata.org/grapher/population-growth-rates
2. Select a single year

## Screenshots

![Image](https://github.com/user-attachments/assets/9fbbce57-fafc-4256-bf61-7f3dfaadfd41)

**Comment by danyx23** [comment]
For standalone charts we don't think this is important enough to keep around as an issue. 

For search we have this problem more often (when searching for an entity, all bar charts are shown like this), but for those we should use focuse states instead which we should get soon (we have them for line and slope charts now and it will be easy to add them to bar charts)
