### ISSUE TITLE
Air Pollution explorer is missing a subtitle in the Explorer index page

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#4245]
https://ourworldindata.org/explorers

![Image](https://github.com/user-attachments/assets/a996b28f-9c68-4456-ac7a-71d45e2e4a5b)

There _is_ a subtitle set in the [TSV config](https://raw.githubusercontent.com/owid/owid-content/master/explorers/air-pollution.explorer.tsv), and it's not using invalid whitespace, as far as I can tell.

So maybe it's getting dropped during the [mirror_explorers job](https://github.com/owid/automation/blob/main/automation/mirror_explorers.py), because the [Air Pollution Explorer page](https://ourworldindata.org/explorers/air-pollution) itself (which gets its data from the GitCMS) has the subtitle.

**Comment by marcelgerber** [comment]
Ah, that explorer had two rows of `explorerSubtitle`, where the second one was empty.

[Just fixed it](https://github.com/owid/owid-content/commit/94e9fe639f33e037a12a4dfb455e9bda64912a0e), I think that should do it.
