### ISSUE TITLE
StackedArea crashes when adjusting timeline while tooltip is visible

### ISSUE THREAD

**Issue by danielgavrilov** [owid/owid-grapher#4250]
I love the new mobile tooltip that sticks to the bottom! I just ran into a small bug with it.

## Description

When adjusting the timeline on a StackedArea chart, if a tooltip is visible, it crashes the chart with error:

```
Error: Cannot read properties of undefined (reading 'fake')
```

I think this can happen only on mobile, since the tooltip doesn't persist on desktop.

## Expected behaviour

Not crashing.

## Steps to reproduce

1. Open a [StackedArea chart](https://ourworldindata.org/grapher/electricity-mix-uk) on mobile (or emulate a touch device with Chrome devtools)
2. Click on the chart to trigger the tooltip
3. If necessary, scroll down to make the timeline visible
4. Interact with the timeline

## Screenshots

https://github.com/user-attachments/assets/a30a7c81-0568-4104-9ef2-b370e765d859

## Environment

Happens both on my iPhone (mobile Safari) and MacBook (Chrome) when emulating a mobile device with devtools.

**Comment by sophiamersmann** [comment]
Hey @danielgavrilov, I've heard a lot about you, thanks for stopping by :)

I can't reproduce on my devices – @marcelgerber, do you want to give it a try?

My best guess is that it trips over `point.fake` [here](https://github.com/owid/owid-grapher/blob/d251b430e99d9113dd125c7228312f5f1d867b5a/packages/%40ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx#L503).

**Comment by marcelgerber** [comment]
Hey @danielgavrilov, good to hear from you, hope you're doing great! 🫶

@sophiamersmann yes, I can repro - both on my phone (Android Chrome) and in Chrome's mobile device emulation (it did take a few attempts, though).
And you're right, it's precisely the line you linked to that's failing.

This is the stacktrace, if it's ever useful:
```
TypeError: Cannot read properties of undefined (reading 'fake')
    at StackedAreaChart.tsx:503:31
    at Array.map (<anonymous>)
    at get activeXVerticalLine (StackedAreaChart.tsx:501:25)
    at Rte (mobx.module.js:775:24)
    at e.computeValue (mobx.module.js:1272:19)
    at e.trackAndCompute (mobx.module.js:1257:29)
    at e.get (mobx.module.js:1217:26)
    at e.read (mobx.module.js:4136:37)
    at Yr.get (mobx.module.js:4400:68)
    at Yr.renderInteractive (StackedAreaChart.tsx:713:47)
    at Yr.render (StackedAreaChart.tsx:734:20)
```

**Comment by sophiamersmann** [comment]
I tested some more and it seems like this only happens when the tooltip is on the latest time point (at the very right).
