### ISSUE TITLE
Scatterplot tolerance goes wrong when applied to the color dimension

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#4284]
In the #4176 work, a bug surfaced where the scatterplot tolerance applied to the color dimension (i.e. the "continents" indicator) doesn't work correctly, resulting in scatter points with no color.
Seemingly, the order of table transforms is subtly wrong here, and we're filtering out the continents variable somewhere before applying infinite tolerance to it.

### 1) Data points shown in gray
I've detected some scatter plots, where the data is shown in gray (regardless of the continent):

- [ ] https://ourworldindata.org/grapher/affected-by-disasters-vs-gdp
- [ ] https://ourworldindata.org/grapher/death-rates-disaster-gdp
- [ ] https://ourworldindata.org/grapher/affected-by-disasters-vs-gdp

![Image](https://github.com/user-attachments/assets/d67dae5e-9a33-4426-a420-0ea31d1e629e)

### 2) Data is not found
I couldn't migrate the following charts. If I attempt to change variable 123 for the new indicator, I get a "No matching data" message and no data is shown. Therefore, I've decided not to migrate these.

- [ ] https://ourworldindata.org/grapher/distribution-democracy-index-polity
- [ ] https://ourworldindata.org/grapher/fertility-rate-vs-mean-years-of-schooling
- [ ] https://ourworldindata.org/grapher/distribution-democracy-index-popw-polity

![Image](https://github.com/user-attachments/assets/22632731-6560-454d-ae0d-77ecb22e6b94)
![Image](https://github.com/user-attachments/assets/5e7cb0c0-b90d-4a16-a7d0-871bd5a318b2)

**Comment by sophiamersmann** [comment]
@lucasrodes this has been fixed. I updated the colour indicator for the three charts that are mentioned under point 2). Just pinging you in case there is something else you wanted to do once this is fixes.
