### ISSUE TITLE
Slope: Projection slopes stay around after unselecting them

### ISSUE THREAD

**Issue by marcelgerber** [owid/owid-grapher#4319]
## Description

The recent slope chart re-implementation has made it so that projections stay around after unselecting them.

## Steps to reproduce

1. Go to https://ourworldindata.org/grapher/population-density-of-the-capital-city
2. Unselect any entity

## Screenshots

https://github.com/user-attachments/assets/8a22513b-d9b7-49c6-a065-f05eae70425f

## Additional context

This is happening because the React key is not unique here:

https://github.com/owid/owid-grapher/blob/5a65e4bb8f714c59bddacc4890c294019d0c862e/packages/%40ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx#L1068-L1069

Probably a good solution is to incorporate `series.column.nonEmptyName` into the key, also?

**Comment by sophiamersmann** [comment]
You mean the line chart, right?

**Comment by sophiamersmann** [comment]
@marcelgerber, I pushed a fix now but let me know if I misunderstood or there is something else :)

**Comment by marcelgerber** [comment]
Ah yes, obviously I meant line charts. thank you!
