### ISSUE TITLE
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by sourabhsurana1008** [owid/owid-grapher#474]
Failed to GET /api/charts.json (500)
Please screenshot this error message and report it in 

```json
{
   "error":{
      "message":"QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>\"$.title\" AS title,\n        charts.config->>\"$.slug\" AS slug,\n        charts.c' at line 3\n    at new QueryFailedError (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\src\\error\\QueryFailedError.ts:9:9)\n    at Query. (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\src\\driver\\mysql\\MysqlQueryRunner.ts:166:37)\n    at Query. (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\Connection.js:525:10)\n    at Query._callback (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\Connection.js:491:16)\n    at Query.Sequence.end (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\sequences\\Sequence.js:83:24)\n    at Query.ErrorPacket (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\sequences\\Query.js:90:8)\n    at Protocol._parsePacket (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\Protocol.js:291:23)\n    at Parser._parsePacket (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\Parser.js:433:10)\n    at Parser.write (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\Parser.js:43:10)\n    at Protocol.write (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\protocol\\Protocol.js:38:16)\n    at Socket. (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\Connection.js:91:28)\n    at Socket. (C:\\Users\\user\\Desktop\\Interview\\React\\grapher\\node_modules\\mysql\\lib\\Connection.js:525:10)\n    at Socket.emit (events.js:198:13)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)",
      "status":500
   }
}
```

**Comment by MarcelGerber** [comment]
From what it looks like, you're using a MariaDB server/client instead of MySQL.
MariaDB doesn't support the JSON selectors/operators we're using (`->` and `->>`).

Please use MySQL 5.7 instead.

**Comment by sourabhsurana1008** [comment]
I am using mysql

**Comment by MarcelGerber** [comment]
Either your database server or client is not MySQL but MariaDB. Otherwise, your error message wouldn't contain `check the manual that corresponds to your MariaDB server version`.

**Comment by sourabhsurana1008** [comment]
Thanks it started working. I want to build front-end, but on build it is only providing gas and css, js file no html.

**Comment by MarcelGerber** [comment]
What exactly are you trying to do with `owid-grapher`? Knowing this would probably help us in helping you.

If you run `yarn dev` and don't see any errors there, you should be able to access an https://ourworldindata.org -lookalike at http://localhost:3099 and an admin site at http://localhost:3030/admin/

**Comment by sourabhsurana1008** [comment]
I am trying to replicate the new graph with my static data after that want to build files to run on a browser.

https://ourworldindata.org/co2-and-other-greenhouse-gas-emissions

**Comment by MarcelGerber** [comment]
Ah, I see what you mean now.

There's the `yarn bake` command which is meant to build a static version of the whole page with all its charts, posts, exports and all in place. The issue there is that you cannot use it locally since it expects a Wordpress database to be present.

In my opinion, it would be useful to provide either
* something like `yarn bake-single` to bake only a single grapher page (with its JSON data, and maybe exports, too)
* or something like `bake-grapher`, which bakes all grapher pages but not posts (which might take quite a long time, at least the first time around)

Neither of these can be done easily at the moment, but I think such a command would be a useful addition (cc @breck7 @danielgavrilov).

@sourabhsurana1008 that's what the disclaimer that owid-grapher is `not currently designed for immediate reuse as a full library, but you are very welcome to adapt any of our code or to send pull requests` (in the README) is about - the code _can_ be used for own projects, but it's not necessarily _easy_. Sorry about that.

**Comment by sourabhsurana1008** [comment]
@breck7 @danielgavrilov   I ran the  **yarn bake co-emissions-per-capita** command but i am facing wordpress datatable missing error " sqlMessage: 'Table \'owid.wp_redirection_items\' doesn\'t exist'".

bake-single and bake-grapher bot command not working.

**Comment by breck7** [comment]
> something like yarn bake-single to bake only a single grapher page (with its JSON data, and maybe exports, too)
>  something like bake-grapher, which bakes all grapher pages but not posts (which might take quite a long time, at least the first time around)

I concur!

I think if we can try to refactor out the global `settings.ts`, and all the baking functions functional, that would allow us to start making a number of improvements to the baking code such as baking a single chart or even baking the full site to an arbitrary folder on disk.

I had started a little refactor of the baker a while ago but then put that on the backburner, so it's useful to hear others might benefit from a Baker refactor.
