### ISSUE TITLE
Map City-Level Data Instead of World Data?

### ISSUE THREAD

**Issue by hxliu-code** [owid/owid-grapher#506]
I have data about US cities that I would like to map, but this repo only allows data for entire countries. How could I change it to map data for cities instead? I know I would have to change the MapTopology.ts file to contain geodata on US cities, but are there other things I would need to change too? And where could I find the necessary geodata for US cities?

**Comment by danyx23** [comment]
Hi @hxliu-code! Sorry for the late reply, we're just cleaning up issues here and making some improvements to our workflow. In case this is even still relevant, our grapher tool at the moment only supports mapping countries and adapting it to graph cities would be a significant amount of work. If you are still interested in this, maybe you can find relevant other work on [ObservableHQ](https://observablehq.com/search?query=cities)? E.g. this project might be relevant: https://observablehq.com/@toja/all-the-cities
