### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by bohning** [owid/owid-grapher#641]
I tried to follow the initial development setup instructions, but step 6 "yarn" fails with the following warnings (maybe not critical) and one error: "error https://registry.yarnpkg.com/core-js-pure/-/core-js-pure-3.6.5.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open '/Users/markus/Library/Caches/Yarn/v6/npm-core-js-pure-3.6.5-c79e75f5e38dbc85a662d91eea52b8256d53b813-integrity/node_modules/core-js-pure/features/array/last-item.js'""

![image](https://user-images.githubusercontent.com/1497707/94421390-c1e1a200-0185-11eb-9c7d-286fa8e7a39b.png)

Any help is much appreciated.

**Comment by MarcelGerber** [comment]
Hi @bohning, this is a know issue with Yarn, and a very infuriating one: https://github.com/yarnpkg/yarn/issues/7212

Can you try `yarn install --network-concurrency 1` instead and see if that works (warning: will probably take quite some time).

**Comment by bohning** [comment]
Hi Marcel,

thanks for your quick response. Before your reply, I tried running a second time and get a whole lot of different warnings/errors. The result of `yarn install --network-concurrency 1` is the following:

`markus@Markuss-MBP owid-grapher % yarn install --network-concurrency 1
yarn install v1.22.7
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > linkifyjs@2.1.9" has unmet peer dependency "jquery@>= 1.11.0".
warning " > @storybook/addon-essentials@6.0.21" has unmet peer dependency "react-is@^16.8.0".
warning "@storybook/addon-essentials > @storybook/addon-docs@6.0.21" has unmet peer dependency "react-is@^16.8.0".
[5/5] 🔨  Building fresh packages...
[-/12] ⢀ waiting...
[-/12] ⢀ waiting...
[3/12] ⢀ fsevents
[7/12] ⢀ sharp
warning Error running install script for optional dependency: "/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents, /Users/markus/Projects/owid-grapher/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@14.12.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@14.12.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v83-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.12.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.12.0 | darwin | x64
gyp info find Python using Python version 2.7.17 found at \"/usr/local/opt/python@2/bin/python2.7\"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markus/Library/Caches/node-gyp/14.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/markus/Library/Caches/node-gyp/14.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/markus/Library/Caches/node-gyp/14.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/usr/local/Cellar/node/14.12.0/bin/node\" \"/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64\" \"--napi_version=7\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v83\"
gyp ERR! cwd /Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --fallback-to-build --module=/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/14.12.0/bin/node\" \"/Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/markus/Projects/owid-grapher/node_modules/watchpack-chokidar2/node_modules/fsevents
node-pre-gyp ERR! node -v v14.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
[-/12] ⠂ waiting...
[-/12] ⠂ waiting...
[3/12] ⠂ fsevents
[7/12] ⠂ sharp
error /Users/markus/Projects/owid-grapher/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/markus/Projects/owid-grapher/node_modules/sharp
Output:
info sharp Using cached /Users/markus/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.12.0 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.12.0 | darwin | x64
gyp info find Python using Python version 2.7.17 found at "/usr/local/opt/python@2/bin/python2.7"
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markus/Projects/owid-grapher/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/markus/Library/Caches/node-gyp/14.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/markus/Library/Caches/node-gyp/14.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/markus/Library/Caches/node-gyp/14.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/markus/Projects/owid-grapher/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.12.0/bin/node" "/usr/local/Cellar/node/14.12.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/markus/Projects/owid-grapher/node_modules/sharp`

**Comment by MarcelGerber** [comment]
In this case, `gyp: No Xcode or CLT version detected!` seems to be the reason why the command fails.

I don't have a Mac myself, but maybe this Stackoverflow thread can help you along: https://stackoverflow.com/q/60573595/10670163

**Comment by bohning** [comment]
That did the trick, thanks a lot.
