### ISSUE TITLE
Admin variable previews should pick chart based on kind of data

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#70]
At the moment it's always maps which doesn't work for non-geographic variables. Should pick like:

Mappable entities => map
Single-year non-mappable data => discrete bar chart
Multi-year non-mappable data => line chart

**Comment by mispy** [comment]
I partially implemented this earlier-- if the data isn't mappable, it switches to a line chart and adds some entities. Look at the `chartIsReady` function in `DatasetEditPage`.

Main thing to add would be that it should become a discrete bar chart if the variable only has a single year in the data.

It would probably be good to refactor `DatasetEditPage` with `VariableEditPage` and make a separate component that is `VariablePreview` or such that can be used by both..!

**Comment by danielgavrilov** [comment]
> Main thing to add would be that it should become a discrete bar chart if the variable only has a single year in the data. 

Sorry, I still can't manage to figure this out. My attempt is in https://github.com/owid/owid-grapher/commit/8672976ad94adac78dcb997a97a637e6f9957070 

How can I find out of if the variable has only a single year?

**Comment by mispy** [comment]
Ah, you're on the right track! What you're looking at there is `ChartData`, which is the component responsible for sort of high-level integration of the chart configuration and data, in cases where that can be done generically across all the chart types. Mainly the computed values that are in that component itself govern the selection of countries.

For this you would want to go through `ChartData` and get to the actual variables themselves. This means you want to look at the "dimensions", which describe which variable is attached to which chart. In particular `DimensionWithData` is the key part you want to access, you're looking for `chart.data.filledDimensions[0].yearsUniq`.

In any case where you can find ways to document or rearrange things to be clearer to you, feel free to do so. A lot of this stuff has never been touched by a programmer aside from me before so it's definitely not arranged optimally for new understanding.

Also, this particular issue isn't high priority at all, so don't worry about it too much if you get stuck.

**Comment by danielgavrilov** [comment]
Thanks for the nice overview! My goal is just to understand things for now, I don't intend to rearrange things yet. 🙂
