### ISSUE TITLE
Indicate the exact position of a hovered map item on the legend

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#73]
Like these maps: https://flourish.studio/2018/04/25/london-ward-maps/

<img width="613" alt="screen shot 2018-07-09 at 10 43 34 am" src="https://user-images.githubusercontent.com/3055384/42428175-f706581e-8364-11e8-95af-678f6048d11b.png">

We can know exactly where the value should be positionally, so we might as well be precise

**Comment by skeletorkun** [comment]
@mispy any examples of graphs to improve in particular? 
Because similar examples in the coronavirus page already provide this :
![image](https://user-images.githubusercontent.com/6833728/78454589-9f247400-76a1-11ea-892c-9dc5ac0d0411.png)

**Comment by mikestratton** [comment]
@mispy I concur with @skeletorkun. Further definition is needed.

**Comment by breck7** [comment]
It looks like this was done at some point. Closing.
