### ISSUE TITLE
relative range

### ISSUE THREAD

**Issue by gaborbit** [owid/owid-grapher#730]
Hi

I thought time=30..latest will show last 30 days. Is it possible to have an url that shows last 30 days?
https://ourworldindata.org/grapher/covid-cases-by-source?time=30..latest&country=BLR

Thanks

Is it related to issue [349](https://github.com/owid/owid-grapher/issues/349)?

**Comment by breck7** [comment]
Hi @gaborhub ,

That is not possible yet. The only dynamic time range we currently support is to show a certain date to the edges, and we don't yet support ranges via urls. It's a very good idea though. We have a big new release coming out soon that would make adding a feature like that a lot easier.

If you are still wanting this in two weeks, please ping this issue and hopefully the latest will be out and we can take a fresh look at this one.

-Breck

**Comment by gaborhub** [comment]
Hi,
I would recommend dynamic range like time=30days..latest
Thanks
Gabor

Ping ;)

**Comment by danyx23** [comment]
We discussed this again and at the moment this is tricky for us to surface usefully in the UI. We might revisit this after some upcoming changes but for now I'll close the issue.
