### ISSUE TITLE
/db/downloadAndCreateDatabase.sh: line 3: mysql: command not found

### ISSUE THREAD

**Issue by pjgadsdon** [owid/owid-grapher#747]
Any ideas? On Windows currently as I cant login in to my Ubuntu

But mysql is running and I have removed the root password

Could be an issue on Windozzz

Thanks

**Comment by MarcelGerber** [comment]
Hi @pjgadsdon, yes, this script is meant to be run on a Linux-like operating system.

But if it's only `mysql` that's missing then you can maybe still run the script by adding MySQL to the PATH. Or are you running from a WSL (Windows Subsystem for Linux) environment?

**Comment by pjgadsdon** [comment]
Yes it was the path but now i get

ERROR 1045 (28000): Access denied for user 'ODBC'@'localhost' (using password: NO)

ODBC??

God windows is awful

**Comment by pjgadsdon** [comment]
I got it

mysql -u root -e "CREATE DATABASE owid;"

in

/db/downloadAndCreateDatabase.sh

**Comment by MarcelGerber** [comment]
So this is fixed now?
I'll close it for now, but feel free to re-open if you still need help.
