### ISSUE TITLE
Mobile optimization: date range selector

### ISSUE THREAD

**Issue by CoreyVidal** [owid/owid-grapher#760]
OWID is my favourite place to view data, particularly for COVID-19. However, the data explorer, and interactivity on mobile is tricky to use.

That's general feedback, but I wanted to make one suggestion in particular: dragging the 2 dots on the date range is spotty. I wanted to suggest an option where you can pick the from and to dates manually using number (date) entry. This would allow for easier granulation of date selection on small screens.

**Comment by MarcelGerber** [comment]
Thank you, Corey, that is a very helpful suggestion, and we will certainly consider it going forward!

In general, you're also correct about the fact that the Covid explorer, and really all charts on OWID, are better experienced on a big screen than on a small phone. We're always trying our best to make them work great on both screen sizes, but it's a hard problem to tackle!
