### ISSUE TITLE
Don't allow selecting countries without renderable data on scatterplots or slope charts

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#79]
This is a bug that has been around for a while, but you can see it on e.g. https://ourworldindata.org/grapher/number-of-child-deaths-slope-chart Where it's possible to select Afghanistan but it doesn't appear on the slope chart.

This is because the data selector looks directly at the data to determine what entities are available without reference to the chart type, so it doesn't know whether it's renderable or not. Determining this list of entities should be the responsibility of the chart transform, which has that information.

Not sure what the best way to get that info from the transform to the selector UI is... maybe expose it via an interface on activeTransform?

**Comment by sherinkurian** [comment]
😊
