### ISSUE TITLE
Improvements to the label placement algorithm for line charts

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#81]
A while ago I implemented a positional labelling system based on some of the charts in the book "The Functional Art". It looks like this:

<img width="219" alt="screen shot 2018-07-30 at 1 33 06 pm" src="https://user-images.githubusercontent.com/3055384/43379068-25ea2d7e-93fd-11e8-8ad4-e06898bc61b5.png">

This HeightedLegend algorithm works by placing all the labels at the height of the line, finding all overlaps, and then shifting all overlaps either down or up depending on which direction has available space. In most cases this works well and finds an acceptable solution.

However, there are occasional edge cases like this where it cannot find a solution: https://ourworldindata.org/grapher/mispy-overlap-test

![global-incidence-and-prevalence-of-tuberculosis](https://user-images.githubusercontent.com/3055384/43379504-664fb8f0-93ff-11e8-8c7d-5b1bcefdab9b.png)

This is because the algorithm always moves all overlapping labels either down or up, it cannot do both simultaneously because it would then need to ensure that it did not create _more_ overlaps in the process of repositioning.

Label placement is a [complex problem in computer science](https://en.wikipedia.org/wiki/Automatic_label_placement), but since this particular problem is 1-dimensional (only the height varies) the algorithm does not need to be super optimized and so I think it should be possible to find a better solution that resolves this edge case (and also has improved labelling behavior in the case when there are clusters in the center).

**Comment by danielgavrilov** [comment]
Fixed by new algorithm in https://github.com/owid/owid-grapher/commit/f16fa239969f43477dd210e6bdf689c7627dc75e

**Comment by mispy** [comment]
Woah your solution is shorter too! Really nice 😄

**Comment by danielgavrilov** [comment]
It was fun to implement!
