### ISSUE TITLE
Support for data time ranges other than annual

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#82]
This is a tricky one since it requires carefully rethinking all aspects of the grapher (the importer and database as well as rendering). We currently get a lot of systemic simplicity out of being able to assume that all time data is in the form of integer years.

However, we will need to implement this at some point to fulfill our core goals of accurately collating all global development data-- there are some datasets we cannot represent in our database right now.

**Comment by breck7** [comment]
This is done in Next + Explorers.
