### ISSUE TITLE
Fix the borders of Somalia and make tiny countries findable on maps

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#83]
Kinda two issues, but they both involve changing the underlying map topography so rolling them together.

Max provides this static image as an example of what maps might look like:

![preview-lightbox-screen shot 2018-05-30 at 15 54 36 3](https://user-images.githubusercontent.com/3055384/43394358-0a13c968-942d-11e8-87d5-1b78bb060199.png)

- Somalia

Our maps (like many) are based on the topojson from https://github.com/topojson/world-atlas, which in turn comes from the Natural Earth vector data here: http://www.naturalearthdata.com/downloads/ 

The borders in this topojson distinguish Somalia from Somaliland: https://en.wikipedia.org/wiki/Somaliland This self-declared state is not widely recognized and readers are sometimes unhappy that we implicitly recognize them in the border configuration-- and we don't tend to have data for Somaliland anyway. That whole bit should just be Somalia like how Google Maps shows it.

<img width="170" alt="screen shot 2018-07-30 at 7 41 07 pm" src="https://user-images.githubusercontent.com/3055384/43395405-8adf0d98-9430-11e8-8672-e42186e237b2.png">

- Tiny countries

There are many small nations for which we have data but which occupy a very small geographic area, so that they are hard to see or hover over on the interactive map (for example, Singapore). These should be represented by small circles, ensuring that all countries occupy a certain minimum visible area on the map.

<img width="101" alt="screen shot 2018-07-30 at 7 42 36 pm" src="https://user-images.githubusercontent.com/3055384/43395466-bdd407f8-9430-11e8-9902-ff84cf5a1eb1.png">

**Implementation**

Ideally we would go and edit the original geojson to make these changes and then rebuild the topojson. From a brief look around I couldn't quite figure out how to do this, but it should be possible.

**Comment by mispy** [comment]
Found an interim solution to the Somalia thing in https://github.com/owid/owid-grapher/commit/165f78dc79bb15f856ebf0b33168dc509111e558 using topojson.merge. I think it should be possible to extract the calculation from that and put it back into the original topojson.

**Comment by mispy** [comment]
Fixed Somalia and the Western Sahara borders properly by using the topojson from here: https://github.com/alexabruck/worldmap-sensitive

I extracted the country names to a CSV file, ran it through our standardizer, and then put it back into the json. A nice upside of that is we no longer need to convert between OWID entity names and map feature ids. Can simplify various aspects of the map code now.

**Comment by mispy** [comment]
A test of the small-country behavior https://mispytest-grapher.netlify.com/grapher/life-expectancy

![life-expectancy 3](https://user-images.githubusercontent.com/3055384/43648239-71229a84-976c-11e8-951e-cc2de44a24aa.png)

**Comment by OurWorldInData-User** [comment]
Hey Jaiden!

That is a very good step in the right direction!
– I would suggest to make the circles a bit smaller. E.g. Malta shouldn't touch Italy. I would make them really small.

– And the threshold for 'minimum country size' can be quite a bit smaller too. E.g. Taiwan, Israel, Rwanda, Burundi, countries in South East Europe and others are visible enough without an overlaid circle. I would mostly use the circle for a few tiny island states that are out in the ocean and where the circle doesn't look too much out of place.

But actually the current world map is actually very good https://ourworldindata.org/grapher/life-expectancy
Maybe it is enough to use the circles as a definition for the hover-over-area. So that it is less fiddly to position the mouse on top of Malta. (i.e. Malta would be shown pretty small but visible, and the area that triggers the Malta hover info is bigger than the visible Malta)

**Comment by mispy** [comment]
Ah that is an excellent idea, it is much easier to improve the mouseover behavior. It now works like this:

- If the mouse is inside the borders of a country, it hovers that country
- If the mouse is outside all borders, it finds the nearest center point of any country, and hovers that if it is reasonably nearby

This way it is fairly easy to find places like Malta at least through the interactivity.

**Comment by OurWorldInData-User** [comment]
Great work Jaiden! This works now really well!

**Comment by toni-sharpe** [comment]
I know I'm necroing this post a little but I had a shot at this problem myself and thought I'd share the solution:

[Just a comment on the linked issues](https://github.com/owid/owid-grapher/issues/1233#issuecomment-2163944012)

IMO the bigger circles are actually a bit better, the map is about showing data, not navigating, so wew want them to be seen easily.

One thing you'll also notice if you sleected "Internet Use" then use the time slider, 1991 show the split of Czechoslovakia, 2011 South Sudan amd 2015 Abzhakia. Done with merged arrays.

https://data-visualisation.pages.dev/WorldMap

<img width="338" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/b2dab556-483c-4ac4-9592-8ce35476d1b7">
<img width="334" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/2fe002c8-7365-40b1-9c03-bfa31d66635c">

<img width="550" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/22a5ae76-6925-4f1b-8a86-85924898c654">
<img width="554" alt="image" src="https://github.com/owid/owid-grapher/assets/10499070/baeccfcc-ffab-4987-be77-1e149d1bd18d">
