### ISSUE TITLE
Split the frontend code from owid-grapher into a standalone visualization library

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#84]
Often people ask what we use to make interactive charts. I can point them at this repo but they can't really just go and adapt it for their own purposes, since everything is tied together as a single web app.

I would like to extract the actual data visualization code from this repository and make it a separate npm dependency that people can easily reuse. Something like [nvd3](http://nvd3.org/), which we used to depend on ourselves until we found it too limited.

I think the grapher code has some interesting properties that could make it a useful addition to this space, particularly in comparison to older stuff like nvd3:

- Fully responsive, including SVG text wrapping and label overlap detection
- Local SVG and PNG exports with text annotation
- Universal rendering: rare datavis library that can run entirely under node
- Nice Mobx interface for efficient state mutation (chart.title = "foo")
- Designed to integrate into other automated systems (like the chart editor)
- We have the funding and incentive to maintain it for 3+ years

I think we could present it as being a "zero configuration" kind of interface, since that's what it's sort of already designed to be: you give it some data and it infers an interactive chart from it. While some customization options would of course be available on the chart itself, the ideal is that you customize it by _annotating the data_ to give the grapher more information to work with.

We don't want to pursue the kind of flexibility of a system like [Vega](https://vega.github.io/vega/). The grapher will always do a limited set of things, but we want it to be the best option for doing the things that it can do.

To allow for easy prototyping, it should come in both the developer-focused, npm variant, and also a CDN script tag bundle you can easily include and play with. Also it should have a cool name!

**Comment by breck7** [comment]
The front-end grapher code is now a TypeScript subproject in Next.

While it doesn't do:

> To allow for easy prototyping, it should come in both the developer-focused, npm variant, and also a CDN script tag bundle you can easily include and play with. Also it should have a cool name!

We could. Closing this for now but we can resurrect this idea at some point if it makes sense, or leave it to someone else to do.
