### ISSUE TITLE
Dual-point interactive timeline on maps

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#88]
Something we've wanted to do for a while is add interactive timelines to each of the chart types which allow you to specify both a start and end year, then show you the chart for that period.

We currently have this only for scatterplots: https://ourworldindata.org/grapher/life-expectancy-vs-health-expenditure

For choropleth maps, in multi-year mode it would color the map according to the _change_ in values between the two selected years.

Some thought will need to be put into how the legend and color selection works for this!

I've never been suuper happy with the usability of the dual-point interface on scatterplots (particularly switching between single and multi year modes). If we can think of improvements to it that would also be good.

**Comment by danielgavrilov** [comment]
Just to add, this is a nice post on different types of _changes_ we might want to show: https://beta.observablehq.com/@mbostock/methods-of-comparison-compared

**Comment by mispy** [comment]
Agreed! If there's some means of determining which comparison method would be most suitable, based on the nature of the data, that would be neat. Not sure how much can be automated there.

**Comment by danielgavrilov** [comment]
@maxroser You requested this feature during the issue spotting:

> New feature needed to make it correct: This chart shows the annual change in a given interval.
So we need intervals as a time-variable.
In this case it needs to say Annual change in forest area, 2010-2015
> https://ourworldindata.org/grapher/annual-change-forest-area?time=latest
https://ourworldindata.org/grapher/annual-deforestation

We have to invest quite a bit of time to make something like this possible. This could be a project lasting a cycle (or two) and we'd have to give up something else on the roadmap. 

Right now it's not at all on the roadmap, I'm just sharing here so you can discuss with @larsyencken in case it should be a priority at some point.
