### ISSUE TITLE
Investigate further: possibility of using SVG file directly as the base for choropleth maps

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#92]
Is there anything stopping us from doing that in practice? How does the performance/filesize compare with topojson? A little weird with React, but it might work.

**Comment by danielgavrilov** [comment]
I think we can convert the SVG into TopoJSON and use a custom projection, as Mike Bostock does [here](https://bl.ocks.org/mbostock/5249328)?

But, is this with the intent of using Max's cartogram? And in that case, wouldn't we need a different cartogram for each year? 

(As I'm writing this, I think it's a brilliant idea to do the year-by-year cartogram anyway! It would be so cool to see the world grow!)

**Comment by mispy** [comment]
That's an excellent point! To do a timeline on a cartogram map properly we would want to use the population statistics from each year.

Might be cool to do a fancy interactive version of that chart as a standalone project even, whether we use it as a grapher option or not.
