### ISSUE TITLE
All charts page on Covid has all broken country labels

### ISSUE THREAD

**Issue by doniks** [owid/owid-grapher#954]
go to Coronavirus -> All Charts : https://ourworldindata.org/coronavirus-data

the curves on all charts have useless generic names like "Confirmed deaths per million" or "Tests", whereas they should be named after the country who's data they represent

![image](https://user-images.githubusercontent.com/26801304/124375059-4f679a80-dca0-11eb-8114-3a2a15051706.png)

**Comment by danyx23** [comment]
@doniks thanks a lot for the report, we're looking into it!

**Comment by danyx23** [comment]
We'll try to fix this soon - in the mean time if you want to look at these charts then it should work if you clear the country selection at the top (https://ourworldindata.org/coronavirus-data?country=#country-by-country-data-on-the-pandemic) and reload the page. Then the charts at the top will display data for only a single country again and the labels will work as expected.

Thanks again for the report!

**Comment by danielgavrilov** [comment]
It seems we fixed this at some point. Please reopen if it's still happening!
