### ISSUE TITLE
Feature Request: Network Graphs

### ISSUE THREAD

**Issue by manunamz** [owid/owid-grapher#969]
Thanks so much to the owid team for all their great work! 🗺 📊

Any chance owid would be willing to add [network graph](https://www.google.com/search?q=network+graph&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiBptmRkPrxAhWaVTABHXbIBBcQ_AUoAXoECAEQAw&biw=1440&bih=825) tooling?

(++ If hierarchical/tree logic could be added as well)

**Comment by danyx23** [comment]
Hi @manunamz! Network graphs are a cool feature definitely! We do prioritize features around what our authors need though and network graphs are not on the immediate roadmap. This may change of course in the future but I would be surprised if we would be adding them within the next 12-18 months. 

We do plan to make it easier to contribute to the owid grapher in the future though, so maybe this could be something for an external contributor to work on in the future.

I'll close this issue for now but feel free to comment again
