### ISSUE TITLE
Tracking embed locations for each chart

### ISSUE THREAD

**Issue by mispy** [owid/owid-grapher#98]
We have the ability to set an origin url for each chart in the grapher so that the chart can link back to the text. However, this requires manual work and people don't always remember to do it. It would be neat if the code could automatically know which of our pages a chart is embedded.

I think the way this would work is that each time a post is saved, the code goes through the html and picks out any embeds, then updates a database table indicating the relationship. If it is the _first_ such relationship, and the chart has no canonical origin url, it also updates the chart setting the origin url to that page.

This one is a little tricky because of the degree of integration between articles and charts it requires. Probably something to do in conjunction with replacing the Wordpress editor.

**Comment by breck7** [comment]
We now have the related links component which does some of these links. Still manual but something we could reopen later. Closing
